### ISSUE TITLE
Update `sound_prefix` variable.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#1009]
```
Make `sound_prefix` in config as
`$${sounds_dir}/${default_language}/${default_dialect}/${default_voice}`
```

Original issue reported on code.google.com by `alexeyme...@gmail.com` on 29 Jun 2015 at 12:30

**Comment by markjcrane** [comment]
Closed do to long period of inactivity. If you still want to push this idea then please state where you propose setting sound_prefix inside advanced -> variables (vars.xml)?
