### ISSUE TITLE
Received fax tif can't be viewed

### ISSUE THREAD

**Issue by genachka** [fusionpbx/fusionpbx#1020]
Using 3.8.4 on Ubuntu 14.04. Resulting .tif file that is emailed as attachment or when trying to directly via Apps > Fax Server > Inbox 
Results in an error from viewers tried (Gimp, Shotwell, Eye of Gnome) that the file can not be opened. Download file directly from the server to local and same results.

**Comment by genachka** [comment]
bump

**Comment by genachka** [comment]
FYI I still have this problem with the latest Fusionpbx 4.1.0 (updated this morning) and Freeswitch 1.4.26 (32bit). Any suggestions?

**Comment by markjcrane** [comment]
There are known problems for faxing on x86 32bit that are working fine on 64bit.

**Comment by genachka** [comment]
Ah, ok I'll test it again once I have moved to 64bit.
