### ISSUE TITLE
Ring Groups: ignores outbound rules

### ISSUE THREAD

**Issue by blessendor** [fusionpbx/fusionpbx#1026]
Problem happen when I add to ring group mobile members.

I don't know how FusionPBX generates dial string, but my outbound routes ignores and used one of different gateway, not which needed. Dial out from SIP client or with Follow Me settings working well with my rules.

I'm not new for dial rules, so I think something special in Ring Group logic defined.

**Comment by markjcrane** [comment]
The dial string is created by evaluating the outbound route with Lua reading the outbound routes and using regex against the 'destination number' Goal is to avoid loop-back as it makes a mess of CDRs and causes problems of its own. This is working on every system I have tried it on. Exception could be outbound routes with additional conditions. Need further help look consider support.
