### ISSUE TITLE
multiple-registratations

### ISSUE THREAD

**Issue by mwehberg** [fusionpbx/fusionpbx#1031]
Sorry if this has been solved already...

What steps will reproduce the problem?
1.added multiple-registrations to sip profile internal
2.added two phones with same extension number (17)
3.called the ext 17 from extension 16

What is the expected output? What do you see instead?
Both phones tied to ext 17 to ring

Only one phone rang even though both are registered

What version of the product are you using? On what operating system?
3.6.3 on Centos

Please provide any additional information below.

I searched through past cases and saw that we needed to added multiple-registrations in sip profile internal.  I think there is another part to the configuration with bridging but I am not clear what to do. 

Mark

**Comment by mwehberg** [comment]
fixed by changes in 999_v_local_extension.xml

added       <action application="bridge" data="${sofia_contact(${dialed_extension}@${domain_name})}"/>
commented out

**Comment by mwehberg** [comment]
Have a new issue with a polycom dropping a registration...

polycom with 6 lines
* lines 1-5 register to 100
* line 6 registers to 803

a voip Gateway registers to 803

Polycom drops registration to 803 every so many seconds...

I found that in the 200 OK to the registration request contains 2 Contacts

Call-ID: call-F1CF67A9-0FA2-2110-0803-0@192.168.1.60.
CSeq: 3677 REGISTER.
Contact: <sip:803@108.3.159.40:5062>;expires=45.
Contact: <sip:803@108.3.159.40:5060>;expires=41.
Date: Fri, 10 Jul 2015 15:30:54 GMT.
 

My guess is that the polycom is ignoring the port number and just expiring prior to it needing to register..??

Is there another setting?

**Comment by richbreton** [comment]
The original issue is probably because you are not using our installer which installs XML_handler by default there were some bugs in the config file solution and we moved over wholesale to

**Comment by richbreton** [comment]
Also you are running on an unsupported platform. 
Neither freeswitch not fusionpbx support Centos anymore. At this time both teams support debian 7 and 8
This out of the realm of issues in our supported install please go to http://fusionpbx.com/support.php for help with unsupported platforms
