### ISSUE TITLE
Call center still cannot delete queues and have duplicate dialplan even after update to latest git above where fix was made

### ISSUE THREAD

**Issue by davidwjacob** [fusionpbx/fusionpbx#1033]
Hello,

this is ref to issue #1002 and fixes made by Mark on Jul 9, 2015.

I have renamed off my fusionpbx folder to fusionpbx-svn, and then ran git clone https://github.com/fusionpbx/fusionpbx.git as instructed on the wiki.

once fixing all permissions and restarting nginx, i go and create a new call center , and everytime i make a change to it, it creates a new dialplan each time i resave the callcenter, so if i change a setting 5 times, i have 5 duplicate dialplans. 

here is the log from my postgres logs when trying to delete the call_center:

2015-07-10 16:31:49 EDT [29756-1] fusionpbx@fusionpbx ERROR:  invalid input syntax for uuid: "" at character 113
2015-07-10 16:31:49 EDT [29756-2] fusionpbx@fusionpbx STATEMENT:  delete from v_call_center_queues where domain_uuid = '994026bd-56be-4b6c-a43f-255b389f6169' and dialplan_uuid = '' 
2015-07-10 16:31:49 EDT [29756-3] fusionpbx@fusionpbx ERROR:  invalid input syntax for uuid: "" at character 104
2015-07-10 16:31:49 EDT [29756-4] fusionpbx@fusionpbx STATEMENT:  delete from v_dialplans where domain_uuid = '994026bd-56be-4b6c-a43f-255b389f6169' and dialplan_uuid = '' 
2015-07-10 16:31:49 EDT [29756-5] fusionpbx@fusionpbx ERROR:  invalid input syntax for uuid: "" at character 111
2015-07-10 16:31:49 EDT [29756-6] fusionpbx@fusionpbx STATEMENT:  delete from v_dialplan_details where domain_uuid = '994026bd-56be-4b6c-a43f-255b389f6169' and dialplan_uuid = '' 

I have tried this on 2 separate systems and get the same result on both, i can give access to one of them if someone wants to look around.

let me know
thanks
Dave

**Comment by markjcrane** [comment]
Delete the duplicates manually  then save It a few times.

Mark

**Comment by davidwjacob** [comment]
Mark,

I have tried what you said however every time you save it just keeps adding dialplan, also its not putting the dialplan_uuid in the v_call_center table , the dialplan_uuid field is blank. 

I have removed all call center config from the DB, do a new git load, create new and it does the same thing.

I am also using the BDR setup , so FS is using postgres as its core with the custom schema from the adv class.  Im wondering if this has something to do with it, i dont know if that makes a difference as whenever i do "restart" call_center, the FS CLI tells me that the queue is not valid.

"2015-07-14 10:59:53.195087 [ERR] mod_callcenter.c:487 [newcenter@pbx.domainname.com] Invalid queue"

IF i run this i dont even see the queue:

fs_cli -x "callcenter_config queue list"
name|strategy|moh_sound|time_base_score|tier_rules_apply|tier_rule_wait_second|tier_rule_wait_multiply_level|tier_rule_no_agent_no_wait|discard_abandoned_after|abandoned_resume_allowed|max_wait_time|max_wait_time_with_no_agent|max_wait_time_with_no_agent_time_reached|record_template
+OK

i know your in training this week, but if you can take a hour maybe before or after, reach out to me and maybe i can show you my system.

Thanks
Dave

**Comment by markjcrane** [comment]
You need to upgrade are you using github yet?

Mark

**Comment by davidwjacob** [comment]
Mark,

i am using github, i have removed all call center data from db, removed the /var/www/fusionpbx folder, then ran the git to get a new version of fusion. fix permissions, and restarted everything, and get same results.

Im in /var/www/fusionpbx/app/call_center and run git diff and get no results:

root@debian [Tue Jul 14 04:33 PM]  /var/www/fusionpbx/app/call_center
<17>:git diff

root@debian

Thanks
Dave

**Comment by markjcrane** [comment]
Is this still a problem when using github Master branch? Or are you using the 4.0 branch?

**Comment by moteus** [comment]
Few days ago I faced with this problem. After attempt delete queue I got record in db with empty uuid and any attempt delete this fail. Unfortunatoly I can not reproduce this. May be I can try today one more time.

**Comment by markjcrane** [comment]
I have not been able to duplicate  this.

**Comment by asmikhailov** [comment]
I have same problem with callcenter

**Comment by markjcrane** [comment]
Delete for call center queues has been fixed. If you have duplicate dialplans for call center queues then you will need to be manually removed.
