### ISSUE TITLE
Dialing Lua issue

### ISSUE THREAD

**Issue by den4davis** [fusionpbx/fusionpbx#1034]
Hello.

I tried to solve this problem by myself, unfortunately without luck.
Please help me to diagnose and solve this issue. All needed info below.
Thank you.

What steps will reproduce the problem?
1. Dial to voicemail *97 or any other internal number, 9696 for example

What is the expected output? What do you see instead?
When number dialed call immediately hung up, the log shows:

[ERR] mod_lua.cpp:203 /usr/share/freeswitch/scripts/app.lua:30: attempt to call global 'config' (a nil value)
stack traceback:
        /usr/share/freeswitch/scripts/app.lua:30: in main chunk

What version of the product are you using? On what operating system?
FusionPBX 3.8 Official Release
FreeSWITCH Version 1.4.20~64bit ( 64bit)
CentOS 6.6

Please provide any additional information below.
/usr/share/freeswitch/scripts/resources/config.lua
--switch directories
        sounds_dir = "/usr/share/freeswitch/sounds";
        database_dir = "/var/lib/freeswitch/db";
        recordings_dir = "/home/fusionpbx/storage/recordings";
        storage_dir = "/home/fusionpbx/storage";
        voicemail_dir = "/home/fusionpbx/storage/voicemail";

--database information
        database = {}
        database["type"] = "mysql";
        database["name"] = "freeswitch";
        database["path"] = "";
        database["system"] = "odbc://freeswitch:freeswitch:pass";
        database["switch"] = "odbc://freeswitch:freeswitch:pass";

--additional info
        domain_count = 1;
        temp_dir = "/tmp";

--include local.lua
        dofile(scripts_dir.."/resources/functions/file_exists.lua");
        if (file_exists("/etc/fusionpbx/local.lua")) then
                dofile("/etc/fusionpbx/local.lua");
        elseif (file_exists("/usr/local/etc/fusionpbx/local.lua")) then
                dofile("/usr/local/etc/fusionpbx/local.lua");
        elseif (file_exists(scripts_dir.."/resources/local.lua")) then
                dofile(scripts_dir.."/resources/local.lua");

**Comment by richbreton** [comment]
Are you the guy making your own rpm installer?

Have you considered bringing up a debian jessie install with our installer and just making sure things match?
