### ISSUE TITLE
Installation wizard.

### ISSUE THREAD

**Issue by volga629** [fusionpbx/fusionpbx#1035]
I am trying run through setup wizard and it failing on configuration file section.  I think there are conflict where it look for config.php and if it found then state that we are installed all, but future down in this section it asking to open configuration file for write. As result in error in wizard and installation failing .

````
                if (is_dir("/etc/fusionpbx")){
                        $config = "/etc/fusionpbx/config.php";
                } elseif (is_dir("/usr/local/etc/fusionpbx")){
                        $config = "/usr/local/etc/fusionpbx/config.php";
                }
                elseif (is_dir($_SERVER['DOCUMENT_ROOT'].PROJECT_PATH."/resources")) {
                        $config = $_SERVER["DOCUMENT_ROOT"].PROJECT_PATH."/resources/config.php";
                }
                else {
                        $config = $_SERVER["DOCUMENT_ROOT"].PROJECT_PATH."/resources/config.php";
                }
                $fout = fopen($config,"w");
                fwrite($fout, $tmp_config);
                unset($tmp_config);
                fclose($fout);

```
Error 

````

Warning: fopen(/usr/share/nginx/fusionpbx/resources/config.php): failed to open stream: Permission denied in /usr/share/nginx/fusionpbx/resources/install.php on line 508

Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/fusionpbx/resources/install.php on line 509

Warning: fclose() expects parameter 1 to be resource, boolean given in /usr/share/nginx/fusionpbx/resources/install.php on line 511

Warning: require(/usr/share/nginx/fusionpbx/resources/config.php): failed to open stream: No such file or directory in /usr/share/nginx/fusionpbx/resources/install.php on line 514

Fatal error: require(): Failed opening required '/usr/share/nginx/fusionpbx/resources/config.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/nginx/fusionpbx') in /usr/share/nginx/fusionpbx/resources/install.php on line 514
```

```

**Comment by volga629** [comment]
Will be nice to have page/step when is will specify all required binaries and directories. This will save a lot path guessing in code. 
I was unable by pass error above some from prospective is the blocker. Can't install new vm.

**Comment by richbreton** [comment]
Are you running debian jessie?
Which version of the install script are you using?

**Comment by volga629** [comment]
No, I am building new template based on fedora 21 Server. I got everything up and running. Look like I was using old svn pull. Right now shows version 3.9.

**Comment by richbreton** [comment]
ok sounds good, dont forget you can always run the recommended i.e. supported install on debian jessie  side by side and see what each package installed provides. Im going to close this ticket as we cant support an OS that freeswitch does not recommend
