### ISSUE TITLE
Status -> Traffic Graph doesn’t now show accurate value

### ISSUE THREAD

**Issue by superattack** [fusionpbx/fusionpbx#1042]
Hi Guys, 

It looks like the traffic graph under Status -> Traffic Graph doesn’t show the correct traffic. 

Looking at the code I can see the following: 

status_interface.php:        $in_bytes = ($netstat_array['RX-OK']*1024);
status_interface.php:        $out_bytes = ($netstat_array['TX-OK']*1024);

The traffic that comes from netstat is summary traffic not the real traffic. 

I’m using Debian 7.9 and latest FusionPBX code. 

Thanks,

**Comment by markjcrane** [comment]
This is a known but low priority issue will be worked on as time permits.
