### ISSUE TITLE
Import/Export/Edit extension as XML

### ISSUE THREAD

**Issue by moteus** [fusionpbx/fusionpbx#1044]
I think it would be very convinient if it be possible work with extension in dialplan manager as with XML.

**Comment by markjcrane** [comment]
This is on the to do list. Something that would be nice have.

**Comment by gary-yu** [comment]
When this feature can be released? 
This feature is something like the "bulk extension" feature in FreePBX, and very useful for production server. Hope you also have the "add | modify | del" action for import.

**Comment by markjcrane** [comment]
Dialplan XML added in the master branch.
