### ISSUE TITLE
require instead of dofile

### ISSUE THREAD

**Issue by moteus** [fusionpbx/fusionpbx#1050]
Now to load Lua file uses `dofile` function
I think more efficien way use `require`
e.g.
```Lua
dofile(scripts_dir.."/resources/functions/config.lua");
require"resources.functions.config"
-- or even better 
require"fusionpbx.resources.functions.config"
```

**Comment by markjcrane** [comment]
This was applied but unfortunately its an interuptive change that requires a change to lua.conf.xml in order to work probably be good to add an app_defaults.php that sets the scripts directory automatically if it is not set.
