### ISSUE TITLE
Feature request: Add time zones support

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#1055]
Hi!
It would be nice to have time zones support, in this way you can have really multitenant PBX platform, but not only within 1 timezone (system for now)
There 2 places to support it.
1. CDR. Normally to store CDR info in UTC, but show to user according to his browser timezone settings.
2. Time conditions. Here to store time conditions (in absolute values) + timezone. Main problem here is daylight saving time different rules for different timezones. For ex, in one zone you can have 1-hour shift and if your server is located in another zone without it, user from time-shifting timezone will encounter problem with time-based conditions when daylight shift is happens.

**Comment by markjcrane** [comment]
This is already possible you might consider official Admin FusionPBX admin training to learn how to do this and many other things.
