### ISSUE TITLE
No Audio on Ec2

### ISSUE THREAD

**Issue by papajowsef** [fusionpbx/fusionpbx#1056]
I setup fusionpbx on virtual box and it works fine. inbound call also works.   I tried on ec2 but there's no audio. I  followed the URL below and audio works fine however Inbound destination/incoming call  is not working.  

https://freeswitch.org/confluence/display/FREESWITCH/Amazon+EC2

Does Fusionpbx supported on EC2?

**Comment by anis-bedhiafi** [comment]
Yes sure it does. What you need to do:
1. From your AWS console Open the following ports in your AWS Security Group:
udp     16384:32768
udp     4569
udp     5060
tcp     5060
udp     5080
tcp     5080
tcp     8000
udp     8000

2. Go to Advanced > XML Editor and open conf/vars.xml
Find the following lines and change AWS EIP with your Server Elastic IP
<X-PRE-PROCESS cmd="set" data="bind_server_ip=<AWS EIP>"/>
<X-PRE-PROCESS cmd="set" data="external_rtp_ip=<AWS EIP>"/>
<X-PRE-PROCESS cmd="set" data="external_sip_ip=<AWS EIP>"/>

Save your changes.

3.In Advanced > XML Editor open conf/autoload/switch.conf.xml and uncomment the following lines:
<param name="rtp-start-port" value="16384"/>
<param name="rtp-end-port" value="32768"/>

Save and restart The AWS Machine.
Done!

**Comment by richbreton** [comment]
thanks @anis-bedhiafi ! did that solve your problem @papajowsef ?

**Comment by papajowsef** [comment]
It solved my incoming problem. Thanks anis-bedhiafi & richbreton  for your help.

**Comment by richbreton** [comment]
Excellent
