### ISSUE TITLE
Voicemail to email v3.9

### ISSUE THREAD

**Issue by andyfor** [fusionpbx/fusionpbx#1059]
On 3.8 I had no issues with voicemail to email but I have a new server up and running with latest 3.9 Fusion and I set up the email default settings to the same email server I was using for 3.8 but I am now getting failed emails for voicemail to emails.

Any ideas? Not really sure where to start debugging this one. The voicemails are fine, can listen to them but no email. Email address and settings fine for the extension in question.

Using Debian Jessie, Postgres, Nginx, Fusion 3.9.0.

Thanks
Andy

**Comment by richbreton** [comment]
@andyfor can you put in the steps you are using to set up you default email settings?

**Comment by andyfor** [comment]
Sure Rich.
Advanced>Default Settings>Email
smtp_auth=false
smtp_from=<my email address>
smtp_from_name=Voicemail
smtp_host=mail.<mydomain>.com
smtp_password=<password for this email address>
smtp_secure=none
smtp_username=<my email address>
Very basic settings for now and it used to work in 3.8

In my extension:
voicemail enabled=true
voicemail to = <my email address, same domain as host above>
voicemail file=audio attachment
voicemail keep local=true

Voicemail message appears on phone and can listen to it but no email sent. 
In Status>Email I see it failed to send but no real reason so tough to debug.

My email addresses are all in working order, been using them all day.

Thanks
Andy

**Comment by richbreton** [comment]
Interesting my entire email settings was missing from Advanced>Default Settings until I upgraded the schema.  

Also just verifying your voicemail to is actually filled out ;)

Can you tell if its hitting the port on your sending mail server?

Also are you sure your smtp provider does not require smtp auth? nearly all do

**Comment by andyfor** [comment]
Ha ha yes voicemail_to was filled out. Ahh I used less than and greater than sign which means my text above was removed, too funny. Will try again, sorry :-)

smtp_auth=false
smtp_from=webmaster@andysdomain.com
smtp_from_name=Voicemail
smtp_host=mail.andysdomain.com
smtp_password=mypassword
smtp_secure=none
smtp_username=webmaster@andysdomain.com


In my extension:
voicemail enabled=true
voicemail to =andy@andysdomain.com
voicemail file=audio attachment
voicemail keep local=true

Will try some digging at sending email server, good idea.
I tried smtp true and false but fails either way.

One difference from before is that this is on VULTR, my working system v3.8 for voicemail to email was on hostvirtual if that makes a difference........

Thanks for your help.
Andy

**Comment by richbreton** [comment]
ah why am I trying to remember that vultr blocks port 25 by default....
hmmm you might have a look at that. I think we had a problem in a class
when someone realized that was happening can you send on port that is not
25 like 587? definitely leave smtp_auth on as it wont attempt to send the
password with it off.

**Comment by richbreton** [comment]
@andyfor 
Ok I think we got you fixed. go ahead and re-enable smtp auth and then have a look at this

https://www.vultr.com/faq/#outboundsmtp

**Comment by richbreton** [comment]
looks like they will lift the restriction for you if you contact support. 

Let me know if this works out, and ill close the ticket and put a note in the documentation im building for 4.0

**Comment by andyfor** [comment]
Ahh good find Rich, thanks for that!

**Comment by richbreton** [comment]
Anytime :-)

**Comment by andyfor** [comment]
Got SMTP opened up for my account at VULTR and now works Rich, good call. SSL not working for some reason on smtp_secure field but likely something at VULTR end or maybe my email server.

Cheers
Andy

**Comment by richbreton** [comment]
let us know if it starts looking like fusion and open another ticket. Thanks!
