### ISSUE TITLE
Inbound is intermittent / No ring while calling the inbound  

### ISSUE THREAD

**Issue by papajowsef** [fusionpbx/fusionpbx#1060]
everything is works fine now on Ec2 however the inbound call is intermittent.  I need to restart the freeswitch in order to call again the SIP number. No logs I can see on fscli.   Also I cannot hear  a ring sound if I try to call the SIP number but I'm able to call the extension number.

**Comment by richbreton** [comment]
is this an install using the new install script on github or google code?

**Comment by papajowsef** [comment]
I used this link in the github, used apache and  run install-both auto 

https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/ubuntu/install_fusionpbx.sh


I noticed that If I saw this log line after the restart I know that it will work.

freeswitch@internal> 2015-07-24 03:02:47.610059 [INFO] mod_pocketsphinx.c:644 PocketSphinx Reloaded
2015-07-24 03:02:47.610059 [INFO] mod_enum.c:880 ENUM Reloaded
2015-07-24 03:02:47.610059 [INFO] switch_time.c:1411 Timezone reloaded 530 definitions

**Comment by papajowsef** [comment]
I only encountered this intermittent inbound on ec2.  In virtual box, it works fine but still cannot hear a ring sound if I try to call the SIP number but I'm able to call the extension number.

**Comment by richbreton** [comment]
I hate to ask this but do you have an inbound route built to your sip phone?

have you tested any other phones?

**Comment by papajowsef** [comment]
Im using zoiper on my android phone and pc.  Is this the issue?

**Comment by richbreton** [comment]
zoiper is a good soft client in so far as I have tested. In truth this is sounding more and more like a nat or firewall issue

**Comment by papajowsef** [comment]
I think so, local extension works perfectly.  I'm just wondering why ec2 behavior on inbound is intermittent compared to a virtual box.  The only difference that I made is following the advice below.  


Go to Advanced > XML Editor and open conf/vars.xml
Find the following lines and change AWS EIP with your Server Elastic IP:

X-PRE-PROCESS cmd="set" data="bind_server_ip=AWS EIP
X-PRE-PROCESS cmd="set" data="external_rtp_ip=AWS EIP
X-PRE-PROCESS cmd="set" data="external_sip_ip=AWS EIP

Save your changes.

In Advanced > XML Editor open conf/autoload/switch.conf.xml and uncomment the following lines:
param name="rtp-start-port" value="16384"
param name="rtp-end-port" value="32768"

**Comment by richbreton** [comment]
unfortunately I just dont know enough about the AWS platform

Those preprocess commands look good to me.

Does amazon block anything>

**Comment by papajowsef** [comment]
I have allowed the ports but anyway I can do an automated restart everytime there's a call. Thanks for your help. I will open a new issue on my outbound.  

Thanks again.
