### ISSUE TITLE
Missing Email and Email fields in Advanced> Default settings on fresh github install

### ISSUE THREAD

**Issue by richbreton** [fusionpbx/fusionpbx#1061]
I'll test this again

but I did a fresh install today for the docs

debian 8.1, github master

Everything installed ok 

in Advanced> Default settings I didn't have an Email section 

I went to Advanced > Upgrade and check everything and ran it and my Email section appeared.

I could have been missing some other sections before I just was not looking for them.

I will retest first thing in the am to see if this is still an issue

**Comment by richbreton** [comment]
alright i did a second install to verify this: 

vultr, jessie, github master, postgres, postgres, nginx

Default Settings does not have email:
These are the main headings I have:

CDR
Domain
Fax
Loggin
Ntp Server Primary
Ntp Server Secondary
Provision
Security
Server
Switch
Theme
Time Conditions
VoiceMail

**Comment by richbreton** [comment]
Upgrade > App Defaults Adds 
Email

Email is the only section that was missing

**Comment by richbreton** [comment]
Third install while working on something, still no email section.

I am using a domain based install.

**Comment by richbreton** [comment]
@markjcrane I have a system up if you want to have a look txt me

**Comment by markjcrane** [comment]
Advanced -> Upgrade -> App Defaults 
will add the missing Email category if its missing. This is also automatically called during the install.php.
