### ISSUE TITLE
Bad default on t46 provisioning template

### ISSUE THREAD

**Issue by jamesorose** [fusionpbx/fusionpbx#1074]
This applies to the Yealink t46g.  The following variable is hard coded into the profile. 
resources/templates/provision/yealink/t46g/y000000000028.cfg
    network.static_dns_enable = 1

This causes dns to be set to static, which is problematic with dhcp (the default). It causes the first provisioning file to get grabbed, but not the static, and general loss of internet on the phone thereafter.

**Comment by richbreton** [comment]
james i think i fixed this a few days ago here:https://github.com/fusionpbx/fusionpbx/blob/master/resources/templates/provision/yealink/t46g/y000000000028.cfg 

Can you verify?

**Comment by jamesorose** [comment]
looks good, thanks.

**Comment by richbreton** [comment]
yup
