### ISSUE TITLE
Follow Me (option 3 voicemail does not work) v3.9

### ISSUE THREAD

**Issue by andyfor** [fusionpbx/fusionpbx#1075]
Using Fusion 3.9 (issue also on 3.8 I believe), Debian 8.

The follow me function, option 3 for voicemail, does not work.
- Set up 3 extensions: 100, 110, 115.
- For ext 100 enable follow me in the Fusion portal and add ext 100 and ext 110 as destinations (0, 30 and confirm for each row.).
- Using phone on ext 115 call ext 100. Phones on ext 100 and ext 110 ring, as expected.
- Answer on regular ext 100 phone. At prompt select 3 for voicemail. Instead of going to voicemail it ends the call for that phone and ext 110 continues to ring. Doesn't go to voicemail.
- By the way if I then answer ext 110 and select 3 at the prompt it will go to voicemail. BUT it should go to voicemail in the last step I believe.

As a side note, when option 2 (reject) is pressed I thought it would reject the call completely, instead the other extension(s) still ring. Just mentioning this in case this is not the desired behavior :)

Cheers.
Andy

**Comment by markjcrane** [comment]
It's time to upgrade to 4.2. Then test again.
