### ISSUE TITLE
Provisioning with Profiles - bad var settings

### ISSUE THREAD

**Issue by jamesorose** [fusionpbx/fusionpbx#1076]
If you set up keys under a provisioning profile, the type fields aren't getting substituted correctly. It is correct in the individual devices fields.

Example (note linekeyX.type, call park is wrong, it should be 10):

#Configure Line Key 2
linekey.2.line = 1
linekey.2.value = park+*5902
linekey.2.extension = 
linekey.2.type = call park
linekey.2.xml_phonebook = 
linekey.2.label = PL2

#Configure Line Key 3
linekey.3.line = 1
linekey.3.value = park+*5903
linekey.3.extension = 
linekey.3.type = 10
linekey.3.xml_phonebook = 
linekey.3.label = PL3

**Comment by markjcrane** [comment]
I ran the same test with github .com/fusionpbx/fusionpbx  master branch and this is the result. I used a device profile as you did.

#Configure Line Key 2
linekey.2.line = 1
linekey.2.value = park+*5902
linekey.2.extension = 
linekey.2.type = 10
linekey.2.xml_phonebook = 
linekey.2.label = Park 2

#Configure Line Key 3
linekey.3.line = 1
linekey.3.value = park+*5903
linekey.3.extension = 
linekey.3.type = 10
linekey.3.xml_phonebook = 
linekey.3.label = Park 3

**Comment by jamesorose** [comment]
I ran some tests on 4.0.0 as well, and could not replicate the issue. 
Either something is weird with my setup, it's been fixed in v4, or the 
bug is buried deeper than just the keys assigned in the profiles.  Feel 
free to close it for now.  I'll try on my own and see if I can patch 
things down to 3.8.

James

**Comment by markjcrane** [comment]
Since this could not be replicated I'm closing the issue.
