### ISSUE TITLE
Transfer to extension with number-alias via destination class.

### ISSUE THREAD

**Issue by moteus** [fusionpbx/fusionpbx#1089]
1. create user with ID = `user-100` and number alias = `100`
2. register with AuthID=`user-100` and UserID=`100`
3. Create new inbound destination and select as action `Extension->User 100`

Expected dialplan is `transfer:100 XML ${context}`
But got `transfer:user-100 XML ${context}`

For now I add 
```php
$apps[$x]['destinations'][$y]['field']['destination'] = "(SELECT CASE number_alias WHEN '' THEN extension ELSE number_alias END)";
```
in `extensions/app_config.php` but I think this should works only for PostgreSQL.

**Comment by markjcrane** [comment]
This was fixed today and should work with all supported databases.
