### ISSUE TITLE
ivr_menu incorrect log entry

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1106]
log message says playing long greeting but in fact is playing short greeting

patch follows

root@fusion-1:/usr/local/freeswitch/scripts# diff ivr_menu.lua /var/www/fusionpbx/resources/install/scripts/ivr_menu.lua
369c369
< 				freeswitch.consoleLog("notice", "[ivr_menu] greet short: " .. ivr_menu_greet_short .. "\n");
---
> 				freeswitch.consoleLog("notice", "[ivr_menu] greet long: " .. ivr_menu_greet_short .. "\n");
520c520
< 	end
---
> 	end
\ No newline at end of file

**Comment by markjcrane** [comment]
I don't see what the patch is changing.

**Comment by fidonet** [comment]
The change is subtle

The old log entry said “long” when in fact it was playing “short”


> On 19 Aug 2015, at 04:18, FusionPBX <notifications@github.com> wrote:
> 
> I don't see what the patch is changing.
> 
> 

— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

LINX ConneXions now available at all Fido Sites - https://www.fido.net/services/backbone/connexions/ <https://www.fido.net/services/backbone/connexions/>

**Comment by markjcrane** [comment]
We are no longer using ivr_menu.lua by default instead using FreeSWITCH's native IVR XML. There are several benefits. 
1. Prevents a few minor bugs that existed inivr_menu.lua.
2. Triggers freeswitch events for IVR actions.
3. Can be cached to save requests to the database.
