### ISSUE TITLE
Allow transfer/record to outbound calls

### ISSUE THREAD

**Issue by moteus** [fusionpbx/fusionpbx#1108]
I suggest move [this part](https://github.com/fusionpbx/fusionpbx/blob/master/app/dialplan/resources/switch/conf/dialplan/999_local_extension.xml#L16-L22) in separate extension/context and use `execute_extension` to configure channels.

This allows add something like
```
action set bind_target=self
action execute_extension apply_digit_map XML utils@${context}
```
in outbound route
Also it will be possible use same execute extension in ring_groups application.

**Comment by markjcrane** [comment]
What is the advantage of doing it this way rather than the way it is currently done?

**Comment by moteus** [comment]
now you configure same thing in 2 places. and you need third to otbound calls.
i suggesg use it only oncy

**Comment by markjcrane** [comment]
Global domain might be better
