### ISSUE TITLE
Time conditions based on country

### ISSUE THREAD

**Issue by badcrc** [fusionpbx/fusionpbx#1109]
I'm in need of a different set of default preset for time conditions so I looked at how they are being set up.

So instead of adding them with app_defaults.php to the database I was thinking of just moving the code to time_condition_edit.php and then just doing a lookup of the ISO from v_default_settings and generating the array for the presets.

This way we can have presets based on the the region of the FusionPBX installation (which IMHO is the usual) and most of the clients (if it's a multi-tenant system) would have the same national holidays.

The other way I thought was adding the values to  v_default_settings as "array-$ISO_CODE" and then selecting the right iso-code but seems more difficult.

I've already the code for the first solution tested but I don't know the reason for this variables to be in the database.

Thanks!

**Comment by markjcrane** [comment]
They will not be accepted in time_condition_edit.php ever would be better in a seperate library but to do that would loose some capabilities that we like to have. If they were to be moved out of default settings then we would loose per domain control and ability for the superadmin to change them.  You would benefit from the fusionpbx admin training more than you realize.

**Comment by badcrc** [comment]
I see, thanks.

PS. I'm looking forward for the admin training but I need to convince my bosses first, not an easy task!

**Comment by markjcrane** [comment]
An all encompassing list of holidays for every country would be enormous. Your idea is interesting. I've kind of operated from the premise that we wouldn't have a complete list therefore allow the superadmin to add them.
