### ISSUE TITLE
Cosmetic: tr line in default settings goes to broken link

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1111]
When you click on the line in default_settings you're taken to a blank page displaying a single line of text "display_setting_edit.php?id=blah" rather than the editor for that option.

Clicking on the pencil icon does work however

**Comment by Len-PGH** [comment]
There have been many updates since. Please check again and reopen if still happening. I'm not able to replicate on master.

**Comment by markjcrane** [comment]
This has been fixed.
