### ISSUE TITLE
Missing Variables in default install

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1114]
In a default / fresh install of Fusion, it looks as though a couple of variables aren't defined or documented anywhere as needing to be set

dsn_system and dsn are used internally but not defined anywhere

Adding them to Advanced->Variables fixes the problem but for a newbie trying to get to grips it is a bit of a gotcha

Ideally these should be defined even if they're just pointing to a .db file on the local system initially

**Comment by markjcrane** [comment]
This is taught in the advanced class that is where it is documented. The class you just took. dsn_system is also rarely used.
