### ISSUE TITLE
provision edit file fileoptionslist.php

### ISSUE THREAD

**Issue by wliateot** [fusionpbx/fusionpbx#1117]
if ($_SESSION["app"]["edit"]["dir"] == "provision") {
		echo recur_dir($_SERVER["DOCUMENT_ROOT"].PROJECT_PATH."/resources/templates/provision/");
}

change to:

if ($_SESSION["app"]["edit"]["dir"] == "provision") {
	if (file_exists('/etc/fusionpbx/resources/templates/provision')) {
		echo recur_dir("/etc/fusionpbx/resources/templates/provision/");
	}else{
		echo recur_dir($_SERVER["DOCUMENT_ROOT"].PROJECT_PATH."/resources/templates/provision/");
	}
}

makes the templates added to work

**Comment by markjcrane** [comment]
Looking at the code today seems to be similar to this suggestion on FusionPBX 4.0.
