### ISSUE TITLE
accountcode not set when ip auth'd

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1120]
We have a number of customers who are authenticated by IP

It would seem that the accountcode is not being set on outbound calls for these users despite the calls landing in the right context and seemingly being associated with the right SIP account.

Outbound calls should then have the SIP Header X-Accountcode set ... this is being set but the value is empty for these calls

**Comment by markjcrane** [comment]
http://fusionpbx.com/support.php
