### ISSUE TITLE
phone number format doesn't format numbers with text in them

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1121]
The format_number function only formats pure numbers

                if (is_numeric($phone_number)) {

We have some dialled numbers which have alpha in them as part of a prefix dialled to identify account codes / etc and we need to strip this from the logs / displayed output too

Ideally we would like to be able to perform a more regex like format on the number, but at the very least also strip characters from the displayed text

So for example C123456442035551234 

The number portion is 442035551234 and the account prefix C123456

I want the CDR report to show +44 203 555 1234 (so do something like rrrrrrr +xx xxx xxxx but of course it doesn't work as the initial string is alphanumeric

**Comment by markjcrane** [comment]
I removed is_numeric
echo format_phone('C123456442035551234');
Correct format: rrrrrrr +xx xxx xxx xxxx

Not sure how regex would work with this feature. Something I will consider someday. But I think current format is actually easier.
