### ISSUE TITLE
Provisioning - Extension no longer lists available devices

### ISSUE THREAD

**Issue by fidonet** [fusionpbx/fusionpbx#1131]
Since this patch, the extensions page no longer shows a list of available devices - the dropdown is empty

commit c9f7869de91ffcde918adbed6b9c87bab8250c96
Author: markjcrane <markjcrane@gmail.com>
Date:   Thu Aug 20 20:16:07 2015 -0600

    Move SQL queries out of the content as a best practice and coding standard. Fix number alias when using auth name and auth id.

**Comment by moteus** [comment]
i think it already fixed 6e74b54969410fa27d30cff87e11f6e1e4386e91

**Comment by markjcrane** [comment]
I just confirmed that this is fixed.
