### ISSUE TITLE
Add A Field To Show Total Entires For: Extensions, Devices, Destination.

### ISSUE THREAD

**Issue by KerryDot0** [fusionpbx/fusionpbx#1137]
Often  looking for total numbers of Extensions, or Destination numbers within a Tenant.

Looking for something like what you see in the Registrations page, that shows a total.

Other pages where this would be useful: , User Manager, Vociemail and Devices, Fax Servers.

**Comment by markjcrane** [comment]
Took 2 hours to grant your request changes committed.
