### ISSUE TITLE
Yealink provisioning t23g with authentication, nginx does not send entire configs

### ISSUE THREAD

**Issue by davidwjacob** [fusionpbx/fusionpbx#1138]
debian 7
git commit ed0265b38f4695826c104bd158ed2cac2466fe52 is what im up to on this sys.

When trying to provision t23g phone, if you are using authentication, the pbx does not send the entire common and mac address file to the phone (see pastebin http://pastebin.com/szyQwHsi ). When you turn off authentication, it works every time.

**Comment by davidwjacob** [comment]
is this a known issue? does anyone else have this problem?

**Comment by Len-PGH** [comment]
There was a bug with rewrite rules. Check the install script for the updated rewrite rules.
