### ISSUE TITLE
Callcenter doesn't add domain in contact.

### ISSUE THREAD

**Issue by YanOtt** [fusionpbx/fusionpbx#1141]
Callcenter doesn't add domain for user in contact.

When Fusion is used in the multi-tenant configuration, then the call, which was routed to the callcenter agent, uses the IP address of the server instead of using the domain name of user. 

For this reason it is impossible to determine from which the domain came the call.

**Comment by markjcrane** [comment]
Seems that could be a bug you should report to FreeSWITCH.

**Comment by YanOtt** [comment]
It isn't FS bug.

You must add "sip_invite_domain=${domain}" in the contact field agents of the call center like for other cases for the bridge application.

**Comment by markjcrane** [comment]
Fixed it with this commit.
https://github.com/fusionpbx/fusionpbx/commit/f77cadfbe68fcf2aab73cac757230b1d3d5ab25b
