### ISSUE TITLE
IVR menu pages rename

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#1142]
After making git clone of master (migrating from SVN) it is unable to get into ivr menu app.
Seems to be cause all links in code says about 
/app/ivr_menu/ivr_menus.php
but actual location is
/app/ivr_menus/ivr_menus.php
After moving ivr_menus dir to ivr_menu all is working fine

**Comment by markjcrane** [comment]
You might update your menu with advanced -> menu manager -> restore default.
