### ISSUE TITLE
Update from 3.9 to 4.0

### ISSUE THREAD

**Issue by getsolveit** [fusionpbx/fusionpbx#1148]
The update via.

cd /var/www/fusionpbx
/usr/bin/php /var/www/fusionpbx/core/upgrade/upgrade.php

-----------------------------------------

        Schema:                 No Change

In the GUI show's it 3.9 and the changes are made here not in the files on my machine done.
What can I do?

**Comment by markjcrane** [comment]
The easy way is paid support. If you don't want to do that then follow instructions here.
http://wiki.fusionpbx.com/index.php?title=GIT'
and
http://wiki.fusionpbx.com/index.php?title=Upgrade

**Comment by getsolveit** [comment]
Thank you, now the 
http://wiki.fusionpbx.com/index.php?title=GIT have help me.

**Comment by markjcrane** [comment]
It certainly works I've done it many times.
