### ISSUE TITLE
Issue with New Hot Desking with Provisioning 

### ISSUE THREAD

**Issue by superattack** [fusionpbx/fusionpbx#1151]
The new hot desking with provisioning is a great fusionpbx feature! However there is a small issue - not in particular with the functionality of the feature, but more due to the user behavior. 

People are forgetful creatures. They log in and they forget to logout. This creates problem since the person can’t use the phone device unless she/he knows the password of the previous user that used the particular device. 

More technically presented - the scenario looks like this: 
1. User 1 logs with *11 on "Device 1” with his/her credentials. 
2. User 1 forgets to log out from “Device 1". 
3. User 2 tries to user “Device 1” by inputing his device user & password, but the devices stays unresponsive with “User 1” on the display. 

Although I'm not using the latest FusionPBX version - I’m sure the problem persists in the latest version since I check the script and looks the same as the one I did the test.

**Comment by markjcrane** [comment]
This was fixed in the end of September 2015. Fix available in FusionPBX 4.0.1.
