### ISSUE TITLE
Incorrect variable name for 'sip-force-contact' in directory.lua script

### ISSUE THREAD

**Issue by SJS87** [fusionpbx/fusionpbx#1154]
The 'sip-force-contact' variable in the directory.lua script has been incorrectly labelled as 'sip_force_contact'. This prevent us from using 'NDLB-connectile-dysfunction' or any of the other options for 'sip-force-contact'.

Location: /usr/local/freeswitch/scripts/app/xml_handler/resources/scripts/directory/directory.lua

We should replace the following string:
name="sip_force_contact"

With the updated string:
name="sip-force-contact"

Thanks,
Shaun

**Comment by markjcrane** [comment]
Thanks for pointing this out. It has now been updated to <variable name="sip-force-contact"
