### ISSUE TITLE
CDR error

### ISSUE THREAD

**Issue by clmorre** [fusionpbx/fusionpbx#1156]
Hi,

Currently experiencing this error. Please help .

[ERR] mod_xml_cdr.c:369 Got error [404] posting to web server [http://127.0.0.1/fusionpbx/app/xml_cdr/v_xml_cdr_import.php]
[ERR] mod_xml_cdr.c:376 Retry will be with url [http://127.0.0.1/fusionpbx/app/xml_cdr/v_xml_cdr_import.php]
 [ERR] mod_xml_cdr.c:387 Unable to post to web server, writing to file

and call detail record does not update to the current date.

**Comment by markjcrane** [comment]
This indicates you are most likely using CentOS. Your web server is not configured to accept a POST on 127.0.0.1.  There are many websites that can teach you how to do this.

Debian and FreeBSD are the official supported platform. Paid support can extend support to other platforms.
