### ISSUE TITLE
Feature Request: Docker Container

### ISSUE THREAD

**Issue by LorbusChris** [fusionpbx/fusionpbx#1157]
An official Docker Container would be immensely useful!
I'll close the issue if here isn't the right place for this.

**Comment by kenayagi** [comment]
+1

**Comment by moteus** [comment]
https://github.com/DigiDaz/fusionpbx-docker
It is not `Official` but you can test and improve it.

**Comment by kenayagi** [comment]
Great. I'll give it a try, thanks.
