### ISSUE TITLE
conf/dialplans, conf/directory, and conf/sip_profiles empty

### ISSUE THREAD

**Issue by xil3so** [fusionpbx/fusionpbx#1159]
Hello,
Just fresh installation using [most recent script](https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/ubuntu/install_fusionpbx.sh) on Debian Jessie with apache2 and postgres, so I ended with recommended freeswitch (I believe it's 1.4) and stable fusionPBX 4.0.0.

I've started it step by step using [fusionpbx:GettingStarted](http://wiki.fusionpbx.com/index.php?title=Getting_Started) got stuck at "Outbound Routes" and decided to cross-check everything with SIP trunk provider site, [IPcomms howto](http://www.ipcomms.net/sample-device-configurations/40-freeswitch)
I was, to say the least, stunned when I noticed that there's *nothing* on the disk[1] in the freeswitch directory.

So after quick googling I've found that: [XML_not_saved_to_fs](http://wiki.fusionpbx.com/index.php?title=XML_Handler#XML_not_saved_to_the_file_system) but, to my amazement, it's presented as an *option*, not default behaviour, so I thought something is wrong with my installation. 
Of course I tried to switch that functionality off (i.e. to switch those options mentioned [before](http://wiki.fusionpbx.com/index.php?title=XML_Handler#XML_not_saved_to_the_file_system) to True, to remove empty.xml from mentioned directories, to comment out "app.lua xml_handler" in conf/autoload_configs/lua.conf.xml ) and to restart freeswitch, but it didn't worked = 
1) gateways/extensions/whatnot already set in fusionpbx wasn't saved to disk
2) when I created new gateway/extension/anything nothing is saved to the respective directory.
3) some remainings of the old behaviour are still visible - i.e. under Accounts > Destination there are still my destinations visible, and under Accounts > Gateways there is old gateway shown but with Status=stopped (disabling/enabling/clicking Start doesn't start it).

Pretty please - 
1). DO NOT make that behaviour default in fusionPBX - I understand it makes user experience smoother but it breaks bonds between freeswitch and fusionpbx completely - I did not installed fusionpbx to let it replace my freeswitch installation but to *manage* my freeswitch - I believe that's huge, substantial difference.
2). provide way to go back - i.e. to flush changes from database to disk (and/or otherwise).

Thank you.

Personally I adore FusionPBX and thanks to it freeswitch' learning curve is not that steep, but.... as stated above.

[1] i.e. in /usr/local/freeswitch/conf/*

**Comment by markjcrane** [comment]
XML files are still possible like it was possible before. Only the default has changed.

1. "DO NOT make that behaviour default in fusionPBX"
It is already a default in FusionPBX 4.0

 "breaks bonds between freeswitch and fusionpbx completely"
I don't agree it still uses the same XML just delivers it on demand. You simply need a little more training. The XML is accessible using memcache and with a few minor changes can have it stored for review on the file system.

2. This is possible you did most of the steps that would be needed.
You might not have cleared you PHP session by logging out and back in and then go into the gui to save the extensions, dialplans, and gateways and sip profiles?

p.s. Your outbound route is problem is probably caused by limit.lua. Edit your outbound route and if you see a line that says limit.lua delete it. This was added by developers in Italy when we were on google code. It is now hidden by behind a permission by default on the dev branch but you are on the stable branch. I'll get a new revision of 4.0.x out soon to address this.

**Comment by xil3so** [comment]
Hello Mark,
Thank you for your answers.

1. I know it's default, I simply meant it's a... maybe not the best thing. Could you please consider, at least, adding something like "\" to your empty.xml files and update that page with information that's default now and that memcached thing?
2. Actually today I tried to go back (I mean, to default config) and didn't manage to get them on the disk, so I tried to go to "on the disk" again and they didn't appear (after freeswitch restart and my logout/login to FusionPBX - you were right, I didn't do that, it wasn't mentioned on that [page](http://wiki.fusionpbx.com/index.php?title=XML_Handler) and it wasn't obvious to me) - I had to create some dummy entry in gateways, extensions and inbound/outbound routes to see all the files saved to disk - just saving existing entries was not enough).

Thanks for your limit.lua remark - although it's not the case (as far as I believe - I can't see it anywhere neither in FusionPBX interface nor on the disk, where my xml files are (I hope) being saved) - currently I'm fighting with 404/Not found* when dialing from my SIP client, but that's obviously some mistake from my side. Keeping things simple will definitely helps - this is why I was so upset when I noticed there is nothing on the disk :)

Thank you for your work so far, and for your help, too.

*) 2015-09-17 21:19:43.777913 [INFO] mod_dialplan_xml.c:635 Processing +000 <101>->+16284xxxxxx in context public
2015-09-17 21:19:43.777913 [WARNING] mod_dialplan_xml.c:665 Context public not found
2015-09-17 21:19:43.777913 [INFO] switch_core_state_machine.c:241 No Route, Aborting

**Comment by markjcrane** [comment]
XML handler is the best way to go to scale for a number of reasons and it is still possible to see the XML for example using:
memcache get dialplan:public
memcache get directory:101@domain

For more information you consider the admin training class which covers this in more detail.
