### ISSUE TITLE
Fax server does not forward e-mail or fax when the field "forward Number" has a valid extension

### ISSUE THREAD

**Issue by msergius** [fusionpbx/fusionpbx#1160]
FusionPBX version 4.0.0
Freeswitch: 1.4.15

How to produce the problem.
Fax server does not forward received faxes to e-mail or fax extension when the field "forward Number" has a valid extension.

Fax server is receiving faxes all the time but when the field "forward Number" has a valid extension, it doesn't forward the fax received to the email or to that extension but we remove the extension from
the "forward Number" field it sends it to the email.

![fax scr](https://cloud.githubusercontent.com/assets/14182404/10028525/f36ca7de-613a-11e5-9375-c5d63fd1c98d.jpg)

**Comment by andyfor** [comment]
I tested this a few weeks ago using v4.0 and it seemed fine. Was using an HT502 ATA with T38 enabled as the extension and connected ATA to a fax machine. Also set fax_enable_t38_request=true in Advanced>Default Settings>Fax.
Was successfully receiving email and getting it to print out on the fax machine. A lot of variables at play of course but just in case this helps you troubleshoot.

**Comment by msergius** [comment]
Hi Andy,
Thank you for your comment but we have tried that and it did not work.

**Comment by msergius** [comment]
In the attached picture you will find the fax server settings, when we put any valid extension in the field "Forward Number" no faxes could be sent to the fax destination or to the email but when we removed the extension from that field it has been sent to the email but not to the fax destination.

![fax scr](https://cloud.githubusercontent.com/assets/14182404/10028488/ce12f5b0-613a-11e5-9174-6608e6d9da8a.jpg)

**Comment by andyfor** [comment]
Any clues from the fax server logs when it fails? Worth checking active calls and the log viewer (and CDRs too) as sometimes between them you can at least get some pointers. There were some bugs at one point in early v4 where the fax TIF image was not being stored in the correct inbox for that extension. mcrane fixed this though. Assume you have latest version (i.e. upgraded). I found it through the fax logs.

**Comment by msergius** [comment]
Hi Andy,
we found the below record from the log viewer that may help:

bd0684bc-xxxx-11e5-9bb7-ad7870dea1cc Dialplan: sofia/internal/xxxxxxxxxxx@x.x.x.x Regex (FAIL) [user_exists] ${user_exists}(false) =~ /^true$/ break=on-false

Andy can you locate the fix details that has been resolved by upgrading?

Thank you

**Comment by andyfor** [comment]
Not sure this is an error, just means that the dialplan regex didn't match. Likely see this a lot in the log viewer. e.g. failed match for local extension, or 7 digit dialing etc.

**Comment by markjcrane** [comment]
This should be fixed in latest 4.0.1 - Master branch. Please confirm.

**Comment by msergius** [comment]
Hi Mark,
That is right, Thank you.

**Comment by msergius** [comment]
Hi Andy,

Sorry for not keep you posted, the issue has been fixed by the upgrade.
Thank you so much for your support
