### ISSUE TITLE
Codecs when sending a Fax

### ISSUE THREAD

**Issue by badcrc** [fusionpbx/fusionpbx#1162]
When sending a fax, the following command is issued to freeswitch from app/fax/fax_send.php

```
$cmd = "api originate {for_fax=1,absolute_codec_string='PCMU,PCMA',accountcode='".$fax_accountcode."',sip_h_X-accountcode='".$fax_accountcode."',domain_uuid=".$_SESSION["domain_uuid"].",domain_name=".$_SESSION["domain_name"].",mailto_address='".$mailto_address."',mailfrom_address='".$mailfrom_address."',origination_caller_id_name='".$fax_caller_id_name."',origination_caller_id_number='".$fax_caller_id_number."',fax_ident='".$fax_caller_id_number."',fax_header='".$fax_caller_id_name."',fax_uri=".$fax_uri.",fax_file='".$fax_file."',fax_retry_attempts=1,fax_retry_limit=20,fax_retry_sleep=180,fax_verbose=true,fax_use_ecm=off,".$t38."api_hangup_hook='lua fax_retry.lua'}".$fax_uri." &txfax('".$fax_file."')";
```

The absolute_codec_string='PCMU,PCMA' means that it should offer both codecs in the first call before re-Inviting to T.38 (https://wiki.freeswitch.org/wiki/Variable_absolute_codec_string)

But what I'm getting is only one codec being sent:

```
.
v=0.
o=FreeSWITCH 1442461082 1442461083 IN IP4 aaa.bbb.ccc.ddd.
s=FreeSWITCH.
c=IN IP4 aaa.bbb.ccc.ddd.
t=0 0.
m=audio 22710 RTP/AVP 8 101 13.
a=rtpmap:8 PCMU/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=ptime:20.
```

This is also found in fax_retry.lua

I have found this thread: http://lists.freeswitch.org/pipermail/freeswitch-users/2011-July/074699.html which relates to https://freeswitch.org/jira/browse/FS-2126  but seems that FusionPBX uses {} so it should work as expected.

Could this be a FreeSWITCH bug or can someone confirm this problem? my version is:
FreeSWITCH Version 1.5.15b+git~20150420T021147Z~777c1154ee~64bit (git 777c115 2015-04-20 02:11:47Z 64bit)

Thanks!

**Comment by markjcrane** [comment]
I also noticed when setting absolute_codec_string='PCMU,PCMA' it only uses the first codec. I tried alternate syntax which also failed so I removed absolute_codec_string.
