### ISSUE TITLE
Access Controls don't write acl.conf or acl.conf.xml

### ISSUE THREAD

**Issue by getsolveit** [fusionpbx/fusionpbx#1163]
Access Controls don't write in the acl.conf or acl.conf.xml

**Comment by markjcrane** [comment]
They don't need to write to acl.conf.xml. By default we use the xml handler
in 4.0 which hands out the xml.

**Comment by getsolveit** [comment]
Ok, but I have change a line in the acl.conf and than it works, without changing this line, no calls are incoming, because the error was:

IP x.x.x.x was deny by acl ‘domains’ …

Von: FusionPBX [mailto:notifications@github.com]
Gesendet: Sonntag, 20. September 2015 21:50
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)

They don't need to write to acl.conf.xml. By default we use the xml handler
in 4.0 which hands out the xml.

**Comment by markjcrane** [comment]
acl.conf.xml will get renamed to acl.conf which disables it. Its then expected that you are using XML handler if not look at the wiki and set it up. Then the xml handler will deliver the ACL automatically using information in the GUI at Advanced -> Access Controls. I don't see a bug here so closing the issue.

**Comment by getsolveit** [comment]
Acl.conf.xml is renamed to acl.conf but i get the same error. XML Handler for sip_profiles, dialplan and directory are enable.

IP 10.0.2.13 Rejected by acl "domains". Falling back to Digest auth.
SIP auth challenge (INVITE) on sofia profile 'internal' for [+123456@1.2.3.4] from ip 10.0.2.13

In the GUI at Advanced -> Access Controls are a second line for the ip 10.0.2.13 in domains.


Von: FusionPBX [mailto:notifications@github.com]
Gesendet: Sonntag, 20. September 2015 23:20
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)


acl.conf.xml will get renamed to acl.conf which disables it. Its then expected that you are using XML handler if not look at the wiki and set it up. Then the xml handler will deliver the ACL automatically using information in the GUI at Advanced -> Access Controls. I don't see a bug here so closing the issue.

**Comment by fidonet** [comment]
Hi

Do you have a screen shot of the ACL settings you’ve configured?

You should have something like 

Name: Domains
Default: deny

and then under nodes
Type - allow
CIDR - 10.0.2.0/24


domain should be empty

— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by getsolveit** [comment]
Hi,

yes, I have,

and what you write, I have configured.

[cid:image001.png@01D0F407.C9BD5000]
But there was an other line like:

Type allow
CIDR empty
Domain 10.11.2.12 ( is the domain from the fusionpbx )

But it don’t work if the line is there or is the line not there.

KR
Oliver

Von: fidonet [mailto:notifications@github.com]
Gesendet: Montag, 21. September 2015 00:45
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)

Hi

Do you have a screen shot of the ACL settings you’ve configured?

You should have something like

Name: Domains
Default: deny

and then under nodes
Type - allow
CIDR - 10.0.2.0/24


domain should be empty

—
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by fidonet** [comment]
You can’t have the IP address and domain in the same line .. it causes “confusion”

don’t forget to flush memcache and reloadacl once you update the ACL

— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by getsolveit** [comment]
No, not the same line. But like the screen, it don’t work.

I have restart freeswitch, is this not enough ?

KR
Oliver

Von: fidonet [mailto:notifications@github.com]
Gesendet: Montag, 21. September 2015 01:01
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)

You can’t have the IP address and domain in the same line .. it causes “confusion”

don’t forget to flush memcache and reloadacl once you update the ACL

—
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by getsolveit** [comment]
Flush memcache have done that.

Thanks for your help. Can I pay for this please? Can you send an invoice?

KR
Oliver

Von: fidonet [mailto:notifications@github.com]
Gesendet: Montag, 21. September 2015 01:01
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)

You can’t have the IP address and domain in the same line .. it causes “confusion”

don’t forget to flush memcache and reloadacl once you update the ACL

—
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by fidonet** [comment]
restarting freeswitch doesn’t clear memcache

You’d need to restart memcache too

or just issue a “memcache flush” in fs_cli


— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by fidonet** [comment]
Hi

No charge from me … but if you want to make a donation to the fusionpbx development / support fund I’m sure Mark would be delighted

You can donate here http://fusionpbx.com/contribute.php <http://fusionpbx.com/contribute.php>


— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby

**Comment by markjcrane** [comment]
You need to add configuration to the lua.conf.xml under xml handler where
you have directory and dialplan.

Mark

**Comment by getsolveit** [comment]
Ah ok,

sorry.

I have donate on this site for fusionpbx development.

Thanks a lot for your help.

KR
Oliver

Von: fidonet [mailto:notifications@github.com]
Gesendet: Montag, 21. September 2015 01:09
An: fusionpbx/fusionpbx <fusionpbx@noreply.github.com>
Cc: getSolve IT <info@getsolve-it.de>
Betreff: Re: [fusionpbx] Access Controls don't write acl.conf or acl.conf.xml (#1163)

Hi

No charge from me … but if you want to make a donation to the fusionpbx development / support fund I’m sure Mark would be delighted

You can donate here http://fusionpbx.com/contribute.php <http://fusionpbx.com/contribute.php>


—
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido / skype://jmorby
