### ISSUE TITLE
Patch to install.sh.  Allow env to set params- avoid md5 mismatch complaint.

### ISSUE THREAD

**Issue by hcoin** [fusionpbx/fusionpbx#1166]
Consider whether  'Auto' installs should allow preset parameters to differ from defaults without triggering blocking question re: md5 mismatch.

Something like this:

--- install_fusionpbx.sh	2015-09-23 13:12:34.203283667 -0500
+++ install_fusionpbxb.sh	2015-09-23 13:31:30.815649696 -0500
@@ -32,17 +32,17 @@
 #Variables are for the auto installation option.
 
 #for apache set to a, for nginx/php-fpm set to n -> for an auto install, user mode will prompt
-APACHENGINX=n
+APACHENGINX=${APACHENGINX=n}
 
 # for mysql set m. for sqlite set s. for postgresql set p
-SQLITEMYSQL=p
+SQLITEMYSQL=${SQLITEMYSQL=p}
 
 # for postgresql v 9.0 (from ppa) set to 9
 # must set SQLITEMYSQL to p
-POSTGRES9=9
+POSTGRES9=${POSTGRES9=9}
 
 # to start FreeSWITCH with -nonat option set SETNONAT to y
-SETNONAT=y
+SETNONAT=${SETNONAT=y}
 
 # rm -Rf /opt? A default install doesn't have /opt so no worries
 # if you do, set to no, and it will link /usr/local/freeswitch to /opt/freeswitch
@@ -50,7 +50,7 @@
 #RMOPT=y
 
 # use freedtm/dahdi? y/n
-DO_DAHDI=n
+DO_DAHDI=${DO_DAHDI=n}
 
 # default distro
 #DISTRO=precise

**Comment by markjcrane** [comment]
We use a different install script by default now.
