### ISSUE TITLE
switch/dialplan/conf/domain.dom.xml empty.

### ISSUE THREAD

**Issue by elmemis** [fusionpbx/fusionpbx#1172]
When create a new domain (example.com) via GUI, generate /usr/local/freeswitch/dialplan/conf/example.com.xml empty.

I think it should be generated with the following contents:
[code]
<?xml version="1.0" encoding="utf-8"?>
<include>
<context name="example.com">
	<X-PRE-PROCESS cmd="include" data="example.com/*.xml"/>
</context>
</include>
[/code]
I use git version update to day.

**Comment by elmemis** [comment]
I use git version update to day.

**Comment by elmemis** [comment]
FIX:
cp -p /var/www/fusionpbx/resources/templates/conf/dialplan/default.xml.noload /var/www/fusionpbx/resources/templates/conf/dialplan/default.xml

**Comment by markjcrane** [comment]
By default fusionpbx uses the XML handler in version 4.0. If upgraded from an earlier version you would want to use update it as well to used the XML handler. If using XML handler then writing the file is not needed. Unless your goal is to skip XML handler and use XML on the file system.
