### ISSUE TITLE
Default Yealink Configuration Not Found

### ISSUE THREAD

**Issue by thebitguru** [fusionpbx/fusionpbx#1184]
I am auto provisioning a Yealink T32G phone using FusionPBX's provisioning functionality.  I noticed that the `Advanced > Provision Editor` shows `y000000000032.cfg` under `yealink/t32g/y000000000032.cfg`, but when I try to get the file through nginx (`https://my_host_name/y000000000032.cfg`) I get `file not found` as the body of the response.  My phone's MAC address specific URL returns the expected configuration (which does _not_ have the content of the common file in it).

The MAC specific configuration is being applied correctly, but since the common file is not being sent, the phone has the wrong time zone, etc.

Does anyone know why this file is not being found or returned?

**Comment by thebitguru** [comment]
Anyone?

**Comment by fidonet** [comment]
You need to set the User Agent string if you’re faking the call from a web browser

Your user agent needs to be the same as the phone would send

The time zone settings aren’t configured in the base template by default I don’t think .. you need to set the variables in Fusion and make sure they’re used in the right place in the config files

Jon

> On 5 Oct 2015, at 06:01, Farhan Ahmad <notifications@github.com> wrote:
> 
> I am auto provisioning a Yealink T32G phone using FusionPBX's provisioning functionality. I noticed that the Advanced > Provision Editor shows y000000000032.cfg under yealink/t32g/y000000000032.cfg, but when I try to get the file through nginx (https://my_host_name/y000000000032.cfg) I get file not found as the body of the response. My phone's MAC address specific URL returns the expected configuration (which does not have the content of the common file in it).
> 
> The MAC specific configuration is being applied correctly, but since the common file is not being sent, the phone has the wrong time zone, etc.
> 
> Does anyone know why this file is not being found or returned?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fusionpbx/fusionpbx/issues/1184>.
> 

— 
Jon Morby
FidoNet - the internet made simple!
tel: 0345 004 3050 / fax: 0345 004 3051
twitter: @fido | skype://jmorby <skype://jmorby> | web: https://www.fido.net

**Comment by thebitguru** [comment]
Thanks for the response, Jon.  You are right, my browser requests were the problem.  When the request for y000000000032 comes from the phone then it seems to work fine.  The Yealink timezones is correct in the FusionPBX config, but the phones aren't picking it up.

I will see if I can emulate the call from the browser and confirm that the configuration is correctly being sent to the phone.

**Comment by thebitguru** [comment]
I used the [user agent switcher](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg?hl=en-US) Chrome extension to change the user agent.  For Yealink I set the user agent to ```Yealink SIP-T32G  32.70.1.33 XX:XX:XX:XX:XX:XX```.  Make sure to replace the X's with the actual MAC address, otherwise it won't work.
