### ISSUE TITLE
Eavesdrop not working

### ISSUE THREAD

**Issue by SJS87** [fusionpbx/fusionpbx#1192]
We've been experiencing problems getting eavesdrop to work as the LUA script includes the *33 (star service key) for the extension, so it can't find the extension as it doesn't exist.

We've resolved this problem by adding the following to eavesdrop.lua (line 30 to 32) which removes the *33 prefix:

	if (string.sub(extension, 1, 3) == "*33") then
		extension = string.sub(extension, 4, -1);
	end

**Comment by markjcrane** [comment]
I appreciate the notification of the problem however I modified the dialplan condition to remove the *33 prefix like this: <condition field="destination_number" expression="^\*33(\d{2,7})$"> and <condition field="destination_number" expression="^\*33(\d{2,7})$">. This allows the prefix to be changed without requiring the lua code to be modified.
