### ISSUE TITLE
Outbound Caller id 0000

### ISSUE THREAD

**Issue by tsv1991** [fusionpbx/fusionpbx#1196]
Hi. When registering an IP gateway (No login and password) outgoing Caller ID is equal to 0000. I tried to put in extension caller id but it did not help.

**Comment by DigiDaz** [comment]
There is no such thing as extension caller id, there is effective caller id and outbound caller id.

The number you present externally should go in outbound caller id

**Comment by markjcrane** [comment]
No response and this is definitely not a bug but a configuration issue. Closing the issue.
