### ISSUE TITLE
Call Detail Record

### ISSUE THREAD

**Issue by clmorre** [fusionpbx/fusionpbx#1208]
Hi,

one of my Tenant is not showing CDR anymore, but other do. When I log in to that tenant and check CDR, this is what I get.

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /var/www/html/fusionpbx/app/xml_cdr/xml_cdr_inc.php:262 Stack trace: #0 /var/www/html/fusionpbx/app/xml_cdr/xml_cdr_inc.php(262): PDOStatement->execute() #1 /var/www/html/fusionpbx/app/xml_cdr/xml_cdr.php(54): require_once('/var/www/html/f...') #2 {main} thrown in /var/www/html/fusionpbx/app/xml_cdr/xml_cdr_inc.php on line 262

Please help

**Comment by markjcrane** [comment]
Sounds like a PHP PDO and MySQL bug try a different version of PHP. Try updating your OS if using debian / ubuntu you would do that with.
apt-get update
apt-get upgrade
p.s. PostgreSQL is the recommended database.
