### ISSUE TITLE
Call Forward

### ISSUE THREAD

**Issue by shishiradhikari** [fusionpbx/fusionpbx#1221]
What steps will reproduce the problem?
User sets call forward to a destination number (*74) => Fusion PBX call forward for the extension gets updated.

What is the expected output? What do you see instead?
But call forward is not coming into effect until and unless pressing 'Save' manually in FusionPBX

What version of the product are you using? On what operating system?
FusionPBX version: 3.8.4
Freeswitch version:  Version 1.4.23 git 9fcf3e0 2015-10-23 15:21:55Z 64bit
OS: CentOS 6.7 x64

**Comment by elfranne** [comment]
Was having issues with call forward with version 3.8.4, but they are fixed in 4.x

**Comment by shishiradhikari** [comment]
My FusionPBX is in production. Can you advise how can i upgrade it to 4.x without affecting other functionalities?

**Comment by moteus** [comment]
Feature Codes for dnd/follow me/callforward  works only if you use xml handler.

**Comment by markjcrane** [comment]
You can call on monday for help on this or follow these instructions to upgrade to 4.0.1 to fix this problem.
http://wiki.fusionpbx.com/index.php?title=GIT
http://wiki.fusionpbx.com/index.php?title=Upgrade#Version_3.8_to_4.0
http://wiki.fusionpbx.com/index.php?title=XML_Handler
