### ISSUE TITLE
Do Not Disturb (DND)

### ISSUE THREAD

**Issue by shishiradhikari** [fusionpbx/fusionpbx#1222]
What steps will reproduce the problem?
User sets DND (*78) => gets updated in FusionPBX 
OR 
Admin sets DND for the extension in FusionPBX

What is the expected output? What do you see instead?
Doesn't forward to Voice Mail of the user/extension. 
(CLI error: Application Not found)

What version of the product are you using? On what operating system?
FusionPBX version: 3.8.4
Freeswitch version: Version 1.4.23 git 9fcf3e0 2015-10-23 15:21:55Z 64bit
OS: CentOS 6.7 x64

**Comment by markjcrane** [comment]
You need to upgrade to FusionPBX 4.0.1
