### ISSUE TITLE
Ring Group - Only 1 External Number is Rung

### ISSUE THREAD

**Issue by voicearray** [fusionpbx/fusionpbx#1232]
Hi, I have FusionPBX 4.0.1 (PostgreSQL) on Deb 8.1 with FreeSWITCH (Version 1.4.23  64bit). I have a ring group (602) setup to ring three internal extensions (401, 402, 410m 412) and 2 external phone numbers with the confirm options. 

When that ring group is dialed (602) it rings the internal extensions and the first external phone number but it does not attempt to dial the second external phone number.

Thank you for your help.

**Comment by moteus** [comment]
Did you test [this fix](https://github.com/fusionpbx/fusionpbx/commit/53702b1973adcb9a8cd5c0abcb4120bf4c54bd1f)?

**Comment by voicearray** [comment]
I have made the change in /var/www/fusionpbx/resources/install/scripts/app/ring_groups/index.lua
The code was found under line 524 and was changed from "|" to delimiter. 

OLD: dial_string = dial_string .. "|" .. square .."]"..dialplan_detail_data;
NEW: dial_string = dial_string .. delimiter .. square .."]"..dialplan_detail_data;

Do I need to reboot or restart anything? Calls to ring group 602 are still only bring rung to one outside external mobile number.

**Comment by markjcrane** [comment]
This was fixed in master branch yesterday by changing | to the delimiter. Reboot is not needed. It solved the problem for the person I was working with.

**Comment by voicearray** [comment]
I have confirmed that the change is present in the  /var/www/fusionpbx/resources/install/scripts/app/ring_groups/index.lu 

I have also reapplied permissions to the file. I also did Advanced Upgrade and then Source Code, Schema, and App Defaults. 

I attempted to do SVN Update but that did not do anything do I do a Git Update?

**Comment by markjcrane** [comment]
SVN is deprecated Google code is read only and shutting down soon. So if you are using subversion now then you are not up to date. Follow these instructions.

http://wiki.fusionpbx.com/index.php?title=GIT
http://wiki.fusionpbx.com/index.php?title=XML_Handler

**Comment by voicearray** [comment]
I have followed the instructions and switched to GIT (it was already on GIT) and XML_Handler (it was already setup). 

I am on the latest version but still I am experiencing the same issue.

**Comment by voicearray** [comment]
Update: It seems to have started to work. I deleted the outbound round and recreated it.

**Comment by akgautam** [comment]
Issue is still in latest version
