### ISSUE TITLE
COMPILE ERROR: 1 [nothing to repeat]

### ISSUE THREAD

**Issue by kismetgerald** [fusionpbx/fusionpbx#1286]
Hey folks,

I'm sure this may not be a big issue, but I figured I'd report it anyway.  I've noticed the following error line in the FS console on an inbound fax call.

```
2015-12-05 08:18:33.507525 [ERR] switch_regex.c:104 COMPILE ERROR: 1 [nothing to repeat][^+13013229000$]
```

I see this same error on all the servers I'm running - all Debian 8.1 x64.

**Comment by moteus** [comment]
Worng regex. should be `^\+....`

**Comment by kismetgerald** [comment]
@moteus  I'm assuming this wouldn't be something I can fix locally, as I don't even know where to begin to look.

**Comment by moteus** [comment]
I suspect it should be in some inbound routes. But to figureout need more information.

**Comment by kismetgerald** [comment]
Hmm, I'm not sure what other information to provide.  I'm happy to assist if you'll tell me what you need me to provide.

**Comment by moteus** [comment]
I think this is not fusion error but error in configuration.
Try ask on irc channel `#fusionpbx`.
Better is also add some additional logs prior this error (put it on some external service like pastebin)

**Comment by markjcrane** [comment]
This simply means that your inbound call has destination_number with a plus (+) in it. FreeSWITCH uses regular expressions the + has a special meaning and has to be escaped. This is the reason for the minor error. Currently only way I'm aware to fix it is to create an inbound route that removes the +.

**Comment by kismetgerald** [comment]
@markjcrane 

Thanks for the response.  If this is a minor error, then I'm fine ignoring it.  However, in order to aid my learning I'd really like to know how to escape the +.  It seems the caller ID# of the caller contains the + - I can see this in the console log.

**Comment by markjcrane** [comment]
You have to remove the escape is \+ but you would have to add that to the caller id number to escape it. However this would cause a problem where caller id number would have \+ in areas you don't want it. So igore the minor issue or remove the +.
