### ISSUE TITLE
casperjs cannot make cross domain ajax requests

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#1290]
There are many post talking it is fixed in 1.0.x, but in 1.1b3 it fails :(

[warning] [remote] getBinary(): Unfortunately, casperjs cannot make cross domain ajax requests
[error] [remote] getBinary(): Error while fetching https://XXXXXXX/forms/details_request.aspx?dxrep_fake=&baseTable=W&tableID=2120792: Error: NETWORK_ERR: XMLHttpRequest Exception 101

**Comment by markjcrane** [comment]
Why are you reporting this here rather than casperjs? This is a non fusionpbx issue.
