### ISSUE TITLE
Call flow ivr greeting.

### ISSUE THREAD

**Issue by volga629** [fusionpbx/fusionpbx#1318]
Hello Everyone,
I want place request to add ability change ivr greeting through flow call. 
Case.

```
Bad weather. 
Dial *45 in to switch ivr greeting from main greeting to bad weather "Welcome, due bad weather office will opened from noon..."

```

**Comment by markjcrane** [comment]
This us already possible by using the greeting id. You can call recordings dialpan and change the same greeting I'd anytime you want to.
