### ISSUE TITLE
Mod_Memcache Not Loaded [Latest Installer / FreeSWITCH v1.6.5]

### ISSUE THREAD

**Issue by kismetgerald** [fusionpbx/fusionpbx#1329]
Just a quick FYI to note my observations while using the latest installer to install FusionPBX and FreeSWITCH v1.6.5.  I did a clean install three times and in all instances I observed the following

1.  **Install fails unless I run the following commands as displayed here** https://freeswitch.org/confluence/display/FREESWITCH/Debian+8+Jessie#Debian8Jessie-Buildingfromsource
![snap 2015-12-14 at 02 58 31](https://cloud.githubusercontent.com/assets/14914151/11775648/8f09b7d6-a20e-11e5-8648-fe6d90c62be8.png)
2. **Mod_Memcache is not loaded, despite all indications to the contrary that it was compiled and built successfully.**  The only resolution I found was to copy the missing two files "*mod_memcache.la*" and "*mod_memcache.so*" from a working system to the mods folder

**Comment by markjcrane** [comment]
This is working in the latest install script.
