### ISSUE TITLE
Feature request: Add restriction for user to see only his domain in dialplan(routes) edit screen.

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#1338]
Right now, if I want to set someone to edit his domain fully by himself, I cannot do this. Cause on a screen of editing rule or route, I can see all domains in drop-down menu. 
Request - to add parameter to lock this dropdown menu only to customer's domain.

**Comment by markjcrane** [comment]
A user in the superadmin group can see all gateways for all domains. A user in the admin group sees only gateways in their domain.

**Comment by samael33** [comment]
No, means in dialplan edit dialog.
Like http://prntscr.com/9n2rzu
I can set for an admin of domain can edit this by himself, but he can see other domains in drop-down menu.

**Comment by markjcrane** [comment]
The dialplan edit tool is too powerful to give to a user in the admin group for multiple reasons. You have mentioned one reason but there are many reasons that an admin should not have access to dialplan edit. If you do so you compromise your security in at least 5 ways.

**Comment by samael33** [comment]
In this case no true "self-service" is possible. But many of clients can live with that :) Thanks :+1:

**Comment by markjcrane** [comment]
One of your admin could use it to remove the freeswitch conf directory or remove the freeswitch files. Could be used to send calls out another tenants outbound route. Or send calls to disa oe to eavesdrop or intercept calls from other domains.  That is just the first things that come to mind I'm sure there is more.

**Comment by markjcrane** [comment]
Be careful with permission defaults are as they are for a reason.
