### ISSUE TITLE
module 'resources.config' not found:

### ISSUE THREAD

**Issue by rajil** [fusionpbx/fusionpbx#1353]
I installed fusionpbx v4.0 with FS 1.6.5 under FreeBSD. When i start freeswitch, i get the following error:

2015-12-30 18:23:09.198602 [ERR] mod_lua.cpp:203 .../local/freeswitch/scripts/resources/functions/config.lua:22: module 'resources.config' not found:
        no field package.preload['resources.config']
        no file '/usr/local/freeswitch/scripts/resources/config.lua'
        no file '/usr/local/lib/lua/5.2/resources/config.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources/config.so'
        no file '/usr/local/lib/lua/5.2/resources.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources.so'
stack traceback:
        [C]: in function 'require'
        .../local/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
        .../local/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
        [C]: in function 'require'
        /usr/local/freeswitch/scripts/app.lua:28: in main chunk
2015-12-30 18:23:09.198608 [ERR] mod_lua.cpp:270 LUA script parse/execute error!

**Comment by markjcrane** [comment]
autoload_configs/lua.conf.xml the script directory is likely not defined or might be incorrect.

**Comment by rajil** [comment]
After doing an Advanced/Upgrade, and restarting FS this error went away.
