### ISSUE TITLE
IVR greeting causes IVR failure

### ISSUE THREAD

**Issue by DigiDaz** [fusionpbx/fusionpbx#1359]
When selecting an IVR greeting that has been uploaded using the recordings app, the IVR fails to work.

It seems that the IVR is seeking the recording from /usr/local/freeswitch/sounds/en/us/callie/ rather than from /usr/local/freeswitch/recordings/domainname

**Comment by markjcrane** [comment]
I'm unable to reproduce this problem.

**Comment by markjcrane** [comment]
Run this from fs_cli or advanced -> command -> switch command.
global_getvar recordings_dir

Working with someone with this problem I believe freeswitch reports a different path to the recordings dir than what is stored in fusionpbx in advanced -> default settings -> switch -> recordings.

**Comment by DigiDaz** [comment]
freeswitch@internal> global_getvar recordings_dir
/usr/local/freeswitch/recordings

**Comment by DigiDaz** [comment]
Retested on latest build, all working fine.
