### ISSUE TITLE
Local extensions couldn't call each other

### ISSUE THREAD

**Issue by blackyzero** [fusionpbx/fusionpbx#1363]
Hello,

i am using latest fusionpbx from GiT repo, running on FreeBSD 10.2, and facing the issue with multi tenant.
The local extensions couldn't call each other, even they are showing as registered status.
i am using default dialplan which comes with fusionpbx and custom profile with port 5090 (copied from external profile)

They can call outside via SIP provider.
The log file is attached in this message.

Please advice me how to fix this.
Thank you.

[FS_log_2.txt](https://github.com/fusionpbx/fusionpbx/files/78636/FS_log_2.txt)

**Comment by markjcrane** [comment]
Call for support.

**Comment by blackyzero** [comment]
i am very new to freeswitch, and it really make me confuse to make it works 
i don't know if selecting freeswitch and fusionpbx is good decision as it costs for support service :(

**Comment by markjcrane** [comment]
You can learn it on your own by documentation, irc, trial and error. Or you can save a lot of time with paid support. 1 hour can likely save you 10 hours or more. PBX / Phone systems and Voice Switches and Gateways have traditionally cost a large amount of money. FusionPBX has features and a design that are well worth your time or money. And cost or time savings to you are very good.

Hint
Are the SIP profiles running? Check by going in the web interface to menu -> advanced -> sip profiles If not then you need to look at fixing your database access.

You did a manual install for FreeBSD this means more work to get everything running and you may have missed something. Like FreeSWITCH database access did you choose PostgreSQL as the database or SQLite or something else? If you chose PostgreSQL (great choice) you need to add the Postgres driver during the 'configure'. If using MySQL you need to setup ODBC (harder). SQLite (easiest) support for SQLite is native in FreeSWITCH.

We will have an official FreeBSD install script sometime this year.

**Comment by moteus** [comment]
I have some notes.
1. I think github issues is more bug trucker / feature reques. You have problem with install/configure. So I think you better ask this question on IRC.

2.
>Dialplan: sofia/sip.domain1.com/1201@sip.domain1.com Action set(user_exists=${user_exists id ${destination_number} ${domain_name}}) INLINE
EXECUTE sofia/sip.domain1.com/1201@sip.domain1.com set(user_exists=false)

This means that there no such extension in database (does 1200@sip.domain1.com can register). I can not say more without more info.

3. 
>i am using default dialplan which comes with fusionpbx and custom profile with port 5090 (copied from external profile)

I think `external` profile does not support calls between extensions by default.
.
PS. I prefer do not continue this convirsation here.
