### ISSUE TITLE
Lua script error

### ISSUE THREAD

**Issue by blackyzero** [fusionpbx/fusionpbx#1374]
Hello,

I am getting following error when making a inbound call, could you please instruct me how to fix this.
I am running FS on FreeBSD 10, and lua52 is already installed. Thank you.

2016-01-06 11:59:41.873365 [ERR] mod_lua.cpp:203 /usr/local/freeswitch/scripts/resources/config.lua:46: module 'resources.functions.file_exists' not found:
        no field package.preload['resources.functions.file_exists']
        no file '/usr/local/share/lua/5.2/resources/functions/file_exists.lua'
        no file '/usr/local/share/lua/5.2/resources/functions/file_exists/init.lua'
        no file '/usr/local/lib/lua/5.2/resources/functions/file_exists.lua'
        no file '/usr/local/lib/lua/5.2/resources/functions/file_exists/init.lua'
        no file './resources/functions/file_exists.lua'
        no file '/usr/local/lib/lua/5.2/resources/functions/file_exists.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources/functions/file_exists.so'
        no file '/usr/local/lib/lua/5.2/resources.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/freeswitch/scripts/resources/config.lua:46: in main chunk
        [C]: in function 'dofile'
        /usr/local/freeswitch/scripts/app.lua:29: in main chunk

**Comment by markjcrane** [comment]
Most likely you don't have freeswitch/conf/autload_configs/lua.conf.xml scripts directory needs to be set with the path to the scripts directory. If that is correct then the directory doesn't have the file or doesn't have permission to the file.
