### ISSUE TITLE
Voicemail to email not working

### ISSUE THREAD

**Issue by shadowym** [fusionpbx/fusionpbx#1376]
Anyone else?  I tried installing from scratch using the master branch and using the okay RPM repos.

Okay RPM repo at least gives an error, "EMAIL NOT SENT, error [No to address specified]".  Yes there is an email address specified and no typos.  Yes it's saved in the database.

On from scratch using master branch I don't get any errors at all.  Everything else in the voicemail system seems to work fine.  I can playback messages in the GUI etc.

There is nothing in /var/log/mailog so it doesn't appear to be getting as far as the email server.

**Comment by bdstephenson** [comment]
I had a similar issue that I was able to fix with help from Moteus on IRC.

We had to modify some LUA scripts and add a fake email address wherever "freeswitch.email" was used and set to a blank value. In my case we were dealing with fax_retry.lua (I was not getting fax emails, got the same error in the logs you got in FS logs); in fax_retry there were several places where "freeswitch.email" was set to "". So I just changed "" to "abc@123.com" and  then emails started working. I do not understand why this fixes it, hopefully someone with more knowledge of the issue will chime in.

I believe the fix for you will be similar, although you will have to edit different files. I also believe Moteus mentioned this issue does not happen on older versions of FS 1.4.

**Comment by shadowym** [comment]
Ok thanks.  I don't fully understand how LUA ties in with everything and how to troubleshoot it so I guess I need to start trying to figure that out.

**Comment by bdstephenson** [comment]
I believe this is a glitch that needs to be corrected in the code for Fusion, at least that is what moteus was thinking. Hopefully he (or someone with commit access) will have this sorted out soon, then all you'll have to do is a quick update.

**Comment by shadowym** [comment]
I got a useful error.

```
2016-01-06 12:07:44.272834 [ERR] mod_lua.cpp:203 /usr/share/freeswitch/scripts/app/voicemail/resources/functions/send_email.lua:169: attempt to concatenate local 'headers' (a table value)
stack traceback:
        /usr/share/freeswitch/scripts/app/voicemail/resources/functions/send_email.lua:169: in function 'send_email'
        /usr/share/freeswitch/scripts/app/voicemail/index.lua:470: in main chunk
        /usr/share/freeswitch/scripts/app.lua:48: in main chunk
```



else
						freeswitch.email(voicemail_mail_to,
							voicemail_mail_to,
							"To: "..voicemail_mail_to.."\nFrom: "..voicemail_mail_to.."\nX-Headers: "..headers.."\nSubject: "..subject,
							body
							);
					end

**Comment by shadowym** [comment]
I got it working by remove the ..headers.. variable.  That variable does not exist in the database.  Now I need to figure out why

**Comment by markjcrane** [comment]
shadowym - I will close your pull request soon if you don't follow the instructions https://github.com/fusionpbx/fusionpbx/pull/1347

**Comment by markjcrane** [comment]
"Okay RPM" - we don't provide any support for this unofficial RPM.

**Comment by shadowym** [comment]
Will any of that information you want us to sign be posted publicly...ever?

**Comment by markjcrane** [comment]
What personal information. The email would be for contact information only. The only public part is the part you already shared your github username.

We won't add code that doesn't follow instructions at https://github.com/fusionpbx/open-source.
The contributor agreement is the Apache foundation contributor license agreement. So we didn't make up our own we use THE standard one which helps to protect the project.

**Comment by markjcrane** [comment]
You can leave off your name from the contributors if you want and use just your username.

**Comment by markjcrane** [comment]
RPM is based on 4.0. This problem was fixed a while ago in 4.1.

**Comment by shadowym** [comment]
That was a separate problem in 4.0 then.  There was an update to master branch 2 days ago which fixed the problem.

**Comment by markjcrane** [comment]
4.1 (dev) is Master when its a full release it will be 4.2 (release)
Despite it being on Master in dev branch at this time it is more stable than 4.0 release despite the fact we have back ported some of the bug fixes.
