### ISSUE TITLE
is fusionpbx work well with version 1.6 ? 

### ISSUE THREAD

**Issue by behesht** [fusionpbx/fusionpbx#1382]
hi 
is fusionpbx work well with version 1.6 ? 
what is the instruction for installing with fs 1.6?
thanks in advance

**Comment by lodperera** [comment]
Hi Behesht,

https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/debian/install_fusionpbx.sh


Will have the freeswitch 1.6

regards
LOD

**Comment by behesht** [comment]
suddenly stop on comiling fs 
have you ever try 1.6 install_fusionpbx.sh file ?

**Comment by behesht** [comment]
369.19user 21.41system 7:24.88elapsed 87%CPU (0avgtext+0avgdata 124076maxresident)k 0inputs+972400outputs (0major+15895743minor)pagefaults 0swaps ERROR: FreeSWITCH Build Failure.

**Comment by Psionix** [comment]
Post your **uname -a** and full installation log.

**Comment by powerpbx** [comment]
If you are using systemd OS there are some things still a bit flaky with that.  Just needs some tweaking of the unit file

**Comment by behesht** [comment]
i use debian 8.3  x86_64 and follow the fusionpbx official instruction for
installing fusionpbx and freeswotch 1.6
any help?

On Wed, Feb 10, 2016 at 7:41 PM, powerpbx <notifications@github.com> wrote:

> If you are using systemd OS there are some things still a bit flaky with
> that. Just needs some tweaking of the unit file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fusionpbx/fusionpbx/issues/1382#issuecomment-182451327>
> .
>



-- 
با تشکر و سپاس
عباس روشن

**Comment by markjcrane** [comment]
https://github.com/fusionpbx/fusionpbx-install.sh
The official install for Debian with the FreeSWITCH package.
