### ISSUE TITLE
Provisioning not creating file

### ISSUE THREAD

**Issue by bigfishvoice** [fusionpbx/fusionpbx#1393]
After applying updates, the ability to download the device config file from the gui is producing a 404 error.  The URL is trying to go to:

https://<OUR DOMAIN>/app/devices/://<OUR DOMAIN>app/provision?mac=XXXXXXXXXXXX&file={$mac}.xml&content_type=application/octet-stream

(mac address and domain removed)

Which doesn't appear to be a valid URL format even.  Additionally when trying to go directly to:

https://<OUR DOMAIN>app/provision?mac=XXXXXXXXXXXX&file={$mac}.xml&content_type=application/octet-stream

It produces the following error:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "," LINE 1: SELECT extension as , effective_caller_id_name, effective_ca... ^' in /var/www/fusionpbx/app/provision/resources/classes/provision.php:749 Stack trace: #0 /var/www/fusionpbx/app/provision/resources/classes/provision.php(749): PDOStatement->execute() #1 /var/www/fusionpbx/app/provision/index.php(296): provision->render() #2 {main} thrown in /var/www/fusionpbx/app/provision/resources/classes/provision.php on line 749

This process was working before the latest update.

**Comment by markjcrane** [comment]
Thanks for reporting this problem it was caused by a pull request from yesterday. I just completed fixing it.
