### ISSUE TITLE
BUG : default settings when copied into domain only shows part of the "Value"

### ISSUE THREAD

**Issue by lodperera** [fusionpbx/fusionpbx#1395]
Hi Team,

Fusion : 4.1

Tested via fresh install as well. 

I copied default settings--> time conditions--> preset-england into a domain.

However when you go to advanced--> domain--> example
once you click the copied time conditions it will show the value as "{" instead of the whole string which is "	{"Anzac Day":{"mon":"4","mday":"25"}}	 "

advanced-domain : https://www.dropbox.com/s/s86d3uuz522l2pu/advanced-domain.png?dl=0
advanced-domain-time condition : https://www.dropbox.com/s/gora2xnq7us1ejt/advanced-domain-time%20condition.png?dl=0

regards
Oshada

**Comment by mafoo** [comment]
you are not meant to copy the presets to a domain, you need to set region (Time Conditions > region) to match the preset you want to use i.e. 'england' in the domain you want it to affect.
If you need direct help there are usually someone who can help on freenode IRC (#fusionpbx)
