### ISSUE TITLE
Issues getting Polycom Directory to provision.

### ISSUE THREAD

**Issue by scarthas** [fusionpbx/fusionpbx#1400]
We are running version 4.1.0 of Fusion and Switch 1.4.26.
Under Provisioning for Default Settings, we have Directory set to True and Enabled.
I added some contacts and filled in the First and Last name, their contact number, and their organization.
I setup a VVX 300 device and used the 4.x template.
Upon provisioning, no contacts showed up under the directory section of the phone.
Are there additional settings or steps in order to get the directory to show on the phone?

**Comment by Len-PGH** [comment]
update to master and check again. Also check the nginx rewrite rules you have with the ones from the newest install script. Please re-open if you still have issues and post what git version you are on.
