### ISSUE TITLE
BUG : IVR invalid retries not working when used without a confirm key

### ISSUE THREAD

**Issue by lodperera** [fusionpbx/fusionpbx#1402]
Hi Team,

Fusion 4.1
FS 1.6.5

IVR config https://goo.gl/ugb59s

IVR doesn't send the call to exit action even after several invalid attempts. 
However if I press the confirm key # after several invalid attempts, then it will send the call to exit action.

Another user confirmed as well. 

<sberube__> Lodperera, I just tested it on my FS 1.4.23 and FPBX 4.1.0 and it never goes to the exit routine.  My settings are confirm macro=blank, Confirm key=blank, confirm attempts=3, max failures=1, max timeouts =1, digit length=5 as I have direct dial enabled and the extensions are 4 digits or less.  I hope that helps.  Let me know if you need me to try something

regards
Lodperera

**Comment by markjcrane** [comment]
Upgrade to latest this was worked on last week. Then report back if it is working for you.

**Comment by moteus** [comment]
To try you can just replace one file `ivr_menu.lua` from current master in fs script dir.
To return file back  just use upgrade->app defaults. It shuld overwrite all changes.

**Comment by lodperera** [comment]
It worked after upgrade.
Thank you.
