### ISSUE TITLE
Feature Request: Diaplan Change

### ISSUE THREAD

**Issue by scarthas** [fusionpbx/fusionpbx#1416]
In the Polycom 4.x and 5.x templates, the initial entry for the dialplan should include up to 7 digits.
Presently the first entry is [*]xxxx
This won't allow for a live transfer to any extension greater than 4 digits.
Changing it to [*]xxxxxxx will allow for up to 7 digit extensions to be transferred to.

**Comment by markjcrane** [comment]
Are you referring to the digitmap? If so latest dev uses a variable that can be set in default settings -> category provision.  polycom_digitmap now by default that value would be empty and it will let you dial anything you want. To customize it you simply set a value for polycom_digitmap.
