### ISSUE TITLE
Follow Me Phone Number Prefix Breaks CID

### ISSUE THREAD

**Issue by skyeblueiscool** [fusionpbx/fusionpbx#1434]
When using the Follow Me number Prefix, Fusion will send the variable as the CID numbers instead of the actual number. 

Here's a  #screenshot:

http://take.ms/oTKzU

Version	4.1.0
Git Information	Branch: master 
Commit: 3ce7924c02ac1ff6c43dcb1c4440fbd1ec9c1302 
Origin: https://github.com/fusionpbx/fusionpbx.git 
Project Path	/var/www/fusionpbx
Switch Version	1.4.26 (64bit)

**Comment by markjcrane** [comment]
Not sure I consider it broken. You told it to prefix the caller id number and CDR reflects that.

**Comment by skyeblueiscool** [comment]
Fixed with Pull request #1435
