### ISSUE TITLE
Static XML release

### ISSUE THREAD

**Issue by nandy1925** [fusionpbx/fusionpbx#1444]
Where can I download the last release where the configuration files are in static XML files that is compatible at least with Debian Wheezy?  Thanks.

**Comment by markjcrane** [comment]
Any version of fusionpbx can do it.
http://fusionpbx.com/download.php

**Comment by nandy1925** [comment]
Hi Mark,

I installed from this script. But the config files are in the database backend. Is there a way how can I generate the XML config files? I read somewhere that Advanced Settings > Switch dialplan, sip_profiles, etc. be changed from False to True and edit the lua.conf.xml. I was expecting the XML files be written. Perhaps there's a tweak I need to do. 

Thanks,
Nandy

**Comment by est42** [comment]
Hi Nandy, this doesn't seems to be supported anymore.

**Comment by markjcrane** [comment]
I would like to ask as to the reason its needed. Your reason why may affect whether its actually needed. Or whether there is an alternative to achieve what you need. If you reply soon I will read it.
