### ISSUE TITLE
gsmopen problem:  INCOMPATIBLE_DESTINATION

### ISSUE THREAD

**Issue by nandy1925** [fusionpbx/fusionpbx#1445]
Hi Mark,

I posted the above problem in the FS mailing-list. Since I encounter this problem with FusionPBX.    (My previous installation is working with gsmopen.) Perhaps there might be some subtle things I overlooked. 

I appreciate for your input.

Thanks and regards,
Nandy

**Comment by blackc2004** [comment]
If you upgraded to 1.6 you might need to set the absolute_codec_string in the outbound route.

**Comment by nandy1925** [comment]
Thanks for the hint blackc2004.  I'm on Debian Jessie and FS 1.6.

Setting this before bridge didn't work:
<action application="set" data="absolute_codec_string=PCMA,PCMU"/>

but this worked:
<action application="export" data="absolute_codec_string=PCMA,PCMU"/>
