### ISSUE TITLE
CDR advanced search fatal error

### ISSUE THREAD

**Issue by elfranne** [fusionpbx/fusionpbx#1452]
When trying to do an advanced search on Apps -> CDR. If you input an uuid in the Bridge UUID you get: 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR: column "bleg_uuid" does not exist LINE 1: ...uid = ' 2bab704e-42e7-4328-bff3-4d3d17b0edd6' and bleg_uuid ... ^' in /var/www/fusionpbx/app/xml_cdr/xml_cdr_inc.php:261 Stack trace: #0 /var/www/fusionpbx/app/xml_cdr/xml_cdr_inc.php(261): PDOStatement->execute() #1 /var/www/fusionpbx/app/xml_cdr/xml_cdr.php(48): require_once('/var/www/fusion...') #2 {main} thrown in /var/www/fusionpbx/app/xml_cdr/xml_cdr_inc.php on line 261

OS: Debian 8 Jessie
FusionPBX Version  4.0.1 

Branch: master
Commit: 3df36af619b3ba1a8ef726b5b03f6c31b7a0e9f0
Origin: https://github.com/fusionpbx/fusionpbx 

FS : 1.4.26 (64bit)

**Comment by markjcrane** [comment]
Just tested this and its working.
