### ISSUE TITLE
Accessibility challenges in web interface

### ISSUE THREAD

**Issue by Nick6489** [fusionpbx/fusionpbx#1454]
When using FusionPBX with a windows screen reader, the menu system design creates challenges. First, every menu item is its own H2 tag, which presents usability issues due to screen reader users’ tendency to skip around by heading by pushing one key, in my case, H. Sections, not individual items, are best made headings, and individual menu items are best placed in one list with nested lists, rather than their own li and ul tags. This assists in keyboard navigation. Secondly, and more troubling, the main menu options render to a screen reader only as text, no conventional link or clickable item. A screen reader user would be able to push enter on such an item without any trouble to expand it, if it is not in an expanded state already. Instead, a screen reader user must use their screen reader’s equivalent of the mouse cursor, something we don’t use all the time, and find the item on the screen to click it. This occurs on Windows with the two most popular screen readers, the open source NVDA and the proprietary JAWS for Windows, as well as both Internet Explorer and Firefox, the two most accessible browsers.

**Comment by markjcrane** [comment]
Which theme are you using?

**Comment by Nick6489** [comment]
The default theme. Similar issues are on the main FusionPBX website re: h2.

**Comment by markjcrane** [comment]
Dev branch uses bootstrap menu which is accessible this feature will be released in FusionPBX 4.2.
