### ISSUE TITLE
Ring Group Simultaneous Ring Strategy

### ISSUE THREAD

**Issue by akgautam** [fusionpbx/fusionpbx#1456]
I am facing the issue with simultaneous ring strategy in external number call is forwarding with multiple session in single number not forwarding to other number. 
it rings the internal extensions and the first external phone number but it does not attempt to dial the second external phone number.

**Comment by moteus** [comment]
I am not sure I understand your question.
I make new ring group:
**Strategy:** `Simultaneous`
**Destinations:** `<NUBER ROUTED VIA GATEWAY>`

And when I call to this ring group call goes to gateway.

**PS.** What version of FusionPBX you use?

**Comment by akgautam** [comment]
Version	4.0.1
Operating System	Linux ip-172-31-30-96 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

**Comment by markjcrane** [comment]
Use strategy: enterprise

**Comment by akgautam** [comment]
Not working
