### ISSUE TITLE
Feature Request: Adding Registration Status On The Accounts->Extensions Page

### ISSUE THREAD

**Issue by KerryDot0** [fusionpbx/fusionpbx#1488]
**Request: ** The ability to look at the Accounts->Extensions page and see what extensions are registered and which are not.  Perhaps a visual indication of status, such as a Green/Red dot, or a check mark.  

**Scenario: ** You have a number of extensions, and some have lost registration, so in troubleshooting you need to reference the Status->Registrations page.  However this page only shows the extension number of the device, and both lists need to be compared.  So the main benefit here would be quickly identifying extensions that go off-line for deployment and troubleshooting purposes.

**Comment by andycol** [comment]
Would adding a line saying reachable/unreachable similar to asterisk next to the registrations on status-> registrations help?

**Comment by KerryDot0** [comment]
Yes I think that would do it.

**Comment by markjcrane** [comment]
Dev branch has this feature will be released in FusionPBX 4.2.
