### ISSUE TITLE
Can't seem to get voicemail -> email working

### ISSUE THREAD

**Issue by ethanmullins** [fusionpbx/fusionpbx#1496]
VM to email was working perfectly fine on my system up until about a week ago. I've verified that the credentials are correct, and i've checked the php-mailer log in /tmp. 

I've noticed that I can resend older, failed emails, and it works perfectly fine and creates a log file in /tmp.

When i just leave a voicemail, it doesn't create a log file in /tmp and it doesn't send the email.

**Comment by markjcrane** [comment]
Make sure you are on the latest version. 
Make sure file permissions are correct and that fusionpbx/secure directory and its contents are 755.

**Comment by markjcrane** [comment]
Contact support or #fusionpbx on irc if still having an issue with this.
