### ISSUE TITLE
Installation Errors in install.php

### ISSUE THREAD

**Issue by willdel** [fusionpbx/fusionpbx#1511]
Just tried to install fusionpbx using install script on main website, using install-both auto on Debian 8.  Install script runs with no issues, until I go to the webpage for the initial install, I just get a blue page. In my developer's tools, I'm showing the following errors (xxx is my server): 

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/jquery/jquery-1.11.1.js 
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-datetimepicker.min.css
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-colorpicker.min.css
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/jquery/jquery.autosize.input.js
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/momentjs/moment.js
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap.min.js
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap-datetimepicker.min.js
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap-colorpicker.js
Failed to load resource: the server responded with a status of 404

Uncaught ReferenceError: $ is not defined install.php:1109

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404

https://xxx.xxx.xxx.xxx/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-colorpicker.min.css
Failed to load resource: the server responded with a status of 404

**Comment by markjcrane** [comment]
Should be fixed please try again.

**Comment by willdel** [comment]
Fresh install, same as above, getting a white screen now and showing the following errors:

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-datetimepicker.min.css
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-colorpicker.min.css
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap-colorpicker.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/jquery/jquery-1.11.1.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/momentjs/moment.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/jquery/jquery.autosize.input.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap-datetimepicker.min.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap.min.js
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/js/bootstrap.min.js
Failed to load resource: the server responded with a status of 404

Uncaught ReferenceError: $ is not defined  install.php:1102

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/themes/default/favicon.ico
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404

https://104.238.146.237/core/install/%3C!--%7Bproject_path%7D--%3E/resources/bootstrap/css/bootstrap-colorpicker.min.css
Failed to load resource: the server responded with a status of 404

**Comment by willdel** [comment]
It is working now, thank you.

**Comment by willdel** [comment]
Now getting this when finishing the install:
Fatal error: Call to a member function execute() on boolean in /var/www/fusionpbx/resources/pdo.php on line 242
