### ISSUE TITLE
regression: ivr direct dial not working

### ISSUE THREAD

**Issue by nguyennp** [fusionpbx/fusionpbx#1516]
create an IVR menu with direct dial. 
Dial in and input extension => call drop
Expected: extension rings

Work arround: 
go to dial manager, edit the dial plan for the selected IVR, change the last action to 

action lua ivr_menu.lua  then it work again.  Note: you need to do this every time you change the IVR using GUI caused it will get overridden to "action ivr ..." instead of "actiion lua ivr_menu.lua"

**Comment by moteus** [comment]
You can configure it in default settings
group: ivr_menu 
category: application 
type: text 
value: lua

**Comment by markjcrane** [comment]
I updated the code for direct dialer using ivr. Update then run upgrade
then app defaults. This should fix the problem.

Mark
