### ISSUE TITLE
expire["sofia_conf"], expire["acl_conf"] has nil value

### ISSUE THREAD

**Issue by nguyennp** [fusionpbx/fusionpbx#1517]
Do a fresh setup of fusion pbx, after start the log said that there was error executing the lua scripts
details error was expire["sofia_conf"], expire["acl_conf"] has nil value.
Although I can do a work arround, it seems that fusionpbx configuration has problem loading default values

workarround:
edit scripts/app/xml_handler/resources/scripts/configuration/sofia.conf.lua
change line 261 to:
                        result = trim(api:execute("memcache", "set configuration:sofia.conf:" .. hostname .." '"..XML_STRING:gsub("'", "&#39;").."' 3600"));

do the same with acl.conf.lua

**Comment by moteus** [comment]
this is wrong workaround.
Try call Advanced->Upgrade->App defaults 
or Advanced->domains->[ANY DOMAIN]->save

This should recreate correct `config.lua`

I think problem in generating `condig.lua` while install

**Comment by moteus** [comment]
Can try #1519
