### ISSUE TITLE
Device Profile Copy Broken

### ISSUE THREAD

**Issue by jamesorose** [fusionpbx/fusionpbx#1525]
Running latest git head.
c00194127c146473c9ca2d6d08a2f0d7751d0d63

Apps-> Devices, Click profiles. Select a profile to edit. Click the copy button. 

Expected behavior -> copies the profile
Actual Behavior -> Creates a blank device in the devices page with the description "Copy".

**Comment by moteus** [comment]
Problem that [device_profile_copy.php](https://github.com/fusionpbx/fusionpbx/blob/master/app/devices/device_profile_copy.php) is equal to [device_copy.php](https://github.com/fusionpbx/fusionpbx/blob/master/app/devices/device_copy.php)
So it do copy device not profile.

**Comment by markjcrane** [comment]
The device copy profile has been fixed in latest and soon to be released 4.2.
