### ISSUE TITLE
Do not use paging on sofia profile settings

### ISSUE THREAD

**Issue by moteus** [fusionpbx/fusionpbx#1526]
It now does not work because of [that](https://github.com/fusionpbx/fusionpbx/blob/master/app/sip_profiles/sip_profile_settings.php#L68)
But I really think it is bad thing because when allsettings place on single page it possible use search to find options woth some value (e.g. with ip) or with some name (e.g. acl)
I see no benefit of using paging here

**Comment by blessendor** [comment]
I agree. Searching needed parameters on the single page is much better.

**Comment by reliberate** [comment]
Understood.  Reverted, and fixed param.
