### ISSUE TITLE
Build failure with latest install scipt on  Debian 8

### ISSUE THREAD

**Issue by robert-gsl** [fusionpbx/fusionpbx#1532]
Hi:

I've built a number of Fusionpbx Debian 8/Freeswitch 1.6 installs over the last month with no issues.  However, as of today (April 1) I've had two build failures in a row using the latest Debian8/Freeswitch link from the Fusionpbx Download site.  First failure was on a small AMD box running Debian8, second failure from a Hyper-V VM running same Debian8.  In both cases the failure occurred in Freeswitch compile with errors about "yasm and nasm" not being found (print_git_revision.c) followed by errors on libvpx.  The AMD box failed the compile right after libvpx, the Hyper-V box (on a physical Cori i5) failed after libs/apr/libtool.

Working with same boxes (AMD and Hyper-V) approx. 1 week ago gave me no issues.

I'm trying to get a new Fusionpbx built for a customer on the AMD box so need some guidance.  The Debian install is vanilla, no GUI, only base system utilities install along with SSH and install is performed using the small netinstall ISO.

**Comment by robert-gsl** [comment]
Ran apt-get install nasm and apt-get install yasm then retired build and compile was successful.  Something must be missing in pre-reqs or something has changed in Debian over last week or so.

**Comment by Soeldner** [comment]
Same here (: thx @robert-gsl 

```
Neither yasm nor nasm have been found. See the prerequisites section in the README for more info.

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
Makefile:3708: recipe for target 'libs/libvpx/Makefile' failed
make: *** [libs/libvpx/Makefile] Error 1
ERROR: FreeSWITCH Build Failure.
```

**Comment by markjcrane** [comment]
To accept pull request from new developers please follow these instructions.
https://github.com/fusionpbx/open-source

**Comment by jamesarems** [comment]
Hi,
Its still not updated. I have manually installed yasm and nasm after  build error .

**Comment by jensenbox** [comment]
I am having this too. Seems like the net-new install is hosed entirely.

It appears that the scripts dir is not getting installed properly nor is the "writer" for xml working.

I will continue to investigate but for now +1

**Comment by jensenbox** [comment]
@markjcrane To the best of your knowledge, has anything in the installer (directories, permissions or whatever) changed recently? Just looking for guidance where I should focus my debugging efforts on this. Thanks!

**Comment by jensenbox** [comment]
The current fix is to do an Advanced > Upgrade then check the box next to "App Defaults" - do the process twice.

**Comment by robert-gsl** [comment]
Thx for the update @jensenbox .  I built a new VM and tried all of this.  I did NOT set up gateway first but did delete all the SIP profiles then ran the Advanced > Upgrade > App Defaults and restarted freeswitch,  Added gateway and had no joy.  Left gateway entry as is, deleted the SIP profiles, ran Advanced > Upgrade > App Defaults and restarted freeswitch and everything golden!  So, it looks like once you add or change a Gateway that you have to run the process to get the config generated.
