### ISSUE TITLE
Missing Entries in MySQL Clean Install Debian

### ISSUE THREAD

**Issue by MK-87** [fusionpbx/fusionpbx#1536]
After a clean install on Debian 8.3 with SQLITEMYSQL=m option, the web config done almost at the end of the installation writes not everything in the MySQL DB. For example these are the default settings (a lot of entries missing and site is white...):
![screenshot_2](https://cloud.githubusercontent.com/assets/18302142/14309017/086189c2-fbda-11e5-85d3-5f3b1e27eeae.png)

I have to go to Domains - select a domain and just press Save - it recreates all entries ok and works, but all the entries should be there also after the web configuration...

**Comment by moteus** [comment]
Some one also mention about this with pgsql yesterday.
So seems it bug in install part.

**Comment by markjcrane** [comment]
This is a known issue. That was discovered after improving some elements of the install. There are benefits trust me. This problem still needs to be resolved. It is easy to work around you simply go to Advanced -> Upgrade -> App defaults and run it and you will have everything that was missing.

**Comment by Bchudasama** [comment]
Hello Mark, 

If I run App defaults Upgrade on a production server what are the others this that could go wrong? as I am having similar issues with call-center Queues not showing in Database but gui is loaded... ...

Thank you for a response.

**Comment by markjcrane** [comment]
We don't test or maintain MySQL unless paid to do so or someone volunteers to work on it. PostgreSQL is the preferred and recommended database that is tested completely and maintained.
