### ISSUE TITLE
fuionpbx issues with SIP gateways (Apr 6 2016) using latest build scripts

### ISSUE THREAD

**Issue by robert-gsl** [fusionpbx/fusionpbx#1538]
Latest fusionpbx builds for FS 1.6 (Debian) and FS 1.4 (Ubuntu) both result in inability to create a functioning SIP gateway.  I have run the build in a clean Debian 8 environment using the Debian build script for FS 1.6 (and made the nasm/yasm install change).  Resulting Fusion install looks fine but creating a gateway entry results in a non-functioning entry (gateway always in stopped state, start does not appear to do anything).  As best I can tell the system does not create the appropriate XML file for the gateway.

I have also tried similar build in clean Debian 8 but using the Ubuntu install script for FS 1.4.  Exact same results.

Build scripts from 7 - 10 days ago (late March) did not appear to have this issue.  Help!

**Comment by robert-gsl** [comment]
More digging:  freeswitch/scripts directory is empty, nothing written at all.  On FS 1.4 install re-running install with install-fusionpbx option followed by upgrade inside fusionpbx does succeed in getting the directory repopulated.  I could then hand edit the xml script (in freeswitch/conf/sip_profiles/external) and gateway does "light up" after a reboot.

On an FS 1.6 install none of the above makes any difference, the scripts directory remains empty, log complains bitterly about missing scripts and having the xml file in place by hand makes no difference at all, gateway stays dead (which makes sense if none of the lua scripts can be found).

**Comment by jensenbox** [comment]
Pretty sure this is the same as #1532 

I am doing an install right now on a virtualbox - recording everything to a WEBM. Will post once it is done.

**Comment by markjcrane** [comment]
Use these install instructions.
https://github.com/fusionpbx/fusionpbx-install.sh
