### ISSUE TITLE
Ring Group only first of same extensions get called

### ISSUE THREAD

**Issue by Sundypha** [fusionpbx/fusionpbx#1540]
**What steps will reproduce the problem?**

0. Given extensions 101 and 102.
1. Set a ring group with a strategy Simultaneous and let say extension 101 is in it
2. Extension 101 is registered via a Deskphone and with a Softphone
2. Call the ring-group from 102
3. Only first registered endpoint gets called

**What is the expected output? What do you see instead?**
I expect that all endpoints of an extension gets called.

**What version of the product are you using? On what operating system?**
`Version	4.0.0
Operating System	Linux ip-172-31-18-11 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by blackc2004** [comment]
For multiple registrations you must use enterprise ring group strategy.

**Comment by Sundypha** [comment]
Thank you, I really should contribute to the docs...
