### ISSUE TITLE
Outbound type destination bugs

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1542]
![screen shot 2016-04-08 at 2 59 53 pm](https://cloud.githubusercontent.com/assets/13256764/14398650/9fad51d2-fd9a-11e5-9de3-c55681394411.png)

Noticed a few bugs with outbound type destinations.
1) If you go to Dial plan->Destinations and try to add the same "OUTBOUND" number to two domains, you get an error about "duplicate detected", not sure if this is correct behavior or not. Since they are outbound and are just used in drop downs for IVR, etc seems like you should be able to add the same number. 
![screen shot 2016-04-08 at 2 59 07 pm](https://cloud.githubusercontent.com/assets/13256764/14398634/84b9a16e-fd9a-11e5-9ecf-28fb2e924f42.png)

2) If you change it to a GLOBAL, it doesn't show under the "destinations" for any domain unless you click "SHOW ALL". I would think that as a super admin you should still be able to see them

3) In IVR/other drop downs if you save it as a global, you cannot select it.

![screen shot 2016-04-08 at 3 01 27 pm](https://cloud.githubusercontent.com/assets/13256764/14398676/d73a7eb8-fd9a-11e5-874d-bd7d5fdb2da9.png)

**Comment by blackc2004** [comment]
Also just realized you cannot delete them if they are of type "global"

**Comment by blackc2004** [comment]
System Information
Version	4.1.0
Git Information	Branch: master 
Commit: 4ac03a8d1ab42342da6f0882b14b62c069d91810 
Origin: https://github.com/fusionpbx/fusionpbx

**Comment by markjcrane** [comment]
2) If you change it to a GLOBAL, it doesn't show under the "destinations" for any domain unless you click "SHOW ALL". I would think that as a super admin you should still be able to see them

Yes as its not assigned to a domain.

**Comment by markjcrane** [comment]
> 1. Duplicate check

It only checks inbound and not outbound this was fixed some time ago.

> 2. If you change it to a GLOBAL, it doesn't show under the "destinations" for any domain

Fixed.

> 3. In IVR/other drop downs if you save it as a global, you cannot select it.

Fixed

> Also just realized you cannot delete them if they are of type "global"

Delete global has been fixed.
