### ISSUE TITLE
XML CDR not working in latest build 

### ISSUE THREAD

**Issue by umair-bizz** [fusionpbx/fusionpbx#1546]
Hi,

I just [on Apr 14, 2016] installed freeswitch+fusionpbx on Debian 8 Jessie 32 bit using latest script from 
https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/debian/install_fusionpbx.sh

Everything seems ok after resetting apps to default. I was able to make internal calls but CDR was not being generated. Upon inspecting logs using fs_cli, I noticed following errors after each call

2016-04-14 12:40:45.336811 [ERR] mod_xml_cdr.c:395 Got error [0] posting to web server [{v_http_protocol}://{domain_name}{v_project_path}/app/xml_cdr/v_xml_cdr_import.php]
2016-04-14 12:40:45.336811 [ERR] mod_xml_cdr.c:402 Retry will be with url [{v_http_protocol}://{domain_name}{v_project_path}/app/xml_cdr/v_xml_cdr_import.php]
2016-04-14 12:40:45.336811 [ERR] mod_xml_cdr.c:418 Unable to post to web server, writing to file

I explored /usr/local/freeswitch/conf/autoload_configs/xml_cdr.conf.xml .
For testing purpose, i replaced url in file with hardcoded values like 
<param name="url" value="https://fusionpbx4/app/xml_cdr/v_xml_cdr_import.php"/>
(fusionpbx4 being my test VM)
and I got CDR entries in fusionpbx.

So apparently some xml variables namely  v_http_protocol, domain_name, v_project_path were not being resolved. 

Can you please solve this or point me to right direction how to solve it.
 
Regards,
P.S. Please excuse me if i did something wrong in reporting. First time on github.... or for that matter git

**Comment by markjcrane** [comment]
These are normally v_http_protocol, domain_name, v_project_path replaced with the correct value during install.

**Comment by markjcrane** [comment]
Normal installs using debian 8 are working fine. This was either manually copied or web server didn't have permission during the the web based install to replace this file.
