### ISSUE TITLE
Polycom Template Consistent Volume

### ISSUE THREAD

**Issue by scarthas** [fusionpbx/fusionpbx#1554]
Presently the entry voice.volume.persist.handset="1" is in the Polycom 4.x and 5.x templates.
Adding voice.volume.persist.handsfree="1" and voice.volume.persist.headset="1" would allow for consistent volume on each output method.
Changing the default ringing volume can only be done with the handsfree entry on.

**Comment by scarthas** [comment]
Additionally, feature.nonVolatileRingerVolume.enabled needs to be on in order for the ringer volume to persist through a reboot.

**Comment by markjcrane** [comment]
Thanks I have added the changes needed to the 4.x and 5.x templates.
