### ISSUE TITLE
Creating fax server

### ISSUE THREAD

**Issue by willempoort** [fusionpbx/fusionpbx#1555]
When creating a fax server with a '+' sign in the number, the '+' is not writen as '\\+' in the dialplan manager. Also the context is not 'public' as it should for external numbers.

System Information
Version 	4.1.0
Git Information 	Branch: master
Commit: 2fd1a44842fc86a813884937ffcd9f5fdd6769e8
Origin: https://github.com/fusionpbx/fusionpbx
Project Path 	/var/www/fusionpbx
Switch Version 	1.6.7 (64bit)

**Comment by markjcrane** [comment]
Context should be the domain name. And then direct 'public' context calls to the domain context.

**Comment by willempoort** [comment]
You mean like: Create a new destination with the (public (telephone))number used for receiving faxes and forward this to the fax-extension number?
This implicates then the the destination number field in the Fax Server Settings form is obsolute then?

**Comment by markjcrane** [comment]
> Create a new destination with the (public (telephone))number used for receiving faxes and forward this to the fax-extension number?
  Yes this is how it was designed. Think of it similar to any other extension.
