### ISSUE TITLE
Use effective_caller_id_name instead of caller_id_name in follow me

### ISSUE THREAD

**Issue by lcx** [fusionpbx/fusionpbx#1560]
I was wondering why follow_me uses caller_id_name instead of effective_caller_id_name

https://github.com/fusionpbx/fusionpbx/blob/master/app/calls/resources/classes/follow_me.php#L298

following use case: 
Customer has two inbound numbers, for both numbers the extension 10 should ring and if not answered it should be forwarded to a external number. 
To be able to distinguish which inbound number was called by the caller, I added a prefix for the inbound route: action set effective_caller_id_name=FOO#${caller_id_name}

If the call is sent to extension 10 without Follow me, then the call show up as FOO#....
if however it is sent to extension 10 with follow me, the FOO# part does not show up.
Am I missing something and this is in some way intentional or is this a legitimate feature request?

**Comment by bdstephenson** [comment]
I have this issue as well, any ideas or fixes would be much appreciated.

**Comment by KerryDot0** [comment]
You could use a directory entry on the phone to have the name show up.

**Comment by mafoo** [comment]
Should be fixed in https://github.com/fusionpbx/fusionpbx/commit/f024039a02db83a0d74e5c8f547d4d8c8bf518c7 but after applying you will need to re-save any followme's to update them

**Comment by bdstephenson** [comment]
mafoo, thank you, after updating that file and re-saving all the follow me extensions it is working as I had hoped.

**Comment by markjcrane** [comment]
Confirmed fixed closing the issue.
