### ISSUE TITLE
One way audio (garbled) on *8ext with G722

### ISSUE THREAD

**Issue by jamesorose** [fusionpbx/fusionpbx#1561]
Dialplan on *8[ext] was changed to "mute=false" and  "pin="

If the codec used is G722 (with yealink phones W52p, T46G, T41p), the callee can hear the caller, but not the other way around.  It's not completely dead air, just garbled.

Does the conference not fully support G722?

Thanks,

James

**Comment by markjcrane** [comment]
Default profile is 8khz audio so you are likely transcoding. Need to use 16khz conference profile.
