### ISSUE TITLE
CDR Export only exporting 50 rows

### ISSUE THREAD

**Issue by ewsamuels** [fusionpbx/fusionpbx#1563]
Hi Mark,

I seem to have an issue exporting CDRs in that I am only getting 50 rows in the CSV.  The CDR display in the GUI is fine though.

4.1.0
Git Information 	Branch: master
Commit: 7b413a805855042cb92c57bb550c87292e392abd 

Regards,

Errol

**Comment by markjcrane** [comment]
This has been fixed thanks for reporting it.
