### ISSUE TITLE
Add var on variables.

### ISSUE THREAD

**Issue by elmemis** [fusionpbx/fusionpbx#1565]
Variables->Default: media_mix_inbound_outbound_codecs=true

necessary for transcoding when using differents codecs on internal profile and external profile.
https://freeswitch.org/confluence/display/FREESWITCH/Codec+Negotiation

Best regards

**Comment by markjcrane** [comment]
We are aware of this variable just haven't added it by default yet.

**Comment by markjcrane** [comment]
It is now a default for new installs.
