### ISSUE TITLE
/var/www used even when apache selected

### ISSUE THREAD

**Issue by PrestonDocks** [fusionpbx/fusionpbx#1567]
When you choose to use apache the script still installs fusionpbx to /var/www 

At the end of the script when you are asked to browse to your IP to finish installation you are unable to connect to fusionpbx.

**Comment by markjcrane** [comment]
We have multiple install scripts please let us know which one you are using.

**Comment by markjcrane** [comment]
NGINX is recommended because it is faster and has an easier configuration.

**Comment by markjcrane** [comment]
NGINX is supported if you want help with Apache please consider paid support.
