### ISSUE TITLE
New FusionPBX System Status

### ISSUE THREAD

**Issue by hmoreno** [fusionpbx/fusionpbx#1570]
![systemstatus](https://cloud.githubusercontent.com/assets/133963/14929781/22e6697e-0e14-11e6-9319-96b04aa6f26c.png)
Hello,

First time poster, long time user here.

I love this product and I have been using version 3.4 for a long time now.   

I decided to make the jump to the new version 4.1 yesterday and although everything is working fine, I was wondering if there is a specific reason why the system metrics are not being updated correctly.

My metrics have been stuck like this for the past 13 hours with no change.

Is there a file or a permission I'm missing out on here? 

Thank you.

Operating system: 
Debian Linux 8
Commands:
cd /usr/src
apt-get install wget
#Debian 8 (jessie) - FreeSWITCH 1.6.x
wget https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/debian/install_fusionpbx.sh

**Comment by markjcrane** [comment]
The page doesn't update automatically have you refreshed the page?

**Comment by screwloose83** [comment]
Also the CPU has over 100% listed. Talk about overclocking it. I have the same issue with mine. But live the new look. And its now mobile friendly. Great work.

**Comment by hmoreno** [comment]
![dashboardupdate](https://cloud.githubusercontent.com/assets/133963/14944591/a4783b22-0fac-11e6-8697-86510f55b78d.png)

Same issue, its been 2 day now and the page still has not updated.

I can hit refresh, I can log out and log in, but still no change.

I just want to know what mechanism this page uses to get this data from the server.   Or which specific PHP file is in charge of updating the dashboard so I can back trace it and figure out why its not working.

Thank you.

**Comment by markjcrane** [comment]
The CPU percentage is definitely wrong. Will work on it as time permits but this is a low priority bug at the moment until some others are fixed.

**Comment by markjcrane** [comment]
CPU was fixed on the dashboard last week.
