### ISSUE TITLE
fusionpbx/app/call_center_active/call_center_active_inc.php breaks with latest update

### ISSUE THREAD

**Issue by screwloose83** [fusionpbx/fusionpbx#1571]
I'm using freeswitch 1.7.0 and the last update 2 days ago breaks the call_center_active.php?queue_name= view. It only returns a call timer with some corruption in front of it. No Agent status show on the page either. If i put the str_to_named_array code back to what it was a few days ago the page has no problems.

**Comment by markjcrane** [comment]
Thanks for reporting this it has been fixed.
