### ISSUE TITLE
DTMF (outgoing) not working

### ISSUE THREAD

**Issue by willempoort** [fusionpbx/fusionpbx#1572]
Outgoing DTMF is not (always) working since Freeswitch Version 1.6.6 and up.
To fix the problem you need to add the "dtmf-type" variable in the SIP profile(s)

In SIP Profiles add variable:
name: dtmf-type		value: rfc2833

**Comment by markjcrane** [comment]
Thanks I have added it to the sip profiles by default in the master branch.
