### ISSUE TITLE
FreeSWITCH 1.6.7 CODEC PROBLEM

### ISSUE THREAD

**Issue by anis-bedhiafi** [fusionpbx/fusionpbx#1574]
Hi,

Installing FusionPBX 4.1 with FreeSWITCH 1.6.7 using  the install script
wget https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/debian/install_fusionpbx.sh
 was working perfectly.

But now if I try to install with the same script here are the problems:
First, after installation finishes, FreeSWITCH profiles aren't started although FreeSWITCH is running.
Second, If I start profiles manually the internal profile will be listening on a random port and not (5060) as usual (Everything is as default in config, I did not touch anything)
Third problem which is worst is FeeSWITCH will offer only G722/8000 HZ codec. A bad voice quality.

BTW, I am working with FusionPBX and FreeSWITCH from version 3.8 (FusionPBX) and version 1.4.26 (Freeswitch) and I know how a clean installation looks like.

Is this a bug in FreeSWITCH 1.6.7 (which was working with the same script) or a problem from debian 8 or a problem with the install script?
Thank you.

**Comment by flyer292** [comment]
We have seen the same bug.  A work around is on each reboot of the server open the console and restart freeswitch.  'service freeswitch restart'
It resolves the issue until the next reboot

**Comment by markjcrane** [comment]
https://freeswitch.org/jira/browse/FS-8321
Set variable media_mix_inbound_outbound_codecs = true

After install running advanced -> upgrade -> app defaults then starting sip profiles gets around the install problem I'll get this fixed. It has been mentioned several times on irc and in some of the install script.

**Comment by anis-bedhiafi** [comment]
Thank you so much, you saved my life.

**Comment by markjcrane** [comment]
Random ports caused  by freeswitch's original configuration setup to use stun after install restart freeswitch so it reads the new configuration.  I'll get the new install to do that after it detects the config.php.

**Comment by anis-bedhiafi** [comment]
Thank you @markjcrane

**Comment by markjcrane** [comment]
media_mix_inbound_outbound_codecs = true is now added by default for new installs.
