### ISSUE TITLE
File Upload not working

### ISSUE THREAD

**Issue by scarthas** [fusionpbx/fusionpbx#1583]
Presently, trying to upload a file to Voicemail Greetings or Recordings gives back a success message but nothing shows up. There are no errors in the log.

**Comment by reliberate** [comment]
Might check file permissions on the server.  Just tested Greeting and Recording file uploading on the latest dev branch and seems to work fine.

**Comment by rhetor22** [comment]
I' having the same issue.  What should the permissions be for these folders?

**Comment by rhetor22** [comment]
scarthas, mcrane resolved this issue on my server by doing a gitpull and running the permissions settings that the installer does against the voicemail recordings folders.  There was some issue with the install script, but probably only for a few days.  Another option is to simply reinstall with the latest script and you should be good to go.

**Comment by markjcrane** [comment]
Here are the permissions for the freeswitch package that will fix the problem.

chown -R freeswitch:freeswitch /var/lib/freeswitch
chmod -R g+s /var/lib/freeswitch
setfacl -R -m u:www-data:rwx,g:www-data:rwx /var/lib/freeswitch
setfacl -R -d -m u:www-data:rwx,g:www-data:rwx /var/lib/freeswitch

chown -R freeswitch:freeswitch /usr/share/freeswitch
chmod -R g+s /usr/share/freeswitch
setfacl -R -m u:www-data:rwx,g:www-data:rwx /usr/share/freeswitch
setfacl -R -d -m u:www-data:rwx,g:www-data:rwx /usr/share/freeswitch

chown -R freeswitch:freeswitch /etc/freeswitch
chmod -R g+s /etc/freeswitch
setfacl -R -m u:www-data:rwx,g:www-data:rwx /etc/freeswitch
setfacl -R -d -m u:www-data:rwx,g:www-data:rwx /etc/freeswitch

chown -R freeswitch:freeswitch /var/log/freeswitch
setfacl -R -m u:www-data:rwx,g:www-data:rwx /var/log/freeswitch
setfacl -R -d -m u:www-data:rwx,g:www-data:rwx /var/log/freeswitch

chown -R freeswitch:freeswitch /usr/share/freeswitch/sounds
chmod -R g+s /usr/share/freeswitch/sounds
setfacl -R -m u:www-data:rwx,g:www-data:rwx /usr/share/freeswitch/sounds
setfacl -R -d -m u:www-data:rwx,g:www-data:rwx /usr/share/freeswitch/sounds

**Comment by Ghost-Hat** [comment]
Hi I have a different problem. When uploading greeting via web interface it gives 
Fatal error: Class 'messages' not found in /var/www/fusionpbx/app/voicemail_greetings/voicemail_greetings.php on line 189
but still loads file. 
Looking through the code it does not appear that the is any errors but then again I'm not fully familiar with a whole mechanics of the platform.
Any ideas how ti fix it?

**Comment by mafoo** [comment]
We already have an issue open related to this - https://github.com/fusionpbx/fusionpbx/issues/2820
