### ISSUE TITLE
Zero Voicemails displayed on user dashboards

### ISSUE THREAD

**Issue by rhetor22** [fusionpbx/fusionpbx#1584]
On a fresh install 4.1.0, user dashboards always display zero voicemails.
![capture](https://cloud.githubusercontent.com/assets/18758031/15062536/c7663430-130e-11e6-9be5-db67eb96e84c.JPG)

**Comment by markjcrane** [comment]
No effort put into details so it doesn't justify a response.

**Comment by rhetor22** [comment]
I apologize for lack of details.  Installed FusionPBX about 3 days ago using the install script at the bottom of this page: https://github.com/fusionpbx/fusionpbx 

I've created a sub domain and successfully created and registered to extensions.  I have added users to the extensions.  When calling an extension and leaving a voicemail, the message is left successfully and the extension can dial *97 and retrieve it.  However, when that user logs into the web portal, the voicemail section as displayed in my first post displays 0, no matter how many messages they have.

Please let me know if you'd like any more information and I will post it ASAP!

**Comment by markjcrane** [comment]
Is there an extension assigned to the current user?
What is the extension being used?
Is number alias empty on the extension?

**Comment by rhetor22** [comment]
Extension 100, 100 as number alias, user is assigned.  See below:
![capture](https://cloud.githubusercontent.com/assets/18758031/15158967/4b3bba78-16c0-11e6-9705-e1e6580603e2.JPG)

**Comment by markjcrane** [comment]
Leave number_alias blank if the extension is numeric.
The URL in your browser is the one that you logged into correct?

**Comment by rhetor22** [comment]
I am logging in using the URL that is listed under Accounts -> Users -> TylerP -> Domain

I have removed the number Alias, logged out and back in, to no effect.

**Comment by markjcrane** [comment]
Need remote access as this is working fine on my system so I'm unable to duplicate the issue.

**Comment by markjcrane** [comment]
Contact me for support.

**Comment by markjcrane** [comment]
Found and fixed the problem over a phone call.
