### ISSUE TITLE
Incorrect time zone (I guess) on Time Conditions

### ISSUE THREAD

**Issue by ozeebrown** [fusionpbx/fusionpbx#1587]
Hi.

I'm trying to create a Time Condition on my Multi Tenant FusionPBX Setup. The time conditions does not function properly because the time zone it checks looks like is on UTC-0. This the server Time Zone. 

How can I make the Time Condition to lookup the local Time Zone? 

The Time Zone works well for Call Reports and Voicemail Log, based on the time zone assigned to the user. Hopefully a way to assign the local time zone to the time condition of Different Tenants.

Thanks.

**Comment by markjcrane** [comment]
This is working fine. It means you haven't defined the time zone the way freeswitch want's to see it. You can set that in Advanced -> Variables or in an older version of FusionPBX System -> variables.
FreeSWITCH variable that needs to be set:  timezone	example value: America/Boise

This is really a training issue or support request not really a bug.

**Comment by ozeebrown** [comment]
Thank you for your reply. I'm from Melbourne Australia. Is there a Documentation/Manual that I can buy outline these Variables and any other advanced Features available. Since they are not documented or discussed anywhere, it's little difficult for a Student like me to where to look at in a situation like this for an example. There are no publications I can find on the website. Or am I missing anything on this? Thanks. Guy.
