### ISSUE TITLE
Warnings in Apps --> CDR --> View (/app/xml_cdr/xml_cdr_details.php)

### ISSUE THREAD

**Issue by stefanomarty** [fusionpbx/fusionpbx#1589]
When viewing the CDR details I get these Warnings:

**Warning: urldecode() expects parameter 1 to be string, array given in /usr/share/fusionpbx/app/xml_cdr/xml_cdr_details.php on line 272**

This one is shown on two different lines, at the "Variables" table:
![schermata 2016-05-07 alle 19 35 53](https://cloud.githubusercontent.com/assets/3297621/15093518/073c0e72-148b-11e6-83bf-4973dd8c7c7b.jpg)

and again on 4 different lines, at the "Call Flow: Caller Profile" table:
![schermata 2016-05-07 alle 19 48 47](https://cloud.githubusercontent.com/assets/3297621/15093585/c0e01db8-148c-11e6-9315-e04db0019e7d.jpg)

One last Warning appears in the same table, with a different error:
**Warning: Invalid argument supplied for foreach() in /usr/share/fusionpbx/app/xml_cdr/xml_cdr_details.php on line 459**
![schermata 2016-05-07 alle 19 50 01](https://cloud.githubusercontent.com/assets/3297621/15093594/ee509e94-148c-11e6-89ef-1329df3e70f2.jpg)

**Comment by markjcrane** [comment]
This was fixed five minutes before you reported it.
https://github.com/fusionpbx/fusionpbx/commit/fcb860d75aef5c3d78c5ed7c2e2d87ca5fe43eed

**Comment by stefanomarty** [comment]
Sounds amazing, it reminds me Minority Report's PreCrime, we can call it PreBug! :-)))

Thanks!
