### ISSUE TITLE
Possible bug - Extension summary doesn't display information

### ISSUE THREAD

**Issue by ethanmullins** [fusionpbx/fusionpbx#1594]
The extension summary section of the CDR records doesn't seem to display any content unless you're logged in as a superuser. I think that I've given a standard user proper permissions to be able to access it, but it doesn't seem to work. You can pull up the page, but it doesn't show any extensions or records. 

Let me know if this is a bug, or if i'm just forgetting permissions on something.

**Comment by blackc2004** [comment]
Does the user have an extension assigned to them?

**Comment by ethanmullins** [comment]
They do not, would that prevent them from seeing the extension summary?

**Comment by ethanmullins** [comment]
Okay, I see what you mean, when you assign the user to an extension it shows you the summary for that extension. I need this particular user to be able to see the summary for all of the extensions within the domain, would that be possible?

**Comment by blackc2004** [comment]
You could make the user an admin, but that gives them a LOT of other options. You could duplicate the admin permissions to a new user group type and assign the user to that. Or you could assign the user to all the extensions.

**Comment by ethanmullins** [comment]
Oh wow, can't believe I didn't realize that. I'll just assign the user to all of the extensions. thanks!
