### ISSUE TITLE
Can't register SIP Phone 

### ISSUE THREAD

**Issue by bmurkoff** [fusionpbx/fusionpbx#1601]
I just installed a fresh copy of Fusionpbx and I am I trying to registor a Polycom phone
- I already changed the the internal SIP profile context to "default" - didn't help

Any help would be greatly appreciated

**Comment by KerryDot0** [comment]
What is happening when you try and register?  

Status->Log Viewer might provide a clue.

Also, the SIP response the polycom is getting?

**Comment by markjcrane** [comment]
I already changed the the internal SIP profile context to "default" - didn't help

It was correct change it back to public.

**Comment by bmurkoff** [comment]
So I ran a packet capture and I the polycom phone making requests however when asking for license.cfg the server is responding with a  "405 not allowed"
