### ISSUE TITLE
missing cdr report in fusionpbx

### ISSUE THREAD

**Issue by romonzaman** [fusionpbx/fusionpbx#1618]
when an agent transfer a call to another extension, fusionpbx lost that calls' CDR.

FreeSWITCH (Version 1.4.19  64bit)
mysql : Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

Version: 3.8.4
Operating System	
Linux fusion01 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

regards
mohammad from EasyDial

**Comment by markjcrane** [comment]
Upgrade to latest and test again.

**Comment by markjcrane** [comment]
This has been fixed in latest.
