### ISSUE TITLE
RingGroups multiple outbound destination

### ISSUE THREAD

**Issue by elmemis** [fusionpbx/fusionpbx#1620]
The var regex_match when set to true never change to false on loop and it does not allow check all possible cases.

Scenario: Simultaneous
Destination        |   Delay  |  Timeout 
0055111223344 | 0 | 30
0055111223345 | 0 | 30
0055111223346 | 0 | 30
0055111223341 | 5 | 30
0055111223342 | 5 | 30
0055111223343 | 5 | 30

First loop execution check the number 0055111223344 and set regex_match = true, next execution loop don't check the others numbers if has create a lot outbound routes.

Add:
regex_match = false;
before the:
for k, r in pairs(dialplans) do

Best regards

**Comment by elmemis** [comment]
Sorry, the file is:
fusionpbx /resources/install/scripts/app/ring_groups/index.lua

**Comment by markjcrane** [comment]
Added with this commit 7693844ddee23e6c6e8bbb1a271ba02985d11e0e
