### ISSUE TITLE
Installation script assigns port 5060 to internal-ipv6 address only

### ISSUE THREAD

**Issue by TheSeanBrady** [fusionpbx/fusionpbx#1628]
Installing on Debian Jessie, fresh installation of the "debian-8-x64" image without an ipv6 network installed on a [Digital Ocean](https://digitalocean.com) VPS. The installation script is assigning port 5060 only to the IPv6 address on the interface. See [this image](http://imgur.com/03nf4Uc) for a screenshot of the sofia status. I've been able to replicate this issue consistently. 

```
root@fusionpbx:/usr/src/fusionpbx-install.sh/debian# ifconfig
eth0      Link encap:Ethernet  HWaddr 04:01:fd:f7:d8:01
          inet addr:192.241.219.65  Bcast:192.241.219.255  Mask:255.255.255.0
          inet6 addr: fe80::601:fdff:fef7:d801/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:30520 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16701 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:302485249 (288.4 MiB)  TX bytes:2564767 (2.4 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:41575 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41575 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:7597908 (7.2 MiB)  TX bytes:7597908 (7.2 MiB)
```

**Comment by markjcrane** [comment]
After install run this in FusionpBX menu -> advanced -> upgrade -> app defaults. Then restart mod_sofia or restart freeswitch or the server then the internal sip profile should get port 5060.

**Comment by TheSeanBrady** [comment]
Issue closed. Docs perviously had instructed to start sip profiles then upgrade app defaults, which causes the behavior above. They have since been updated. If you apply app defaults first it works perfectly. Also @markjcrane's instructions will fix the issue should you do it out of order, or find yourself in the same situation.
