### ISSUE TITLE
Failed to create the switch conf directory ''.

### ISSUE THREAD

**Issue by gregoriusus** [fusionpbx/fusionpbx#1630]
- Clean install of Debian 8 - minimal
- run install as instructed on fusionpbx documentation (Download)
- everything ok
- go to ip through wizard and on lasta step i get error:

Failed to create the switch conf directory ''.

can anyone help me what could be wrong?

**Comment by markjcrane** [comment]
Copy and paste the v install instructions you used.

**Comment by gregoriusus** [comment]
I figure it out. I didn't start Freeswitch first :-(( I thought that script ran it, but it didn't

**Comment by markjcrane** [comment]
FreeSWITCH is usually started when installing the package you have pointed out that we should double check its running. Thanks.

**Comment by gregoriusus** [comment]
If I can steal this issue, I would also point that lua scripts are not automatically copied to /usr/share/freeswitch/scripts. I had to do it manually. Otherwise everything is ok.

**Comment by Ceus** [comment]
Interesting enough. I've gotten the same comment but FreeSWITCH is started. I used the install directions from the website:

```
apt-get update && apt-get upgrade && apt-get install -y git
cd /usr/src
git clone https://github.com/fusionpbx/fusionpbx-install.sh.git
chmod 755 -R /usr/src/fusionpbx-install.sh
cd /usr/src/fusionpbx-install.sh/debian
./install.sh
```

Not sure whether or not I missed something.

**Comment by markjcrane** [comment]
Advanced -> Upgrade -> App Defaults should copy the lua scripts into place.
See the readme here https://github.com/fusionpbx/fusionpbx-install.sh

**Comment by connected201** [comment]
hi, i had seems problem!
http://awesomescreenshot.com/0f160zv0c1
http://awesomescreenshot.com/04e60zv12c
anyone can resolve this problem?
best regards

**Comment by johnknott** [comment]
Same here, Debian 8 minimal.
Tried manually starting freeswitch, restarting system etc.
Always get "Failed to create the switch conf directory ''".

**Comment by InTheEnd** [comment]
Same problem on Debian 8
```
Failed to install
Failed to create the switch conf directory ''.
```

**Comment by deathrock** [comment]
I tried 

> systemctl restart freeswitch

But it didnt work for me. I still get 

**Running requires
Install phase 1 complete for FusionPBX
Install phase 1 started for switch
	Copying Config
Failed to install
Failed to create the switch conf directory ''.**

Is it not a permissions thing?

**Comment by deathrock** [comment]
Nevermind. It works from Internet explorer but not chrome.

**Comment by magic2k** [comment]
same here - error under chrome, but all well using firefox
