### ISSUE TITLE
lua script are not copied during install script and no config.lua created

### ISSUE THREAD

**Issue by gregoriusus** [fusionpbx/fusionpbx#1632]
During installation lua files weren't copied. I had to copied it manually in etc/share/freeswitch/scripts

**Comment by gregoriusus** [comment]
I have same error as one closed issue and solutions of upgrade doesn't resolve it. Since I had to manually copied lua files, because install script didn't copy them, I guess there is also problem that config.lua is not created. I guess it should be created durring install?

Path to lua files is ok in lua.conf.

- - - - -
[ERR] mod_lua.cpp:203 .../share/freeswitch/scripts/resources/functions/config.lua:22: module 'resources.config' not found:
        no field package.preload['resources.config']
        no file '/usr/share/freeswitch/scripts/resources/config.lua'
        no file '/usr/local/lib/lua/5.2/resources/config.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources/config.so'
        no file '/usr/lib/lua/5.2/resources/config.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources/config.so'
        no file '/usr/local/lib/lua/5.2/resources.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/resources.so'
        no file '/usr/lib/lua/5.2/resources.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './resources.so'
stack traceback:
        [C]: in function 'require'
        .../share/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
        .../share/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
        [C]: in function 'require'
        /usr/share/freeswitch/scripts/app.lua:28: in main chunk
2016-06-08 20:06:07.773736 [ERR] mod_lua.cpp:270 LUA script parse/execute error!

**Comment by mafoo** [comment]
This is normally a result of File permissions issues i would recommend you either come on the IRC and we try and help
or from the fusionpbx-install.sh you can run /debian/resources/switch/package-permissions.sh to try and reset the permissions, then run the app_defaults again

**Comment by markjcrane** [comment]
This is working on current confirmed it many times its either a permissions problem or default settings -> switch category -> scripts_dir is not setup correctly.
