### ISSUE TITLE
Global Gateway - Missing once created

### ISSUE THREAD

**Issue by cgoldsbrough** [fusionpbx/fusionpbx#1661]
Hello,

New to fusionpbx so this could be a none issue or a misunderstanding of how it should work however I thought I would mention it just in case this is a legitimate issue.

Fresh install of Debian 8 via the installer script.
Setup as a multi domain / tenant

I have tried to add two global gateways as a failover which create perfectly however they cannot be edited or seen (that I can find) once created, they disappear from the interface completely and do not show up in any of the domains created.

I checked in the database using adminer which shows the gateway data if I change the database to associate the gateway with a domain it appears in the interface.

After a little digging in gateways.php I found that the issue, unless intended to work in this way, is the "get total gateway count from database" section which only returns the count for rows matching $_SESSION['domain_uuid'] which makes sense, unless it is a global gateway, perhaps an if statement of when a superadmin is logged in show global gateways is a better way to handle this, as you only want superadmins to edit them.

So to change this behaviour so it appears (I appreciate this now appears in all domains with my edit though an if statement as mentioned would sort this out if you wanted to have only superadmins view global gateways in all domains) I changed the line to:

`$sql = "select count(*) as num_rows from v_gateways where (domain_uuid = '".$_SESSION['domain_uuid']."' or domain_uuid is null) ";`

I am happy to stand corrected on this but I simply could not see a way to get the global gateway edited, deleted or anything else without this change when used in a multi domain setup.

**Comment by moteus** [comment]
Confirm. Also on sip status gataway has link only if selected domain for which they bolong

**Comment by blackc2004** [comment]
x2 confirm.. Was working before latest git pull.

**Comment by moteus** [comment]
I found proble. It quite easy to fix just need add `or or domain_uuid is null` but may be we need separate permission to see/edit global gateways.
I can imagine that admins from some domain can use global gateway but they should not be able to edit it.

**Comment by cgoldsbrough** [comment]
I think some sort of ACL or superadmin only is required as I would not want a multi domain tenant changing the global gateway if I was setting up some sort of hosted system that used a common sip trunk provider for instance.

This would likely make the most sense and keep the interface clean so another section is not required. At first I thought perhaps the global gateways might appear in another menu but I think the ACL route is much cleaner.

I have not looked at the code extensively but does the superadmin value get stored in the session? So the code could be modified with a simple if superadmin show global gateways else show domain gateways.

**Comment by moteus** [comment]
Now problem in this line `https://github.com/fusionpbx/fusionpbx/commit/fcb53fd7f9449dac9cb8769dd55a35dc7f6eb452#diff-0cb23358f730c98adcfce6a634a123c4R104`
It use incorrect count to calculate paging.

**Comment by markjcrane** [comment]
I've updated the code please update and test again.

**Comment by moteus** [comment]
I think it fixed and may be closed
