### ISSUE TITLE
Missing closing brackets

### ISSUE THREAD

**Issue by powerpbx** [fusionpbx/fusionpbx#1662]
/app/gateways/gateways.php

Missing closing brackets on line 106 and 129

`(permission_exists('gateway_domain')`

**Comment by yrojasbox** [comment]
That did the trick resolving Gateway HTTP ERROR 500.

But now when I go to Accounts > Gateways

The gateways are missing.

**Comment by markjcrane** [comment]
This has been fixed thanks for reporting it.
