### ISSUE TITLE
Cannot add New Call Center Queues

### ISSUE THREAD

**Issue by Bchudasama** [fusionpbx/fusionpbx#1670]
cannot add more than one queue to the call center. Queue show in the gui but are not added to database. Please help

**Comment by Bchudasama** [comment]
Let me explain more. I have created 4 Call center Queues and a bunch of agents. Only the first created Queue has agents populated in it. the rest of the Queues have no agents showing up inspite of adding them into the Queue. when I query the Call center Queue. i only see one in the database but the GUI shows all four . 

Please someone could look at this and respond

**Comment by Bchudasama** [comment]
further more 

this is my version 
Linux hpbx01 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux 

Database is PostgreSQL that is original for FusionPBX

**Comment by TheSeanBrady** [comment]
I would suggest taking this issue to the Fusion PBX [IRC channel](http://webchat.freenode.net/?channels=fusionpbx&uio=Mj10cnVlJjk9dHJ1ZQ58) and asking for help there if you haven't already.

**Comment by markjcrane** [comment]
Version of FusionPBX?

**Comment by Bchudasama** [comment]
this is my version 4.0.1
Linux hpbx01 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

Database is PostgreSQL that is original for FusionPBX

**Comment by markjcrane** [comment]
Tested and working fine on latest 4.2 release will be very soon.
