### ISSUE TITLE
Alter column command does not work in BDR setups

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1676]
I noticed when doing updates that this alter table kept trying to run on my production boxes. I tried to run it manually in PSQL and got this error:

ALTER TABLE v_xml_cdr ALTER COLUMN json TYPE jsonb;
ERROR:  ALTER TABLE ... ALTER COLUMN TYPE may only affect UNLOGGED or TEMPORARY tables when BDR is active; v_xml_cdr is a regular table

Just thought I would let you know that this appears to be a limitation of BDR since you teach BDR in classes and probably have a lot of people using it.

**Comment by markjcrane** [comment]
I am aware of this for BDR you would have to export the table data and drop the table. Add the new table and then insert the backed up data.
