### ISSUE TITLE
Phrases not working

### ISSUE THREAD

**Issue by jessetn** [fusionpbx/fusionpbx#1677]
Reported on IRC, someone mentioned it's a known issue, but did not find it on here.  Here's what I found:
Errors when creating a Phrase, and same error when adding to a ring group as timeout destination:
[ERR] switch_xml.c:1310 Error including /etc/freeswitch/lang/de/phrases/*.xml
[ERR] switch_xml.c:1310 Error including /etc/freeswitch/lang/en/phrases/*.xml
[ERR] switch_xml.c:1310 Error including /etc/freeswitch/lang/fr/phrases/*.xml
[ERR] switch_xml.c:1310 Error including /etc/freeswitch/lang/ru/phrases/*.xml
[ERR] switch_xml.c:1310 Error including /etc/freeswitch/lang/he/phrases/*.xml

Error when calling ring group:
switch_ivr_play_say: Can't find macro b8dab3bb-21f9-42ec-98c1-902e23090a6e

A file system search did not find the macro UUID.  This is in app_defaults.php:
['default_setting_value'] = '/usr/local/freeswitch/conf/lang'

**Comment by markjcrane** [comment]
Phrases are fixed. 
Update your source code then run menu -> upgrade -> app defaults.
This has been fixed you need to make sure languages is in autoload_configs/lua.conf.xml
<param name="xml-handler-bindings" value="configuration,dialplan,directory,languages"/>

New installs will include this by default. If you added languages then restart

**Comment by markjcrane** [comment]
Phrases on latest are definitely working fine closing the issue.
