### ISSUE TITLE
Schema & Data Types shows same alter statement every time

### ISSUE THREAD

**Issue by bigfishvoice** [fusionpbx/fusionpbx#1678]
When doing a schema & data type update, it produces the same ALTER statement every time it is run.  I've logged out and back in and ran it again and still produces the same statement.

Database Type:  pgsql
SQL Changes:
ALTER TABLE v_xml_cdr ALTER COLUMN json TYPE jsonb;

The table print out shows that the column is correct, but the ALTER continues to appear.

**Comment by blackc2004** [comment]
Are you running a BDR setup?

**Comment by bigfishvoice** [comment]
Yep.

**Comment by blackc2004** [comment]
See here: https://github.com/fusionpbx/fusionpbx/issues/1676

**Comment by bigfishvoice** [comment]
Great, thanks.
