### ISSUE TITLE
cidlookup not working

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#1686]
I'm fairly new to this, so maybe it's something I'm doing wrong.

I enabled mod_cidlooup hoping that it would pull names from the Contacts and display them on the handsets. Unfortunately it did not, and instead started displaying "UNKNOWN" on all the handsets where it had just shown the telephone number before. Using "cidlookup [number]" from fs_cli did the same thing - always returning unknown.

Poking around, I found that /usr/local/freeswitch/conf/autoload_configs/cidlookup.xml has a line:

`<param name="odbc-dsn" value="$${dsn_system}"/>`

I'm guessing that this is some sort of macro - however all the other .xml files just reference $${dsn} and not $${dsn_system}. Unfortunately changing this made no difference.

I eventually changed it to a full DSN:

`<param name="odbc-dsn" value="pgsql://hostaddr=127.0.0.1 dbname=fusionpbx user=fusionpbx password=XXXXXX">`

.. and this worked - the caller ID is now pulling names from the contacts section.

**Comment by blackc2004** [comment]
You need to just set dsn_system under advanced -> variables and then restart freeswitch.
