### ISSUE TITLE
Intermittent 'String could not be parsed as XML' error - status_registrations.php

### ISSUE THREAD

**Issue by SJS87** [fusionpbx/fusionpbx#1698]
We intermittently see the error 'String could not be parsed as XML' on the page '/app/registrations/status_registration.php'. This occurs more frequently when there are a greater number of registered extensions.

The error is occurring in '/app/registrations/status_registration_inc.php' on line 84 '$xml = new SimpleXMLElement($xml_response);', due to line 79 '$xml_response = trim(event_socket_request($fp, $cmd));' intermittently returning no results. We can workaround the error by adding 'if(strlen($xml_response) > 0){' to line 80 and '}' to line 91, the result is we intermittently get 0 registrations instead.

We're unable to replicate the error if we open the page '/app/registrations/status_registration_inc.php' this is being called by AJAX in 'status_registration.php'.

Suspect the problem may be related to the AJAX query, but can't yet confirm.

**Comment by moteus** [comment]
Can you dump `$xml_response` and validate it?

**Comment by SJS87** [comment]
I'm not sure that would help in this case, I believe $xml_response is intermittently empty (nothing to validate) which causes the error. If we add 'if(strlen($xml_response) > 0){' to line 80 and '}' to line 91, we intermittently get 0 registrations instead of the error proving that the string is empty when the error occurs.

**Comment by moteus** [comment]
Sorry. Did not see this sentence. Too many words :)
Yes I think it valid fix. You can make PR I think or wait while mcrane wake up.

**Comment by SJS87** [comment]
It has occurred to me that it could be problem with the connection to the event_socket, however it's odd that we can't replicate this when we open the page 'status_registrations_inc.php' directly although we are manually refreshing that page instead of using the AJAX query.

What I've done so far is only workaround, I think there's still more to be done before we can propose a fix.

**Comment by SJS87** [comment]
After refreshing the page 'status_registrations_inc.php' over 10 times I was eventually able to replicate to the error, I no longer suspect this problem is related to the AJAX query in 'status_registrations.php'.

**Comment by SJS87** [comment]
This is now in our enviroment fixed, our connection to the event_socket was using old code which has since been updated. Updating this code (switch.php, event_socket.php, detect_switch.php and switch_settings.php) fixes our problem.
