### ISSUE TITLE
voicemail recording broken

### ISSUE THREAD

**Issue by gramels** [fusionpbx/fusionpbx#1704]
after latest upgrade to

4.1.0
Git InformationIBranch: master 
Commit: c3463392ebf293ac7be77b4cca512da95666b8e8 
Origin: https://github.com/fusionpbx/fusionpbx.git 

the following error was shown and confirmed by others on irc

2016-06-26 09:46:54.510453 [ERR] mod_lua.cpp:203 ...pts/app/voicemail/resources/functions/record_message.lua:29: attempt to index global 'Settings' (a nil value)
stack traceback:
        ...pts/app/voicemail/resources/functions/record_message.lua:29: in function 'record_message'
        /usr/share/freeswitch/scripts/app/voicemail/index.lua:318: in main chunk
        /usr/share/freeswitch/scripts/app.lua:48: in main chunk

reproduce:
call an offline extensions with voicemail
listen to the "not available" message
see the error

**Comment by kismetgerald** [comment]
I can confirm this as well.  Voicemail hangs up in the middle of playing the "not available" message.

**Comment by moteus** [comment]
I think i already report this just after commit. @mafoo forgot add code to load libraries [like this](https://github.com/fusionpbx/fusionpbx/blob/3ad7fe027c249756cdc2d46c424804ca149fdf5a/resources/install/scripts/call_flow.lua#L35-L36)

**Comment by patrickkeller** [comment]
thank you for the fast fix, but now there is another error

2016-06-26 17:36:13.402483 [ERR] mod_lua.cpp:203 ...pts/app/voicemail/resources/functions/record_message.lua:185: Error in CoreSession::recordFile (arg 3), expected 'int' got 'nil'
stack traceback:
	[C]: in function 'recordFile'
	...pts/app/voicemail/resources/functions/record_message.lua:185: in function 'record_message'
	/usr/share/freeswitch/scripts/app/voicemail/index.lua:318: in main chunk
	/usr/share/freeswitch/scripts/app.lua:48: in main chunk

**Comment by gramels** [comment]
I get

2016-06-26 17:36:11.342169 [ERR] mod_lua.cpp:203 ...pts/app/voicemail/resources/functions/record_message.lua:29: attempt to index global 'Settings' (a nil value)
stack traceback:
        ...pts/app/voicemail/resources/functions/record_message.lua:29: in function 'record_message'
        /usr/share/freeswitch/scripts/app/voicemail/index.lua:318: in main chunk
        /usr/share/freeswitch/scripts/app.lua:48: in main chunk

**Comment by patrickkeller** [comment]
@gramels i had to manually upgrade the code. the upgrade via webinterface didn't worked for me too.

**Comment by moteus** [comment]
@patrickkeller i think i know why.

**Comment by moteus** [comment]
please try #1706.
Sorry I can not do tests today but I think it should also works.
But I think you also do some think wrong with upgrade.
App default should set thouse values in default settings.

**Comment by gramels** [comment]
is there anything one could do wrong in the upgrade using the web interface?

**Comment by patrickkeller** [comment]
@moteus Thank you, i've updated the code to the last state. Now everything has stopped working.
I have only done source code update & app defaults via webinterface. Maybe i'm getting something wrong?

2016-06-26 21:08:17.382260 [ERR] mod_lua.cpp:203 /usr/share/freeswitch/scripts/resources/config.lua:51: attempt to concatenate global 'scripts_dir' (a nil value)
stack traceback:
	/usr/share/freeswitch/scripts/resources/config.lua:51: in main chunk
	[C]: in function 'require'
	.../share/freeswitch/scripts/resources/functions/config.lua:22: in function 'load_config'
	.../share/freeswitch/scripts/resources/functions/config.lua:26: in main chunk
	[C]: in function 'require'
	/usr/share/freeswitch/scripts/app.lua:28: in main chunk
2016-06-26 21:08:17.382260 [ERR] mod_lua.cpp:270 LUA script parse/execute error!

**Comment by moteus** [comment]
Sorry. I already post fix for this few hours ago.
@markjcrane Please checkout #1708

**Comment by patrickkeller** [comment]
Thank you for your help but the problem persits, the fix had no effect :-(

**Comment by patrickkeller** [comment]
@moteus #1709 fixed it! Everything works now, event the voicemail recording, the root topic of this issue ;-) 
Awesome work, i will donate money to the project to honor this
