### ISSUE TITLE
save always adds fax actions on destinations page

### ISSUE THREAD

**Issue by gramels** [fusionpbx/fusionpbx#1710]
each time I click save on destinations page with a fax server selected two new actions (sleep & tone detect) are added

![untitled1](https://cloud.githubusercontent.com/assets/2668342/16364780/8305ba7c-3bef-11e6-9434-697282137c72.png)

**Comment by markjcrane** [comment]
This would happen if fax detection is enabled. If its a dedicated fax number then you don't need to enable fax detection.

**Comment by markjcrane** [comment]
This has been fixed. 6b69616d7fb64d9c2302d9a5cfd85336eb4d7c43
