### ISSUE TITLE
MusicOnHold uploading files

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#1714]
New local categories are not created and local_stream is not restarted when uploading MoH files via GUI.
So, for now I'm uploading new MoH files to global categories (which is created) and than - move them to domain.

**Comment by samael33** [comment]
My bad. Files are uploaded.
Only new MoH is not appearing in local_stream show. Need to manually reload local_stream module.

**Comment by gramels** [comment]
I get

`2016-06-27 18:58:22.002145 [ERR] mod_local_stream.c:814 Unknown source default`

likely the dafeult MoH files are not found any more.

**Comment by samael33** [comment]
Yes. More details on this one.
For some reason when you get an XML loaded, timer is not set to "soft", but just "". 
Also for mess with uploading local/global MoH.
When you have on domain only global MoH, you can't upload local. You have to upload a MoH as a global first, than - make it local by setting it the domain, and only after this you can upload local MoH correctly.

**Comment by moteus** [comment]
>For some reason when you get an XML loaded, timer is not set to "soft", but just "".

I think it already fixed yesterday (https://github.com/fusionpbx/fusionpbx/commit/0354e137ea84febf69f3a65e164473813513ffe5)

**Comment by samael33** [comment]
Yes, just tried this. But with uploading still a bit problems I described.

**Comment by samael33** [comment]
Now category is created, but files are not uploaded. Tested both on Safari and Chrome.
http://prnt.sc/bn53jv

**Comment by gmaruzz** [comment]
see: https://github.com/fusionpbx/fusionpbx/issues/2245
