### ISSUE TITLE
Profile copy does not work.

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1718]
When you go to profiles, select one and then click "Copy" it displays a message that the copy completed, but instead of creating a new profile, it creates a new device with no information at all.

**Comment by blackc2004** [comment]
System Information
Version	4.1.0
Git Information	Branch: master 
Commit: 873c7ad0a255613c22bfc8e748fbc3b29c80c3a5 
Origin: https://github.com/fusionpbx/fusionpbx 
Project Path	/var/www/fusionpbx
Switch Version	1.6.8 (64bit)

**Comment by moteus** [comment]
Dublicate #1525

**Comment by blackc2004** [comment]
Thanks. Didn't see that one!
