### ISSUE TITLE
No mod

### ISSUE THREAD

**Issue by Natep267** [fusionpbx/fusionpbx#1721]
Sorry new to fusionpbx, went to class over two years ago, everything have changed a lot!  So..... please put this simply, what is the fix for MOD?  I updated and restarted.  I still have the same error as other ticket.  Please advise and keep in mind I am not a programmer.

**Comment by markjcrane** [comment]
Can you describe what you meant by MOD? Not sure what is wrong?

**Comment by Natep267** [comment]
Music on hold.  When I do *9664 there is no hold music and the line drops after 3 seconds.  This is a fresh install (about 2 days ago on centos 7 using powerpbx guide and fusionpbx.fusionpbx build.  After rebooting the system I receive this error in the logs.  I did try to install mod_shout.

2016-06-30 09:13:07.309083 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x7f26a4086bb0 Connected. 
2016-06-30 09:13:07.311651 [ERR] switch_core_sqldb.c:1183 ERR: [select (select domain_name from v_domains as d where domain_uuid = s.domain_uuid) as domain_name, * from v_music_on_hold as s order by music_on_hold_name asc ] 
[STATE: 42000 CODE 1064 ERROR: [MySQL][ODBC 5.2(w) Driver][mysqld-5.5.47-MariaDB]You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* from v_music_on_hold as s order by music_on_hold_name asc' at line 1 
] 
2016-06-30 09:13:07.311676 [ERR] freeswitch_lua.cpp:460 DBH NOT Connected. 
2016-06-30 09:13:07.311692 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x7f26a4086bb0 released. 
2016-06-30 09:13:07.312060 [CRIT] switch_loadable_module.c:1520 Error Loading module /usr/lib64/freeswitch/mod/mod_local_stream.so 
**Module load routine returned an error**

The log file after trying to do *9664

2016-06-30 09:37:56.004185 [ERR] switch_core_file.c:260 Invalid file format [local_stream] for []!

**Comment by markjcrane** [comment]
This probably means Extension summary may also have an error please test it. The answer will help determine if it's possible to use a slight variation of the syntax to fix the problem.

**Comment by Natep267** [comment]
I went to Extension Summary tab and found no errors.  All looks normal. If I put a call on hold I receive no music.
Now in log.

49faceaa-3ed0-11e6-9e59-2b75b4a225d3 2016-06-30 10:38:54.403108 [DEBUG] switch_ivr.c:623 sofia/internal/908@xxx.xxx.xxx.xxxCommand Execute playback(local_stream://) 
49faceaa-3ed0-11e6-9e59-2b75b4a225d3 EXECUTE sofia/internal/908@xxx.xxx.xxx.xxx playback(local_stream://) 
2016-06-30 10:38:54.403108 [ERR] switch_core_file.c:260 Invalid file format [local_stream] for []!

**Comment by moteus** [comment]
Can you try in `Advenced->Command->SQL` this query
```SQL
select d.domain_name, s.*
from v_music_on_hold as s left outer join v_domains as d
  on d.domain_uuid = s.domain_uuid
order by music_on_hold_name asc
```

**Comment by Natep267** [comment]
Sql command executed.  Still have issue.

**Comment by moteus** [comment]
I just suggest this sql syntax. To quick and *temporary* fix I think you can go to `Advenced->Scripts`
`app->xml_handler->configuration->local_stream.conf.lua`
and change
```Lua
	sql = "select ";
	sql = sql .. "(select domain_name from v_domains as d where domain_uuid = s.domain_uuid) as domain_name, * ";
	sql = sql .. "from v_music_on_hold as s ";
	sql = sql .. "order by music_on_hold_name asc ";
```
to 
```Lua
	sql = "select d.domain_name, s.* "
	sql = sql .. "from v_music_on_hold as s left outer join v_domains as d "
	sql = sql .. "on d.domain_uuid = s.domain_uuid "
	sql = sql .. "order by s.music_on_hold_name asc "
```

**Comment by Natep267** [comment]
completed and I reboot.  Same issue.

**Comment by Natep267** [comment]
I can rebuild server.  I am using guide on https://www.powerpbx.org/content/fusionpbx-v4-freeswitch-v16-centos-v7-install-guide-v1.1

**Comment by moteus** [comment]
You get this again?
```
2016-06-30 09:13:07.309083 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x7f26a4086bb0 Connected. 
2016-06-30 09:13:07.311651 [ERR] switch_core_sqldb.c:1183 ERR: [select (select domain_name from v_domains as d where domain_uuid = s.domain_uuid) as domain_name, * from v_music_on_hold as s order by music_on_hold_name asc ] 
[STATE: 42000 CODE 1064 ERROR: [MySQL][ODBC 5.2(w) Driver][mysqld-5.5.47-MariaDB]You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* from v_music_on_hold as s order by music_on_hold_name asc' at line 1 
] ```

PS. you can goes to IRC.

**Comment by Natep267** [comment]
no.  I am still getting;

2016-06-30 11:55:45.457212 [WARNING] mod_local_stream.c:806 Unknown source , trying 'default' 
2016-06-30 11:55:45.457212 [ERR] mod_local_stream.c:814 Unknown source default

**Comment by markjcrane** [comment]
The SQL query for this has been updated and should now work with MySQL or MariaDB thanks moteus for the suggestion.

Take a look at music on hold -> edit one of the categories the name is likely to be something like default/8000 remove the rates so it will look like default. Then restart local stream from menu -> advanced -> modules and test again.

Tip:
The recommended and strongly encouraged database is PostgreSQL. You will see a few features in the future that will only work for PostgreSQL unless people pay for them to be made compatible for MySQL or someone contributes code to extend support to MySQL. There is a just a lot of PostgreSQL features MySQL doesn't have that will take a lot of extra work to enable.
