### ISSUE TITLE
MusicOnHold uploading files

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#1729]
Music On Hold files are not uploading.
Tested on both Chrome and Safari, category created, but file is not uploading.

**Comment by markjcrane** [comment]
Update and try again.

**Comment by samael33** [comment]
Already on commit 9e5ce42

**Comment by samael33** [comment]
Tested on Chrome - in some cases it works (not sure in which...) Will test more.

**Comment by samael33** [comment]
Actually not working only for one domain. Can't say why, it was first domain I created.
https://drive.google.com/file/d/0B2Upe9OeGoOXTXRYYjlkbzFaY0E/view?usp=sharing
And also - I need manually do in cli - reload mod_local_stream

**Comment by samael33** [comment]
Sorry, was really my bad with file permissions issue. 
But new MoH classes are not created in fs, need to do reload via cli by hands.
Sorry again.

**Comment by samael33** [comment]
Tested it. On commit  79cdf70  all is ok, Thanks again!
