### ISSUE TITLE
Unable to build xml menu

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#1731]
when you dial an ivr you get the following error and the call hangs up
this only happens when you add an option
** UPDATE **
this occurs when you set the extension to 800 or 900 etc

2016-07-04 15:06:11.431445 [ERR] switch_ivr_menu.c:977 Unable to build xml menu
2016-07-04 15:06:11.431445 [ERR] mod_dptools.c:2041 Unable to create menu

**Comment by markjcrane** [comment]
This is working fine around this time maybe memcache was not being flushed which could be done with Status -> SIP Status -> Memcache Flush
