### ISSUE TITLE
custom logo not pulling through on all pages

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#1733]
When you upload a custom logo and choose menu style inline the logo displays on the dashboard page
all otherpages it shows the square as if the logo is missing(screenshot below)
upon inspecting the element i discovered you need to create a folder in /var/www/fusionpbx/apps/${appname}/images/ and copy the file into their
the image should automatically pull through all pages
logo was setup under domain settings subcatogory logo
see below
http://pasteboard.co/7JSWCUggy.png

http://pasteboard.co/7JPjE2qJV.png

**Comment by markjcrane** [comment]
There isn't a bug on this feature you are doing it wrong. For rebrand training attend the Admin Training or pay for support so you can learn how to do it right.
