### ISSUE TITLE
TLS/SRTP dial-string param change

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1734]
How do you accomplish this in the FusionPBX config?  https://wiki.freeswitch.org/wiki/SIP_TLS#Step_5_-_Securing_the_RTP_Channels_.28optional.29

> Edit conf/directory/default.xml and change the dial-string param to:
>  ```
> <param name="dial-string" value="{sip_secure_media=${regex(${sofia_contact(${dialed_user}@${dialed_domain})}|transport=tls)},
>   presence_id=${dialed_user}@${dialed_domain}}${sofia_contact(${dialed_user}@${dialed_domain})}" />
> ```

**Comment by pixel2920** [comment]
dialplan manager, local_extension: action export rtp_secure_media=true

**Comment by pixel2920** [comment]
Fixed in new .lua scripts by mcrane.

**Comment by canadamcpherson** [comment]
Adding "dialplan manager, local_extension: action export rtp_secure_media=true" creates external forwarding issues for me. External forwarding goes to the voicemailbox without ringing the external phone number.

I may be entering in a wrong order. Is there a order for this, or is there anything else that I should do?

**Comment by DCVOIP** [comment]
I have voted down the above comment as if ever you call forward, it overwrites the dial string in the extension so I imagine when turning off call forwarding, you would lose this.

**Comment by canadamcpherson** [comment]
Is there a way to solve the forwarding issue?
