### ISSUE TITLE
Fusionpbx CDR Call recording not showing up

### ISSUE THREAD

**Issue by girishdharmaraj** [fusionpbx/fusionpbx#1742]
Hi seems the call recording portion on the CDR page is broken,
$${base_dir}/recordings/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}/${uuid}.wav
the .wav file is getting created but the Fusionpbx CDR page does not show the recordings inline. Any idea what I am missing ? I also tried to have the domain-name result the same.

Fusionpbx v4 Freeswitch v1.6 CentOS v7

**Comment by markjcrane** [comment]
The path you have isn't correct. Its missing the domain name. 

This is the default setting for sip profile -> record-template this is a relative path. $${base_dir} does not always exist.
${domain_name}/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}/${uuid}.wav
