### ISSUE TITLE
service module is not working

### ISSUE THREAD

**Issue by anshkatriya** [fusionpbx/fusionpbx#1743]
I have added apache service to start/stop service in  **status->services** module.

I am getting status correct in case of pid, but I am not able to get status of service in case of pid_file. Also, command is not being executing service. I am getting error like " **Failed to stop httpd.service: Interactive authentication required.** ".

Thanks.

**Comment by moteus** [comment]
May be web server has no permission to start/stop services. I am not sure it good Idea have such permissions.

**Comment by markjcrane** [comment]
Permissions issue.
