### ISSUE TITLE
odd ) in classes/scripts.php

### ISSUE THREAD

**Issue by kevinlong206** [fusionpbx/fusionpbx#1744]
Just did a first install of fusionpbx from git today 

/var/www/fusionpbx/app/scripts/resources/classes/scripts.php
Line 217 there is an odd )  character

Made installing on debian difficult , had to drop the db and start again since the installation process was broken.

Thanks 

-
Kevin Long

**Comment by moteus** [comment]
I think it already fixed
https://github.com/fusionpbx/fusionpbx/commit/3f51ab0a4352a96ee479a65fa7f7167f2aac8196
