### ISSUE TITLE
Image broken on outgoing fax CDR record

### ISSUE THREAD

**Issue by bigfishvoice** [fusionpbx/fusionpbx#1745]
When an outbound fax is displayed in the CDR record, the icon image is pointing to an invalid URL:

/themes/default/images/icon_cdr__.png

![brokenimage](https://cloud.githubusercontent.com/assets/16521420/16710067/8a21cffc-45f0-11e6-8e8d-0951df3f925f.JPG)

**Comment by markjcrane** [comment]
Fixed. The image is no longer shown when the direction is no set.

**Comment by bigfishvoice** [comment]
Thanks Mark.
