### ISSUE TITLE
Random Port on IPV4 internal instead of 5060

### ISSUE THREAD

**Issue by sanderkwantes** [fusionpbx/fusionpbx#1748]
Today i did a fresh install on a Debian 8 machine. After installation i found that both external (IPV6 and IPV4) sip ports are at port 5080.  With the internal ports only the IPV6 is on port 5060. The IPV4 port seems to randomly change after restarting. Any idea how to solve this?

**Comment by webmustang** [comment]
https://freeswitch.org/jira/browse/FS-8321
Set variable media_mix_inbound_outbound_codecs = true

After install running advanced -> upgrade -> app defaults then starting sip profiles gets around the install problem I'll get this fixed. It has been mentioned several times on irc and in some of the install script.
