### ISSUE TITLE
User Voicemail not working as expected

### ISSUE THREAD

**Issue by sanderkwantes** [fusionpbx/fusionpbx#1758]
After a fresh install on digital ocean Debian 8.5 VPS i created an extension. Somehow when i change a voicemail related field within the extension and then save it, nothing has actually changed. If i change another field within the extension the change is applied after saving. Have i forgot something? Or could this be a bug?

**Comment by pixel2920** [comment]
Have you tried this on different browsers? Cleared cache?

**Comment by sanderkwantes** [comment]
It seems the issue only happens when letters are used at the extension field. If letters are not allowed then maybe it would be a good idea to show a message 'please only use digits'.

**Comment by moteus** [comment]
Its allows but not for voicemail_id, So you have to use Number-Aliases for such thing.
