### ISSUE TITLE
local_extension always fail - always transfer to "limit_exceeded"

### ISSUE THREAD

**Issue by nandy1925** [fusionpbx/fusionpbx#1759]
Problem:  Calling another local extension always fail.
FusionPBX version 4.1.0;  FreeSWITCH version 1.6.9
Failure point:  Dialplan ->  [local_extension] > action: limit hash ${domain_name} ${destination_number} ${max_limit} ${limit_destination}
Failure analysis done:
1. changed hash to db (got error message when "limit_status hash" in fs_cli)
2. ${max_limit} is always 0.  I presume it is a user directory variable.   If I'm right, here's the BUG...

**Comment by markjcrane** [comment]
freeswitch mod_db is required to be running. In any case this is a support request not a likely a bug contact paid support.
