### ISSUE TITLE
Copying sofia profile issues - "invalid profile"

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1765]
Assuming there is an "internal" profile:
1. Copy "internal" profile --> new profile "internal_nat" for example
2. Disable "internal" profile
3. Start "internal_nat" profile is OK until restarting FreeSWITCH
4. Attempting to start either "internal" or "internal_nat" profile results in "invalid profile"
5. This wreaks havoc on inbound calls and extension-to-extension calls

**Comment by markjcrane** [comment]
You copy a profile you either need to change the port or IP address it is listening too before starting it.
