### ISSUE TITLE
All calls go to voicemail

### ISSUE THREAD

**Issue by stefanomarty** [fusionpbx/fusionpbx#1767]
After commit [e133b7a](https://github.com/fusionpbx/fusionpbx/commit/e133b7a5e189b4812af5824b2280772b38dbbb46), ALL the calls to internal extensions are answered by voicemail. Here's a log extract:
```
d4bdfc3d-042c-43ce-a282-868540fdf550 
Dialplan: sofia/internal/1111@www.domain.name parsing [www.domain.name->voicemail] continue=false 
Dialplan: sofia/internal/1111@www.domain.name Regex (PASS) [voicemail] () =~ // break=on-false 
Dialplan: sofia/internal/1111@www.domain.name Action answer() 
Dialplan: sofia/internal/1111@www.domain.name Action sleep(1000) 
Dialplan: sofia/internal/1111@www.domain.name Action set(voicemail_action=save) 
Dialplan: sofia/internal/1111@www.domain.name Action set(voicemail_id=${destination_number}) 
Dialplan: sofia/internal/1111@www.domain.name Action set(voicemail_profile=default) 
Dialplan: sofia/internal/1111@www.domain.name Action lua(app.lua voicemail)
```

As a quick turnaround I disabled the voicemail dialplan line (900-voicemail -> FALSE).

Looks like this is due to the:
`<action application="answer"/>`

in 900_voicemail.xml

**Comment by markjcrane** [comment]
This would resolve the issue. Run these from Advanced -> Command -> SQL -> reset then run this. Then go to Advanced -> App defaults. It will add new dialplans with the new order.

delete from v_dialplans where app_uuid = 'a0cb498c-6e09-441f-83ea-a7684565c44e' and dialplan_name = 'cidlookup';
delete from v_dialplans where app_uuid = 'b26a08a5-a062-42ca-b90f-d47f905dd876' and dialplan_name = 'call_screen';
delete from v_dialplans where app_uuid = '71cf1310-b6e3-415b-8745-3cbdc8e15212' and dialplan_name = 'local_extension';
delete from v_dialplans where app_uuid = 'e3c14f2f-7697-4b5d-9c62-2443c0e22bf2'
and dialplan_name = 'voicemail';

**Comment by markjcrane** [comment]
Other option is to set cidlookup to order 870, call_screen to order 880 and local_extension to 890 and voicemail will using 900.

**Comment by markjcrane** [comment]
Alternative SQL
update v_dialplans set dialplan_order = '870' where app_uuid = 'a0cb498c-6e09-441f-83ea-a7684565c44e' and dialplan_name = 'cidlookup';
update v_dialplans set dialplan_order = '880'  where app_uuid = 'b26a08a5-a062-42ca-b90f-d47f905dd876' and dialplan_name = 'call_screen';
update v_dialplans set dialplan_order = '890' where app_uuid = '71cf1310-b6e3-415b-8745-3cbdc8e15212' and dialplan_name = 'local_extension';
update v_dialplans set dialplan_order = '900'  where app_uuid = 'e3c14f2f-7697-4b5d-9c62-2443c0e22bf2'
and dialplan_name = 'voicemail';

**Comment by markjcrane** [comment]
This is now fixed for you when using upgrade -> app defaults.
https://github.com/fusionpbx/fusionpbx/commit/cc4cd99d5ee85b0ca186baa6566b49f1a8c08010
