### ISSUE TITLE
Brand-new install of FPBX no voicemail login prompt

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1769]
logs: `2016-07-22 00:37:15.316997 [ERR] switch_ivr_play_say.c:145 Can't find macro voicemail_enter_pass.`

**Comment by pixel2920** [comment]
same with `2016-07-22 00:38:39.037031 [ERR] switch_ivr_play_say.c:145 Can't find macro voicemail_enter_id.`

**Comment by pixel2920** [comment]
Already tried upgrade > app defaults etc.

**Comment by markjcrane** [comment]
It's a phrases problem that will be fixed today or tomorrow.

**Comment by markjcrane** [comment]
Update your source code then run menu -> upgrade -> app defaults.

This has been fixed you need to make sure languages is in autoload_configs/lua.conf.xml 
<param name="xml-handler-bindings" value="configuration,dialplan,directory,languages"/>

New installs will include this by default. If you added languages then restart
