### ISSUE TITLE
Cannot manage/get rid of "select domain name" on login page

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1773]
The only way to get a domain name to show on the login page is to copy the "domain_name" array member to that domain on the Advanced > Default Settings.  Doesn't appear to be a way to manage the settings for a particular domain within Default Settings.

**Comment by markjcrane** [comment]
Default settings are settings for the entire system across all domains. So there is no need to manage domain settings from this page.  You need the FusionPBX Admin training so you will understand the design better.
