### ISSUE TITLE
Cannot create Voicemail with voicemail_id with leading zeros.

### ISSUE THREAD

**Issue by mihing** [fusionpbx/fusionpbx#1774]
The leading zeros are removed.

**Comment by markjcrane** [comment]
Worked fine on latest FusionPBX version when I went to Apps -> Voicemail -> Add then added 0123 and a pin number of 123. Database I tested with PostgreSQL. Version tested latest 4.1 which is about to be released as 4.2.

**Comment by markjcrane** [comment]
Unable to duplicate on latest version.

**Comment by mihing** [comment]
I went to Apps -> Voicemail -> Add then added "0123" and a pin number of 123. My Voicemail ID "0123" converted to "123". Database I tested with PostgreSQL. Version tested latest 4.1.0.
