### ISSUE TITLE
Voicemail to email - Not working

### ISSUE THREAD

**Issue by flyer292** [fusionpbx/fusionpbx#1785]
I have configured all of email setting and it was working a few weeks ago, not sure when it broke
Emails are working from the login page when I click on forgot password
After the voicemail has been received under status -->emails it shows Failed for each one

**Comment by markjcrane** [comment]
Check for the failed response by looking in /tmp directory.

**Comment by flyer292** [comment]
The from Server field is empty in the logs.  On the SMTP server that I am using there is nothing at all in the logs.  When I do a password reset it goes though within a second and I do see the connection in the SMTP logs on my email server right away

**Comment by flyer292** [comment]
I delete the email section from Default Settings, and reload from source and configured it again.
This appears to have fixed the problem
Please close this ticket
