### ISSUE TITLE
Password reset link allows you to reset ANY users password

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1786]
Password reset link allows you to reset ANY users password.

Click on the link in the email, then in the box where it says "username" enter any user name on the system (in the domain) and reset the password.

This seems like a huge security flaw to me as you can guess an email, then guess a username, reset passsword and you're in the system. 

Even allows "users" to reset an "admins" password.

**Comment by markjcrane** [comment]
Good thing password reset is disabled by default. It was made by another developer. I'll take a look at it right now.

**Comment by markjcrane** [comment]
The password reset has been removed until it can be analyzed, fixed or replaced. 3b438f5d0e16cb8d80887659d3bce311b13fd711

**Comment by markjcrane** [comment]
I removed this feature for the time being.
