### ISSUE TITLE
MOH not working, cant create stream

### ISSUE THREAD

**Issue by jpinder70** [fusionpbx/fusionpbx#1789]
Go go Apps > Music on Hold

There's no way to create a local or global MOH folder. Pretty much there's no more music on hold.

016-08-01 15:23:54.130340 [ERR] switch_core_file.c:260 Invalid file format [local_stream] for [moh]!

**Comment by markjcrane** [comment]
This works if its configured correctly. But you might consider going to advanced -> variables and set music on hold to local_stream://default instead of local_stream://moh
