### ISSUE TITLE
IVR Greet long box is missing the arrow to convert to text box

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1793]
The IVR Greet Long is missing the arrow box to convert it to a text input. This is useful for when using the SAY: option as once you save the IVR you cannot switch to text input to update the say. you have to move to a different option, click SAY again and then re-enter all your data.

**Comment by markjcrane** [comment]
It has only been there as an 'onchange' event but it would be useful to always show up.

**Comment by markjcrane** [comment]
Wish granted. 783a9d170de466c50cb2dfa1b7a236425518a3f8

**Comment by blackc2004** [comment]
Gracias!
