### ISSUE TITLE
Time Conditions - newbie

### ISSUE THREAD

**Issue by lwa8988** [fusionpbx/fusionpbx#1796]
I am starting to use time conditions with our FusionPBX but the rules I set do not get followed.  I have changed time on the server, set time zone, edited times / dates but the call never follows the rules set.  Am I missing a setting?  I have reviewed documentation and followed the settings without change in outcome.

CLI results of test call:
Dialplan: sofia/internal/1002@mypbx.example.com:5060 Regex (PASS) [callRoute00001] destination_number(1000) =~ /^1000$/ break=on-false
2016-08-04 07:52:28.394143 [DEBUG] switch_xml.c:3053 XML DateTime Check: date time[2016-08-04 07:52:28] =~ 2016-08-04 07:40:00~2016-08-04 07:50:00 (FAIL)
Dialplan: sofia/internal/1002@mypbx.example.com:5060 Date/TimeMatch (FAIL) [callRoute00001] break=never
Dialplan: sofia/internal/1002@mypbx.example.com:5060 Regex (PASS) [callRoute00001] destination_number(1000) =~ /^1000$/ break=on-false
2016-08-04 07:52:28.394143 [DEBUG] switch_xml.c:3053 XML **DateTime Check: date time[2016-08-04 07:52:28] =~ 2016-08-04 07:50:00~2016-08-04 07:55:00 (FAIL)**
Dialplan: sofia/internal/1002@mypbx.example.com:5060 Date/TimeMatch (FAIL) [callRoute00001] break=never
Dialplan: sofia/internal/1002@mypbx.example.com:5060 Regex (PASS) [callRoute00001] destination_number(1000) =~ /^1000$/ break=on-false
2016-08-04 07:52:28.394143 [DEBUG] switch_xml.c:3053 XML DateTime Check: date time[2016-08-04 07:52:28] =~ 2016-08-09 09:00:00~2016-08-09 21:00:00 (FAIL)

**Comment by markjcrane** [comment]
A screen shot of your time condition would be better. Next upgrade and run app defaults and you will have an option in the dialplan for talking clock then you know what time freeswitch thinks it is with the time zone adjustment. Unlikely time conditions are actually broken.

**Comment by lwa8988** [comment]
Thanks for your quick reply.  Upgrade done but same result.

<img width="615" alt="screen shot 2016-08-04 at 9 19 32 am" src="https://cloud.githubusercontent.com/assets/20839785/17405318/ad08ec4c-5a24-11e6-962a-44180d6e3891.png">

cli data:
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Regex (FAIL) [dx] destination_number(5050) =~ /^dx$/ break=on-false
Dialplan: sofia/internal/5000@mypbx.example.com:5060 parsing [mypbx.example.com->physicianOnCallRoute] continue=true
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Regex (PASS) [physicianOnCallRoute] destination_number(5050) =~ /^5050$/ break=on-false
**2016-08-04 09:10:31.574137 [DEBUG] switch_xml.c:3053 XML DateTime Check: date time[2016-08-04 09:10:31] =~ 2016-08-04 09:10~2016-08-04 09:15 (FAIL)**
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Date/TimeMatch (FAIL) [physicianOnCallRoute] break=never
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Regex (PASS) [physicianOnCallRoute] destination_number(5050) =~ /^5050$/ break=on-false
2016-08-04 09:10:31.574137 [DEBUG] switch_xml.c:3053 XML DateTime Check: date time[2016-08-04 09:10:31] =~ 2016-08-04 09:15~2016-08-04 09:20 (FAIL)
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Date/TimeMatch (FAIL) [physicianOnCallRoute] break=never
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Regex (PASS) [physicianOnCallRoute] destination_number(5050) =~ /^5050$/ break=on-false
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Action bridge(sofia/gateway/998cc854-2bd5-4ae9-9688-b8ddd9e35e5e/extchangedhere) 
Dialplan: sofia/internal/5000@mypbx.example.com:5060 parsing [mypbx.example.com->att_xfer] continue=false
Dialplan: sofia/internal/5000@mypbx.example.com:5060 Regex (FAIL) [att_xfer] destination_number(5050) =~ /^att_xfer$/ break=on-false

**Comment by flyer292** [comment]
Run this on the actually OS and ensure you are using the correct time zone for your OS - dpkg-reconfigure tzdata

**Comment by markjcrane** [comment]
Your example doesn't look practical.

Most people use 
* Day of Week
* Time of Day
* Hour of Day

**Comment by markjcrane** [comment]
This is really a support request rather than an 'issue'. Please check the www.fusionpbx.com for support options for further help.

**Comment by lwa8988** [comment]
We are setting a calendar to call a user based on date / time.  Our employees work shifts of 9am-9pm and then 9pm -9am.  Users will change each shift and may change with in a shift. Date / time option is what I am using on our other system to achieve this.  We set up the calendar each week to input the schedule for the week.  I set up a test time condition but it did not call correctly, I have had longer times also but same result.  Seems that no matter what I set with date / time they all fail.  I can do Day of week, Time of day, hour of day and they work.  What test do you suggest for the date / time to see that it works?

**Comment by markjcrane** [comment]
In your case you used "Date and Time" and set it to one specific day. Which it would never match again the following week.

**Comment by lwa8988** [comment]
The person working changes every day so that is correct, there are never
two weeks that are the same so we change the schedule each week.  So if
employee 1 is on 8/4/2016 from 9am to 9pm he may not be on for another 3
days or could be another two weeks. I am trying to have a rule that calls
the user that is working on a specific date and time, not on a day of the
week.

When I set the date-time rule it shows the correct time in the CLI but says
the rule fails, cant' figure out why.  Seems to be a bug to me but I could
be doing something wrong.  I appreciate your help, I have sent and emails
to the FusionPBX already but did not get a response, will try again.

Thanks.
