### ISSUE TITLE
Failed to create the switch conf directory ''.

### ISSUE THREAD

**Issue by deathrock** [fusionpbx/fusionpbx#1798]
**Running requires
Install phase 1 complete for FusionPBX
Install phase 1 started for switch
	Copying Config
Failed to install
Failed to create the switch conf directory ''.**

I get this on the last page of the install.

**Comment by deathrock** [comment]
Solution was to use Internet Explorer instead of chrome to do the web config install

**Comment by markjcrane** [comment]
Firefox works too. Chrome should work.
