### ISSUE TITLE
*BUG* Conference Recordings missing

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#1800]
When you add a new "conference centre" under greetings there is no system standard greetings to choose from anymore.
this was previously working 100%

**Comment by andycol** [comment]
Temporary work around is if you copy all the files from /usr/share/freeswitch/sounds/en/us/callie/conference/8000/ to /var/lib/freeswitch/recording/${domainname}

**Comment by EasyBB1** [comment]
This is caused by the recur_sounds_dir() function in resources/functions.php. The function is overly complex at the moment with 48 lines of code. I've re-written the function to 13 lines of code and tested it to be working.

**Comment by andycol** [comment]
so if i replace my functions.php with the above it should fix it?

**Comment by markjcrane** [comment]
This has been fixed.
