### ISSUE TITLE
SIP Registration Failure

### ISSUE THREAD

**Issue by Ceus** [fusionpbx/fusionpbx#1804]
I'm using FusionPBX 4.1.0 and randomly phones begin failing to register. Some will remain registered and others will not register at all. I've gone through everything I can think of and I am unable tell why the problem is happening.

Has anyone else had this problem?

**Comment by markjcrane** [comment]
You can check the fail2ban logs to /var/logs/fail2ban to see if you are getting banned.
Also don't set your local ip address in the domains access control list.

**Comment by Ceus** [comment]
Thanks for responding so quickly, Mark. It appears that fail2ban isn't banning the IP. There is nothing in the Access Control list either. It is a very strange issue, given that one minute everything works great and the next it is not allowing registrations.

I have removed all firewalls as an attempt to see if that was an issue, but nothing as of yet.

**Comment by andycol** [comment]
have you looked at a sip trace with either tcpdump or sngrep?
is this perhaps happening on yealink handsets?

**Comment by Ceus** [comment]
I used tcpdump and sngrep. Both show that the phones are not connecting to the server. Strange part is that my clients that are having the problem are on different routers and connections all together. So I assume it has to be something with the server.

Fail2ban has been ruled out because it's not logging anything, I've disabled it completely and still ran into the same problem.

Not sure if there are configurations on the server that I am missing. Could this be related to running the server on a Hyper V Server? I currently host many FreePBX Systems that have no issues at all, but I'd like to move everyone from FreePBX to FusionPBX, I just can't do that until I get this registration issue fixed.

**Comment by andycol** [comment]
is SIP running on your public ip and check iptables
do iptables -vnL
and do lsof -i :5060
you might have to do apt-get install lsof

**Comment by Ceus** [comment]
![screenshot at aug 12 13-01-30](https://cloud.githubusercontent.com/assets/3145889/17632409/c6bce836-608d-11e6-9400-f6e630a0b1cd.png)
![screenshot at aug 12 12-58-46](https://cloud.githubusercontent.com/assets/3145889/17632410/c6d11568-608d-11e6-8406-619f3c133a93.png)

**Comment by andycol** [comment]
try join our irc channel #fusionpbx on freenode and we can help u there.

**Comment by markjcrane** [comment]
This is a support request try irc or paid support at http://fusionpbx.com find support on the menu.
