### ISSUE TITLE
New ring's in vars.xml are not imported

### ISSUE THREAD

**Issue by mafoo** [fusionpbx/fusionpbx#1808]
Currently if someone updates https://github.com/fusionpbx/fusionpbx/blob/master/resources/templates/conf/vars.xml to include a new ring type it won't get imported to fusionpbx as it only takes it's list of rings from https://github.com/fusionpbx/fusionpbx/blob/master/app/vars/app_defaults.php
Should we either
- remove the ring's from app_defaults and scan vars.xml for them
  - Pro's
    - Most obvious logical place to maintain the rings for people familiar with FreeSWITCH
   - Con's
     - cannot set attributes such as enabled or description (not that they are used at the moment)
- migrate all but us-ring from vars.xml and add comment explaining to add them to app/vars/app_defaults
  - Pro's
    - Tells user what file to update and single point of maintenance
    - Attributes such and enabled and description can be set

Let me know or catch me on IRC and will implement it.

**Comment by markjcrane** [comment]
Advanced -> Variables -> Ring Tones should have their own category called 'Ring Tones'
Variables could be read from vars.xml and you can add additional attributes like enabled and description to the xml.

Other option would be add an array to the app_config.php. Same way as permissions are handled or device vendors added to app/devices/app_config.php.

**Comment by mafoo** [comment]
I have prepared a PR that should implement what has been suggested including migrating old ringtones to the correct category before attempting to import the ones from vars
I will now close this issue as testing and feedback will occur on the PR
https://github.com/fusionpbx/fusionpbx/pull/1813
