### ISSUE TITLE
ring groups screen dosen't list ring tones - only moh choices are available

### ISSUE THREAD

**Issue by nyfon** [fusionpbx/fusionpbx#1834]
This caused by resources/classes/ringbacks.php on line 54 being set to $sql .= "where var_cat = 'Defaults' "; but ringtone is saved in the db as var_cat='ringtone'
$sql .= "where var_cat = 'ringtone' "; will allow display of default ringtone choice

**Comment by markjcrane** [comment]
Thanks for reporting this problem because of your report this has been fixed.
