### ISSUE TITLE
Ring Group

### ISSUE THREAD

**Issue by Tricom114** [fusionpbx/fusionpbx#1848]
I am running a pretty new install.  Switch Version	1.6.9 (64bit)
Under "Ring Groups" there is only the default music on hold option.  No other ring option, and no us-ring option.

**Comment by jlcrews** [comment]
I noticed this as well recently...sometimes music is too soft to indicate to callers there is call progress occurring so I would like the ability to have us-ring as a choice again.

**Comment by markjcrane** [comment]
Update your source code then run advanced -> upgrade -> schema and then advanced -> upgrade -> app defaults. Then check the ring group it should then have the ring tones.

**Comment by jlcrews** [comment]
This is fixed when I ran git pull today.

Thanks
