### ISSUE TITLE
removing the audible click sound during recording playback

### ISSUE THREAD

**Issue by jlcrews** [fusionpbx/fusionpbx#1856]
Is it possible to make no audible click in between playback of recordings?

If you have 3 recordings I hear a click in between each one.  I would think it would be silent.

If you you use an IVR menu to transfer to the dial by name directory I hear a click then a second later I hear another click before the dial by name recording "please enter the first few letters of the person's first of last name".

The current direct extension dialing recording that says "your call is being transferred" is great because it lets the caller know the call is going somewhere and you do not notice a click if there is one because this message is reassuring the caller that the call is progressing along.

I hear the click in between the playbacks of various recordings.  Like when an extension does not answer after hearing the ringing call progress you hear
click
"the person at extension xxx is not available "
click
"record your message at the tone"
click
beep (to tell you to start talking as the recording of the voice mail message has began)

In the old analog PBX world flash hook transfers and other things made click sounds like this...and when callers hear a distinct click that sometimes think their call got disconnected (for example when transferring a call)

This is not a hot, major issue but if others would like this...please add your vote as perhaps I am just a finicky phone audio person

**Comment by markjcrane** [comment]
I don't hear a click sound on my server between the voicemail messages. I suspect you have something else going on that is injecting a sound that sounds like a click between the sounds.

p.s notice your jlcrews.md file in the main directory at https://github.com/fusionpbx/open-source can you try again at creating a pull request that puts the file in the fusionpbx/open-source/contributors directory.

**Comment by jlcrews** [comment]
Thanks...I placed the file in open-source.

I will keep looking for the source of that click
