### ISSUE TITLE
Wrong User/Password after delete a domain

### ISSUE THREAD

**Issue by h3is3nb3rg27** [fusionpbx/fusionpbx#1885]
I've installed fusionpbx on Debian 8.5 following the steps on the Download section.
All works fine at the beginning. I created a few extensions and domains. I decide to delete one of the created domains (not the main) and then i was unable to login again.
I'm behind a NAT (pfsense), and if i login through the LAN address actually work. The problem happens when try to login through the port forwarded public address.

**Comment by markjcrane** [comment]
This is because fusionpbx is multi-tenant and your browser isn't pointed to the domain that is in the server. You can login with user@domain. The domain being your ip addrress or domain used seen in advanced -> domains.

**Comment by kenayagi** [comment]
Just a note, that could maybe be useful to someone else: I found that this happened even after changing nginx port to non-443.
Explicitly specifying user@domain allowed me to login.
