### ISSUE TITLE
How do you save the SIP to SIP (IP to IP) accounts on the system? 

### ISSUE THREAD

**Issue by fitreklam** [fusionpbx/fusionpbx#1887]
How do you save the SIP to SIP (IP to IP) accounts on the system?

**Comment by markjcrane** [comment]
You can send calls to another server by using a gateway with registration true or false combined with an outbound route or by using a bridge statement https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools:+bridge in an outbound route.

Inbound can be handled with an inbound route or dialplan destinations.
