### ISSUE TITLE
mod_local_stream.c:819 Unknown source default

### ISSUE THREAD

**Issue by sattarnawab** [fusionpbx/fusionpbx#1890]
Hi Mark,
I just did an upgrade to the fusionpbx and facing this issue.

**Comment by markjcrane** [comment]
FreeSWITCH devs changed the path and got rid of the music/default directory now just has music. By doing this they broken everyone using music on hold that had music working with the default directory.

**Comment by markjcrane** [comment]
This will fix the package install leaving default as part of the path.

#remove the music package to protect music on hold from package updates
mkdir -p /usr/share/freeswitch/sounds/temp
mv /usr/share/freeswitch/sounds/music/*000 /usr/share/freeswitch/sounds/temp
apt-get remove -y --force-yes freeswitch-music-default
mkdir -p /usr/share/freeswitch/sounds/music/default
mv /usr/share/freeswitch/sounds/temp/* /usr/share/freeswitch/sounds/music/default
rm -R /usr/share/freeswitch/sounds/temp
