### ISSUE TITLE
Provisioning of any keys other than line keys broken

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#1893]
A change was made two days ago in commit 75b36f0 at line 757 to apps/provision/resources/classes/provision.php which has broken memory key provisioning for Grandstream phones (and possibly others).

```
foreach($device_keys as $row) {
```
...was changed to:
```
foreach($device_keys['line'] as $row) {
```
Now "memory" keys are no longer injected into the provisioning template. Reverting this change fixes it.

**Comment by markjcrane** [comment]
> foreach($device_keys['line'] as $row) {

This section of code works updates variables in the label for example ${user_id} so this code would make variables not get updated to their values for something like memory keys. I suspect this isn't your problem.

Are you using a custom template? If not which template are you using?

**Comment by markjcrane** [comment]
https://github.com/fusionpbx/fusionpbx/commit/8f7665c2d8fe88029e052c2e706361ad3f61f5dd New commit will exchange variable names for their values for memory, expansion, and programmable in addition to lines.

**Comment by Tatermen** [comment]
> `foreach($device_keys['line'] as $row) {`
> 
> This section of code works updates variables in the label for example ${user_id} so this code would make variables not get updated to their values for something like memory keys. I suspect this isn't your problem.

This line means that the code only parses keys of subcategory "line". It ignores all other key types (memory, programmable, expansion).

For example, prior to the above commit, it generates the following for memory key one

```
<!--  Multipurpose Key 1 -->
<!-- Key Mode. -->
<!-- 0 - Speed Dial, 1 - BLF, 2 - Presence Watcher, 3 - eventlist BLF  -->
<!-- 4 - Speed Dial via active account, 5 - DialDTMF, 6 - Voicemail, 7 - CallReturn -->
<!-- 8 - Transfer, 9 - CallPark, 10 - Intercom, 11 - LDAP Search -->
<!-- Number: 0-11 -->
<!-- Mandatory -->
<P323>0</P323>
<!-- Account. 0 - Account 1, 1 - Account 2, 2 - Account 3, 3 - Account 4, 4 - Account 5, 5 - Account 6 -->
<!-- Number: 0 - 5 -->
<!-- Mandatory -->
<P301>0</P301>
<!-- Name. Max length allowed is 32 characters. -->
<!-- String -->
<P302>Roderick</P302>
<!-- User ID. Max length allowed is 64 characters. -->
<!-- String -->
<P303>xxxxxxxxxxx</P303>
<!-- Multipurpose Key 2 -->
<!-- Key Mode. -->
<!-- 0 - Speed Dial, 1 - BLF, 2 - Presence Watcher, 3 - eventlist BLF -->
<!-- 4 - Speed Dial via active account, 5 - DialDTMF, 6 - Voicemail, 7 - CallReturn -->
<!-- 8 - Transfer, 9 - CallPark, 10 - Intercom, 11 - LDAP Search -->
<!-- Number: 0-11 -->
<!-- Mandatory -->
<P324>0</P324>
<!-- Account. 0 - Account 1, 1 - Account 2, 2 - Account 3, 3 - Account 4, 4 - Account 5, 5 - Account 6 -->
<!-- Number: 0 - 5 -->
<!-- Mandatory -->
<P304>0</P304>
```

After that commit, this section of the template is left blank:

```
<!--  Multipurpose Key 1 -->
<!-- Key Mode. -->
<!-- 0 - Speed Dial, 1 - BLF, 2 - Presence Watcher, 3 - eventlist BLF  -->
<!-- 4 - Speed Dial via active account, 5 - DialDTMF, 6 - Voicemail, 7 - CallReturn -->
<!-- 8 - Transfer, 9 - CallPark, 10 - Intercom, 11 - LDAP Search -->
<!-- Number: 0-11 -->
<!-- Mandatory -->
<P323></P323>
<!-- Account. 0 - Account 1, 1 - Account 2, 2 - Account 3, 3 - Account 4, 4 - Account 5, 5 - Account 6 -->
<!-- Number: 0 - 5 -->
<!-- Mandatory -->
<P301></P301>
<!-- Name. Max length allowed is 32 characters. -->
<!-- String -->
<P302></P302>
<!-- User ID. Max length allowed is 64 characters. -->
<!-- String -->
<P303></P303>
```

> Are you using a custom template? If not which template are you using?

We are using a custom template, but tried reverting to the FusionPBX provided one (grandstream/gxp21xx) to test, thinking something had changed and we needed to update ours.

**Comment by Tatermen** [comment]
I can confirm that 8f7665c appears to have fixed it.
