### ISSUE TITLE
BUG: Admin's updating IVR do not write to the dialplan

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1911]
Create an IVR as superadmin, then log in as an ADMIN and make any change to the IVR. This will write a blank dialplan to the dialplan manager and calls to the IVR will fail.

To fix you need to log in as superadmin, re-save the IVR then go to dialplan manager and delete the duplicate blank one.

**Comment by kismetgerald** [comment]
I can confirm this on my system as well.

**Comment by markjcrane** [comment]
This should be fixed please update the source and try again.

**Comment by blackc2004** [comment]
Appears fixed!
