### ISSUE TITLE
Provisioning Templates for Yealink T40P phones are missing

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#1914]
Is it possible to please add Yealink T40P's to provisioning?

**Comment by blackc2004** [comment]
You should be able to use the T42 or T41 templates for it. They are all pretty much the same.

**Comment by konradSC** [comment]
Yes, I can use the T41 or T42 template to get the basic extension to the phone, but the phone will request y000000000054.cfg which is not present on the server. This file contains things like the Remote Phonebooks. The T41 file is y000000000036.cfg. That is why with Yealinks we need model specific templates built.

**Comment by Len-PGH** [comment]
i put a pr in for this https://github.com/fusionpbx/fusionpbx/pull/1941  I don't have this phone to test on but should work

**Comment by markjcrane** [comment]
Yealink t40p provisioning templates were added closing the issue
