### ISSUE TITLE
Ring Group no registered users

### ISSUE THREAD

**Issue by teknoprep** [fusionpbx/fusionpbx#1923]
when you have a ring group that rings a single user and that extension is not registered.. it does not move on to the next destination which i have set as that users voicemail

**Comment by markjcrane** [comment]
What is the ring group strategy?

**Comment by teknoprep** [comment]
i tried both sim and ent... same issue

**Comment by markjcrane** [comment]
It should not go to the users voicemail the ring group will go to its exit action.

**Comment by teknoprep** [comment]
It's not going to the exit action if it's a vm

On Nov 6, 2016 2:43 AM, FusionPBX <notifications@github.com> wrote:

It should not go to the users voicemail the ring group will go to its exit action.

-

**Comment by markjcrane** [comment]
I just tested it it again internally by calling the ring group number and through the carrier.
There is one destination going to an extension that is not registered and it is going to the exit action as it should.

Destinations can only be extensions, external numbers and bridge statements. They cannot be sent direct to voicemail which would require a transfer to *99 <extension> unless using loopback.
