### ISSUE TITLE
Upgrade from 4.1.0 to 4.2.x fails

### ISSUE THREAD

**Issue by beedsley** [fusionpbx/fusionpbx#1924]
Using either the GUI or command line results in "access denied" for some pages and if you log out, you cannot log back in. Followed the instructions at: http://docs.fusionpbx.com/en/latest/advanced/upgrade.html#version-4-0-to-4-2
Can easily reproduce this behavior and am willing to provide www and ssh access for you to verify.

Let me know what additional information i can provide.

**Comment by markjcrane** [comment]
The upgrade has not failed you go to browser pbx.yourdomain.com/logout.php

**Comment by markjcrane** [comment]
Or if upgrade was started with you logged out you may not have had this issue. If you have a single domain system make sure browser domain matches or login with username@domain

Then the menu will be gone go to core/upgrade/index.php update schema and menu.

**Comment by markjcrane** [comment]
Need more help with the upgrade pay for support.

**Comment by beedsley** [comment]
Also, the documentation says to do:

Go To Advanced -> Group Manager
On 'superadmin" click Permissions and then Restore Default 

after you click on Permissions, the "Restore Default" is not available.

**Comment by beedsley** [comment]
Thanks Mark, by adding the domain to the login, i am able to login and am running 4.2 successfully, thank you!
