### ISSUE TITLE
After 4.2 upgrade: APPS: Conference Controls and Conference Profiles: "Access Denied"

### ISSUE THREAD

**Issue by beedsley** [fusionpbx/fusionpbx#1925]
Fulfilled all the steps in:

http://docs.fusionpbx.com/en/latest/advanced/upgrade.html#version-4-0-to-4-2

Upgraded from 4.1 to 4.2 but have an error:

APPS: Conference Controls and Conference Profiles: "Access Denied"

**Comment by beedsley** [comment]
Well, not sure why, but both are working now.

**Comment by markjcrane** [comment]
After you update the group permissions you need to logout and back in for them to apply.
