### ISSUE TITLE
[v4.2] mp3 voicemail does not work

### ISSUE THREAD

**Issue by rajil** [fusionpbx/fusionpbx#1928]
Hello,

I set the record_ext variable to mp3 in Advanced>Variables, flushed memcache and restarted freeswitch. The module mod_shout is loaded. However, the voicemails are still using the wav format.

```
freeswitch@voip> module_exists mod_shout
true
```

Thanks

**Comment by bkuhls** [comment]
Did you configure the Mod Shout Decoder in Advanced -> Settings?

**Comment by rajil** [comment]
Documentation of [Freeswitch] (https://wiki.freeswitch.org/wiki/Mod_voicemail#vm_message_ext)  seems to suggest that vm_message_ext might be the variable to set rather than record_ext.

**Comment by markjcrane** [comment]
rail is correct record_ext is for recordings *732 not for voicemail.
