### ISSUE TITLE
[v4.2] voicemail doesn't read out voicemail extension number

### ISSUE THREAD

**Issue by jebsolutions** [fusionpbx/fusionpbx#1930]
https://github.com/fusionpbx/fusionpbx/pull/1929

bug: variable scope of voicemail_greet_id is only defined inside the inner if statement.

symptoms: The person at [] is unavailable.
i.e. won't say the extension number when you get to voicemail

also see this in the logs:
[ERR] switch_cpp.cpp:977 Error! invalid args.

**Comment by markjcrane** [comment]
Accepted your pull request that fixes this issue;.
