### ISSUE TITLE
Restriction on recording calls is not working correctly.

### ISSUE THREAD

**Issue by ash144** [fusionpbx/fusionpbx#1935]
Hi there!
The problem - call recording does not work correctly.
Debian 8, FusionPBX 4.2 new install.
Dialplan - has not changed after the installation, user_record enabled.
![dialplan_user_record](https://cloud.githubusercontent.com/assets/21078917/18689459/e06a75c8-7f91-11e6-99c7-90a63d8ed0c6.PNG)
On the extensions specified Record = Local.
I make inbound call, but the call is recorded!
If you look at the log, we see that the conditions in the group (except the last) are ignored.
Freeswitch log in attach.
[fs_log_user_record.txt](https://github.com/fusionpbx/fusionpbx/files/483587/fs_log_user_record.txt)

**Comment by markjcrane** [comment]
Your log shows that a command to record the call is being set.

**Comment by moteus** [comment]
may be need check `from_user_exists` for `local` calls as whell?

**Comment by ash144** [comment]
markjcrane: call should not be recorded, becouse in extension "Record = Local".
Do I understand correctly that the dialplan this action should not have been executed? This logical AND?
![user_record](https://cloud.githubusercontent.com/assets/21078917/18701815/54500520-7fe7-11e6-9bc9-826340fef6e8.PNG)
In my call:
${user_exists}=true (PASS)
${call_direction}=inbound (**FAIL!**)
${user_record}=local (PASS)

**Comment by ash144** [comment]
markjcrane: call should not be recorded, becouse in extension "Record = Local".
Do I understand correctly that the dialplan this action should not have been executed? This logical AND?
![user_record](https://cloud.githubusercontent.com/assets/21078917/18702585/097f7f0e-7feb-11e6-83cf-8e4b59d29fa3.PNG)
In my call: user_exists=true, call_direction=inbound, user_record=local.
In log:
_Regex (PASS) [user_record] ${user_exists}(true) =~ /^true$/ break=never
Regex (FAIL) [user_record] ${call_direction}(inbound) =~ /^local$/ break=never
Regex (PASS) [user_record] ${user_record}(local) =~ /^local$/ break=never
Action set(record_session=true) INLINE_                             **<--- why?**

**Comment by moteus** [comment]
If I understand correctly `user_exists` is for destination number. and it is exists because you transfer to extension. But source is not extenstion but some trunk. So as I say may be need check also from_user_exists. Not sure how,

**Comment by ash144** [comment]
Sorry, maybe I'm wrong to formulate the question.
That is, I have to change the default dial plan in FusionPBX, to selected option to record when a call (Local / Inbound / Outbound) worked fine?
I thought that this function works immediately after installation. If not, then I will try to adjust it.
Default dialplan for call record:
![dialplan_user_record1](https://cloud.githubusercontent.com/assets/21078917/18707462/dbb373b4-7ffe-11e6-8a91-2b918a7d02fb.PNG)
![dialplan_user_record2](https://cloud.githubusercontent.com/assets/21078917/18707464/e0354c28-7ffe-11e6-90c3-3fc9afa1a451.PNG)
![dialplan_user_record3](https://cloud.githubusercontent.com/assets/21078917/18707467/e33e4df2-7ffe-11e6-9251-bba0aa61cce3.PNG)

**Comment by moteus** [comment]
I do not use it. Just say what I see. It checks if destination number point ot existed user and call direction inbound and in match `local`. may be need use `from_user_exists` or remove this condition at all because direction is `inbound` can not match `local` type record.

**Comment by ash144** [comment]
moteus: thanks, i try.

**Comment by markjcrane** [comment]
user_exists dialplan is delete it and run app -> defaults.
Its more likely the directory for the recording with domain name as a sub directory doesn't exist.
Or file permissions are wrong.
