### ISSUE TITLE
admin cannot update destinations

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1936]
An admin user cannot update destinations. Go into the destination, change the action, save the action is then "blank". and the inbound route is blank.

<img width="1370" alt="screen shot 2016-09-20 at 6 04 37 pm" src="https://cloud.githubusercontent.com/assets/13256764/18694204/d3193ed4-7f5c-11e6-8dab-b9f038322017.png">
<img width="1353" alt="screen shot 2016-09-20 at 6 04 44 pm" src="https://cloud.githubusercontent.com/assets/13256764/18694205/d31d15ea-7f5c-11e6-9993-59e5cf379083.png">

**Comment by andycol** [comment]
this works for me i am on the latest commit

**Comment by markjcrane** [comment]
Make sure you ran upgrade -> schema.

**Comment by markjcrane** [comment]
Just tested this and it working fine I worked on a fix a couple weeks ago.
