### ISSUE TITLE
Feature:- Add pin number to user for outbound calls

### ISSUE THREAD

**Issue by KerryRJ** [fusionpbx/fusionpbx#1946]
I would like to be able to add a pin number to the user information that will be collected before an outbound call is made and stored in the CDR.

Is the user information the place to make the change or should the pin number app be used?

**Comment by andycol** [comment]
use the pin number app and it does add it in the cdr's
if you want it to display on the front page of call detail records you will need custom development

**Comment by markjcrane** [comment]
This already exists. You can set pin_number= to a number and then add a lua script pin_number.lua. I teach how to use this in better detail int he FusionPBX admin training.
