### ISSUE TITLE
Fax destinations are creating incorrect dialplans

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1947]
If you create a destination for a fax with an extension # as the destination, the dialplan is getting created with the FULL DID. 

System Information
Version	4.2.0
Git Information	Branch: master 
Commit: 01f4dfe527d9504f8e0ccff72a1976aef0833af4 
Origin: https://github.com/fusionpbx/fusionpbx 
Project Path	/var/www/fusionpbx
Switch Version	1.6.8 (64bit)

![screen shot 2016-09-26 at 7 54 33 am](https://cloud.githubusercontent.com/assets/13256764/18839284/48ab3cb8-83bf-11e6-9363-5dc0b1bb085e.png)
![screen shot 2016-09-26 at 7 54 47 am](https://cloud.githubusercontent.com/assets/13256764/18839286/48b2a8d6-83bf-11e6-958c-0fc396ee64d5.png)
![screen shot 2016-09-26 at 7 55 21 am](https://cloud.githubusercontent.com/assets/13256764/18839285/48ad2be0-83bf-11e6-9ff9-f1075ff04049.png)

**Comment by blackc2004** [comment]
Sorry, It's actually the creation of the FAX destination itself that's generating the wrong dialplan entry.

**Comment by markjcrane** [comment]
When you create a fax extension or edit it leave the destination as empty notice its not in bold so it is not required. When it is empty it will use the extension number as the destination number. The destination in the fax settings is referring specifically to the destination_number for the fax dialplan. In other words you the user thought it meant the DID and this broke it. Its for advanced purposes leave it alone if you don't know what it is used for.

**Comment by blackc2004** [comment]
> Its for advanced purposes leave it alone if you don't know what it is used for.

Mark, I'm getting a little sick of your condescending tone in these requests (here and #1943). I'm both a contributor in code and I have taken both admin and advanced classes multiple times.  There's no mention of this in any admin or advanced class documentation or in the wiki or docs.fusionpbx.com

There's no need to be condescending in your replies.
