### ISSUE TITLE
Creating a fax server extension then go to dialplan and the "edit" button's are missing

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1948]
If you create a fax server and then go to the dialplan, most of the EDIT buttons are missing. Seems like maybe the creation of a fax server is resetting permissions somewhere? You have to log out and back in to get the edit buttons back.

![screen shot 2016-09-26 at 8 06 43 am](https://cloud.githubusercontent.com/assets/13256764/18839685/b114e366-83c0-11e6-957b-2a3597af0ca1.png)

System Information
Version	4.2.0
Git Information	Branch: master 
Commit: 01f4dfe527d9504f8e0ccff72a1976aef0833af4 
Origin: https://github.com/fusionpbx/fusionpbx 
Project Path	/var/www/fusionpbx
Switch Version	1.6.8 (64bit)

**Comment by markjcrane** [comment]
This has been fixed on both master and 4.2 stable branches.
