### ISSUE TITLE
Call Center Queues don't record

### ISSUE THREAD

**Issue by hatclub** [fusionpbx/fusionpbx#1950]
How to reproduce:
Create a Call Center Queue
Record = True
Call the queue and answer the call
Calls are not recorded (or if they are, I can't find them - no evidence of recording is seen in the full CDR detail) - even when calls are answered by an extension that has "Record = All"

**Comment by markjcrane** [comment]
Record on the extension applies only to calls reaching it through the dialplan. Call center queue is direct bridge bypassing the dialplan to the extension and therefore would not be recorded. But call center does have a record option.

**Comment by Len-PGH** [comment]
There was a bug in a 1.6.x version of Freeswitch (forget which but was before 1.6.13)  Could try to update FreeSWITCH
