### ISSUE TITLE
Problem with default voicemail greeting

### ISSUE THREAD

**Issue by DigiDaz** [fusionpbx/fusionpbx#1956]
The extension number does not play in latest master.

Instead of "The person at extension, XXX, is not available"

You get "The person at extension, is not available"

In macro.lua, if (voicemail_alternate_greet_id) then

seems to get matched as its an empty string but even if it gets passed that you then get a problem with voicemail_greet_id which doesn't seem to get assigned anywhere.

**Comment by jebsolutions** [comment]
I had this problem as well.  Mark added a fix for this bug and it's working fine for me now.
#1930 

I did a full backup.  Then a source + default settings Upgrade pulled in the fix.

**Comment by DigiDaz** [comment]
Yes I saw that, I will double check again now but I think this is a completely different issue unless there has been a very recent fix.

**Comment by flyer292** [comment]
I have the same issue on my system as well

**Comment by markjcrane** [comment]
Fixed this issue earlier today update to latest source and it should work fine.
