### ISSUE TITLE
Call Timeout affect incoming but also outgoing call

### ISSUE THREAD

**Issue by MK-87** [fusionpbx/fusionpbx#1961]
> elfranne commented on Oct 22, 2015

`Call Timeout (Accounts -> Extensions) setting does affect incoming but also outgoing calls. When calling out the call drop with "failed" after the set timeout value.

How to reproduce:
change a local extension "call timeout" to a lower value (15sec).
try to call out
change it back to 30sec, notice the difference.
`
1year old bump; 
Hello, anyone got a solution to this problem that it does not affect outgoing calls also?

**Comment by markjcrane** [comment]
The timeout variable is set on the extension xml so that it can be used for inbound timeout. You could add a call_timeout variable to your outbound routes to override the timeout. Please give this a try.

**Comment by markjcrane** [comment]
I don't see a bug here call_timeout intentional affects inbound and outbound. If you want it to affect only outbound then set it on an outbound route. If you want to change it on inbound then add a dialplan with call_direction inbound. Set continue to true and then set the call timeout.

**Comment by jebsolutions** [comment]
I am seeing something, that I think is related.

I have a DID going to a time condition which redirects to either an "office hours" or "extended hours" ring group.  All extensions in both ring groups ring for 45 seconds.  The fail over destination for each ring group is a voicemail box.

If I pick up an incoming call within 30 seconds everything works.  But if I don't answer the call it never goes to voicemail.  The incoming call is always disconnected after 30 seconds.

If I modify the inbound route and insert a line to force it to "answer" the incoming call everything works:

condition 	destination_number 	^(5555555555)$ 			0 	20
action 	answer 				0 	25  <--- insert this line
action 	transfer 	1100 XML 192.168.0.203 			0 	30

This fixed incoming calls being disconnected after 30 seconds for me.

I would recommend doing a file/database backup before trying this.  The caveat is that inbound routes may became impossible to edit.  No errors...just no changes are saved?  I am working to make this separate problem reproducible.

**Comment by cookiesowns** [comment]
@jebsolutions Any updates on reproducing this bug? We have FusionPBX deployed and are experiencing odd issues with inbound/outbound calls related to calltimeouts.

Not 100% sure if the issue you are describing is what we are facing.
