### ISSUE TITLE
Blocking Extensions from Dialing out not working.

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#1965]
Hi I have setup a PBX that needs to allow some extensions to dial-out and some not to dial-out.

The Phones that I am blocking from dialing out I have added local on the To Allow section on the Extension but that is not working.

When a user from that extension tries to dial he gets prompted for a pin like all other users.

Normal user when the dial-out they a prompted to enter password and that works fine.

Is there a way I can stop those phones from dialing or accessing the trunk?

**Comment by andycol** [comment]
Did you add the toll allow section in the outbound route?

**Comment by markjcrane** [comment]
If he did it would have worked. You are required to add a condition that checks toll_allow variable.
