### ISSUE TITLE
BUG: IVR Greet short is not pulling the correct file path

### ISSUE THREAD

**Issue by blackc2004** [fusionpbx/fusionpbx#1966]
IVR greet short is not pulling from the domain path, instead it's pulling from the freeswitch path.

IE:
2016-10-04 10:20:35.616237 [ERR] mod_sndfile.c:204 Error Opening File [/usr/local/freeswitch/sounds/en/us/callie/main_menu_v2-day_noTrailCond-new.wav] [System error : No such file or directory.]

But it should be pulling from:
/usr/local/freeswitch/recordings/mydomain.com/main_menu_v2-day_noTrailCond-new.wav

**Comment by blackc2004** [comment]
Sorry, just found this issue which is the same thing: https://github.com/fusionpbx/fusionpbx/issues/1957

Closing this ticket.

**Comment by gmaruzz** [comment]
After recording is done, from app menu create a phrase which "Play" that recording in the required "Language" (eg, en), then use the "phrase" throughout IVR. That works
