### ISSUE TITLE
Fax Server

### ISSUE THREAD

**Issue by Tricom114** [fusionpbx/fusionpbx#1971]
A few days ago with an update there started this new issue.  When you create a new fax server, or update a current fax server, it either disappears from the dialplan manager or is not created in the dialplan manager.    My current fax servers are working, and I can fax out.  I just can not update the ones I have because they will stop working, or create new ones because the new ones are not added to the dialplan manager.

**Comment by markjcrane** [comment]
Update the source code then fax dialplan should be working resave one of the faxes to confirm.

**Comment by Tricom114** [comment]
That seems to have done the trick.  Thanks!
