### ISSUE TITLE
Password Admin Lockout

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#1972]
after an new fresh install and a few days of config time on the last day to check i wasnt able to login at all total fail

i try to do the password reset
http://fusionpbx-docs.readthedocs.io/en/latest/additional_information/password_reset.html?highlight=password

and updated - 1 , still an fail to login..

I have not gone live yet bit all settings is there and ready

Any help will be great, thanks

**Comment by markjcrane** [comment]
Make a not of your password in /var/www/fusionpbx/resources/config.php

Then delete it or move it out of the Web directory. Run the install again create a new user account.

**Comment by MrCoolLV** [comment]
@markjcrane thank you it worked and gained access.. i see the number of ext's but i don't the extensions itself. please review screenshot 

![dsfgsdgfsdfgsdgf](https://cloud.githubusercontent.com/assets/22685867/19206414/b594a6e8-8c9d-11e6-9233-2120ba5235db.png)

- Thank you

**Comment by MrCoolLV** [comment]
Same goes with groups, and ivr's you see them in the dashboard but thats about it

**Comment by markjcrane** [comment]
Are you saying in a roundabout way that you don't see the menu?

**Comment by MrCoolLV** [comment]
the count in dashboard is correct, but the actual list of extensions or ring groups are empty.

**Comment by MrCoolLV** [comment]
@markjcrane any update will be great thanks

**Comment by markjcrane** [comment]
Again are you saying the menu is missing? Maybe you have more than one domain and it is showing only the current domain.

**Comment by MrCoolLV** [comment]
@markjcrane your maybe right, so as superadmin how can i view all the ext's and group's from all domains.

that way i can correct it ?

**Comment by markjcrane** [comment]
You view the extensions one domain at a time using the domain select list on the right side or press the escape button to show the domain search tool.

**Comment by MrCoolLV** [comment]
ya after 
###
Make a not of your password in /var/www/fusionpbx/resources/config.php
Then delete it or move it out of the Web directory. Run the install again create a new user account
### 

i lost the data that took me 4 days to do i'll just re add it in

**Comment by markjcrane** [comment]
You did not loose you data. It is on a different domain or you chose a different database either way it's still there somewhere.

**Comment by MrCoolLV** [comment]
I will try again, but is not showing any domains in the list nor giving me an option to switch over

**Comment by MrCoolLV** [comment]
@markjcrane anyway to force admin to view all without the switching, is not giving me domain options to switch after i did reinstall with the same database

**Comment by MrCoolLV** [comment]
@bigfisgvoice

**Comment by markjcrane** [comment]
Advanced -> Domains it will only show the Domain  tool if there is more than one domain.
