### ISSUE TITLE
Feature Request: Add Device Settings to Device Profile

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#1973]
Under Device Profiles we are able to add common Keys for devices. It would be very helpful to be able to add common Settings in the Profiles as well like we can enter under Devices. (Name,Value,Enabled,Description)
[settings.pdf](https://github.com/fusionpbx/fusionpbx/files/516775/settings.pdf)

**Comment by markjcrane** [comment]
This feature is the to do list.

**Comment by jlcrews** [comment]
I would vote for this as well.

**Comment by konradSC** [comment]
Added
