### ISSUE TITLE
Feature Request: DND

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#1974]
It would be helpful to have a DND toggle (on/off) feature code like Call Forward has.

**Comment by markjcrane** [comment]
If you are on master branch 4.3 you can update your source delete your Do not Disturb dialplan then run Upgrade -> App Defaults. Then you can test it with *77.  Please report back how it is working for you.

**Comment by konradSC** [comment]
Working well on our lab system. Great little feature :) Thanks.

**Comment by markjcrane** [comment]
Built it in the car while my wife was driving. On my way to LA, California for the Advanced training starting Tuesday next week.

**Comment by konradSC** [comment]
Tested it with my young kids starting WWIII in the same room. The DND toggle does not work on them. That will be my next feature request. Have a good trip!
