### ISSUE TITLE
Yealink T21 Register Failed via SIP

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#1975]
having a bit of a problem connecting via sip with Yealink T21
![yealink t21 e2 phone](https://cloud.githubusercontent.com/assets/22685867/19212961/e801caae-8d13-11e6-8ca1-2b047fc3b26b.png)

to test to see if is pbx, i installed zoiper and set it to another ext and worked
![asdfasfd](https://cloud.githubusercontent.com/assets/22685867/19212967/049580a2-8d14-11e6-88e2-53a45d70d803.png)

not to sure why the phone will not connect, both are using server via domain

**Comment by MrCoolLV** [comment]
any update ?

**Comment by bigfishvoice** [comment]
I had this problem before.  Make sure the phone has the latest firmware. That helped me on the T22s.

**Comment by MrCoolLV** [comment]
yes, is to the latest 52.80.0.130

**Comment by MrCoolLV** [comment]
which matches what i see online here
http://support.yealink.com/documentFront/forwardToDocumentDetailPage?documentId=77

**Comment by MrCoolLV** [comment]
![sasfasfd](https://cloud.githubusercontent.com/assets/22685867/19222228/4bce1e58-8e08-11e6-87a4-49276ade311b.png)

**Comment by bigfishvoice** [comment]
I see that you are Account 2, is Account 1 registered?  Make sure they are on ports, some firewalls don't handle multiple phones/accounts going out on the same 5060 port.

Another thing to try is Factory Reset.  Then if you were using auto provisioning, manually configure the account and see if that gives you a different result instead of using auto provision.

**Comment by MrCoolLV** [comment]
Yes, Account 1 is fine is another pbx in another server , not the same ip or domain

Not using autoprovisioning , the 2nd account is use for other pbx systems.. I have 18 3cx servers for our clients and they connect via sip just fine but when i try to connect to fusion it fails 

Now side note 3cx new linux i have setup and tested yesterday, the Yealink T21 connected to it just fine no banning or anything works out of the box not sure why fusionpbx is having a hard time on an basic setup

**Comment by MrCoolLV** [comment]
my client uses polycom vx300 via sip im wording they going have the same problem too

**Comment by bigfishvoice** [comment]
Are you using the External SIP profile or just the Internal?  We typically disable the External profile and just use the Internal.

**Comment by MrCoolLV** [comment]
they will need box, they have 4 offices and pbx will be internal in one location and external on the other 3

**Comment by bigfishvoice** [comment]
Not talking about the location of the pbx, but the SIP profile that is running on the server.  The internal profile is what the extensions authenticate against.

I would still suggest doing a factory reset and then only setting up the Fusion account and see if it works in by itself.

**Comment by MrCoolLV** [comment]
your the man, that did the trick, thank you so much
