### ISSUE TITLE
Firewall ?

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#1977]
i have no idea whats going on, one min works the next nothing works and have to reboot.
i don't see this being a problem with other pbx systems, im only getting it here fusion

i called support willing to pay, i left a vmail 

i may have to go back to 3cx

**Comment by markjcrane** [comment]
Run iptables -L to see if fail2ban is blocking your IP address.

**Comment by MrCoolLV** [comment]
Hello, all looks good on my end and phones still not working

root@debian:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by markjcrane** [comment]
That shows fail2ban is not running or not installed.

**Comment by MrCoolLV** [comment]
sorry that was an #3cx linux system


root@debian:~# tables -L
-bash: tables: command not found
root@debian:~# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
fail2ban-nginx-dos  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-nginx-404  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-fusionpbx  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-freeswitch-dos-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-dos-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-ip-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-ip-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dports ssh
fail2ban-nginx-dos  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-nginx-404  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-fusionpbx  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-freeswitch-dos-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-dos-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-ip-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-ip-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-tcp  tcp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-freeswitch-udp  udp  --  anywhere             anywhere             multiport dports sip,sip-tls,5080,5081
fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dports ssh
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpts:sip:sip-tls
ACCEPT     udp  --  anywhere             anywhere             udp dpts:sip:sip-tls
ACCEPT     tcp  --  anywhere             anywhere             tcp dpts:5080:5081
ACCEPT     udp  --  anywhere             anywhere             udp dpts:5080:5081
ACCEPT     udp  --  anywhere             anywhere             udp dpts:16384:32768
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:sip
ACCEPT     udp  --  anywhere             anywhere             udp dpt:sip
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:5080
ACCEPT     udp  --  anywhere             anywhere             udp dpt:5080
ACCEPT     udp  --  anywhere             anywhere             udp dpts:16384:32768

Chain FORWARD (policy DROP)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain fail2ban-freeswitch-dos-tcp (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-freeswitch-dos-udp (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-freeswitch-ip-tcp (2 references)
target     prot opt source               destination
REJECT     all  --  194.63.141.94        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  h185-20-99-2.host.redstation.co.uk  anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-freeswitch-ip-udp (2 references)
target     prot opt source               destination
REJECT     all  --  194.63.141.94        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  h185-20-99-2.host.redstation.co.uk  anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-freeswitch-tcp (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-freeswitch-udp (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-fusionpbx (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-nginx-404 (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-nginx-dos (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-ssh (2 references)
target     prot opt source               destination
REJECT     all  --  116.31.116.11        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  62-4-15-52.rev.poneytelecom.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  108.30.65.218.broad.xy.jx.dynamic.163data.com.cn  anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

**Comment by MrCoolLV** [comment]
working thank you
