### ISSUE TITLE
inbound

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#1980]
im getting an voice "the person your trying to reach is unavailable " even tho all settings are correct

please advise

![asdsasdasd](https://cloud.githubusercontent.com/assets/22685867/19246384/eeb21930-8eda-11e6-956f-df180ce944e4.png)
![sfsadfasfdasdf](https://cloud.githubusercontent.com/assets/22685867/19246385/eeb81aba-8eda-11e6-8807-aca9ac418cee.png)

**Comment by MrCoolLV** [comment]
here is the ivr

![sdasdfd](https://cloud.githubusercontent.com/assets/22685867/19246469/5a983f26-8edb-11e6-9b29-b53c1d0af7a1.png)

**Comment by MrCoolLV** [comment]
# > 800 > ivr wav file

**Comment by bigfishvoice** [comment]
Make sure in the IVR destinations, you are sending them to the Extension and not the Voicemail of the extension.  You have to scroll up to the very top to see the extensions.

**Comment by MrCoolLV** [comment]
no is set to ivr 800, when i dail from internal plays the message

**Comment by bigfishvoice** [comment]
I would check the log file to see if you can see where it is actually routing to.  It might help determine the cause.

**Comment by MrCoolLV** [comment]
shows no logs 👎 this only happens calling actual #

**Comment by MrCoolLV** [comment]
i do see this

fc5a66dc-e0d9-43cd-8cb5-70ff8fc19bdb Dialplan: sofia/external/17865310408@66.193.176.35 Regex (FAIL) [Main] destination_number(17778427193101) =~ /^(7542008917)$/ break=on-false

**Comment by bigfishvoice** [comment]
Are you calling the extension 800 or the DID that is pointing to the IVR?

**Comment by MrCoolLV** [comment]
im going did that shoud go to ivr 800

**Comment by MrCoolLV** [comment]
when i call ext works, when i call DID it fails

**Comment by bigfishvoice** [comment]
As a test, go to Dialplan > Dialplan Manager > Enable is_local

is_local will allow the call to be routed internally which may give you the desired result.

**Comment by MrCoolLV** [comment]
ok, sorry still the same

**Comment by MrCoolLV** [comment]
i disabled "in_local"

i noticed this in logs
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:643 (sofia/external/17865310408@66.193.176.35) State ROUTING going to sleep 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:584 (sofia/external/17865310408@66.193.176.35) Running State Change CS_HANGUP 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:850 (sofia/external/17865310408@66.193.176.35) Callstate Change RINGING -> HANGUP 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:852 (sofia/external/17865310408@66.193.176.35) State HANGUP 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] mod_sofia.c:438 Channel sofia/external/17865310408@66.193.176.35 hanging up, cause: NO_ROUTE_DESTINATION 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] mod_sofia.c:577 Responding to INVITE with: 404 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:60 sofia/external/17865310408@66.193.176.35 Standard HANGUP, cause: NO_ROUTE_DESTINATION 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:852 (sofia/external/17865310408@66.193.176.35) State HANGUP going to sleep 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:619 (sofia/external/17865310408@66.193.176.35) State Change CS_HANGUP -> CS_REPORTING 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:584 (sofia/external/17865310408@66.193.176.35) Running State Change CS_REPORTING 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.306783 [DEBUG] switch_core_state_machine.c:938 (sofia/external/17865310408@66.193.176.35) State REPORTING 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:174 sofia/external/17865310408@66.193.176.35 Standard REPORTING, cause: NO_ROUTE_DESTINATION 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:938 (sofia/external/17865310408@66.193.176.35) State REPORTING going to sleep 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:610 (sofia/external/17865310408@66.193.176.35) State Change CS_REPORTING -> CS_DESTROY 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_session.c:1647 Session 30 (sofia/external/17865310408@66.193.176.35) Locked, Waiting on external entities 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [NOTICE] switch_core_session.c:1665 Session 30 (sofia/external/17865310408@66.193.176.35) Ended 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [NOTICE] switch_core_session.c:1669 Close Channel sofia/external/17865310408@66.193.176.35 [CS_DESTROY] 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:741 (sofia/external/17865310408@66.193.176.35) Running State Change CS_DESTROY 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:751 (sofia/external/17865310408@66.193.176.35) State DESTROY 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] mod_sofia.c:343 sofia/external/17865310408@66.193.176.35 SOFIA DESTROY 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:181 sofia/external/17865310408@66.193.176.35 Standard DESTROY 
4b797b8b-e3c9-4f7b-b10d-47e56d605366 2016-10-10 14:49:48.366680 [DEBUG] switch_core_state_machine.c:751 (sofia/external/17865310408@66.193.176.35) State DESTROY going to sleep

**Comment by MrCoolLV** [comment]
may i doing something wrong ? send me your email so i can $ you

**Comment by bigfishvoice** [comment]
Are you on the IRC #fusionpbx?  If so, that is probably best.  What is your username?

**Comment by markjcrane** [comment]
Or you can use FusionPBX official support.
https://www.fusionpbx.com then click on Support
