### ISSUE TITLE
Is it possible to add contact name in registrations table?

### ISSUE THREAD

**Issue by sergey-mz** [fusionpbx/fusionpbx#1981]
Is it possible to add code to show contact name in registrations table?
Contact element looks like this:
`<contact>&quot;Contact Name&quot; &lt;sip:249@10.0.15.124:5060;transport=udp;fs_nat=yes;fs_path=sip%3A249%4010.0.15.124%3A5060%3Btransport%3Dudp&gt;</contact>`
It's possible to extract contact name in quotation marks and show in the table like below.
Otherwise to find extension **name** we have to search extensions table.

In file app/registrations/resources/classes/status_registrations.php at line 54:

```
//get contact name
    if (isset($row->{'contact'})) {
        sscanf(html_entity_decode($row->{'contact'}), '%s <',$registrations[$x]['contact-name']);
    }else{
        $registrations[$x]['contact-name'] = "&nbsp;";
    }

```

In file app/registrations/status_registrations_inc.php at line 120:
`echo "  <th>".$text['label-contact-name']."</th>\n";`
Line 144:
`echo "  <td class='".$row_style[$c]."'>".$row['contact-name']."&nbsp;</td>\n";`

It will also require translation for label-contact-name.

**Comment by markjcrane** [comment]
Please signup as a contributor and then you can send pull requests for the changes.
See this for instructions.
https://github.com/fusionpbx/open-source

**Comment by markjcrane** [comment]
Try sending a pull request.

**Comment by markjcrane** [comment]
If you signup as a contributor and send a pull request we will accept the change.
