### ISSUE TITLE
Extension registration issues

### ISSUE THREAD

**Issue by stephentyers1975** [fusionpbx/fusionpbx#1988]
Hi,
I'm brand new to fusionpbx and come from an asterisk background. I'm am unable to register extensions. I have built fusionpbx on a digitalocean droplet and am trying to register an extensions and failing. I did manage to get 2 extensions registered using port 5080 after looking at the external profile but then they can't call anything (each other or built in shortcodes). So think they are not meant to register in this method and I keep getting booted.

I have even tried building a local fusionpbx instance on virtual box so everything is on a local private LAN 192.168.0.x and still no luck. I've checked fail2ban etc.. all fine. I'm pulling my hair out as this is  an awesome product, far superior than freepbx and asterisk, but i'm stuck at stage one.I have limited linux experience.

Please help or point me in the right direction. As on the wiki and youtube tutorials it looks simple
Kind regards
Steve

**Comment by markjcrane** [comment]
Port 5080 doesn't do registrations by default it is anonymous. Where are the phones in relation to the PBX same network? or is the PBX on a WAN IP or behind its own firewall?

**Comment by DigiDaz** [comment]
Steve,

Blast away your DO droplet and spin one up with a fresh Debian 8 and follow the instructions here: https://www.fusionpbx.com/app/www/download.php

Your phones should be registering to port 5060 not 5080, 5080 is for carriers not extensions. If you have any problems, try posting at http://www.fusionpbxforums.com/ or alternatively ask in IRC at #fusionpbx on Freenode

**Comment by stephentyers1975** [comment]
Thanks for the quick feedback. I got it working a few hours later. I was trying to use the external IP address for the sip server in the client settings instead of my domain. So it was always banning my IP's

Thanks for the help
