### ISSUE TITLE
Can't copy dialplans

### ISSUE THREAD

**Issue by brucejg** [fusionpbx/fusionpbx#1989]
When copying a dialplan, none of the rules are copied, only the name, order, etc.

**Comment by markjcrane** [comment]
Assuming you are on the master branch. Check the dashboard for the version of FusionPBX do you see 4.3?

**Comment by markjcrane** [comment]
I fixed this on master branch version 4.3.

**Comment by brucejg** [comment]
I am on 4.2

Branch: 4.2
Commit: f52649f2fdd9d5223067b2a3583b966906883869
Origin: https://github.com/fusionpbx/fusionpbx.git
