### ISSUE TITLE
IVR behavior

### ISSUE THREAD

**Issue by brucejg** [fusionpbx/fusionpbx#1990]
If an IVR allows extension dialing and IVR choices have the same number of digits as an extension, then the IVR logic does an is_user check on the entry.  So, if your extensions are numbered 301, 302, etc., and your IVR choices are 701, 702, etc., and a user presses 701, the IVR logic runs is_user, plays the invalid user message and then correctly connects the user to the proper IVR selection.

I created a work around by creating extensions for each IVR selection.  In this case, I created extension 701, 702, etc.  These extensions do nothing except allow the is_user test to pass.

**Comment by markjcrane** [comment]
I set the direct dial condition after all the other options this should fix any case where IVR option uses a transfer which is used most of the time.
