### ISSUE TITLE
Configuring secure sip/rtp with wildcard cert

### ISSUE THREAD

**Issue by stephentyers1975** [fusionpbx/fusionpbx#1993]
HI,

Is there a definitive dummies type guide on setting up secure/tls sip and media for fusionpbx? I want to host multiple companies on one box using the multi-domain feature on fusionpbx. I have no idea where to start. Currently i'm pointing my main domain to my PBX with voice.mydomain.com. If I wanted to have each company on a subdomain under my main domain, do I need a wildcard certificate for domain?? If I have completely different domain spaces pointing to my PBX I guess I need a SAN certificate. Either way I am a complete newbie to Linux and this world and really appreciate some help on the basics of getting this up and running. I'm from a Microsoft Lync background and I don't even know who to generate CSR,s or replace the self-signed certificate on the box.

Many thanks again
Steve

**Comment by markjcrane** [comment]
SIP TLS
https://freeswitch.org/confluence/display/FREESWITCH/SIP+TLS

SRTP
http://wiki.freeswitch.org/wiki/Secure_RTP

Which certificate provider to used dpends on what phones you use. You want to use ones that work well with your phones check the phone manufacturer's documentation.

If you are using snom or yealink you could used openvpn to secure the calls to the server. These phones support openvpn.
