### ISSUE TITLE
Ring group and call routing not honoring busy

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#2002]
When an extension is busy on a call, a second call still comes to it, even when you have set a forward on busy,
i have also tested with rollover on ring group

**Comment by markjcrane** [comment]
Ring group uses a bridge statement directly to the end point. So the set forward on busy is skipped. It requires the call to use the dialplan.

Rollover strategy requires the endpoint returning a busy but if the phone does not then it doesn't rolloever until you get it to return a busy.
