### ISSUE TITLE
Fix?: Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]

### ISSUE THREAD

**Issue by rossbcan** [fusionpbx/fusionpbx#2006]
fusionpbx trunk (today)
sqlite

After editing and saving an extension:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such function: now' in /usr/local/fusionpbx/resources/classes/orm.php:811 Stack trace: #0 /usr/local/fusionpbx/resources/classes/orm.php(811): PDO->exec('insert into v_d...') #1 /usr/local/fusionpbx/app/extensions/extension_edit.php(499): orm->save(Array) #2 {main} thrown in /usr/local/fusionpbx/resources/classes/orm.php on line 811

This appears to be an incompatibility between mysql and sqlite [function time: now()]. I patched it to work, but devs may wish to "bless" this solution.

line 806:
- $sql .= "now(), ";
+$sql .= "datetime('NOW'), ";

not displaying correctly on web. Replace now() with datetime('NOW')

gets rid of error.

Comments? Final solution?

Bill Ross

**Comment by jebsolutions** [comment]
defined database ransaction_date field with "default current_timestamp" attribute.  i.e. it will auto-populate on insert.

Then you don't need to insert this field on database update at all so you can eliminate line 778:

				$sql .= "transaction_date, ";

and eliminate line 796:
					$sql .= "now(), ";

and the non-standard sql problem should be fixed.

**Comment by markjcrane** [comment]
Update and try again the problem should be fixed.
