### ISSUE TITLE
Fatal error: device_edit.php on line 305

### ISSUE THREAD

**Issue by jessetn** [fusionpbx/fusionpbx#2007]
Error when adding/copying new device.
Fatal error: Call to undefined method database::name() in /var/www/fusionpbx/app/devices/device_edit.php on line 305

Edit:  ver 4.3 , commit 636555f5161d38f6095c76c4e6b94b569c0a2265

**Comment by jessetn** [comment]
This seems to fix it...
Change line 305:  $database->name('devices');
to this:  $database->name = 'devices';

device copy still not working though.

**Comment by markjcrane** [comment]
It should be fixed now also had to do the same on dialplan edit. Make sure to update and try again.

**Comment by markjcrane** [comment]
Fixed I removed $database->name entirely.
