### ISSUE TITLE
Fatal Error saving dialplan

### ISSUE THREAD

**Issue by bigfishvoice** [fusionpbx/fusionpbx#2009]
When trying to save any dialplan I receive the following error:

Fatal error: Call to undefined method database::name() in /var/www/fusionpbx/app/dialplan/dialplan_edit.php on line 174

Is this a bug or is there something that needs to be changed to accommodate this commit?

Version: 4.3.0 with current updates as of last night.

**Comment by markjcrane** [comment]
Update and test it again.

**Comment by bigfishvoice** [comment]
Yes, it's working now.  Thank you.
