### ISSUE TITLE
Outgoing Question

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#2010]
I have multi sip trunks connected for different #'s but i want certain ext to use outbound from other sip trunks other then the main
1. siptunk1 main inbound/outbound all
2. siptunk1 main inbound/ ext 204 211 233 outbound 
3. siptunk1 main inbound/ ext 302 267 234 outbound
4. siptunk1 main inbound
5. siptunk1 main inbound

how can this be done ?

**Comment by bigfishvoice** [comment]
Here is one way that I've found.  There are other ways I'm sure.

1.  Create an outbound route for the specific trunk you want to assign users to.

2.  Edit the trunk and add a new condition as shown in line 1 of the image below.  Make sure that it is first in the list above the other conditions by making the order less than the first condition.

3.  Change the order at the top of the page from 100 to something lower than the other outbound routes you don't want the extensions using.  This will allow the special trunks to be checked first.

4.  Save & Test.  You should be able to watch in Status > Active Calls go out on the trunk you specified.

Note:  My example shows ^300$ as the extension.  You should be able to use ^204|211|233$ as your data value to allow multiple extension as you have in your example above.  If you had a large number of extensions, you could also use a regex with wildcards or even use the Toll Allow variable which is a little different but can produce the same results.

![capture](https://cloud.githubusercontent.com/assets/16521420/19711408/8c761af2-9b03-11e6-91b4-c350b31674be.JPG)

**Comment by MrCoolLV** [comment]
I try this and noticed did not work, do i need to restart sip services ?

**Comment by bigfishvoice** [comment]
No, outbound routes do not require a restart

**Comment by markjcrane** [comment]
Instructions are correct method works fine unless using for a large number of extensions. In that case would need some development work.

**Comment by MrCoolLV** [comment]
some reason failed for me

**Comment by bigfishvoice** [comment]
Keep it simple and do one trunk at a time and test at each step.  Make sure the specific routes are sequentially less than the generic routes.   Default is 100 for an outbound route.  Your specific routes should be something like 99 in order to be processed first.
