### ISSUE TITLE
trunk borked using sqlite db

### ISSUE THREAD

**Issue by rossbcan** [fusionpbx/fusionpbx#2013]
DO NOT use sqlite with trunk

**Comment by rossbcan** [comment]
fusionpbx trunk
fs 1.6.11
sqlite

GUI Install / configure appears to complete, but GUI Dialplan Manager is missing most entries. Attempting to upgrade App Defaults results in PHP fatal error. Changing to PostgreSQL db allows install and and app upgrade to complete successfully.

Suspect this is related to more sqlite / mysql incompatibilities similar to the sqlite now() incompatability reported by myself and resolved several days ago.

do this: fgrep -r "now()" fusionpbx and, see many hits which may be contributing factors.

I can only reccommend that trunk users avoid sqlite db until resolved

Regards;
Bill Ross

**Comment by markjcrane** [comment]
What kind of hardware were you running sqlite on?

**Comment by rossbcan** [comment]
OpenWrt Linux x86_64
Linux SecurePBX 3.14.4 #1 SMP Tue Oct 11 18:55:33 EDT 2016 x86_64 GNU/Linux
Dual core intel Celeron 1037U, 4G RAM
Sqlite-3.7.12.1 2012-05-22 02:45:53 6d326d44fd1d626aae0e8456e5fa2049f1ce0789
Sqlite3 has NO patches

Regards;
Bill

**Comment by markjcrane** [comment]
Not necessarily true for everyone

**Comment by markjcrane** [comment]
SQLite uses file system locking to protect the data and prevent database corruption. When inserts come in faster than the read and write performance of the file system then you get problems with SQLite. If you point SQLite to a ram drive run the install and then move it to the file system. In the  config.php update the path after the install.

**Comment by rossbcan** [comment]
Thanks I will test as you suggest once I have time and report back.

**Comment by rossbcan** [comment]
OpenWrt Linux x86_64

Linux SecurePBX 3.14.4 #1 SMP Tue Oct 11 18:55:33 EDT 2016 x86_64 GNU/Linux

Dual core intel Celeron 1037U, 4G RAM

Sqlite-3.7.12.1 2012-05-22 02:45:53 6d326d44fd1d626aae0e8456e5fa2049f1ce0789

Sqlite3 has NO patches

 

Regards;

Bill
