### ISSUE TITLE
Different domains

### ISSUE THREAD

**Issue by joebusby** [fusionpbx/fusionpbx#2014]
Login for a specific tenant requires the domain to be in the URL for browser logins

Some hacker bots figure out the domain and attempt to login on various extensions with assorted passwords

Is there a way to use one DNS (fqdn) entry to point the browser to the right IP address and then register users and phones on a different (pre-approved) domain or fqdn?   Then having one domain in the URL of web logins and browsing a different tenant on login?  That way bots that identify the domain get the same treatment they normally get with the ip address right and the correct registration domain or fqdn is not published?  Is possible? or maybe a feature request or not necessary?

I had to adjust fail2ban for more bots learning the domain.

Thanks for reading.

**Comment by Tatermen** [comment]
You could probably configure your devices as if it were using a proxy, eg:

**User ID:** 101
**Password:** \*\*\*\*\*\*
**Registrar:** whatever.domain.the.tenant.has
**Proxy:** sip.example.com

I briefly tried this with a Grandstream phone and it registered okay, but I won't take this as a definitive answer. If you are using FusionPBX autoprovisioning you would have to alter the template to include the Proxy address as well.

We use a wildcard DNS entry for our tenants.  For example, we created the following DNS records:

```
sip.example.com IN 3600 A 10.23.45.69
*.sip.example.com IN 3600 CNAME sip.example.com
```

Each tenant then gets a domain of whatever.sip.example.com. This means that when setting up a new tenant we do not have to setup any new DNS records. It also means that bots etc cannot guess the domain by looking at what resolves and what doesn't.

**Comment by joebusby** [comment]
Thanks for that helpful advice. I will give it a try.

**Comment by markjcrane** [comment]
You can use outbound proxy to get the phone to the right server and then the regular server address for registering the domain if using device provisioning.

**Comment by joebusby** [comment]
Thanks for all the help.  I was not able to figure out how to get the wildcard CNAME record entered on my DNS provider's system, but I put an "A" record in:  *.sip with the IP address of the server and the test.sip.mydomain.com tenant will now register a phone with the same URL that is not publicly available.  sip.mydomain.com was pointed elsewhere. That looks like it should work well. Anything.sip.mydomain.com will get to the pbx, but I thinking the bot won't guess the correct domain, let alone the domain, password and extension number.

**Comment by markjcrane** [comment]
I've always used the A record wildcard.
