### ISSUE TITLE
Problem with Provision for Polycom devices.

### ISSUE THREAD

**Issue by anis-bedhiafi** [fusionpbx/fusionpbx#2015]
When I add a new device with polycom/5.x template. Then I want to configure some keys for speed dial. The directory.xml is always empty and it always containing the following
`<directory>
    <item_list>
    </item_list>
</directory>`
I used category (programmable) and polycom (automata).
Is this a bug or am I missing something in the configuration?

Thank you.

**Comment by markjcrane** [comment]
Speed dial and the directory.xml are not related. Directory comes from contacts if enabled. Take a look at provision -> names starting with contact_*.

I teach how to do this in detail in the Admin training.
