### ISSUE TITLE
fax to email doesn't use default port

### ISSUE THREAD

**Issue by jebsolutions** [fusionpbx/fusionpbx#2017]
Fax to email doesn't use Advanced->Default Settings->smtp port settings.

Pull request to work around this + optionally allow self-signed certificates:
https://github.com/fusionpbx/fusionpbx/pull/2011

**Comment by markjcrane** [comment]
I put a comment on your pull request.

**Comment by jebsolutions** [comment]
I created a new PR for 4.2:
https://github.com/fusionpbx/fusionpbx/pull/2022

I am attaching the three changed files here just in case:

[fax and email fixed 4.2.zip](https://github.com/fusionpbx/fusionpbx/files/562598/fax.and.email.fixed.4.2.zip)

I am working on a separate PR for the master branch.

**Comment by jebsolutions** [comment]
PR for master branch #2023

**Comment by jebsolutions** [comment]
Thank you mark!

Resolved per pr 2022/2023.
