### ISSUE TITLE
Group Manager "File not found"

### ISSUE THREAD

**Issue by jessetn** [fusionpbx/fusionpbx#2018]
under Group Manager, clicking 'Protected', opens blank white page that says "File not found."
4.3
Commit: 91c9548e35ab796362e914f31fedf392b0ac2675

**Comment by jebsolutions** [comment]
https://github.com/fusionpbx/fusionpbx/blob/master/core/groups/groups.php

line 188

"/core/users/groups.php" doesn't exist any more.

I think it should be "/core/groups/groups.php".

**Comment by jessetn** [comment]
Yep you're absolutely correct.  Changing this manually works.

**Comment by markjcrane** [comment]
Fixed in https://github.com/fusionpbx/fusionpbx/commit/eaa80449f7e20a5a769386449f397e53c8ccd5d7
