### ISSUE TITLE
Call Flows 

### ISSUE THREAD

**Issue by jessetn** [fusionpbx/fusionpbx#2019]
Created a Day/Night Mode in Call Flows and got the error:
COMPILE ERROR: 1 [nothing to repeat]
Referenced issue #1286 , checked Dialplan -> Day Night and got this:
`<condition field="destination_number" expression="^*40$" break="on-true">`
when it should be
`<condition field="destination_number" expression="^\*40$" break="on-true">`

**Comment by markjcrane** [comment]
This bug applied to master branch only. Thanks for reporting it. It has been fixed.
https://github.com/fusionpbx/fusionpbx/commit/166e81e9f5569550d5f1a08b81472273e8460a86
