### ISSUE TITLE
No source paths Advanced->Backup

### ISSUE THREAD

**Issue by camodor** [fusionpbx/fusionpbx#2027]
Hi!
I install clean freeswitch + fusionpbx on debian 8 with ./install.sh
Goto advanced>backup and no bakup path defined
FreeSWITCH Source install paths in advanced>default settings no exist.

**Comment by jebsolutions** [comment]
I agree.   

The install script already assumes postgres and knows all the paths so it should create the defaults accordingly.  

Also, the backup should include the postgres database.  Without the database I don't think you can really restore anything meaningful if something bad happens.  Correct me if I'm wrong on this?

On my own config as a work around I have a script /root/backup.sh.  It makes a time stamped (YYYY-MM-DD) backup of the database.  I cron job this, so I have a daily copy of the database I can roll back to.

The script also copies the last backup into /lastbackup/fusionpbx-postgres.sql.  I then include the /lastbackup path into the default backup paths.  

Before I do a backup from the gui I run /root/backup.sh once to give me a recent database snapshot.  Then I do a gui backup so the .tar.gz will include my snapshot.

Ideally, the gui would automatically do this postgres dump immediately before the backup.  Perhaps the install will add a sudoers line for the php user to be able to run the database backup script.

Similarly, the restore should restore the database from the backup as well.

I realize this is not a small change, but I think it's necessary.  If someone follows the instructions on the wiki and added the default paths... they will still have no postgres backup.   

/root/backup.sh:
#!/bin/sh
TODAY=$(date +"%Y-%m-%d")
mkdir /backups
mkdir /lastbackup
su -c "/usr/bin/pg_dump fusionpbx" postgres > /backups/fusionpbx-postgres-$TODAY.sql
# be sure to add /lastbackup directory in the advanced defaults backup config
cp /backups/fusionpbx-postgres-$TODAY.sql /lastbackup/fusionpbx-postgres.sql
chown -R www-data:www-data /lastbackup

**Comment by markjcrane** [comment]
We get the paths for freeswitch from freeswitch so it has to be running. 
Make sure you are using this install script
https://www.fusionpbx.com/app/www/download.php

**Comment by jebsolutions** [comment]
@markjcrane,

Thanks for the quick response. 

Yesterday I created a Debian 8 VM from scratch for testing.  I used the same script you linked to.  No Advanced->Default settings for the "backup" category are automatically created.

You have to create them manually.  Otherwise you get "Backup failed, no backup paths created" (or something to that effect).

**Comment by markjcrane** [comment]
Backup paths are not supplied by default to advanced -> default settings. In other words if you are are expecting them automatically that would be a feature request. It will be added in the future by default.
