### ISSUE TITLE
Call Recording Change UUID File name

### ISSUE THREAD

**Issue by girishdharmaraj** [fusionpbx/fusionpbx#2028]
I am using the below for call recording and everything works fine, the recording shows up in the GUI
/var/lib/freeswitch/recordings/${domain_name}/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}/${uuid}.wav

but if I change the UUID.wav (file name) to say callername_callernumber_destinationnumber.wav the file is created in the respective folder but the web GUI does not show the inline call recording in the call detail cdr page. Is this normal ?

**Comment by moteus** [comment]
Yes. This is how Fusion works.

**Comment by markjcrane** [comment]
The file name is how it links to the Call Detail Record you changed the name which broke that code that assumes it will have the ${uuid}.wav. Please contact support if you want to sponsor a way to fix this.
