### ISSUE TITLE
LDAP plugin - blank passwords - Allows login

### ISSUE THREAD

**Issue by flyer292** [fusionpbx/fusionpbx#2029]
with method ldap enabled if someone logs into the system with a known user account and does not enter a password for either an ldap or database user the system allows them to log in and grants them that users access

If the account does not exist it create a new user account with default permissions

**Comment by markjcrane** [comment]
A note to those that don't know LDAP is off by default.

I tested this yesterday with someone else if its misconfigured this can happen once we had correct it then it seemed to work fine. If you want to take this further contact support by phone. 
https://fusionpbx.com/app/www/support.php.

**Comment by flyer292** [comment]
I will leave this closed for now, but I was the one that did the setup with you yesterday
We tested incorrect passwords but not blank passwords.  Incorrect passwords return a false, but blank passwords return an authorized true.
Please let me know when you have time to work on this with me again

**Comment by markjcrane** [comment]
Thanks for reporting this and the follow up. I've updated the code on both branches if the password is empty it gets an automatic authorized false. Please update, test and report back.

**Comment by flyer292** [comment]
Yes this fixed the issues, thanks!
Suggestion for an Enhancement 
under Defaults a new variable for a "master type password"  (hopefully people would set a very complex password, or keep it disabled when not needed)
When used with the users login ID it would set sets user_authorized = true.  and not actually check ldap (bypass) 
This would allow administrators to emulate a users login... also great for initial setup of a new users account
We can work on this next time I call you... I would assume if would be very easy and just another if statement above the actually ldap checks
if (strlen($bind_pw) = new variable
