### ISSUE TITLE
no mwi on phones after freeswitch restart

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2035]
Hello,

After the service freeswitch restart, the phones no longer show up light or message indicators for voicemails. Could someone help me on how to fix this issue. your help is much appreciated.

Thank you
Krishna.

**Comment by markjcrane** [comment]
Could be caused by NAt

**Comment by kkoilada** [comment]
Hi,

I don't think so its natting issue as I can clearly see that subscription
message sent to server for mwi and the server responds with 202 with no
content info. Please check the below trace for further review:

2272  15.248930 98.197.251.115 -> 10.255.250.20 SIP 534 Request: SUBSCRIBE
sip:*97@208.83.10.115:9000, in-dialog |

2291  15.256472 10.255.250.20 -> 98.197.251.115 SIP 790 Status: 202 Accepted
|





In 202 Accepted, I do not see any content in updating the phones that it
has voicemail(s) to lightup the phone.



Session Initiation Protocol (202)

    Status-Line: SIP/2.0 202 Accepted

        Status-Code: 202

        [Resent Packet: False]

        [Request Frame: 357]

        [Response Time (ms): 6]

    Message Header

        Via: SIP/2.0/UDP 192.168.1.101:5060
;branch=z9hG4bK620224736;rport=5060;received=98.197.251.115

            Transport: UDP

            Sent-by Address: 192.168.1.101

            Sent-by port: 5060

            Branch: z9hG4bK620224736

            RPort: 5060

            Received: 98.197.251.115

        From: "Krishna Koilada" <sip:102@grfp.anyconnect.us>;tag=1452326427

            SIP Display info: "Krishna Koilada"

            SIP from address: sip:102@grfp.anyconnect.us

                SIP from address User Part: 102

                SIP from address Host Part: grfp.anyconnect.us

            SIP from tag: 1452326427

        To: <sip:*97@grfp.anyconnect.us>;tag=zoFU3OVfomSZ

            SIP to address: sip:*97@grfp.anyconnect.us

                SIP to address User Part: *97

                SIP to address Host Part: grfp.anyconnect.us

            SIP to tag: zoFU3OVfomSZ

        Call-ID: 0_2665200995@192.168.1.101

        CSeq: 9 SUBSCRIBE

            Sequence Number: 9

            Method: SUBSCRIBE

        Contact: <sip:*97@208.83.10.115:9000>

            Contact URI: sip:*97@208.83.10.115:9000

                Contact URI User Part: *97

                Contact URI Host Part: 208.83.10.115

                Contact URI Host Port: 9000

        Expires: 20

        User-Agent: NetrixUC-1

        Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE,
REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE

        Supported: timer, path, replaces

        Allow-Events: talk, hold, conference, presence, as-feature-event,
dialog, line-seize, call-info, sla, include-session-description,
presence.winfo, message-summary, refer

        Subscription-State: active;expires=20

        Content-Length: 0

**Comment by moteus** [comment]
Try open Advenced->XML Editor, uncomment [this line](https://github.com/fusionpbx/fusionpbx/blob/master/resources/templates/conf/autoload_configs/lua.conf.xml#L51) and restart fs

**Comment by kkoilada** [comment]
Moteus,

It works now after uncomment and restarting fs. Thank your for solving this issue.

Thank you
