### ISSUE TITLE
Microsoft Bing Speech-to-text transcription

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#2036]
While looking at this new feature, I found a bit of a problem.

It looks as though the code is using an older version of the Bing Speech API (Project Oxford), for which it is no longer possible to get API keys for. The newer API keys only work with the Microsoft Cognition API.

The second stage of uploading the data to Bing looks okay, but getting the accessToken fails as the process has [changed](https://www.microsoft.com/cognitive-services/en-us/Speech-api/documentation/GetStarted/GetStarted-cURL) (different URL, no longer uses JSON). 

I got it to work with the newer Cognitive keys by changing the following in resources/install/scripts/app/voicemail/resources/functions/record_message.lua :

Change Line 56:
```access_token_cmd = "curl -X POST \"https://api.cognitive.microsoft.com/sts/v1.0/issueToken\" -H \"Content-type: application/x-www-form-urlencoded\" -H \"Content-Length: 0\" -H \"Ocp-Apim-Subscription-Key: "..api_key1.."\""```

Remove lines 60 and 64 (JSON decoding no longer needed).

Change Line 67:
```transcribe_cmd = "curl -X POST \"https://speech.platform.bing.com/recognize?scenarios=smd&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&locale=en-US&device.os=Freeswitch&version=3.0&format=json&instanceid=" .. gen_uuid() .. "&requestid=" .. gen_uuid() .. "\" -H 'Authorization: Bearer " .. access_token_result .. "' -H 'Content-type: audio/wav; codec=\"audio/pcm\"; samplerate=8000; trustsourcerate=false' --data-binary @"..file_path```

**Comment by blackc2004** [comment]
Really? when did they change this?

I tested yesterday and the code was working fine... maybe because I have old keys still?

**Comment by Tatermen** [comment]
I think it must have been a recent thing. The keys I got this morning to test with do not work with the Project Oxford API - they return a "401 Invalid secret" message. The Project Oxford website also seeems to no longer exist and instead redirects to the MS Cognition site.

I would suspect that older keys will work with the old method, and newer keys only work with the newer method. I didn't have any old keys to test if they would work with the new method.

**Comment by markjcrane** [comment]
blackc2004 - please respond.

**Comment by blackc2004** [comment]
I updated the code with tatermen's code and used my old keys and it worked fine.
