### ISSUE TITLE
mwi subscription error

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2039]
Hi,

I am having an issue on one of the server where the below log shows up on console:
==========================
[WARNING] switch_cpp.cpp:1360 [mwi_subscribe] non numeric voicemail id: *97
2016-11-04 22:36:26.169235 [WARNING] switch_cpp.cpp:1360 [mwi_subscribe] can not find voicemail: *97@xyz.us
=====================
The phone is sending subscription message for mwi, however, due to this the phone no longer gets update on count of the voicemails i.e 1 or 2 or 3 etc..

However, I don't see this issue on the other server though. your valuable input is much appreciated.

thank you

**Comment by markjcrane** [comment]
moteus this is a question is for you.

**Comment by moteus** [comment]
is just try subscribe with voicemail `*97@xyz.us`.
And fusion requires only numeric voicemail ID. (Type of field in database)
So I just print warning about this.
I think there some problem in configuration of device.

**Comment by kkoilada** [comment]
I don't think so it's the problem with the device as the same phone receives correct info from other server which is part of the cluster. moreover the other server doesn't show this mwi error whereas this one shows. I tried restarting freeswitch but no use. Any further advice is much appreciated.

**Comment by moteus** [comment]
You can add line `log.noticef('event: %s\n%s', name, event:serialize('xml'))` e.g. [here](https://github.com/fusionpbx/fusionpbx/blob/master/resources/install/scripts/app/voicemail/resources/scripts/mwi_subscribe.lua#L110) on both servers and compire them.
Also you can checkout SUBSCRIBE or REGISTER messages.
`*97@xyz.us` should not be there in any case. Is just number to check voicemail.
If you see it there then your device is misconfigured
