### ISSUE TITLE
phone not responding to the invite originated from the cluster server

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2040]
Hi,

I have two servers where BDR takes care of multimastering the database. When phones from same domain register to different servers, and they call each other the server proxies on behalf of other server and sends invite for the incoming call.

But, the phone doesn't responds as the invite is not coming from the server where it was registered. 

fs_nat and couple of other parameters are enabled but no use. Is there any work around for this scenario?

Below is the brief of the issue:

IP phone 1 ------> server 1.1.1.1 for xyz-domain
IP phone 2 ------> server 1.1.1.2 for xyz-doamin

IP phone 1 calls IP phone 2, server 1.1.1.1 sends invite to IP phone 2 and the phone 2 does not respond, which apparently times out and sends it to voicemail.

your help is much appreciated on this issue.

Thank you

**Comment by markjcrane** [comment]
fs_nat is not correct it would be fs_path. This isn't a bug.
The primary purpose of github issues is bugs.

**Comment by kkoilada** [comment]
you are right its fs_path, I used the wrong term. However, the issue is
intact as stated in the ticket. Does this really work in such scenario
where phone receives the invite from the other server? if not then I have
to make sure that all phones resides on a particular server.

Thank you

**Comment by markjcrane** [comment]
When done right fs_path proxies the call through the server the phone registered to.

**Comment by kkoilada** [comment]
you are correct and I do see the server proxies the call. Upon close look, I find that the server sending the sip
Invite with private ip of the phone rather public ip. However, for the phones that resides on same server, the server sends the invite with public ip of the phone. I check different nat settings on sip profile and restarted the sip profiles and freeswitch but no luck. Is there any parameter for fs path scenario to send invite with public ip rather private ?? Your help is much appreciated.

Thank you
