### ISSUE TITLE
Yealink Phone Book not working

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2045]
Hi I have a problem adding a remote phone book on Yealink phones (T23G, T46G and T22P).

I have tried Updating the provisioning file and the results are the same.

Anyone has an Idea what I am missing?

**Comment by jessetn** [comment]
Either replace {$yealink_remote_phonebook_1_url} in your favorite_setting.xml provisioning file with your phone book URL, which should look something like this http://$${domain_name}/app/provision/?file=directory.xml
Or add the yealink_remote_phonebook_1_url setting to your device's settings, and add your URL as the value.

This is working on my T46G, but only if provisioning is left on "Enable"

**Comment by blackc2004** [comment]
If you're on 4.2, You shouldn't need to update anything in the provision files, just enable the default settings for contacts_* under provision.

**Comment by ernestkm** [comment]
i have updated to the Latest Version of the System and this is not working.

i am on version 4.3.1 any advice?
