### ISSUE TITLE
Ring groups do not ring all registered devices per extension

### ISSUE THREAD

**Issue by emaktech** [fusionpbx/fusionpbx#2048]
How to replicate:

1. Go to **Apps | Ring Group**
2. Set strategy to **Simultaneous** and set an internal extension in **Destinations**
3. Register 2 or more devices to that extension
4. Call ring group extension, only one registered device will ring at the destination extension(s)

In reality, I experience the same behavior with different ring strategies as well. In all test cases, when dialing the user's extension, all devices ring correctly as expected, it is only when forwarded from a ring group that this behavior is encountered.

This occurs no matter what delay, timeout or prompt settings are set.

**Comment by markjcrane** [comment]
This is not a bug this is Freeswitch design to keep things in multi threaded. For this situation use ring group strategy enterprise. In the fusionpbx admin training and I'll tell you why.

**Comment by mpiugl83** [comment]
Hi, Thanks it helped me.
I am having a small issue now. I hear no ring tone when the destination points to the ring group. If I point it to an extension, it works properly. The current route is Carrier->My Asterisk Server->A2Billing->SIP to FusionPBX->RingGroup->Extensions (6).  If I instead do Carrier->My Asterisk Server->A2Billing->SIP to FusionPBX->Extension, I hear the ring tone until I answer.
