### ISSUE TITLE
strange ring on inbound routes

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#2079]
I am on  Commit: 54ea97a9d086473f6d93978bc5f7686538754089 
when i create an inbound route and you dial the number from external the ringtone is very bad quality and breaks up
but if i change the inbound route like below
http://pasteboard.co/rxCANfQh2.png
then it works fine

**Comment by jebsolutions** [comment]
@andycol 

It's not clear to me from your screenshot what you changed.  Can you do two screen shots, one non-working and one working after you made the changes?

**Comment by andycol** [comment]
this is resolved since updating to latest commit
