### ISSUE TITLE
Polycom 4.x Non Standard SIP Port not working

### ISSUE THREAD

**Issue by netpro25** [fusionpbx/fusionpbx#2080]
fusionpbx/resources/templates/provision/polycom/4.x/{$mac}.cfg

Line 13 should either be changed to the following, or the following needs to be added to the provisioning file.

{if isset($row.sip_port)}reg.{$row.line_number}.server.1.port="{$row.sip_port}"{else}reg.{$row.line_number}.server.1.port="5060"{/if}

**Comment by markjcrane** [comment]
I think this disguises the real problem that the port always should be set.

**Comment by netpro25** [comment]
Mark,

Basically what's happening is when you specify a non standard port the phone is still getting port 0 in the GUI, so I had to enter/change that value to use my non standard port.

**Comment by markjcrane** [comment]
Committed to 4.2 and master please test to confirm its working for you and report back.
