### ISSUE TITLE
Upgrade broke the file path for users & group manager sections

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2081]
Hi... 

Just recently I executed upgrade source code under fusionpbx and unaware of any things broken. But, it is discovered that when clicked on "users" under accounts and group manager under Advanced it shows the "file not found".
For example, when clicking on users --the path taken is "core/users/index.php" which is incorrect; However, the actual path is "/core/users/users.php"

Any help or guidance in finding the code source for making amendments is much appreciated.

thank you
Krish

**Comment by markjcrane** [comment]
Did you update the menu in the menu manager or from the upgrade page. I think you are may have missed that step of the upgrade.

**Comment by kkoilada** [comment]
Thank you very much for your input. It works now.
