### ISSUE TITLE
Change FusionPBX root folder

### ISSUE THREAD

**Issue by Montana357** [fusionpbx/fusionpbx#2082]
Hello, im in the need of changing the root folder of fusionpbx to other name or to be the apache root to show domain.com/ instead of domain.com/fusionpbx

**Comment by MrCoolLV** [comment]
? does not show fusionpbx .. and is is set to root

**Comment by markjcrane** [comment]
What you want is setup by default for Debian 8 install.
All you need to do is move your files to the root of the website or change the apache config file to look in the fusionpbx folder.

There are many websites that describe how to update the apache configuration. I you want additional help them consider paid support and we will make the change for you.
