### ISSUE TITLE
New Yealink provision options in Default Settings not working

### ISSUE THREAD

**Issue by jessetn** [fusionpbx/fusionpbx#2085]
yealink_rport/retransmission/session_timer settings "type" is set to boolean by default, and doesn't seem to work.  Changing type to "text" is working for me.

**Comment by markjcrane** [comment]
https://github.com/fusionpbx/fusionpbx/commit/4ff9f0c7564aac0411ede3c8042357cf02cc111d
Allow provision variables of type boolean and numeric. This will fix the issue you reported.
Thanks for reporting it.
