### ISSUE TITLE
v_recording_play.php not found

### ISSUE THREAD

**Issue by Comsolvia** [fusionpbx/fusionpbx#2090]
When looking at a CDR detail of a call there is two links for play and download. The links goes to `../v_recording_play.php` but that file doesn't exist. (row 200 in app/xml_cdr/xml_cdr_details.php )

Br - Tomas

**Comment by markjcrane** [comment]
Version of fusionpbx?

**Comment by Comsolvia** [comment]
Sorry, I'm using 4.1 but I looked around in the repository and it seems to be the same in 4.2

**Comment by markjcrane** [comment]
Not sure I added those links so it took me a few minute to find them. Thanks for reporting this issue so that it could be fixed.  I have fixed it in both the master branch and in the 4.2 release branch.
