### ISSUE TITLE
New installation not working

### ISSUE THREAD

**Issue by ednt** [fusionpbx/fusionpbx#2097]
Hi,
I just installed FusionPBX on a new clean debian 8.
I do exactly what's written on the web page.

I can not start the services in SIP Status.

Reason:
freeswitch is not started.
It fails to start when I try it with: service freeswitch start

In /var/log/syslog
Failed to reset devices.list on /system.slice/freeswitch.service: No such file or directory
Failed at step SETSCHEDULER spawning /bin/mkdir: Operation not permitted

Ok, I can start it by hand via:
/usr/bin/freeswitch -u www-data -g www-data -ncwait

If I then press the Start button at any service I get in
/var/log/freeswitch/freeswitch.log
[ERR] mod_lua.cpp:203 cannot open /usr/share/freeswitch/scripts/app.lua: No such file or directory

And the file app.lua is really not available.
The complete scripts directory is empty.

Btw. there are also 2 critical messages in the log:
[CRIT] switch_loadable_module.c:1520 Error Loading module /usr/lib/freeswitch/mod/mod_callcenter.so
[CRIT] switch_loadable_module.c:1520 Error Loading module /usr/lib/freeswitch/mod/mod_local_stream.so

Main point:
I do everything right (in my opinion) but it is not working.
So something with the install script or freeswitch is wrong.
Not easy for a FusionPBX newbie.

Best regards,

Bernd

**Comment by bigfishvoice** [comment]
Bernd,

After the install, did you go through and run Advanced Settings > Upgrade > App Defaults

**Comment by ednt** [comment]
Hi,

yes, of course. I did exactly all the steps from the website and the video.
And to be sure I did it again, but still the same (as expected).

**Comment by markjcrane** [comment]
Try updating the source and try again. If not ask on irc or call for support we can save you a lot of time.

**Comment by shajunr88** [comment]
I just installed fusionpbx in ubuntu and after installation "./install.sh: systemctl: not found" message was shown.
When trying to check the status freeswitch using "service freeswitch status", it shows the command not found message.
So i want to know whether i need install freeswitch before installing fusionpbx.The directory usr/local/freeswitch/bin is created only after installing freeswitch seperately.
Some socket errors are also showing when running fusionpbx.

**Comment by markjcrane** [comment]
The latest install script was designed for Debian 8.

**Comment by shajunr88** [comment]
Is freeswitch to be installed before installing fusion pbx

**Comment by shajunr88** [comment]
I followed the above mentioned install script. But systemctl commands will not work in ubuntu 14.04.

**Comment by markjcrane** [comment]
The install script was not built for Ubuntu it was built for Debian. It would take some adjustments to work with Ubuntu.
