### ISSUE TITLE
Deleting Voicemail through Apps > Voicemail does not work properly

### ISSUE THREAD

**Issue by Motjida** [fusionpbx/fusionpbx#2100]
Version	4.3.0
Branch: master 
Commit: 36c649f2a9e7bd64fedd10b2fb034626a0276639 
Origin: https://github.com/fusionpbx/fusionpbx.git 
Project Path	/var/www/fusionpbx
Switch Version	1.6.10 (64bit)

When deleting voicemails via Apps > Voicemail, the VM is removed from the database, but is stays on the filesystem. There are also several errors in the log (see attached)
[error_log.txt](https://github.com/fusionpbx/fusionpbx/files/601687/error_log.txt)

**Comment by jebsolutions** [comment]
I fixed this one too.

https://github.com/fusionpbx/fusionpbx/pull/2202

**Comment by jebsolutions** [comment]
Based on feedback, I created a separate PR to fix just this one issue:

https://github.com/fusionpbx/fusionpbx/pull/2221
