### ISSUE TITLE
IVR or Ringgroups added doesn't show xml fields under dial-plan manager

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2153]
Hi Everyone,

When I try adding IVR or Ringgroups, it adds to the system and the names shows up under dial-plan manager,but when I click on those names it shows no data at all... I am seeing the same issue across other domains as well... Any help in fixing this issue is much appreciated.
![image](https://cloud.githubusercontent.com/assets/20993773/20546087/9ad89dbe-b0d8-11e6-8faa-bc6ca230208f.png)

Thanks
krish

**Comment by markjcrane** [comment]
Nothing is missing for these features instead you stumbled upon a new feature. Do you see the xml button? If you click on it you will see the xml. This new approach is more efficient to manage the dialplan for the feature.

**Comment by kkoilada** [comment]
So, the traditional way of configuring was gone. I didn't notice that. Thanks for your help Mark. I overlooked that XML couldn't be edited. But, the XML doesn't show the information that I placed in IVR configuration. I provisioned when the dtmf 1 is pressed, it should dial cell # but I don't see that in xml. could you please help me where I am missing the information?
![image](https://cloud.githubusercontent.com/assets/20993773/20548086/22b50396-b0e6-11e6-8b48-84bc4b2e329c.png)

![image](https://cloud.githubusercontent.com/assets/20993773/20548099/4688499a-b0e6-11e6-87c7-e2030b0b36c2.png)

 This is the parameter info upon clicking the left play button: menu-exec-app:transfer 7052066737 XML demo.anyconnect.us

**Comment by markjcrane** [comment]
If you edited the IVR Menu dialplan on an older version then updated the IVR Menu you would loose your changes. So because of that there was no loss of functionality only now it takes less inserts or updates to manage the XML dialplan for the IVR menu and is therefore more efficient.

**Comment by markjcrane** [comment]
If you want to learn more I'm available for support calls for training or via the training classes. There are good reasons for all changes.

**Comment by kkoilada** [comment]
Mark,
I've attended your class two months ago and looking forward to attend the programming class. I might need to buy support hours if I can't fix this issue. Looking forward working with you.

thanks
Krishna.

**Comment by markjcrane** [comment]
> I can't fix this issue. Looking forward working with you.

Fix what issue? I describe what is wrong?

**Comment by kkoilada** [comment]
The issue I am seeing here is that " action parameters are not showing up in xml under dialplan", which leaves me no idea what's going on for that IVR dialplan. By the way, I have setup this IVR menu few minutes ago,  which is not an old one though. 
Thanks for your prompt response. Appreciated.

thanks

**Comment by markjcrane** [comment]
> The issue I am seeing here is that " action parameters are not showing up in xml under dialplan",

The actions never showed up in the the dialplan. Before 4.2 the IVR Menus were handled with a lua script. Before that they were XML on the file system. And now they are XML handled by XML handler.

**Comment by markjcrane** [comment]
The exit action was in the dialplan.

**Comment by kkoilada** [comment]
Thanks for correcting me Mark on this. The dialing issue got fixed by changing the number to a  different cell # and reprovisioned the previous #. Its weird though but its working now.
