### ISSUE TITLE
V4.2 BUG voicemail asks for password even with voicemail_authorized set to true

### ISSUE THREAD

**Issue by lodperera** [fusionpbx/fusionpbx#2154]
I have following configured in V4.2

advanced-->variables
voicemail_authorized=true

But still when you dial VM through the extension, it asks for the password. 
 
log http://pastebin.com/mZMBpAjm

I'm copying the conversation we had on IRC.

<Lodperera> mcrane, in advanced-->variables I have voicmail authorize to true on V4.2 so that wouldn't ask for the password when dialed from the extension.
<Lodperera> but still asks for the password. I cleared memcache, xml and acl then refreshed in sip status page. still it asks foe the pass.
<Lodperera> http://pastebin.com/mZMBpAjm
<Lodperera> any other setting that I might have missed?
<mcrane> weren't you the one asking for authentication plugin framework?
<Lodperera> nope.. not me,
<mcrane> voicemail_authorized
<DigiDaz> Lodperera: You sure you have the order right? I do not see it mentioning the variable
<mcrane> to true
<DigiDaz> ah, you set it somehwere else anyway, I always put it in the dialplan
<mcrane> it looks like a recent change broke it
<mcrane> as it is set in mine and it is asking for the password
<Lodperera> I can confirm that it was working before as well. Do you want me to report a bug in git so you can look at it when you have some time?
<mcrane> sure

**Comment by markjcrane** [comment]
This has been fixed and tested thanks for reporting it.
