### ISSUE TITLE
Grandstream GXP20xx provisioning modification

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#217]
```
I've made some changes to fusionpbx's provisioning system locally that allows 
us to auto-provision certain Grandstream phones (GXP2000 and GXP2010 in 
particular), which require a postprocess of the plaintext config to add a 
specifically formatted binary header + checksum. As far as I know this isn't 
needed on the NEW grandstream phones (GXP21xx), so its use might be limited, 
but attached a patch for it anyway just incase it's deemed useful enough to 
include.
```

Original issue reported on code.google.com by `m...@lawlr.us` on 5 Jan 2012 at 2:42

Attachments:
- [grandstream-provision.patch](https://storage.googleapis.com/google-code-attachments/fusionpbx/issue-217/comment-0/grandstream-provision.patch)

**Comment by markjcrane** [comment]
Provisioning has changed dramatically since this was posted closing the issue. Current firmware prevents this from being an issue today.
