### ISSUE TITLE
Call forwarding dialplan not working

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#2181]
We're having an issue with call forwarding that I can't figure out.

If we set the call forward via the "Call Routing" app on the web interface, it works. In the database it sets forward_all_destination in v_extensions to:

```
{instant_ringback=true,domain_uuid=225b30ba-0117-460d-8d1b-8cd135b8e3f7,sip_invite_domain=EXAMPLE,domain_name=EXAMPLE,domain=EXAMPLE,extension_uuid=be8ac644-17a8-455f-a81b-205fd38d5620,toll_allow='',sip_h_Diversion=<sip:101@EXAMPLE>;reason=unconditional,sip_h_X-accountcode=${accountcode},presence_id=101@EXAMPLE}sofia/gateway/eeee4960-e374-4fbe-8425-62b9e3332f65/5551629
```

However if we use the feature code, calls get sent to voicemail regardless of whatever destination number we enter. It generates the following in the database, which is missing the bridge and several other parts.

```
{presence_id=101@EXAMPLE,instant_ringback=true,domain_uuid=225b30ba-0117-460d-8d1b-8cd135b8e3f7,sip_invite_domain=EXAMPLE,domain_name=EXAMPLE,domain=EXAMPLE,toll_allow='',sip_h_Diversion=<sip:101@EXAMPLE>;reason=unconditional,accountcode=}
```

In the freeswitch logs we see the following:

```
2016-11-24 15:15:03.776320 [ERR] switch_cpp.cpp:1360 [route_to_bridge] Unsupportded condition: ${user_exists}
2016-11-24 15:15:03.776320 [WARNING] switch_cpp.cpp:1360 [call_forward] Can not build dialstring for call forward number.
```

This appears to relate to changes made to scripts/call_forward.lua and resources/functions/route_to_bridge.lua last week, but I cannot figure out where it is going wrong. I suspect it is route_to_bridge.lua that is failing, (the "cannot build dialstring" comes from call_forward.lua calling route_to_bridge.lua) but it is not generating any errors in the freeswitch logs other than those above.

**Comment by moteus** [comment]
Seems you have outbound routes with condition `${user_exists}`.
Lua implementation respect all conditions and does not build dialstring if it can not calculate such condition. It only support destination number and toll allow.
But PHP match only destination number. and assume all other conditions as passed.
So without more information it hard to say.

PS. #freeswitch IRC is more intercative.

**Comment by Tatermen** [comment]
Removing the user_exists condition from the dialplan has fixed the issue and we can forward a call externally. However, I would note that FusionPBX generates this condition and adds it to Outbound routes by default. 

Another thing is that other than the "could not build dialstring" in the logs, no errors are otherwise generated when it fails to find a valid route and the voice prompt to the user and the web interface both indicate a call forward has been applied.

**Comment by moteus** [comment]
It possible add some more constant for conditions in Lua.
To test you can add line like `['${user_exists}'] = 'false';` [here](https://github.com/fusionpbx/fusionpbx/blob/master/resources/install/scripts/call_forward.lua#L273)
I think it right value because we already check either this user exists in code.
Also we can add e.g. `call_direction=outbound` and may be some more values.

**Comment by moteus** [comment]
>However, I would note that FusionPBX generates this condition and adds it to Outbound routes by default.

When I wrote this functions there no such condition :).
Try this one - https://github.com/fusionpbx/fusionpbx/pull/2183

**Comment by Tatermen** [comment]
I'll give it a test once it's merged. 

Thanks for the assistance. :)

**Comment by markjcrane** [comment]
It has been merged and should fix the problem. Re-open if you have an issue after updating it.
