### ISSUE TITLE
Gateways delete and reference error - 404 Not Found

### ISSUE THREAD

**Issue by voxeljorz** [fusionpbx/fusionpbx#2192]
I have tried adding gateways and clicked on it but returns 404 Not Found page. Also tried deleting specific gateway and returns the same error.

Link Reference: https://10.1.128.104/app/gateways/href=

Version: 4.3.0
Git Information : Branch: master
Commit: 23326d6918bedf59977704e5e59cf33b6b2436f6
Origin: https://github.com/fusionpbx/fusionpbx.git
Switch Version: 	1.6.12 (64bit)

**Comment by markjcrane** [comment]
I removed the changes to gateways that broke this recently. Thanks for reporting it.

**Comment by voxeljorz** [comment]
You're welcome sir, happy to help ;)
