### ISSUE TITLE
webrtc sql error

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2206]
Hi,

I tried setting up webrtc function on fusion but when even with certificates installed, it is still not working. When I reload the mod_verto, the below error shows up:
2016-11-28 21:43:59.815149 [ERR] switch_core_sqldb.c:587 NATIVE SQL ERR [no such table: json_store]
select name from json_store where name=''

Any help is much appreciated in sharing the working config for webrtc.

thanks
krish.

**Comment by markjcrane** [comment]
The error there json_store doesn't exist. You have to create it to fix it.

**Comment by kkoilada** [comment]
I've done that but I get the same error. The table I created in both fusion as well as freeswitch db. Though this error pops up, I see the message that mod_verto successfully loaded. By the way, you have mentioned the freeswitch book code, and I am wondering which code you are referring to. I do have recent version of the book but unable to find the code that you are referring for. 
===
create table json_store (
	name varchar(255) not null,
	data text
	);
===========

**Comment by markjcrane** [comment]
Not used in fusion pbx database only in freeswitch.

**Comment by markjcrane** [comment]
Google search json_store fifth item down.
http://code.metager.de/source/xref/freeswitch/src/mod/endpoints/mod_verto/mod_verto.c

**Comment by kkoilada** [comment]
Mark,

Sorry to bug you on this...I am not sure where to dump this code i.e. path
and file format.. can you provide me some help on how to get this working?

thank you
krishna.
