### ISSUE TITLE
Fatal error: Uncaught --> Smarty: unable to write file

### ISSUE THREAD

**Issue by anshkatriya** [fusionpbx/fusionpbx#2217]
I have installed fusionpbx in virtual server. I want to check provisioning module of FusionPBX. But when I am going to download files for any devices I am getting error like :

Fatal error: Uncaught --> Smarty: unable to write file //wrt583ff686d58cf9.75957020 <-- thrown in /var/www/fusionpbx/resources/templates/engine/smarty/sysplugins/smarty_internal_write_file.php on line 45

Even I am confused that why it's going to write file on '//file_path' instead of /tmp folder.

**Comment by jebsolutions** [comment]
There is an issue where the temp dir may not be set during the install.  I'm not sure if this is your problem or not, but you can check: 

As always...backup your system first.  

Go to Advanced->Defaults.
Scroll down until you get to the Server section.

Go to Advanced->Default Settings and look under the Server heading
You should see these two entries for Subcategory,Type,Value,Enabled:
backup, dir, /tmp, True
temp, dir, /tmp, True

If you don't see them then add them to the Server category.

Then go to Advanced->Upgrade.  
Check App Defaults
Click Execute

**Comment by anshkatriya** [comment]
Thanks. It's resolved my issue.
