### ISSUE TITLE
settings under device doesn't update the mac.cfg file

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2220]
Hi ... 
I tried to enabled shared line appearance on the yealink phone under device settings but I do not see the value populated in cfg file. I tried putting the value as $infront of it but still no luck. Is there a way to get this value populated for the device?
![image](https://cloud.githubusercontent.com/assets/20993773/20806243/b1070baa-b7bf-11e6-957f-676e6fbc5322.png)

the mac.cfg file shows no value....
=======
## ranges from 1 to 6;
##account.X.shared_line =

#Assign account1 as shared line; 0-Disabled (default), 1-Broadsoft SCA, 2-BLA;
account.2.shared_line =

**Comment by Tatermen** [comment]
If you look at the template you'll see this code:

```
#Assign account1 as shared line; 0-Disabled (default), 1-Broadsoft SCA, 2-BLA;
{if isset($shared_line_1) }
account.1.shared_line = {$shared_line_1}
{else}
account.1.shared_line = 0
{/if}
```

So the setting name that you need to use for line 1 is ```shared_line_1```.

Unfortunately account 2 does not have the necessary template code to handle this

```
#Assign account1 as shared line; 0-Disabled (default), 1-Broadsoft SCA, 2-BLA;
account.2.shared_line =
```

**Comment by kkoilada** [comment]
Can I copy the same code and paste it for account 2? In doing so, will it work ??

Thanks
Krish

**Comment by Tatermen** [comment]
It should, assuming you change ```$shared_line_1``` to ```$shared_line_2```

However, it will cause issues updating FusionPBX. I would suggest making a custom template, for example instead of modifying ```yealink/t27p``` I make a copy and call it ```yealink/t27p_custom```. That way my changes to the ```t27p_custom``` template will not cause update conflicts.

Or you could make the changes and contribute them to the FusionPBX project.

**Comment by Len-PGH** [comment]
I updated this template for lines 2-6. Please update and try again.

**Comment by kkoilada** [comment]
Len,

Thanks for the updating the code. However, with the help of my friend, I find that the issue is when mentioning the variable with - or . it doesn't update the variable, and without those special characters, the variable is getting updated. I got it working when issued the variable without (-, .(period)).

thanks
krish.

**Comment by Len-PGH** [comment]
Krish,

  You're welcome. Happy to hear you have it worked out.

**Comment by markjcrane** [comment]
Provision variables should be letters, letters + numeric, and underscores with letters.

**Comment by kkoilada** [comment]
@markjcrane -thank you very much for the info.. appreciated..
