### ISSUE TITLE
Adding extensions not possible

### ISSUE THREAD

**Issue by ccsmart** [fusionpbx/fusionpbx#2224]
After update which solved https://github.com/fusionpbx/fusionpbx/issues/2222 now its not possible to add extensions ("+" button has no effect).

**Comment by ccsmart** [comment]
Same for outbound routes and dialplan manager.

**Comment by jebsolutions** [comment]
Which branch of FusionPBX are you on?  4.2 or the master branch?

**Comment by markjcrane** [comment]
Try Firefox or Chrome as it may be a browser issue or restart your browser. What you describe is certainly working if you still having and issue with it please contact support from www.fusionpbx.com.
