### ISSUE TITLE
Install of master seems broken

### ISSUE THREAD

**Issue by DigiDaz** [fusionpbx/fusionpbx#2231]
If you install current master, all menus are missing, running app defaults, menu defaults etc does not help.

I believe it probably relates to commit 373eb5ffc5178076e80eb672e8399dbde5f12752

If I checkout the revision before that, all installs correctly then I am able to upgrade to current master.

**Comment by markjcrane** [comment]
Run a default install then manually switch the branch to master after the PHP install. Problem easily solved for now this way for the development branch. I will be rewriting and simplifying the install. As it asks enough questions to provide ample opportunity for mistakes and new users are likely to leave if they don't get the install to work first time.
