### ISSUE TITLE
fax notification sending foul language - WTF TOT3

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2237]
Hi,

can anyone please help me in finding the file to change the notification text for the failed or subject line text information for fax notifications? Below is the info that I received on e-mail for failed notification:

==========
Subject: Fax to: 9728071989**WTF TOT 3**

We are sorry the fax failed to go through. It has been attached. Please check the number 9728071989WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 5 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 7 WTF TOT 7 WTF TOT 7 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 5 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 3 WTF TOT 5 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 7 WTF TOT 7 WTF TOT 7 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 5 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 WTF TOT 2 , and if it was correct you might consider emailing it instead. We tried sending 5 times ways. You may also want to know that the call was busy 0 of those times. 
================

**Comment by markjcrane** [comment]
That is not in FusionPBX code but that you can search for it using github search in this repository. Such a search will confirm what I have said that it is not in the code. Any such wording would be unprofessional and removed immediately if it were to occur.

What you have is a someone that put that phone number followed by those letters when sending the fax.

**Comment by markjcrane** [comment]
How was the fax sent through the gui or do you give them some other method to send the fax?

**Comment by kkoilada** [comment]
The fax was sent through gui
