### ISSUE TITLE
Upgrading Source on 4.1 Issues

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2238]
Hi 

I am having issues after upgrading Source on 4.1 some functions stop working.

Extensions that were not set to record cannot be recorder after the update.
Activating Pin Numbers on Outbound routes for new Domains not working.

These are the 2 that I have just Experienced for now but I think there could be more.

Thanks and Regards
Ernest Manamela

**Comment by markjcrane** [comment]
Did you upgrad to 4.2? Delete the dialplan -> user_exists and then run upgrade -> app defaults. Then test again.

**Comment by ernestkm** [comment]
Hi Mark

I did an apt-get update && apt-get upgrade and when done I did a Source Update and Update App Defaults.

I did not do the git upgrade.

Could that be the problem?

Thanks and Regards
Ernest Manamela

**Comment by markjcrane** [comment]
That means updated the operating system.

You need to update the source code with git or through the gui with the upgrade source unless that fails. If it does fail then go to the console and run.

cd /var/www/fusionpbx/
git pull
chown -R www-data:www-data /var/www/fusionpbx'

Then go back through the Advanced -> upgrade. And go to docs.fusionpbx.com search for upgrade and read through the instructions.
