### ISSUE TITLE
Fusion sip extention can not login into softphone

### ISSUE THREAD

**Issue by a-t101** [fusionpbx/fusionpbx#2251]
I have a **FS** v1.6.13 on my Debian 8( From git) and it is OK.
After that i installed the last FusionPBX to manage my PBX telephony FS.
But it gives me error :  403 You must define a domain called x.x.x.x in your directory...
Both i installed by **FusionPBX** guid in their web site.
Im going crazy cause about 4 days im working and not a good result yet.
I know Fusion store data in DB and i give him a Pgsql user name and password.( not the default one it suggest after ./install command) and also FS with --enable-core-pgsql-supprt in ./configureaiton.
And i searched a lot, and all says as this [link](http://serverfault.com/questions/365992/cannot-connect-softphone-as-a-freeswitch-extension).
But when i go to sip status from FusionPBX, it says that my ip is correct, and also i did what they say but no success.
Just one time it worked! and i did not why it work.
And after it does not work and again says 403 you must ....
And after that i create an extention, i go to FS terminal and type user_exist 101 (user i created in fusionpbx)it return me false.
Can it be DB issue?
I do not know why just one time it worked and after i after that again gave me 403 error.
Cause i did changed a lot i could not understand what was the cause to work it.
Is it a bug?
What exactly i am doing wrong??
Really any help will appreciate.

Can it

**Comment by a-t101** [comment]
Any idea?

**Comment by moteus** [comment]
This is not bug in Fusion I think so it wrong place to discuss this. Better ask on IRC channel.

**Comment by a-t101** [comment]
I searched all stacks and also freeswitch forums.
Could you please give me a keyword of my problem, so i can search and solve it?
Thx

**Comment by moteus** [comment]
Most likely you use wrong domain name for user. You can chekcout `user_exists 101@domain.name.com`

Again. I strongly recomendet ask such questions on IRC channel.

**Comment by a-t101** [comment]
It seems no one knows the reason !
See [this](http://stackoverflow.com/questions/41138694/sip-extention-created-by-fusionpbx-can-not-login-into-softphone)!
My Domain is default and the ip and user_exist return false.
It seems freeswitch does not read or fusion does not write the created extention.
:-<

**Comment by markjcrane** [comment]
Many people are using zoiper and it works fine for them. If you want my help I'm interested in remote desktop access to solve it consider www.fusionpbx.com/support.php.
