### ISSUE TITLE
call forward bypassing outbound routes?

### ISSUE THREAD

**Issue by reedwan** [fusionpbx/fusionpbx#2252]
Hello, When an extension is set to call forward, the gateway appears in the extension's dial string along with the call forwarding number. Am I correct in understanding that outbound routes are bypassed and the call is sent directly to the gateway? I also have a 4.0 install and that uses loopback instead of the gateway. #

**Comment by markjcrane** [comment]
The call forward all used the dial_string and with this came some of the problems you have mentioned. This has now been changed upgrade fusionpbx to the very latest source in 4.2.x or master branch for the fix.
