### ISSUE TITLE
Unable to log in after fresh install

### ISSUE THREAD

**Issue by rmakings** [fusionpbx/fusionpbx#2259]
Hey guys... probably a user error type of deal.. but does anyone have any suggestions on how to log in after a fresh install... I've tried both database types, but no matter what, my user/pass selected during the install doesn't work

I've verified the usernames are being created in the db
Also, updating the password via the password reset instructions in the docs doesn't resolve the issue.
The failed authentications do show in the auth.log

**Comment by rmakings** [comment]
Apparently, one must log in using the full domain - i.e. user@domain.com.

Can we get this updated in the docs?  It might be fringe case, but still, it might save someone a few hours....

**Comment by markjcrane** [comment]
You only have to login with username @domain.com when you didn't use the domain in your browser as part of the URL.

**Comment by markjcrane** [comment]
You only have to login with username @domain.com when you didn't use the domain in your browser as part of the URL.
