### ISSUE TITLE
RO and HE missing in 4.2

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#2261]
From my Apache log

172.21.1.218 - - [21/Dec/2016:07:21:54 +1100] "GET /fusionpbx/core/install/resources/images/flags/ro.png HTTP/1.1" 404 250
172.21.1.218 - - [21/Dec/2016:07:24:16 +1100] "GET /fusionpbx/core/install/resources/images/flags/he.png HTTP/1.1" 404 250

**Comment by markjcrane** [comment]
Yes they are missing as the flags for those countries were never added.

**Comment by markjcrane** [comment]
We don't have flags for this right now so I used file_exists to prevent the request if the flags don't exist. In addition the default install on Debian doesn't require this install page anymore.
