### ISSUE TITLE
after fresh install there is no menu

### ISSUE THREAD

**Issue by lordofcode2020** [fusionpbx/fusionpbx#2273]
Hi , I've installed the fusionpbx maybe 5 times but doesn't solve the problem , and i have tried to do reset unfortunately not worked

**Comment by andycol** [comment]
do you see anything even upgrade?
then do menu defualts

**Comment by lordofcode2020** [comment]
no , there is no menu , but i tried to do that by searching this page in the fusiopbx folder and i have upgraded but didn't work , still no menu

**Comment by lordofcode2020** [comment]
I tried did not work

**Comment by Len-PGH** [comment]
Try this.

cd /var/www/fusionpbx
git pull
chown -R www-data:www-data /var/www/fusionpbx
cd /var/www/fusionpbx && php /var/www/fusionpbx/core/upgrade/upgrade_domains.php

**Comment by Len-PGH** [comment]
No response closing.

**Comment by markjcrane** [comment]
The issue is not hard to fix the basics is upgrade schema to make sure you have the latest database schema, and then menu 'restore default'.
