### ISSUE TITLE
Rewrite in OOP?

### ISSUE THREAD

**Issue by odannyc** [fusionpbx/fusionpbx#2277]
I was looking through some source files and everything looks very procedural. Are there any future plans to rewrite in object oriented style with composer?

**Comment by markjcrane** [comment]
If you look in the main directory you will see resources/classes if you look some more you will see some app directories have a sub directories of resources/classes so me of the code is OO than you may habe noticed. As with a most software it is evolving and will be more object oriented over time.

**Comment by markjcrane** [comment]
If composer was more like npm I would get more excited about it. We will also be moving to a template engine which we are already using for provisioning. Much of the important work is already handled in classes.
