### ISSUE TITLE
Voicemail will not play in Chrome 55.0.2883.87

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#2281]
When playing voicemail in Chrome 55 (cached cleared and also tried in incognito mode), voicemails do not play. This is the developer's console:

`Uncaught (in promise) DOMException: [line 1] The play() request was interrupted by a call to pause().`

Voicemails play OK in Firefox 50.1.

**Comment by pixel2920** [comment]
additional info
FPBX 4.3.1
URL /app/voicemails/voicemail_messages.php?id=<guid>

**Comment by markjcrane** [comment]
Works on FireFox and Chrome 54 on Mac OSX.

**Comment by markjcrane** [comment]
Works on Windows 10 with Chrome 54

**Comment by markjcrane** [comment]
I upgraded Chrome to version 55 on Windows 10 it also worked fine. So far unable to duplicate the issue.

**Comment by markjcrane** [comment]
Looks to be working fine upgrade to the latest and try disabling your chrome extensions or add ons. Restart and try again.
