### ISSUE TITLE
Follow me issue, ring group and destination number

### ISSUE THREAD

**Issue by mestan84** [fusionpbx/fusionpbx#2283]
I have following issue with follow me:

- if follow me is enabled > when calling to number it disconnects directly, it doesn't even ring.
- disable me follow me and issue is gone

But I need follow me for prompt.

Also when using ring group and a put a external destinaton number. This number is not being called.

Also in freeswitch you put # in front or end of destination, does fusionpbx has this also? Thank you.

**Comment by mestan84** [comment]
I didn't understand you exactly... Where do I put it manually?

Under gateway I don't see any external and destination number.

**Comment by kkoilada** [comment]
Its under ring group, section destinations where you enter the phone number..

**Comment by mestan84** [comment]
I tried this a lot but can't figure out. Can you do this for me? Will pay.

**Comment by kkoilada** [comment]
I am here to help to the extent I can but not willing to take money for it... After all we all using the open source product and we should be kind enough to help each other... 

now coming to your issue, can you send the fs_cli logs and screenshot of the ringgroup page?

**Comment by markjcrane** [comment]
Your carrier could reject the call if it doesn't like the caller id you are sending.
