### ISSUE TITLE
Cannot upload music on hold

### ISSUE THREAD

**Issue by dukkh4** [fusionpbx/fusionpbx#2284]
Cannot upload music on hold. Files have been converted to 16bit, 48hz mono. When i upload a file, it says file uploaded successfully but they do not appear under in the list. Also, module Local Stream is now in stopped state and cannot be started from the webgui

**Comment by markjcrane** [comment]
How large it the file and do you have a space in the file name or other special characters?

**Comment by dukkh4** [comment]
file is 25 Mb i have 40 gb free space, no spaces or special characters in the filename

**Comment by mryanb** [comment]
Running into the same issue here. Uploading an mp3 that was converted to a 16bit 48kHz wav with `ffmpeg`. The wav is 8.3MB. The upload post completes and the page refreshes.

Currently running 4.2.2.

**Comment by markjcrane** [comment]
Check your php.in for upload max file size.

**Comment by mryanb** [comment]
@markjcrane Thanks. That resolved the issue.

**Comment by bayden10** [comment]
I've increased the file size to 40MB but still cannot upload an 11MB WAV file.

**Comment by markjcrane** [comment]
Restart php fpm or the server to apply the changes to the php.ini file.

**Comment by mryanb** [comment]
@bayden10 Also make sure you update both `upload_max_filesize` and `post_max_size`

**Comment by bayden10** [comment]
@mryanb thanks for your reply, I did make the changes to the active php.ini which was located /etc/php5/cli/ then **service apache2 restart**, later also rebooted the server. I also tried creating a new upload directory within FusionPBX/Apps/Music on Hold with no luck. I think this maybe a permissions issue. I've checked the log viewer but nothing jumps out.

**Comment by mryanb** [comment]
@bayden10 You will want to make those changes to `/etc/php5/fpm/php.ini` not the config for the CLI.

**Comment by bayden10** [comment]
@mryanb sorry I found this when checking. **php -i | grep "Loaded Configuration File"
Loaded Configuration File => /etc/php5/cli/php.ini** .  I have updated /etc/php5/fpm/php.ini and reloaded (no luck) and rebooted and now works.. thanks for your help
