### ISSUE TITLE
ATA Outbound Fax not registering fax tone on other end.

### ISSUE THREAD

**Issue by rhubeek** [fusionpbx/fusionpbx#2289]
Hi, 

I have a fax machine that i'm running in the config below, 

Fax -> Cisco SPA112 ATA(have also tried grandstream) -> FusionPBX Extention -> SIP 

When sending outgoing fax, it never registers an answer from the receiver. As such it fails to ever send the fax. It will work if i remove the Fusion part and go straight to SIP.  Receiving works.

Calling with a phone to the receivers fax i get a fax signal, so the call is going through.

![image](https://cloud.githubusercontent.com/assets/24949297/21706039/0b50751e-d418-11e6-9033-c5684c7d747a.png)

I have modified these settings in the PBX. 

I have tried G711 and T.38.

When sending fax to a phone it does ring, and i can answer. 

If
![image](https://cloud.githubusercontent.com/assets/24949297/21706633/e84cfa7e-d41c-11e6-9690-d7b657c371dc.png)

I can't seem to figure it out. Is there anyone else who has had this problem? i noticed someone else had a similar problem without posting a resolution. But i have been fiddling with it for a few days now trying to figure it out, but i'm just reaching a dead end with fusion not accepting fax going through it.

Warm Regards,

**Comment by Len-PGH** [comment]
There were recent fax bug fixes in FreeSWITCH.  You might consider to roll back or update once 1.6.15 comes out soon.  If this isnt related to that, in the extension settings you can try bypass media. That might help.

**Comment by Len-PGH** [comment]
FreeSWITCH 1.6.15 is out. Please try to update FreeSWITCH
