### ISSUE TITLE
Yealink t32g provisioning {mac}.cfg small problem

### ISSUE THREAD

**Issue by rhetor22** [fusionpbx/fusionpbx#2294]
Line 1991 of the yealink t32g provisioning file {mac}.cfg is missing a squigly bracket and causing the autoprovision file build to fail.

It is:
foreach $keys["programmable"] as $row}

and should be:
{foreach $keys["programmable"] as $row}

**Comment by Len-PGH** [comment]
Thank you. Got that fixed on master and 4.2.1

**Comment by rhetor22** [comment]
woohoo!  I helped!
