### ISSUE TITLE
Accounts -> Users wrong url

### ISSUE THREAD

**Issue by rhetor22** [fusionpbx/fusionpbx#2295]
For version 4.3.1, when going to Accounts -> Users, the following url is loaded:

mypbx.com/core/users/index.php which does not exist.

I think it should be:

mypbx.com/core/users/users.php

**Comment by Len-PGH** [comment]
try this
 advanced > upgrade >check box app defaults then execute
check box menu defaults then execute
check box Permission Defaults then execute

**Comment by rhetor22** [comment]
Fixed!
