### ISSUE TITLE
 ERROR in /var/www/fusionpbx/core/user_settings/user_dashboard.php

### ISSUE THREAD

**Issue by donweasel** [fusionpbx/fusionpbx#2299]
Hi just installed FusionPBX on DEBIAN 8 maybe 3 times following this guide https://www.fusionpbx.com/download.php

and when i log in im having a lot of errors:

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 111

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 111

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 339

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 408

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 523

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 669

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 756

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 932

![image](https://cloud.githubusercontent.com/assets/25114110/21952262/75e3f144-d9e5-11e6-9971-ca00669a7cf1.png)

Any help will be appreciated

Thanks.

**Comment by wmlele** [comment]
Same here. I have just made a fresh install of FusionPBX (I've done others before), and the outcome, at the first login is what it's shown above. 

Moreover, I have seen that the install scripts checks out the 4.2 branch, which is quite different from what the 4.2 used to be when I last used it in november. Is there a way to instruct the install script to check out a specific commit? Or to downgrade the install, should the above happen?

thanks
L.

**Comment by markjcrane** [comment]
Yes you could modify the script to pickup a specific commit however the problem has been fixed earlier tonight. You can re-install or simply run the following on the console or via ssh.

cd /var/www/fusionpbx
git pull
chown -R www-data:www-data /var/www/fusionpbx
cd /var/www/fusionpbx && php /var/www/fusionpbx/core/upgrade/upgrade_domains.php

Logout of the browser and back in.

**Comment by donweasel** [comment]
Thanks for the quick response, this definitely fixed it.

**Comment by wmlele** [comment]
Thanks, a lot!
