### ISSUE TITLE
Cannot turn off Voicemail on Extensions

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2300]
Hi 

I have a problem I cannot switch off voicemail on extensions.
When I try to disable it from the extensions it just goes back after saving.

I am using FusionPBX 4.2

**Comment by markjcrane** [comment]
Try it from menu -> advanced -> voicemails. You can delete the voicemail box from there if you would like.

-Mark

**Comment by ernestkm** [comment]
Hi mark

I think it is Apps ---> Voicemail.
Thats how I got it to work.

Thanks for the quick response.
