### ISSUE TITLE
/usr/share/freeswitch/scripts/app/toll_allow/index.lua - error in script

### ISSUE THREAD

**Issue by inform11** [fusionpbx/fusionpbx#2303]
Hi!
In scrips toll_allow/index.lua error!
now there:
			RU = {
				{"international", "810%d+|8[89]40%d+|87%d%d%d%d%d%d%d%d%d"};
				{"mobile",        "89%d%d%d%d%d%d%d%d%d"                  };
				{"tollfree",      "8800%d%d%d%d%d%d%d|10[1-9]"            };
				{"landline",      "8[3-68]%d%d%d%d%d%d%d%d%d%d"           };  - 8[3-68]+10 digits
				{"unknown",       ""                                      };

must be:

			RU = {
				{"international", "810%d+|8[89]40%d+|87%d%d%d%d%d%d%d%d%d"};
				{"mobile",        "89%d%d%d%d%d%d%d%d%d"                  };
				{"tollfree",      "8800%d%d%d%d%d%d%d|10[1-9]"            };
				{"landline",      "8[2-68]%d%d%d%d%d%d%d%d%d"           }; - 8 [2-68]+9 digits
				{"unknown",       ""                                      };
			};
 
after upgrade i have problem!

**Comment by moteus** [comment]
`82xxx` is some thing like `local area` code. And they canceled few years ago.
May be I miss some thing.

**Comment by inform11** [comment]
The most important thing is the number of digits
 8[3-68]+10 digits = 12
must be 11

**Comment by inform11** [comment]
thank you!
