### ISSUE TITLE
Warning: Missing argument 3 for switch_music_on_hold::select(),

### ISSUE THREAD

**Issue by oliverv** [fusionpbx/fusionpbx#2305]
on creating extention : 
Hold Music	
Warning: Missing argument 3 for switch_music_on_hold::select(), called in /var/www/fusionpbx/app/extensions/extension_edit.php on line 1810 and defined in /var/www/fusionpbx/app/music_on_hold/resources/classes/switch_music_on_hold.php on line 53

Please advice

**Comment by willempoort** [comment]
Same here.
Although 3rd parameter (options) is optional to my opinion.
To get rid of the error you can through in an empty extra parameter in extensions_edit.php at line 1810
                echo $moh->select('hold_music', $hold_music, '');

**Comment by oliverv** [comment]
anybody has work around of fix for this yet ?

**Comment by willempoort** [comment]
See my work arround, it works ;)

**Comment by oliverv** [comment]
Thanks!! that worked.

**Comment by markjcrane** [comment]
This has been fixed.
