### ISSUE TITLE
tetrix.ttml file location error during tone test *9198

### ISSUE THREAD

**Issue by AuriokNomad** [fusionpbx/fusionpbx#2315]
Did fresh install from script on Debain 8 system, when attempting to do *9198 receive error 
2017-01-19 18:59:12.549700 [WARNING] mod_tone_stream.c:171 Failed to open [/usr/conf/tetris.ttml] 

Appears file is no longer under directory listed in dialplan, change to new location under dialplan with:

{loops=10}tone_stream://path=${base_dir}/share/freeswitch/conf/vanilla/tetris.ttml

**Comment by Len-PGH** [comment]
Try updating and run app defaults from Advanced > Upgrade.  Can always manually download from freeswitch source also.
