### ISSUE TITLE
BUG: Valet parking to *5900 do not announce slot

### ISSUE THREAD

**Issue by lodperera** [fusionpbx/fusionpbx#2316]
Hi Team,

FPBX 4.2.1
Fswitch 1.6.5

ext100 called ext101
ext101 tried attended transfer to *5900 for Valet parking. (http://fusionpbx-docs.readthedocs.io/en/latest/additional_information/feature_codes.html?highlight=*5900#id15)

But instead of announcing the parking slot number, FPBX plays MoH.

http://pastebin.com/y5LdwqTQ

**Comment by markjcrane** [comment]
How are you transferring the call? You need to use an attended transfer so that you can hear where the call is parked. That is how it has always worked for FreeSWITCH.

**Comment by lodperera** [comment]
Yes I did an attended transfer.

Yealink phones.

Ext 100 calls ext 101
ext 101 press trans button on the yealink phone
that puts ext 100 on hold.
Then ext 101 dials *5900#
Ext 101 hears MoH instead of slot announcement

**Comment by markjcrane** [comment]
I don't think valet 'park in' has changed at all in a couple years.
Try this with a different phone to see if it makes a difference or different firmware.

**Comment by markjcrane** [comment]
Try upgrading FreeSWITCH you are several versions behind on FreeSWITCH stable release currently 1.6.13.

**Comment by lodperera** [comment]
Not a bug as mcrane showed me.
Needs to enable the dialplan entry of valet_park_in and valet_park_out



	valet_park	park+*5901-*5999	coonanplumbing.pbx.talkup.com.au	470	False	 	
	valet_park_in	park+*5900	coonanplumbing.pbx.talkup.com.au	470	True	 	
	valet_park_out	park+*5901-*5999	coonanplumbing.pbx.talkup.com.au	475	True

**Comment by Len-PGH** [comment]
closing
