### ISSUE TITLE
DTMF Options not working on Version 4.3.1 

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2317]
Good Day

Please note that DTMF Options not working on Version 4.3.1.
When dialing out to clients or suppliers with IVR options on their systems DTMF is not working.

Thanks and Regards
Ernest Manamela

**Comment by markjcrane** [comment]
This is not a 4.3.1 specific issue this is an issue between you and your carrier not using the same type of DTMF.
