### ISSUE TITLE
New installation is not showing DB user fusionpbx details

### ISSUE THREAD

**Issue by alexhaozheng** [fusionpbx/fusionpbx#2318]
Dear all,

I recently have installed Debian 8.7 and installed fusionpbx by following the instructions from FusionPBX website as below:

Version of Debian:
root@labfusionpbx2:/usr/src/fusionpbx-install.sh/debian/resources/backup# cat /etc/issue
Debian GNU/Linux 8 \n \l
root@labfusionpbx2:/usr/src/fusionpbx-install.sh/debian/resources/backup# cat /etc/debian_version
8.7

Instructions of FusionPBX installation:
apt-get update && apt-get upgrade -y --force-yes
apt-get install -y --force-yes git
cd /usr/src
git clone https://github.com/fusionpbx/fusionpbx-install.sh.git
chmod 755 -R /usr/src/fusionpbx-install.sh
cd /usr/src/fusionpbx-install.sh/debian
./install.sh

when installation completed, i just got below, there is no info about DB user fusionpbx, thus i even could not backup the system/database. When I login fusionpbx web page for first time after installation, there is no setup step, just straight forward opened the normal admin page.

Any idea on this? I can see the fusionpbx installed version is 4.2.1.

Any input is much appreciated!!!

.
.
.
CREATE ROLE
GRANT
GRANT
GRANT
ALTER ROLE
ALTER ROLE
INSERT 0 1
INSERT 0 1
INSERT 0 1

Installation has completed.

   Use a web browser to login.
      domain name: https://192.168.2.38
      username: admin
      password: 9qeAWqpGrLv6BnG

   The domain name in the browser is used by default as part of the authenticati                                             on.
   If you need to login to a different domain then use username@domain.
      username: admin@192.168.2.38

   Official FusionPBX Training
      Admin Training    24 - 26 Jan (3 Days)
      Advanced Training 31 Jan - Feb 2 (3 Days)
      Timezone: https://www.timeanddate.com/worldclock/usa/boise
      For more info visit https://www.fusionpbx.com

   Additional information.
      https://fusionpbx.com/support.php
      https://www.fusionpbx.com
      http://docs.fusionpbx.com

**Comment by markjcrane** [comment]
The new install was designed to be easy. I didn't want people to get stuck on the install. So it is all being done for you with no questions you get a username and random password at the end and you login and start to use it.

> DB user fusionpbx, thus i even could not backup the system/database. 

The database password is random and saved in /etc/fusionpbx/config.php.

**Comment by alexhaozheng** [comment]
Mark, thanks for your reply!!

As I am new to FusionPBX, not sure whether there is  any place mentioned this change?

**Comment by markjcrane** [comment]
It was mentioned on:
twitter.com/fusionpbx

youtube.com/fusionpbx
Here is the direct link https://www.youtube.com/watch?v=YmIht8hEHYU

docs.fusionpbx.com
Quick install

**Comment by alexhaozheng** [comment]
OK, i got it. 

Appreciate for your help!

**Comment by glarkou** [comment]
Is it possible to run the old installation in order to add a remote database (AWS) instead of the default database?
