### ISSUE TITLE
Outbound called ID when using Follow Me to external destination

### ISSUE THREAD

**Issue by FozzyGo4** [fusionpbx/fusionpbx#2321]
Hi Guys,

Firstly awesome GUI for Freeswitch. Im a 12 year user of FreePBX and Asterisk so now getting my hands dirty with this awesome bit of tech!

I was playing around with the follow me feature of an extension and came across an issue when using follow me from an internal extension to an extension with follow me set to an external number e.g a mobile number. The issue I found is that if for example extension 100 calls 101 and follow me on 101 is set to 101 and 0123456789 (the mobile number), the caller ID will show as 100 on 101's phone but show as "No Caller ID" on the mobile even though the outbound_caller_id is set on all extensions. It is using the effective_caller_id.

This is not an issue though for calls from outside to the extension e.g 0987654321 calls the DID for ext 101 and when the follow me gets to the mobile, I see 0987654321 is calling me on the mobile.

So to fix this I did the following but thought it should be automatically set when configuring the follow me for an extension.

When setting up a follow me, FusionPBX inserts a dial string which I found under advanced of the extension. It looks like this:- Obviously I substituted my domain with sub.domain.tld for this example.

```
{fail_on_single_reject=USER_BUSY,instant_ringback=true,ignore_early_media=true,domain_uuid=b4455729-695b-405a-b7e5-a6aa2b3345b4,sip_invite_domain=sub.domain.tld,domain_name=sub.domain.tld,domain=sub.domain.tld,extension_uuid=f296dae8-93e5-4f5f-b08e-938e65e3c5c6,group_confirm_key=exec,group_confirm_file=lua confirm.lua,origination_caller_id_name=${effective_caller_id_name},origination_caller_id_number=${effective_caller_id_number},sip_h_X-accountcode=sub.domain.tld,accountcode=sub.domain.tld,toll_allow=''}[outbound_caller_id_number=${effective_caller_id_number},presence_id=101@sub.domain.tld,leg_delay_start=0,leg_timeout=30]${sofia_contact(101@sub.domain.tld)},
[outbound_caller_id_number=${effective_caller_id_number},presence_id=101@sub.domain.tld,leg_delay_start=10,leg_timeout=30]sofia/gateway/c3caa190-9654-4fea-9489-801be74f2802/0123456789
```

If I change the section that sets the called id for the gateway and the number to dial to the following:
current:
```
[outbound_caller_id_number=${effective_caller_id_number},presence_id=101@sub.domain.tld,leg_delay_start=10,leg_timeout=30]sofia/gateway/c3caa190-9654-4fea-9489-801be74f2802/0123456789
```

To:
```
[origination_caller_id_number=${outbound_caller_id_number},presence_id=101@sub.domain.tld,leg_delay_start=10,leg_timeout=30]sofia/gateway/c3caa190-9654-4fea-9489-801be74f2802/0123456789
```

It works as desired. So to the developers of FusionPBX. Is it possible to set this parameter, (**origination_caller_id_number=${outbound_caller_id_number}**) when following detects the number to dial is external?

**Comment by markjcrane** [comment]
I fixed this in a dynamic way a week or two ago on both stable and master branch.
