### ISSUE TITLE
sip_profile_domain_delete.php does not exist

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#2324]
Line 322 of **/fusionpbx/app/sip_profiles/sip_profile_edit.php** references **sip_profile_domain_delete.php**. This file does not exist.

**Comment by markjcrane** [comment]
Thanks for reporting this I have added it in https://github.com/fusionpbx/fusionpbx/commit/bc9f9793939ea6bd808f729df1940a3de597a243.
