### ISSUE TITLE
Streaming MOH

### ISSUE THREAD

**Issue by MarvinSk** [fusionpbx/fusionpbx#2327]
Is it possible to configure Streaming MOH from a Icecast/Shoutcast Source.

Can anyone provide some guidance

Thanks in advance

**Comment by ippbx** [comment]
yes, look at mod_shout or mod vlc.

**Comment by MarvinSk** [comment]
Please spare more detail in...

I am assuming you cannot set it up via FPBX Gui

**Comment by ippbx** [comment]
Check the FreeSWITCH confluent and Fusionpbx docs, it is well documented.
