### ISSUE TITLE
PHP Error when editing/adding follow me settings

### ISSUE THREAD

**Issue by nwilkens** [fusionpbx/fusionpbx#2335]
/app/calls/call_edit.php?id=<uuid>

Fatal error: Call to undefined function extension_presence_id() in /var/www/fusionpbx/app/calls/resources/classes/follow_me.php on line 352

**Comment by markjcrane** [comment]
What version of FusionPBX are you using?

**Comment by nwilkens** [comment]
Looks like I pulled in a version from around Jan 11 22:00 2017.

**Comment by markjcrane** [comment]
Try upgrading and test again. I believe this was fixed already.

**Comment by markjcrane** [comment]
FusionPBX 4.2.0 has a security vulnerability you want to get onto 4.2.1 or higher.

**Comment by nwilkens** [comment]
Thanks -- upgraded, and this error is gone.   4.2.2 appears to be my local version at this point.
