### ISSUE TITLE
impossible to save data in edit destination page in 4.3 version

### ISSUE THREAD

**Issue by Webmasterparis** [fusionpbx/fusionpbx#2339]
hello marc,

I install fresh version of fusionpbx 4.3 , and I confirm problem urgent.

If you select one domain OK

you go to the menu  dialplan / destination / 

you edit number telephone OK

in action > you select one number extension ex: 503 

and you click in save .

the number is never save ???

this is bug..

I need to downgrade to version 4.2.2  and now it work ???

tanks to fix it please

**Comment by markjcrane** [comment]
Maybe you forgot to run advanced -> upgrade schema?

**Comment by Webmasterparis** [comment]
not I sure I do that , I not forget

**Comment by Webmasterparis** [comment]
I reinstall all from scrash and now all it is ok

tanks marc crane
