### ISSUE TITLE
Provision

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#2340]
Hi!
Right now at this provision template
http://fusionbpx.ip/app/provision/?mac=0015E92B993C

I've got an answer with bunch of errors.
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>739</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>761</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>761</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>761</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/fusionpbx/app/provision/resources/classes/provision.php</b> on line <b>761</b><br />

Right now resolved with adding 
error_reporting(0);
to 
fusionpbx/app/provision/index.php

**Comment by Tatermen** [comment]
If it helps, I noticed this happens in the 4.2 branch, but not in the master branch.

**Comment by Len-PGH** [comment]
warnings can be turned off in config.php
