### ISSUE TITLE
Error in time condition edit

### ISSUE THREAD

**Issue by drenda** [fusionpbx/fusionpbx#2347]
Hi,
editing time condition I've this error:

Warning: Invalid argument supplied for foreach() in /var/www/fusionpbx/app/time_conditions/time_condition_edit.php on line 596

I set time condition based on day of week + 2 hour conditions.

Thanks

**Comment by Len-PGH** [comment]
What version are you running

**Comment by drenda** [comment]
Hi.

Branch: 4.2
Commit: 0bd81b1af389cbc3091e90523c13fd9c09030532
Origin: https://github.com/fusionpbx/fusionpbx.git

**Comment by drenda** [comment]
Also,
going to the dialplan from that time rule I've another error: Warning: ksort() expects parameter 1 to be array, string given in /var/www/fusionpbx/app/dialplan/dialplan_edit.php on line 292

**Comment by markjcrane** [comment]
This should be fixed if you update to the latest 4.2.2.
