### ISSUE TITLE
adminer login issue after the newest update

### ISSUE THREAD

**Issue by canadamcpherson** [fusionpbx/fusionpbx#2348]
Since the new update which does not provide the database password at the end of the installation, I cannot login into adminer. I got the password from config file, but it still does not allow signing into adminer.

**Comment by Len-PGH** [comment]
From Advanced > Default Settings you can toggle "auto_login" Under the Adminer Section to "true" . Then click Reload button at the top right beside the copy and toggle buttons.  When you login this should allow Adminer to work.  The other method should work but this is an alternative way until we find if what you are reporting is a bug or not.

**Comment by canadamcpherson** [comment]
Using the latest as of 2017-02-05 (just upgraded). The issue is there. However, something grabbed my attention, and I wonder if this is the reason. The localhost 127.0.0.1 is not within the access control. Would that be the reason? Were previous installation automatically adding the localhost to access control allow list?

**Comment by markjcrane** [comment]
> Since the new update which does not provide the database password at the end of the installation,

No an issue the password is in /etc/fusionpbx/config.php.

> it still does not allow signing into adminer.

The common issue here is when people assume server: localhost is a value and in reality its not a value at all by default. So you need to manually try localhost or 127.0.0.1.

**Comment by liveincan** [comment]
I am having the same issue. auto_login set to true works. However when auto_login set to false, cannot login manually. I am using credentials from /etc/fusionpbx/config.php
//pgsql: database connection information
	$db_host = 'localhost'; //set the host only if the database is not local
	$db_port = '5432';
	$db_name = 'fusionpbx';
	$db_username = 'fusionpbx';
	$db_password = '**************************';
Tried using both localhost and 127.0.0.1 for server but keep getting 'Unable to connect to PostgreSQL server: FATAL: Peer authentication failed for user "fusionpbx"'
