### ISSUE TITLE
Errors on CDR Statistics

### ISSUE THREAD

**Issue by canadamcpherson** [fusionpbx/fusionpbx#2349]
The following errors are shown on CDR Statistics page.

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344

**Comment by Len-PGH** [comment]
What version are you running?

**Comment by canadamcpherson** [comment]
A version that was released on last Sunday. However, I ran the upgrade today and it seems that it is resolved. I am closing this.

**Comment by canadamcpherson** [comment]
I just upgraded today. The issue still exist but now the error is reduced to one line:

Warning: Division by zero in /var/www/fusionpbx/app/xml_cdr/xml_cdr_statistics_inc.php on line 344.

It is seen when all permissions are given to the superadmin. However, you may put this on low priority. Just something to keep in mind.

**Comment by markjcrane** [comment]
I'm working on it will let you know when it's fixed.

**Comment by canadamcpherson** [comment]
Thanks Mark!

**Comment by canadamcpherson** [comment]
The issue is resolved. Thanks!
