### ISSUE TITLE
Installing App-SMS. Giving error on line 214 of app_defaults.php

### ISSUE THREAD

**Issue by canadamcpherson** [fusionpbx/fusionpbx#2358]
I have the latest today's update.

When Installing App-SMS it gives the following error when executing app defaults in Upgrade menu.

Fatal error: Call to undefined method database::save() in /var/www/fusionpbx/app/sms/app_defaults.php on line 214

I looked at that line.

211 			$database = new database;
212			$database->app_name = 'default_settings';
213			$database->app_uuid = '2c2453c0-1bea-4475-9f44-4d969650de09';
214			$database->save($array);
215			$message = $database->message;
216			unset($database);

Is something really wrong in line 214?

**Comment by blackc2004** [comment]
You need to use 4.3 for app-sms to work.

**Comment by canadamcpherson** [comment]
So it does not work with stable version?

**Comment by markjcrane** [comment]
Yes right now the app-sms works only on the master branch which is 4.3.
