### ISSUE TITLE
voicemail to email

### ISSUE THREAD

**Issue by ricky560** [fusionpbx/fusionpbx#2360]
I have tried to setup voicemail to email on 4.2.2 with now luck.  when it fails the failed email show that it was trying to send from itself to itself

From: user@domain.com
To: user@domain.com 

instead of 

From: user@domain.com
To: user@example.com

what are the configuration settings for email to a imap/smtp connection?

**Comment by markjcrane** [comment]
FusionPBX sends the emails to your server to send. So the settings are dependent on what you use so we can't give you specifics for your smtp settings without knowing information about your email server.

**Comment by canadamcpherson** [comment]
Look at the documentation. Mark has done a good job on explaining that. Also keep in mind that you need to have a SMTP account setup.

**Comment by ricky560** [comment]
I reviewed the logs in /tmp and changed the mail server to a gmail account and it worked both for voicemail to email and fax to email.
Thanks for your help 

    On Monday, February 6, 2017 6:40 PM, canadamcpherson <notifications@github.com> wrote:
 

 Look at the documentation. Mark has done a good job on explaining that. Also keep in mind that you need to have a SMTP account setup.—

**Comment by canadamcpherson** [comment]
N.P

**Comment by Len-PGH** [comment]
resolved. closing
