### ISSUE TITLE
Fax to email in fusionpbx

### ISSUE THREAD

**Issue by quochuy0880** [fusionpbx/fusionpbx#2367]
Hi all,

Please guide me step by step how to setup :(. I based on https://github.com/bwmarrin/fsfax but it cannot work

Thanks
Jason

**Comment by jebsolutions** [comment]
If you are going to use FusionPBX then I suggest you don't follow that guide.  

FusionPBX already includes fax support built in.

Log into your FusionPBX gui with your web browser.  Look under the Apps menu.  This is where you will find the Fax Server setup.

**Comment by Len-PGH** [comment]
Please visit http://www.fusionpbx.com/support.php for paid support if you need help and also keep in mind that admin and advanced classes are available to expedite learning FusionPBX
