### ISSUE TITLE
purge recorded audio

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#2368]
best way to delete all the audio or a way to set x amount of days "30days" to auto delete ?

**Comment by MrCoolLV** [comment]
update ?

**Comment by hsingfoo** [comment]
you might be able to setup a cron job. If you do, please share your code.

**Comment by MrCoolLV** [comment]
I see, i was thinking this was an option to set that i missed ...

**Comment by MrCoolLV** [comment]
working on script, whats the path where the audio is stored ?

**Comment by blackc2004** [comment]
find /var/lib/freeswitch/recordings/*/archive/* -name '*.wav' -mtime +7 -exec rm {} \;

**Comment by MrCoolLV** [comment]
above path isn't for voicemail's correct ?

**Comment by markjcrane** [comment]
You can adjust the path for voicemail to do what you need here is the path add it to the find command above.
/var/lib/freeswitch/storage/voicemail
