### ISSUE TITLE
Call Center Queues, error selecting IVR

### ISSUE THREAD

**Issue by drenda** [fusionpbx/fusionpbx#2369]
In the edit of the Call centere Queues, the selection of the IVR doesn't work well.
I select an entry of the list of IVR (I've 3 enties), but when I save, remains selected the last entry (not the one I selected).

Thanks

**Comment by drenda** [comment]
Sorry, my bad. My IVR had the same extension number (I did copy of the first one).

Should not be checked the if the extension number is yet used before permit the user to save?

Thanks

**Comment by markjcrane** [comment]
I don't follow the question if you want to ask again then please describe the question in more detail and re-open the issue.

**Comment by drenda** [comment]
In short the problem is you can duplicate an IVR keeping the same extension number. This can be dangerous when you go to create the dialplan and select the IVR.
I'm not so expert to think if is desirable have more IVR with the same extension number....but maybe not.

So I suggested to add a check on the extension number.

Thanks

**Comment by DigiDaz** [comment]
You can copy ANY extension number in FusionPBX, as far as I am aware this is never checked to this is not just restricted to IVR.

I have come across clients who have created a ring group with same extension as a time condition or IVR etc.

**Comment by markjcrane** [comment]
This is why it's a good idea to have a numbering 'plan'. So that a time condition or other feature would never have a conflicting number.

**Comment by markjcrane** [comment]
Much better description of the issue.

Note - It takes an enormous effort to prevent every way someone can hurt themselves.

**Comment by DigiDaz** [comment]
Yes, I appreciate this would be a huge job. Its not something I recall ever being covered in any class but similarly never raised either, either within classes or on IRC etc. I often get into a tangled mess myself and wonder how others deal with this.
