### ISSUE TITLE
No module named ESL

### ISSUE THREAD

**Issue by fitreklam** [fusionpbx/fusionpbx#2373]
Hello

I am getting the following error. 

Can you help me please.

----------------------------------------------------------
root@MasterPBX:~# python esl.py
Traceback (most recent call last):
  File "esl.py", line 6, in <module>
    import ESL
ImportError: No module named ESL

**Comment by markjcrane** [comment]
FusionPBX doesn't use python for anything. FreeSWITCH has support for Python. You are asking for help on this in the wrong project.

**Comment by markjcrane** [comment]
ESL stands for event socket library.
