### ISSUE TITLE
Error removing entries in Dialplan

### ISSUE THREAD

**Issue by drenda** [fusionpbx/fusionpbx#2374]
If you try to remove all lines of the dialplan you have this error:

`Warning: ksort() expects parameter 1 to be array, string given in /var/www/fusionpbx/app/dialplan/dialplan_edit.php on line 292`

Furthermore you are not able to add lines anymore.

I'm using Branch: 4.2 
Commit: 81df86d28d215c09a804a96a033fa3f23a57a7ba 
Origin: https://github.com/fusionpbx/fusionpbx.git

**Comment by markjcrane** [comment]
ksort has been wrapped in ... to prevent the warning.
if (is_array($details)) {

This was done on master branch sometime ago just applied it to the 4.2 branch.
