### ISSUE TITLE
issue in voicemail options

### ISSUE THREAD

**Issue by unbornx** [fusionpbx/fusionpbx#2375]
entering a external phone number  as an option in voicemail doesn't create "menu-exec-app:transfer 95555555555 XML local.domain" as it does in IVR Menu.
It end up being "95555555555:" when you try to edit it.

In Ivr menu edit, it checks if it is numeric and adds proper text, but this check is missing in voicemail options. (check if the option param is numeric)

**Comment by markjcrane** [comment]
Its fixed. Please update then test and report back whether it is working for you or not.

**Comment by unbornx** [comment]
thanks, works now

**Comment by markjcrane** [comment]
Great closing the issue.
