### ISSUE TITLE
Error in dashboard for custom group permissions

### ISSUE THREAD

**Issue by drenda** [fusionpbx/fusionpbx#2376]
I created a clone of "user" group and just remove conferences and fax. When the user login the dashboard present this error:

`Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 111

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 111

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 339

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 408

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 523

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 669

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 756

Warning: in_array() expects parameter 2 to be array, null given in /var/www/fusionpbx/core/user_settings/user_dashboard.php on line 932`

Is not visible any menu and so the user is stuck. I'm using Branch: 4.2 
Commit: 81df86d28d215c09a804a96a033fa3f23a57a7ba 
Origin: https://github.com/fusionpbx/fusionpbx.git

**Comment by markjcrane** [comment]
Make sure you updated fusionpbx to latest.
Most warning have been fixed chances are thus one has already been fixed.

**Comment by drenda** [comment]
I am already up to date.

**Comment by markjcrane** [comment]
Please update again should be fixed.

For future reference in /etc/fusionpbx/config.php bottom of the file you can un-comment one of the last lines to hide the warnings. New installs hiding this for users as this really is a better setting for developers so we find them instead of users. When we are become aware of them we do try to fix them as soon as possible.

**Comment by drenda** [comment]
Thanks, now works!

**Comment by markjcrane** [comment]
Great thanks for reporting it.
