### ISSUE TITLE
Cisco SPA504g SIP Transport

### ISSUE THREAD

**Issue by MarvinSk** [fusionpbx/fusionpbx#2380]
Hello All,

Anyone know if there was every a fix for Cisco SPA504G unable to register with SIP Transport (UDP)

This issue goes back 7 years.. I know the work-around is to set the transport to (TCP)

This issue seems to only exist when FS is Behind NAT.

Any ideas?

**Comment by Len-PGH** [comment]
Check that your provisioning template is current https://github.com/fusionpbx/fusionpbx/tree/master/resources/templates/provision/cisco/spa504g  I was able to provision with UDP with SPA504g
