### ISSUE TITLE
device_username_password permission

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#2388]
If the device_username_password permission is removed from a user, that user can no longer save changes to devices due to a Javascript function ```check_duplicates()``` still attempting to read a now non-existent device_username form field and causing a Javascript error.

```
		function check_duplicates() {
			...
				//check username
				if (duplicate_mac == false) {
					var username = document.getElementById('device_username').value;
					var domain_uuid = document.getElementById('domain_uuid').value;
					if (username != '') {
						...
```

**Comment by markjcrane** [comment]
This was fixed by removing check_duplicates some time ago.
