### ISSUE TITLE
Reopen [ERR] mod_local_stream.c:837 Unknown source default

### ISSUE THREAD

**Issue by willempoort** [fusionpbx/fusionpbx#2389]
Sorry to re-open this issue but it really drives me nuts.
It seems that no matter what and how I do to change the value of the variable "hold_music" ,
It always result in a value of "local_stream://default"
I changed it as global var as well as at the internal SIP Profile.
I upgraded Fusion PBX to 4.3.2 and Freeswitch to 1.6.15 (64bit).
Still the same issue. Dialing *9664 results in:
EXECUTE sofia/internal/80@10.12.5.20 playback(local_stream://default)
2017-02-22 01:13:20.115816 [ERR] mod_local_stream.c:837 Unknown source default

External calls that are put on hold also get no MOH, resulting in the VoIP service provider dropping the line after 60 seconds of no sound :(

**Comment by markjcrane** [comment]
You likely upgraded freeswitch and they changed the path slightly. So verify the path with the file system.

**Comment by willempoort** [comment]
It's not about the path only. I did change the path to different values like:
/usr/share/freeswitch/sounds
/usr/share/freeswitch/sounds/music
/usr/share/freeswitch/sounds/music/default

Also made a 8000 directory with .wav files both in /usr/share/freeswitch/sounds/music and /usr/share/freeswitch/sounds/music/default

No succes.
I changed the default value in /etc/freeswitch/autoload_configs/local_stream.conf
No succes
I changed the name to /etc/freeswitch/autoload_configs/local_stream.conf.xml

How can I read the local_stream://default value from the fs_cli
It looks like somewhere it's hard coded.

This also seems the case with the hold_music variable.
In the dialplan *9664 it says:
action	playback		$${hold_music}

global_getvar		hold_music	gives: /usr/share/freeswitch/sounds/music/8000/tuttut.wav

But when dialing *9664 I see the the playback still looks like:
EXECUTE sofia/internal/80@10.12.5.20 playback(local_stream://default)
2017-02-22 10:11:01.895825 [ERR] mod_local_stream.c:837 Unknown source default

Hope this all makes it more clear where I struggle or misunderstand something ?

**Comment by willempoort** [comment]
OK, for those who don't want to spend hours on figuring out where the local_stream really is pointing to; here are the right commando's for the cli of Freeswitch 1.6 since show_local_stream is not working anymore.

local_stream show 
local_stream show default/8000

**Comment by markjcrane** [comment]
Issue reports like this give people the impression that music on hold is broken. It is not broken it is simply not configured correctly.

The path could be incorrect. FreeSWITCH package did recently change the path which broke a lot of systems using the package. They removed the 'default' directory and put the 8000, 16000, 32000, 48000 directly in the main music directory. This was an organizational mistake as the structure implies only one music on hold category will exist. That lacks vision to what it can be used for.

The permissions need to be correct.
The sample rate needs to match if it is defined.

**Comment by robfitsy** [comment]
Under Apps->Music on Hold, Click on the pencil on the right to edit the 'default', and under the next page, set sampling to default. 
`$ fs_cli -x 'local_stream show'`
`moh/48000,/usr/share/freeswitch/sounds/music/48000`
`moh/32000,/usr/share/freeswitch/sounds/music/32000`
`default,/usr/share/freeswitch/sounds/music/8000`
`moh/8000,/usr/share/freeswitch/sounds/music/8000`
`moh/16000,/usr/share/freeswitch/sounds/music/16000`

"default/8000" has now become "default" and it should all work again.
