### ISSUE TITLE
Auto Provisioning not Adding All Activated Default Settings

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2390]
Good day

I am having a problem with Auto Provisioning not Adding All Activated Default Settings.
When i check some of those settings they are set as boolean and value of true.

I think a Boolean should be set as 1 for true and 0 for False.
Could this be the problem?

**Comment by markjcrane** [comment]
Currently default settings are literal true is true and false is false. You are assuming 1 and 0 which maybe good but it is literally true = 'true' and false = 'false'.
