### ISSUE TITLE
Cisco SPA 504g Provision (Maybe others as well)

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#2395]
Small bug in {$mac}.xml of Cisco SPA504g (and maybe others SPA as well)

When you provision line keys, you should add $row.device_key_line and not $row.device_key_value to Extension_X description, current config causes every line key uses only line 1.

@@ -184,7 +184,7 @@
 {if $row.device_key_category == "line"}
 {if $row.device_key_type == "line"}
 
-<Extension_{$row.device_key_id}_ group="Phone/Line_Key_{$row.device_key_id}">{$row.device_key_value}</Extension_{$row.device_key_id}_> 
+<Extension_{$row.device_key_id}_ group="Phone/Line_Key_{$row.device_key_id}">{$row.device_key_line}</Extension_{$row.device_key_id}_> 
 <Short_Name_{$row.device_key_id}_ group="Phone/Line_Key_{$row.device_key_id}">{$row.device_key_label}</Short_Name_{$row.device_key_id}_>
 <Share_Call_Appearance_{$row.device_key_id}_ group="Phone/Line_Key_{$row.device_key_id}">{if $row.device_key_extension == "shared"}shared{else}private{/if}</Share_Call_Appearance_{$row.device_key_id}_> 
 <Extended_Function_{$row.device_key_id}_ group="Phone/Line_Key_{$row.device_key_id}"/>
@@ -656,4 +656,4 @@

**Comment by markjcrane** [comment]
Please state the version of FusionPBX you are on?
Status -> System Status

**Comment by samael33** [comment]
Branch: 4.2 
Commit: 9484da738b6be94d93c4ac3154cb776eca1663d8 
Origin: https://github.com/fusionpbx/fusionpbx.git

**Comment by markjcrane** [comment]
Just applied to with this commit to master and 4.2 branch. Will close the issue after this is applied to all SPA phones.
https://github.com/fusionpbx/fusionpbx/commit/31d8523d7fca4a40cff0c06e70658095244741cd

**Comment by Len-PGH** [comment]
cisco and linksys templates updated on 4.2 and master.  tested on spa504g

**Comment by devangn** [comment]
I am also trying to provision cisco spa504g

here is screen shot of provision config from cisco web portal
![provision1](https://cloud.githubusercontent.com/assets/11748910/25270229/7ba875c8-269d-11e7-899c-48305689fdf1.png)

and here is screen shot of device config in fusionpbx for this cisco device
![provision2](https://cloud.githubusercontent.com/assets/11748910/25270232/7f39d542-269d-11e7-8697-cd9e1159d11f.png)

I have tried tftp as well as https servers but i am not getting any hits on tftp or nginx side however if i try the url directly from browser https://my.domain/app/provision/index.php?mac=ma-c-add-re-ss
the xml config file is loading there

What could be the issue?

**Comment by markjcrane** [comment]
Yuu have to have a Certificate signed by Cisco in order to do HTTPS.
