### ISSUE TITLE
Call center queue Announcement issue

### ISSUE THREAD

**Issue by fropa** [fusionpbx/fusionpbx#2405]
I've tried new files that should resolve queue announcement problem and I've got an error:
"Fatal error: Uncaught Error: Call to undefined function switch_select_destination() in /var/www/fusionpbx/app/call_centers/call_center_queue_edit.php:829 Stack trace: #0 {main} thrown in /var/www/fusionpbx/app/call_centers/call_center_queue_edit.php on line 829
"

when I comment that line on this file error dissaperas but then i cannot save new call_center configuration.

changed files : 
app_config.php
app_languages.php
call_center_queue_edit.php
switch.php

**Comment by markjcrane** [comment]
What version of FusionPBX are you on?
Status -> System Status

**Comment by markjcrane** [comment]
If you aren't on 4.2.2+ then please upgrade test again and re-open this after the upgrade if you still have an issue.
