### ISSUE TITLE
Cannot Login to Web Interface

### ISSUE THREAD

**Issue by bothwellw** [fusionpbx/fusionpbx#2406]
Hi

I have install fusionPBX on Debian 8.

I try to login with the admin account that is shown at the end of the install but I keep getting
invalid username and password.

I have tried with FireFox and Chromium

thanks
Bothwell

**Comment by Len-PGH** [comment]
Are you logging in with admin@x.x.x.x

**Comment by bothwellw** [comment]
i am using admin only

just tried with admin@10.0.0.4 

no luck yet

**Comment by Len-PGH** [comment]
Need more info.  What OS and device did you install on?

**Comment by bothwellw** [comment]
root@Debian:/home/bothwell# uname -r
3.16.0-4-amd64

root@Debian:/home/bothwell# lsb_release -da
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 8.7 (jessie)
Release: 8.7
Codename:jessie

root@Debian:/home/bothwell# php --version
PHP 7.0.16-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Len-PGH** [comment]
I just ran the install script on vultr and was able to login. What are you installing on hardware/VM wise?

**Comment by bothwellw** [comment]
Sure thanks, I installed on windows azure , and also on Oracle virtual machine

**Comment by bothwellw** [comment]
Sure thanks, I installed on windows azure , and also on Oracle virtual machine with Windows 8.1 host

**Comment by rmakings** [comment]
If you have a FQDN configured, you must login with that.  i.e. if the hostname is abc.local then login with admin@abc.local

**Comment by bothwellw** [comment]
I started from scratch and its working now.

many thanks for your time
