### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by drenda** [fusionpbx/fusionpbx#2412]
Hi,
from few days the upgrade inside fusion pbx doens't work anymore with this error:

`error: Your local changes to the following files would be overwritten by merge:
	secure/fax_to_email.php
Please, commit your changes or stash them before you can merge.
Aborting
Updating 4aea00b..33bdd90`

Thanks

**Comment by markjcrane** [comment]
Git thinks there was a local change to fax_to_email.php.

cd /var/www/fusionpbx
git stash

Will dump the change if there was one. Then upgrade in the web browser will work again.

**Comment by drenda** [comment]
works thanks!
