### ISSUE TITLE
Domain select trunctated in SQL statement

### ISSUE THREAD

**Issue by captnbli** [fusionpbx/fusionpbx#2413]
I have a domain defined as 192.168.2.2. Tracing the SQL statement when a device tries to register, the lookup is:

`SELECT domain_uuid FROM v_domains WHERE domain_name = '192.168.2.'`

So, the name is being truncated! Help, this is a major problem!

**Comment by moteus** [comment]
Need more information.
What version of Fusion you use.
When this happens. There few places where Fusion may invoke such query.

**Comment by markjcrane** [comment]
How did you install fusionpbx? 
Please be specific with a link.
What operating system?

**Comment by captnbli** [comment]
Thanks for your help. Sorry, but I had inadvertently changed the ip on the phone.

**Comment by markjcrane** [comment]
No reports of truncated domain so figured it was an accident by someone.
