### ISSUE TITLE
CDR Statistics

### ISSUE THREAD

**Issue by dmonty2** [fusionpbx/fusionpbx#2427]
When doing a CDR Statistics search the "Minutes" column is always the same for inbound or outbound.  

https://github.com/fusionpbx/fusionpbx/blob/master/app/xml_cdr/xml_cdr_statistics_inc.php
The calls to get_call_seconds_between had an empty where clause argument.

$stats[$i]['seconds'] = get_call_seconds_between($stats[$i]['start_epoch'], $stats[$i]['stop_epoch'], '');

Changing the calls to this fixes the Minutes column:

$stats[$i]['seconds'] = get_call_seconds_between($stats[$i]['start_epoch'], $stats[$i]['stop_epoch'], $sql_where);

**Comment by markjcrane** [comment]
It fixed thanks for reporting it.
