### ISSUE TITLE
Provision Bug-clicking on specific device in registration tab for provision,unregister or reboot provisions all other phones associated with that extension

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2435]
Under registrations sections, the provision for a specific account/extension provisions all other phones associated with that extension instead provisioning only that specific device with that extension. Is this a bug ?

**Comment by markjcrane** [comment]
This is not a bug you are telling it to provision a device but you don't realize that the command is associated to the sip user that the device is using. So all phones using that extension will re-provision as expected.
