### ISSUE TITLE
Extensions for second domain

### ISSUE THREAD

**Issue by wrestler07** [fusionpbx/fusionpbx#2446]
How to create the second and subsequent domains and register them extensions? Do you need to create postgesql for this and how?

**Comment by DigiDaz** [comment]
Have you even bothered to look at any of the docs??

http://docs.fusionpbx.com/en/latest/advanced/domains.html

**Comment by wrestler07** [comment]
Of course..I'm created domain Newdomain.com..then in this domain created new extensions 101. Then in zoiper I'm register: server : ip address. Account: 101@newdomain.com.. and password..not registered

**Comment by DigiDaz** [comment]
Your problem is server : ip address, you need server: newdomain.com

**Comment by wrestler07** [comment]
I have default domain 109.200.35.xxx . Zoiper settings: 
Server: 109.200.35.xxx
Accaunt: 101
Password: 101
Extensions are registered..
I'm create new domain Newdomain.com. and create new extensions
Zoiper settings:
Server: 109.200.35.xxx
Accaunt: 101@newdomain.com
Password: 101
Not registered

**Comment by DigiDaz** [comment]
Server: newdomain.com
Accaunt: 101
Password: 101
Extensions are registered..
I'm create new domain Newdomain.com. and create new extensions
Zoiper settings:
Server: 109.200.35.xxx
Accaunt: 101@newdomain.com
Password: 101
Not registered

**Comment by DigiDaz** [comment]
Server: newdomain.com <<-------------------------- NOT IP address

**Comment by markjcrane** [comment]
Even better sub.domain.com
Examples using fusionpbx.com as the primary domain make sure to substitute with your domain name.

- voip.fusionpbx.com
- pbx.fusionpbx.com
- rpi.fusionpbx.com
- blue.fusionpbx.com
- green.fusionpbx.com

You add the domains in the Menu with Advanced -> Domains. Then you select the domain you want and add your extension to that domain with Accounts -> Extensions. You then setup your phone to register to the extension in the domain you selected.

**Comment by markjcrane** [comment]
Resources that can help you get started.

- http://docs.fusionpbx.com
- https://youtube.com/fusionpbx
- https://youtu.be/kejAxlYSW3o
