### ISSUE TITLE
Music on Hold - not working on all extensions ?

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#2457]
some works , some dont not sure if is a setting i need to do or bug

![nocroom pbx](https://cloud.githubusercontent.com/assets/22685867/24370880/d877ad74-12dd-11e7-9083-0f448f77c3ec.png)

**Comment by markjcrane** [comment]
You set this to 16khz if some phones are using 8khz then it won't work edit the default group and set it to sampling: default restart mod local stream or freeswitch then it will work for any rate but it will transcode it if the rate is wrong.
