### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by tonyhain** [fusionpbx/fusionpbx#2469]
I pulled down a pdf and later the html zip blob, and both times the 'register_phones' page was missing. The only reason I even noticed was during a search I tripped over that page :
http://fusionpbx-docs.readthedocs.io/en/latest/getting_started/register_phones.html
and after verifying it was not in either the pdf or html, I looked at the git source which shows it should have been included. It is also missing from docs.fusionpbx.com, and there may be other pages missing from the compiled set. I have not looked.

**Comment by markjcrane** [comment]
Maybe that page is not linked from one of the other pages.

**Comment by Len-PGH** [comment]
that section was moved to the provision section and is why it didn't build into the pdf and html zip
http://docs.fusionpbx.com/en/latest/applications/provision/provision_manual_grandstream.html
http://docs.fusionpbx.com/en/latest/applications/provision/provision_manual_zoiper.html
