### ISSUE TITLE
centos install script lacks error checking

### ISSUE THREAD

**Issue by tonyhain** [fusionpbx/fusionpbx#2470]
the centos install script fails to verify that anything actually completed correctly. it just asserts that everything finished. The centos script installs irontec.repo, which appears to be hosted at OVH. Due to frequent & widespread attacks from OVH networks, many of their /16's are hard filtered at the firewall.  The install script claimed all went well despite the repo timing out on just about everything. The only way to get the script to complete without timeouts or errors was to put in a 1 minute cron to keep deleting that repo entry which kept getting overwritten every time the script was restarted. While that repo itself may work at other locations, the fact that the script didn't recognize that nothing was actually installing is a problem.

**Comment by DigiDaz** [comment]
Which install script are you using?

**Comment by markjcrane** [comment]
The right place to report this problem would be the fusionpbx-install.sh repo if the install came script came from there. CentOS install is new and I have not tested it and consider it not production ready yet.
 
https://github.com/fusionpbx/fusionpbx-install.sh/issues

**Comment by markjcrane** [comment]
The CentOS script was based on the Debian script that I wrote but modified by another developer for CentOS. I moved the irontec repo into a new script called sngrep.sh which is not called by default but provides an easy way to run it for those interested.
