### ISSUE TITLE
missing operator panel app menu in fr-fr language

### ISSUE THREAD

**Issue by unbornx** [fusionpbx/fusionpbx#2478]
select * from v_menu_languages where menu_item_title like '%Panel%' ; yield only pl, sv-se, de-at and en-us. So if a user have fr-fr language, the menu dont show up.
I manually added it and it works.

**Comment by markjcrane** [comment]
Please share a translation for fr-fr so it can be fixed

**Comment by unbornx** [comment]
i'd say "Panneau Operateur"

**Comment by markjcrane** [comment]
I just added this to the menu for both stable and master branches thanks for pointing it out. Have any other issues with other menus please let me know.
