### ISSUE TITLE
Park slot issue after 2 beeps on hold using Yealink T48G - possible bug

### ISSUE THREAD

**Issue by ledzpm** [fusionpbx/fusionpbx#2479]
I have a Yealink T48G and when i retrieve a parked call from park+*5901, and lets say i put the call on hold then my yealink phone will beep after an amount of time reminding me i have a call on hold so I am able to hit resume after the first beep no problem. If I place it back on hold and let it beep 2 times and hit resume i cant hear the other caller and the other caller still hears the hold music. During this state i am not hearing the other caller I am able to transfer the call back to the park slot and resume it successfully. I have tested this over and over and can reproduce it. 

Some information the way i use the park slot on my device setting for the yealink T48 I have the key setup as Category: Line Yealink: BLF Value: park+*5901

Now I did test having an inbound call go directly to my extension and if I place on hold and let it beep many times I have no issue. Seems to be only issue with park slot.

System information:
Version 4.2.2
Branch 4.2
Switch Version: 1.6.13 (64bit)
Operating System: Linux fusionpbx 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by ledzpm** [comment]
Did some further testing but with a Polycom VVX 410 using the software version 5.x, I am able to pick up a call from the parked slot and place it on hold for several minutes and resume with no issue. This issue seems to be only Yealink so far.

The Yealink software firmware I have running is 	35.81.0.15

**Comment by ledzpm** [comment]
Upgraded the Yealink firmware to 	35.81.0.70 but issue still remains. Tested the Polycom again but longer over 4 minutes and resumes successfully still.

The Polycom button is set for Category: Line , Polycom: Automata , Value: park+*5901

**Comment by ledzpm** [comment]
The work around the users use for now is instead of placing the parked call on hold they transfer it back to the parked slot button.

**Comment by DigiDaz** [comment]
Any way you can get sip traces of both of these, ie the good and the bad.

**Comment by ledzpm** [comment]
[bad.txt](https://github.com/fusionpbx/fusionpbx/files/905617/bad.txt)

**Comment by ledzpm** [comment]
[good.txt](https://github.com/fusionpbx/fusionpbx/files/905621/good.txt)

**Comment by ledzpm** [comment]
for the sip trace 
inbound call goes to extension 7122 and that phone parks the call on park+*5901, then extension 7106 picks up the call and places the call on hold. After my phone beeps two times and I hit the resume button I hear nothing and on the end of the call I still hear hold music. After that i hungup and stopped the trace and saved the output as bad.txt

**Comment by ledzpm** [comment]
for the sip trace good.txt
inbound call goes to extension 7122 and that phone parks the call on park+*5901, then extension 7106 picks up the call and places the call on hold. After my phone beeps one time and I hit the resume button I successfully resume the call and end the trace and save it as good.txt

**Comment by ledzpm** [comment]
for the sip trace I used "sofia global siptrace on "

**Comment by ledzpm** [comment]
Well I did further testing and followed the Fusionpbx docs 
http://fusionpbx-docs.readthedocs.io/en/latest/features/parking.html?highlight=park

For the Yealink I changed the button from BLF to "Call Park" and this is working perfectly now. Just wish the button would light up red when a call park is active, instead the green light goes out. This is working now back in business!

**Comment by markjcrane** [comment]
"Call Park" does light up red when you use the default valet park. Are you using park+*5901 on the call park key?

**Comment by ledzpm** [comment]
Not for me, below is a screenshot of the configuration of the button and 
a picture of a the park line un-used and another in use



Devin Culp
Senior Network Manager
Creative Network Innovations
321-259-1984

**Comment by markjcrane** [comment]
Could be a NAT related problem preventing the message reaching you.

**Comment by ledzpm** [comment]
I think your right because I enabled stun and it is red now

Devin Culp
Senior Network Manager
Creative Network Innovations
321-259-1984
