### ISSUE TITLE
Call forward loop segfaults freeswitch

### ISSUE THREAD

**Issue by lcx** [fusionpbx/fusionpbx#2481]
All of a sudden freeswitch started segfaulting today. 
I am still running FS version 1.4.19 and Fusion 3.8. 
My customer set a call forward from extension 10 to extension 16 and from extension 16 to extension 10. 
If someone calls either extension, freeswitch segfaults. 
I could find something regarding max_forwards ( https://www.mail-archive.com/freeswitch-users@lists.freeswitch.org/msg17397.html ) although I'm not sure if this would help. 
Also detecting a loop in fusion would also not really help, as in this case the CF is also present on the phone. Removing the CF from fusion does not solve the problem.

**Comment by markjcrane** [comment]
Maybe the segfaulting is telling you to upgrade. FusionPBX 3.8 has a serious security problem and you are risking your customer. Open your issue if you upgrade to latest FreeSWITCH and latest FusionPBX releases and still have the problem.

**Comment by lcx** [comment]
installed a new testsystem from master some weeks ago (version 4.2.2) 
set up 2 extensions, 6000 and 6001. 
Each has a call forward to the other 6000 -> 6001 -> 6000
Call one of the extensions and freeswitch segfaults. 

```
[2530312.557827] freeswitch[11036]: segfault at 7fd134133ff8 ip 00007fd16066f5f4 sp 00007fd134133ff0 error 6 in liblua5.2.so.0.0.0[7fd16065e000+31000]
```

I don't think it's a fusionpbx issue, rather a freeswitch issue but it has to be somehow addressed. 
Since this just happened again since one of my customers does this several times and forgets about it but if they receive a call on one of those extensions it kills my fusionpbx. 
Although the upgrade needs to happen soon, this won't fix this issue.
