### ISSUE TITLE
domain delete still not working

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#2489]
Hi Marc,

I see this is still not working on the latest commit.

I suspect it is not getting the id when parsed

//get the id
        if (count($_GET)>0) {
                $id = check_str($_GET["id"]);
        }

**Comment by markjcrane** [comment]
Which version?

**Comment by andycol** [comment]
4.3 master branch

**Comment by markjcrane** [comment]
It's nothing to do with the GET and $id. I'll look at it as time permits.

**Comment by andycol** [comment]
I have compared the code to 5.2 and its the same.
Any idea why this is broken?
Nginx logs show no errors either

**Comment by andycol** [comment]
Sorry 4.2

**Comment by markjcrane** [comment]
Fixed in the master branch.

**Comment by markjcrane** [comment]
Installed 4.2 added two domains and then deleted them and they worked fine. And 10 hours ago I fixed the problem that prevented the delete transaction from finishing in that Master branch currently 4.3.2.

Still have problems with it contact official support so I can remote in and take a look at it.
