### ISSUE TITLE
lets encrypt

### ISSUE THREAD

**Issue by zilasb** [fusionpbx/fusionpbx#2497]
Fresh new install. Tried to install certificated. Followed instructions on : http://fusionpbx-docs.readthedocs.io/en/latest/getting_started/lets_encrypt.html

Now when try to access sub1.xxx.com getting error 502 Bad Gateway
Error is in /etc/nginx/includes/fusionpbx-default-config (if I comment this file page loads with SSL error).

error.log:

2017/04/11 18:26:32 [error] 1753#1753: *3 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 50.167.161.201, server: sub1.xxx.com, request: "GET /favicon.ico HTTP/1.1", host: "sub1.xxx.com", referrer: "https://sub1.xxx.com/"
2017/04/11 18:28:52 [crit] 1781#1781: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 50.167.161.201, server: sub1.xxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "sub1.xxx.com"

**Comment by markjcrane** [comment]
Yes sorry they just changed their script and we will have to change ours to accommodate for the changes.

**Comment by zilasb** [comment]
NP. I figured it be the case. Can you please drop a note when you will have updated instructions in wiki so i can try. Thanks!

**Comment by Len-PGH** [comment]
try this:
edit  /etc/apt/sources.list
add   deb http://ftp.debian.org/debian jessie-backports main
  apt-get update && apt-get upgrade
  apt-get install certbot -t jessie-backports

then try again

**Comment by markjcrane** [comment]
The script has been updated and is working again.

**Comment by louisyssel** [comment]
I just tried a clean install on clean and new Debian 9 VM, and tried the above, still getting Bad Gateway.

**Comment by louisyssel** [comment]
I just tries the same on a new clean VM on Ubuntu 16.04, and I still get the same error message.
502 Bad Gateway nginx/1.10.0 (Ubuntu).

Please assist.

**Comment by mafoo** [comment]
Freeswitch is currently unsupported on Debian 9, you have to use Debian 8, or wait for 1.8 to be released

**Comment by markjcrane** [comment]
Debian 8 is officially supported Debian 9 was released very recently and need more time to support it.
