### ISSUE TITLE
Update ldap.php - Broke AD LDAP

### ISSUE THREAD

**Issue by flyer292** [fusionpbx/fusionpbx#2498]
The change that was done to remove break; and add exit; made login display a blank page when using LDAP AD authentication.
I put this back on my server and login for AD users works fine now

**Comment by markjcrane** [comment]
'break' is not allowed in PHP 7 or higher so it had to be replaced or removed I will take a look at the code and see if there is a better option to exit.

**Comment by markjcrane** [comment]
Its fixed thanks for reporting the issue.
