### ISSUE TITLE
IVR-Direct dial-bug

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2505]
Under IVR Menu, when direct dial is enabled it doesn't pops up additional field in restricting what numbers that can be directly dialed. That being said, when I try to dial the registered extension it says that was an invalid entry.

Fusionpbx-version-4.3.0

Does anyone else facing the same issue?

**Comment by markjcrane** [comment]
Currently no reason to do a popup on what is allowed to be dialed because all that is allowed to be dialed is what is defined  in the IVR Menu options and direct dial is only for valid extensions defined in acccounts -> extensions.
