### ISSUE TITLE
Yealink W56P template

### ISSUE THREAD

**Issue by rajil** [fusionpbx/fusionpbx#2507]
Please add the template for W56P phone. It shares the same base as W52P.

**Comment by markjcrane** [comment]
Can you please look at your nginx logs and see the exact name of the y00000* file that w56p requests when it tries to provision. /var/log/nginx/error.log or access.log. This is needed to make the template.

**Comment by Len-PGH** [comment]
Got W56P added to 4.2 and master. Please update and see if they work please.
