### ISSUE TITLE
cdr page needs reload button

### ISSUE THREAD

**Issue by tonyhain** [fusionpbx/fusionpbx#2536]
the cdr page  ~/app/xml_cdr/xml_cdr.php  lacks a reload button like the log page has. A ~better~ option might be a checkbox for auto-refresh at interval ... but that would require more coding than a cut-n-paste from another page.

**Comment by markjcrane** [comment]
Added the refresh button auto-refresh would extra load on the server. Better for the user to choose when to refresh the content.
