### ISSUE TITLE
Can not create alfanumeric extensions in 4.3

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#2539]
Note: numeric extension creation works

Just put an alfanumeric field, it won't add. I will look for this bug later, but in case someone fix it before.

**Comment by markjcrane** [comment]
I just tested this on latest 4.3.x and it works fine on PostgresSQL.

**Comment by markjcrane** [comment]
This is likely a bug on your unofficial version of FusionPBX.

**Comment by moteus** [comment]
https://github.com/fusionpbx/fusionpbx/pull/2508

**Comment by daniel-lucio** [comment]
I don't know how you assume with such a short text that it is my **"unofficial version"**, I never fork; I always use tarballs from here. My **"unofficial" installation method** runs under Centos, it only works with stable releases (aka 4.0 and 4.2).

This deployment was done from one of your attendees to your course. I still don't know why you encourage people to use **DEVEL branch** (aka 4.3 at this point) if it has that many bugs. It results that the installation was done before @moteus send the pull request.

**Comment by markjcrane** [comment]
Why did I assume because you just announced that version yesterday. I also know from experience eorking with. Last wwe talked to me about another thing that was fixed remember ldap.
