### ISSUE TITLE
Ring group destinations doesn't have add row

### ISSUE THREAD

**Issue by sergey-mz** [fusionpbx/fusionpbx#2540]
New ring group doesn't have empty row to add destination extension.
It's impossible to add destination.
Same when edit existing group.
![image](https://cloud.githubusercontent.com/assets/13353200/25442927/5a29df2e-2a74-11e7-9032-f33c18f0c66a.png)

Version 4.3.2 . Pulled updates this morning.

**Comment by Len-PGH** [comment]
try this.
advanced > upgrade and check box schema Schema then click execute

**Comment by sergey-mz** [comment]
I did it right after I pulled updates.
BTW: It didn't work before I pulled updates either.

**Comment by sergey-mz** [comment]
Line 413  of ring_group_edit.php
`$rows = $_SESSION['ring_group']['destination_edit_rows']['numeric'];`
returns empty value so it can't  add empty row.
If I add line below
`if ($rows == "") {$rows=1;}`
then it works.

**Comment by markjcrane** [comment]
This setting was added by default a while back. So you updated your source code but failed to do the proper steps to upgrade FusionPBX. You must run Advanced -> Upgrade -> App defaults after updating the source code and then hit the reload button or logout and back in.
