### ISSUE TITLE
Unable to load Freeswitch on Debian 8 / virtuozzo

### ISSUE THREAD

**Issue by nguyenquangtoan** [fusionpbx/fusionpbx#2545]
Hi
I ve not received any email reply (sent twice) on a paid support on this issue: Unable to load Freeswitch on Debian 8 / virtuozzo
Please advise what is a working contact channel, outside of email, for this case
Thanks

**Comment by markjcrane** [comment]
You are welcome to call the support number. +1 208 906 8227

**Comment by markjcrane** [comment]
Not enough details here to track down your email. So either email again support@fusionpbx.com.
