### ISSUE TITLE
Missing $ in line 66 of user_edit.php

### ISSUE THREAD

**Issue by arthurd123** [fusionpbx/fusionpbx#2554]
I was getting http 500 error for user_edit.php with the new code in line 66:
messages::add(text['message-maximum_users'].' '.$_SESSION['limit']['users']['numeric'], 'negative');

I added a $ before "text" and that fixed it: 
messages::add($text['message-maximum_users'].' '.$_SESSION['limit']['users']['numeric'], 'negative');

**Comment by markjcrane** [comment]
Thanks for reporting this it has been fixed.
