### ISSUE TITLE
call detail: status cancelled

### ISSUE THREAD

**Issue by MrCoolLV** [fusionpbx/fusionpbx#2555]
what does that mean ?

thanks
![2017 05 02 png 1163x707](https://cloud.githubusercontent.com/assets/22685867/25626736/51890afc-2f15-11e7-94fc-31b7ac69617d.png)

**Comment by andycol** [comment]
means the person hungup the call before it connected to the external party
eg: i dial 12345 from my extension and i hangup before it rings

**Comment by MrCoolLV** [comment]
thank you
