### ISSUE TITLE
How can I change default  port 5060?

### ISSUE THREAD

**Issue by hackerspk** [fusionpbx/fusionpbx#2558]
Hello everyone. I just installed fusionpbx. Port 5060 is blocked in my area. Is there anyway to change it? What I have tried is:

Changed it in vars.xml
1. `<X-PRE-PROCESS cmd="set" data="internal_sip_port=5060" />`
2. Rebooted the server..
3. Restarted the internal profile.

It did not work.
Any help please.

**Comment by tonyhain** [comment]
I haven't actually changed them, but on .../app/vars/vars.php toward the bottom are the sip profiles for internal and external ports. 5080 is the default external port, so you may not need to change anything if that is open.

**Comment by hackerspk** [comment]
Thank for your reply tnoyhain. The hole 50xx series is blocked actually. Therefore, I must have change it. Still no luck.

**Comment by markjcrane** [comment]
Change it to any valid port likely about 40,0000. You can change it in advanced -> variables or from Advanced -> SIP Profiles.
