### ISSUE TITLE
active conferences not working on latest commit

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#2559]
Below images show 2 calls in the coference but nothing when you click it live

![image](https://cloud.githubusercontent.com/assets/13945173/25699831/2bff6cd4-30c5-11e7-8faa-e48f15dee5fd.png)

![image](https://cloud.githubusercontent.com/assets/13945173/25699840/3831b502-30c5-11e7-9e64-a32da0b98baf.png)

**Comment by andycol** [comment]
fix is to add  $conference_name = substr($name, 0, strlen($name) - strlen('-'.$_SESSION['domain_name']));
in conferences_active_inc.php and 
$conference_name = $conference_uuid.'-'.$_SESSION['domain_name']; in 
in conference_interactive_inc.php

change the @ to a -

**Comment by andycol** [comment]
fix in pull request https://github.com/fusionpbx/fusionpbx/pull/2562

**Comment by markjcrane** [comment]
This fix is based on ignorance. You don't know why we changed from - to @.  And you so called fix is changing it back to what it was.

**Comment by markjcrane** [comment]
I'm testing now to see if this is actually a problem without the fix.

**Comment by andycol** [comment]
A fix is a fix but if you find a better way then thats fine. Maybe you can explain why it was changed to a @?

**Comment by markjcrane** [comment]
I believe all you needed to do to fix the problem that you originally reported is re-save the conference which would update the dialplan.

**Comment by markjcrane** [comment]
The fix was a retreat back to the older way of doing it because the developer that made the change had no idea why it was changed.

**Comment by andycol** [comment]
Ps. Not based on ignorance just trying to help others with the same issue i had.

**Comment by markjcrane** [comment]
The real fix would be making it use the @ successfully.

**Comment by markjcrane** [comment]
But I don't think it was broken. More likely you didn't know that you needed to re-save your conference to get an updated dialplan.

**Comment by markjcrane** [comment]
If bumping into this problem with Apps -> Conference re-save your conference room and it should update the dialplan and work.
