### ISSUE TITLE
queues  FIFO

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2568]
version master
Admin user add FIFO Queues,  but does not add an internal queue extensions number
<img width="1183" alt="2017-05-09 17 37 44" src="https://cloud.githubusercontent.com/assets/15113513/25856307/4bc7da52-34de-11e7-8adf-ea32f2f42b7f.png">

<img width="1201" alt="2017-05-09 17 34 26" src="https://cloud.githubusercontent.com/assets/15113513/25856188/f06c1db2-34dd-11e7-815d-f78fc026d00a.png">

**Comment by manchelsi** [comment]
use call center?

**Comment by markjcrane** [comment]
Right now the answer is yes Call Center is preferred. Call Center has more intuitive terminology and has had better documentation for longer so attention has gone in that direction. 

In the future will add more features for the FIfo Queues web interface.
