### ISSUE TITLE
Grandstream templates, no need of all models

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#2577]
I have found that Granstream 21XX applies for all phones. I have here a 2135 and 2170. The only difference is one is a super-set of the other. Phone will ignore P codes that won't apply

I suggest move them into a single template called 21XX.

**Comment by markjcrane** [comment]
The move would break all phones currently assigned to more specific templates. Would like to have many people using grandstream respond on this change.

**Comment by daniel-lucio** [comment]
Remember it is 4.3. It is DEVEL

**Comment by markjcrane** [comment]
I don't need a reminder. Its the Master branch meant for development.

**Comment by markjcrane** [comment]
In reality the 21xx is kind of old template compared to some of the others.

**Comment by bigfishvoice** [comment]
Instead of changing the 21XX, can't we just add two new templates 2135 & 2170?  Changing the 21XX would break the 2130 & 2160 models that have many more features (physical speed dial keys to name one) than the 2135 & 2170.  I would had to have to have a single template for every model, but don't want to try cramming a bunch of unnecessary stuff in to a template.

**Comment by daniel-lucio** [comment]
@markjcrane , 21XX is the generic name to call them all. Even granstream in the http://www.grandstream.com/support/tools website does not give a template for each model. they give a 21xx example.

Using a generic template won't break, the phone will ignore P tags that are irrelevant to it. You just need to reassign the template to each device. Which it won't be a big issue since provisioning in granstream by default re-pulls the information until it is rebooted. I have found as well that if the phone has data, and provisioning is invalid or missing (let's say, you have a value in PXX tag, and provisioning HTTP payload doesn't provide PXX) the phone will keep its working value.  So, this will prevent a major break. You will only need to reboot the phone after you change the name.

Making a template for each model makes the development harder.

BTW, 2135 and 2170 has physical speed dials as well. 2170 has more. So, I don't see @bigfishvoice argument valid unless he discovers a phone limitation size or a bug on the phones.

**Comment by markjcrane** [comment]
http://www.grandstream.com/support/tools
About halfway down the page you find this 'Configuration Template'
Here is the link it goes to http://www.grandstream.com/sites/default/files/Resources/config-template.zip

Unzip the file and we you will see the following.
dp715_config_1.0.0.33.txt
dp750_config_1.0.3.23.txt
gac2500_config_1.0.3.11.txt
gac2500_config_1.0.3.13.txt
gvc320x_config_1.0.3.24.txt
gvc320x_config_1.0.3.30.txt
gxp110x_config_1.0.8.6.txt
gxp116x_config_1.0.8.9.txt
gxp140x_config_1.0.8.9.txt
gxp1450_config_1.0.8.9.txt
gxp16xx_config_1.0.4.56.txt
gxp16xx_config_1.0.4.57.txt
gxp17xx_config_1.0.0.48.txt
gxp17xx_config_1.0.1.8.txt
gxp2124_config_1.0.8.6.txt
gxp2130_40_60_70_35_config_1.0.7.99.txt
gxp2130_40_60_70_35_config_1.0.8.47.txt
gxp21xx_config_1.0.8.6.txt
gxp2200_config_1.0.3.27.txt
gxp_config_1.2.5.3.txt
gxv300x_config_1.2.3.7.txt
gxv3140_config_1.0.7.80.txt
gxv3175_config_1.0.3.76.txt
gxv3175v2_config_1.0.1.55.txt
gxv3240_config_1.0.3.162.txt
gxv3240_config_1.0.3.171.txt
gxv3275_config_1.0.3.162.txt
gxv3275_config_1.0.3.171.txt
gxw40xx_config_1.0.15.5.txt
gxw410x_config_1.4.1.5.txt
gxw42xx_config_1.0.5.16.txt
ht503_config_1.0.15.5.txt
ht701_ht702_config_1.0.8.2.txt
ht704_config_1.0.8.2.txt
ht80x_config_1.0.3.2.txt
ht81x_config_1.0.3.2.txt
htx86_config_1.1.0.45.txt

**Comment by markjcrane** [comment]
From this list you will see that there is a template gxp2130_40_60_70_35 meant for gxp2130, gxp2140, gxp2160, gxp2170, and gxp2135. Logic tells us that there must be a reason that they didn't just use the gxp21xx template.

**Comment by bigfishvoice** [comment]
Sounds logical to me.

**Comment by markjcrane** [comment]
I believe the correct way is to follow closely follow what Grandstream has provided in their config-template.zip file. With option of these being broken down further for customer readability gxp2130_40_60_70_35.

**Comment by markjcrane** [comment]
If grandstream releases templates where they start to condense the models further then we definitely want to follow that if they were to do it in the future.
