### ISSUE TITLE
Content type set to text/plain when emails go to sendmail 

### ISSUE THREAD

**Issue by powerpbx** [fusionpbx/fusionpbx#2578]
When freeswitch mailer-app is set to `sendmail` in `/etc/freeswitch/autoload_configs/switch.conf.xml`, the formatting of the received email is wrong.  Content type is set to `text/plain` instead of `text/html` so the mail client shows raw html.

**Comment by powerpbx** [comment]
I found a workaround to just use sendmail.  Probably not an ideal universal fix.  As far as I can tell, in the absense of a content type statement, sendmail adds in `text/plain` which would be incorrect.

So I added the content type to the template.
`/usr/share/freeswitch/scripts/app/voicemail/resources/templates/en/us/email_body.tpl`

Content-Type: text/html
${newline}
${newline}
<html>

`/usr/share/freeswitch/scripts/app/voicemail/resources/functions/send_email.lua`

At line 199
```
body = body:gsub("\n", "");
body = body:gsub("${newline}", "\n");
body = trim(body);
```

**Comment by powerpbx** [comment]
I eventually figured out that this can be done in FusionPBX GUI by changing method to `sendmail`.

**Comment by lamixer** [comment]
Thanks for posting this, powerpbx! I FINALLY got email working only to find that fusionpbx was sending out html email and calling it plain text, resulting in something very foul to look at. Your fix of changing the method to sendmail in the default settings didn't work for me (maybe I did it wrong), but modifying the files as you instructed worked a charm.

So thanks again.

**Comment by markjcrane** [comment]
Send mail is the preferred method but it takes a bit of work to configure to relay.
