### ISSUE TITLE
Not possible to edit Dialplan - Outbound Routes

### ISSUE THREAD

**Issue by mfrlinux** [fusionpbx/fusionpbx#2601]
Is can add, but in editing the interface does not show the options to edit the routes that have been added.
Don't show options such as: Gateway, Dialplan Expression, Prefix, Enabled....
What is shown is options is include general settings to Dialplan and not outbound route settings.

**Comment by markjcrane** [comment]
Are you logged in as a user in the admin group or in the superadmin group? From your description it sounds like you only have admin level access.

**Comment by markjcrane** [comment]
A screen shot to show what you are trying to describe?

**Comment by mfrlinux** [comment]
I think it's a permission problem.
Follow the nginx log:
<code>
 [crit] 19587#0: *183 open() "/var/lib/nginx/tmp/fastcgi/3/01/0000000013" failed (13: Permission denied) while reading upstream, client: 10.10.10.61, server: fusionpbx, request: "GET /app/dialplan/dialplan_edit.php?id=5706b509-0f92-4594-91cb-f30c0177f0ed&app_uuid=8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "177.125.96.141", referrer: "https://177.125.96.141/app/dialplan/dialplans.php?app_uuid=8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3"

[error] 19587#0: *225 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/var/lib/php/session/sess_i474n6dbfa8pf704t6m85lc9n7, O_RDWR) failed: Permission denied (13) in /var/www/fusionpbx/login.php on line 30" while reading response header from upstream, client: 10.10.10.61, server: fusionpbx, request: "GET /login.php?path=%2Fapp%2Fdialplan%2Fdialplan_edit.php%3Fid%3D5706b509-0f92-4594-91cb-f30c0177f0ed%26app_uuid%3D8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "177.125.96.141", referrer: "https://177.125.96.141/login.php?path=%2Fapp%2Fdialplan%2Fdialplan_edit.php%3Fid%3D5706b509-0f92-4594-91cb-f30c0177f0ed%26app_uuid%3D8c914ec3-9fc0-8ab5-4cda-6c9288bdc9a3"
</code>
I "opened the legs" /var/lib/nginx and /var/lib/php/session/ directories with chmod 777 and it worked.
Maybe the problem is in script, i using CentOS 7 
centos/resources/php.sh -> line 31 in #update permissions.

**Comment by markjcrane** [comment]
User reported its fixed with "and it worked."
