### ISSUE TITLE
One day missing on the Thanksgiving preset mday range

### ISSUE THREAD

**Issue by nostikj** [fusionpbx/fusionpbx#2603]
It seems that that preset for Thanksgiving, wday 5-6, mday 22-28 will not cover Fri, Nov. 29, 2019.
No obvious fix, other than an additional condition entry.

**Comment by markjcrane** [comment]
Maybe extend mday to 22-29.

**Comment by markjcrane** [comment]
I checked a couple more websites including this one.
 https://www.calendar-12.com/holidays/thanksgiving/2019

Thanksgiving for the United States is always on a Thursday.
