### ISSUE TITLE
Issues with Follow me   Parse error........: on line 439

### ISSUE THREAD

**Issue by ruslanguns** [fusionpbx/fusionpbx#2604]
Dear colleagues,

I am expecting an issue when trying to forward the calls of an extension with Call routing.

**Getting that message after setting up a call forward rule :** 

> Parse error: syntax error, unexpected '$dial_string' (T_VARIABLE), expecting function (T_FUNCTION) in /var/www/fusionpbx/app/calls/resources/classes/follow_me.php on line 439

I checked the file in order to see if there's any issue with the variables, and I found that:

`Line 439:          $dial_string = str_replace(",]", "]", $dial_string);`

Please let me know if you guys know what should I do in that case to fix this module. 

RuslanGuns

**Comment by markjcrane** [comment]
Thanks for reporting this it has been fixed.
