### ISSUE TITLE
Logout botton does not appear since translation missing

### ISSUE THREAD

**Issue by ruslanguns** [fusionpbx/fusionpbx#2608]
Hi everybody,

Looks like if the language is switched to Spanish the LOGOUT bottom does not appear in the sub-menu under Home Menu option...

Look at the sampe, click to view:

>    [English language]( https://goo.gl/ng0HZS) Screenshot 1

>   [Spanish language](https://goo.gl/85rdjC) Screenshot 2

If you see at the screenshots looks like the Logout is missing however it's not a matter of permissions, is a matter of Language since I confirmed it trying modifying the URL:

> "https://my_Great_FusionPbx_URL/logout.php"
and works by adding /**logout.php**...

Thanks in advance!

**Comment by markjcrane** [comment]
It was missing the translation please update and try again. You didn't supply a translation so its now likely saying Logout in English.

**Comment by markjcrane** [comment]
Please provide the translation if you want it added.

**Comment by mafoo** [comment]
A fix for this issue has been done in master and 4.2 that will use the English text when the current text is empty, however as mcrane pointed out if you have words wrong it really helps us if you can provide the translations. If you want help with where to look come on the IRC and someone will try to help.
for reference the behaviour was addressed with
master - https://github.com/fusionpbx/fusionpbx/pull/2622
4.2 - https://github.com/fusionpbx/fusionpbx/pull/2623
