### ISSUE TITLE
inbound routes added "caller-details and not found"

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2630]
version master
menu inbound routes default added caller details and not found:
<img width="1201" alt="2017-06-03 13 01 49" src="https://cloud.githubusercontent.com/assets/15113513/26752637/46dded5a-485d-11e7-968c-7e2ddfa12942.png">
click enabled => True/False =>
<img width="1095" alt="2017-06-03 13 05 41" src="https://cloud.githubusercontent.com/assets/15113513/26752641/6aedfe9c-485d-11e7-8cb0-acb60b720ec0.png">
Ok', delete caller details and not found:
<img width="1088" alt="2017-06-03 13 06 40" src="https://cloud.githubusercontent.com/assets/15113513/26752650/9f0bb822-485d-11e7-8f87-f1a7033aca07.png">
<img width="1075" alt="2017-06-03 13 07 25" src="https://cloud.githubusercontent.com/assets/15113513/26752653/ab7a5a78-485d-11e7-93ed-093c535d6c89.png">
Add new domain:
<img width="1089" alt="2017-06-03 13 08 25" src="https://cloud.githubusercontent.com/assets/15113513/26752660/c5fbb414-485d-11e7-88d6-fb26dc0c5b59.png">
Then again:
<img width="1107" alt="2017-06-03 13 09 24" src="https://cloud.githubusercontent.com/assets/15113513/26752670/fb19bf7e-485d-11e7-81d0-24113a210538.png">
Add menu inbound admin permission:
<img width="1074" alt="2017-06-03 13 12 28" src="https://cloud.githubusercontent.com/assets/15113513/26752681/78253f2a-485e-11e7-8593-c121578205a9.png">

**Comment by markjcrane** [comment]
You are saying you want to delete those and they are defaults? What you haven't said is why you want to remove them?

**Comment by manchelsi** [comment]
if admin privileges exposed no read "Dialplan Manager" =>
click enabled => True/False ("caller-details and not found") =>
Read "Dialplan Manager"

**Comment by moteus** [comment]
@markjcrane I think problem is that admin from one domain can enable/disable extensions for all domains.
May be there exists permission for edit global extensions?

**Comment by markjcrane** [comment]
If the user in the superadmin group give dialplan_edit and dialplan_delete to a user in the admin group they have done something very stupid and are in extreme need of training.

**Comment by markjcrane** [comment]
Dialplan edit and dialplan delete are to only be assigned to the superadmin group.

**Comment by manchelsi** [comment]
Yes, but is it possible to hide for the admin "caller-details and not found"?

**Comment by markjcrane** [comment]
With some additional development work it would be possible to hide them. However do not give the admin ability to edit or delete any dialplan or at some point in the future you will see why that is not allowed.

**Comment by manchelsi** [comment]
For example, look like this:

141         else {
142                 if ($app_uuid == 'c03b422e-13a8-bd1b-e42b-b6b9b4d27ce4') {
143                                 if (if_group("superadmin")) {
144                         $sql .= "and (app_uuid = '".$app_uuid."' or dialplan_context = 'public') ";
145         }       
146         if (if_group("admin")) {
147                         $sql .= "and (app_uuid = '".$app_uuid."') ";
148 }               
149                 }


Just in my opinion this is redundant information for the admin privileges...

**Comment by manchelsi** [comment]
In my opinion you can hide these details

**Comment by markjcrane** [comment]
I know they can be hidden as I wrote most of the code. However are you giving admin users more permission to the dialplan beyond dialplan_view?

**Comment by markjcrane** [comment]
Also would ask what version of FusionPBX you are running and what file you saw if_group admin in?

**Comment by manchelsi** [comment]
/app/dialplan/dialplans.php 
string 143

**Comment by manchelsi** [comment]
If I remove for the admin: 
"or dialplan_context = 'public'"
