### ISSUE TITLE
Downgrade Version 4.3.1 to 4.2.2 Due the bugs

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2643]
Hi

Is there a way I could downgrade from Version 4.3.1 to 4.2.2?
I am getting lots of bugs on 4.3.1 and most functions and settings not working.

Auto-provisioning is not pulling most of the phone configs and some of the setting on the Default Settings, Cannot get phone book to work.

I have tested all this on Version 4.2.2 and all is working fine.

Please can you advise.

**Comment by ernestkm** [comment]
Also the Call Centre Queues are not working.

**Comment by markjcrane** [comment]
My advice don't downgrade from 4.3 to 4.2. If you do this you have re-save everything that has a dialplan. In other words call center, conference center, ring groups, call flows and more.

**Comment by ernestkm** [comment]
Hi Mark 

Thanks for the feedback is there a way that I can pull the updates for 4.2.2 on 4.3.1.
Reason asking there is no development and or updates for 4.3.1

**Comment by markjcrane** [comment]
There are updates on the 4.2 and the 4.3 branches.

**Comment by markjcrane** [comment]
Maybe you pulled source for just the release.
