### ISSUE TITLE
at package not installed

### ISSUE THREAD

**Issue by lcx** [fusionpbx/fusionpbx#2651]
Fax to email uses at -f to schedule resending in 3 minutes time if something doesn't work, unfortunately the at package was not installed by the installer.

**Comment by markjcrane** [comment]
What package includes it?

**Comment by lcx** [comment]
yeah, sorry for the short issue text, didn't want to forget about it.

**Comment by mafoo** [comment]
This should be addressed in https://github.com/fusionpbx/fusionpbx-install.sh/pull/101

**Comment by markjcrane** [comment]
Added to the install script.
