### ISSUE TITLE
Today, version master, installation script error:

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2657]
INSERT 0 1                                                                                                                                                    
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...6ffda26', '6e05f681-9c61-49f4-8039-88d5c2e1eef0', '', 'numbe...                                                                                    
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1640                                     
Stack trace:                                                                                                                                                  
#0 /var/www/fusionpbx/resources/classes/database.php(1640): PDO->exec('insert into v_d...')                                                                   
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(109): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()                                                           
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()                                           
#5 {main}   
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1640                 
                                                                                                                 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...6ffda26', '6e05f681-9c61-49f4-8039-88d5c2e1eef0', '', 'numbe...             
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1640
Stack trace:                           
#0 /var/www/fusionpbx/resources/classes/database.php(1640): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(109): database->save(Array)                                             
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()                                                      
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()                                           
#5 {main}                              
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1640                                                                                    
INSERT 0 1                                                                                                       
ОШИБКА:  неверный синтаксис для uuid: ""                                                       
СТРОКА 1: ...5f681-9c61-49f4-8039-88d5c2e1eef0', 'superadmin', '', '8ab4d...           
                                                               ^               
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...8cb9e77', '6e05f681-9c61-49f4-8039-88d5c2e1eef0', '', 'numbe...
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1640
Stack trace:                           
#0 /var/www/fusionpbx/resources/classes/database.php(1640): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(109): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()
#5 {main}
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1640

**Comment by manchelsi** [comment]
OS: Debian 8

**Comment by mafoo** [comment]
Thank you for the bug report it has been addressed in https://github.com/fusionpbx/fusionpbx/pull/2663
it looks like under certain conditions app_uuid can get set to '' which causes the problem above

**Comment by manchelsi** [comment]
install commit a78a29b6e20144e43126b39e0a4d114a27653e8e no problem. Later I did not install everything, except for master.

**Comment by manchelsi** [comment]
Today no install:

INSERT 0 1                                                                                                               
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...9d76d18', '5b2ea081-56b5-4f52-b6d0-dc18f1e7c4c1', '', '6ad54...                                                                                    
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1642
Stack trace:                                                                                   
#0 /var/www/fusionpbx/resources/classes/database.php(1642): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(110): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()                                                           
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()                                           
#5 {main}                              
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1642                 
                                                                                                                 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...9d76d18', '5b2ea081-56b5-4f52-b6d0-dc18f1e7c4c1', '', '6ad54...             
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1642
Stack trace:
#0 /var/www/fusionpbx/resources/classes/database.php(1642): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(110): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()                                                      
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()                                           
#5 {main}   
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1642                 
INSERT 0 1                                                                                                       
ОШИБКА:  неверный синтаксис для uuid: ""                                                       
СТРОКА 1: ...ea081-56b5-4f52-b6d0-dc18f1e7c4c1', 'superadmin', '', 'a691c...           
                                                               ^              
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...1044466', '5b2ea081-56b5-4f52-b6d0-dc18f1e7c4c1', '', '6ad54...
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1642
Stack trace:
#0 /var/www/fusionpbx/resources/classes/database.php(1642): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(110): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()
#5 {main}
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1642

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ОШИБКА:  неверный синтаксис для uuid: ""
LINE 1: ...1044466', '5b2ea081-56b5-4f52-b6d0-dc18f1e7c4c1', '', '6ad54...
                                                             ^' in /var/www/fusionpbx/resources/classes/database.php:1642
Stack trace:
#0 /var/www/fusionpbx/resources/classes/database.php(1642): PDO->exec('insert into v_d...')
#1 /var/www/fusionpbx/app/number_translation/resources/classes/number_translation.php(110): database->save(Array)
#2 /var/www/fusionpbx/app/number_translation/app_defaults.php(39): number_translation->import()
#3 /var/www/fusionpbx/resources/classes/domains.php(352): include('/var/www/fusion...')
#4 /var/www/fusionpbx/core/upgrade/upgrade_domains.php(55): domains->upgrade()
#5 {main}
  thrown in /var/www/fusionpbx/resources/classes/database.php on line 1642

**Comment by mafoo** [comment]
manchelsi i installed a new system with debian 8 with the install scripts and it all goes in without a hitch using version https://github.com/fusionpbx/fusionpbx/commit/5bfda43d16488a9b742dc7adb43ecd626e5a75d4 
I am not sure how it's managing to trip up for you, is it possible for you to come onto IRC and we can help dig a bit deeper what is going on. (we are on freenode in #fusionpbx)

**Comment by manchelsi** [comment]
OK. Now I'll take a new virtual machine. I'll install it on her. I will write the results.

**Comment by manchelsi** [comment]
New install Debian 8, exec script => result:
http://paste.ubuntu.com/24822409/

**Comment by manchelsi** [comment]
use en_US-UTF8
http://paste.ubuntu.com/24822502/

**Comment by mafoo** [comment]
manchelsi thank you for barring with me on this, I have tracked it down!
there were two issues and i wasn't debugging them correctly
first was the previous mentioned PR, however this then led to the second which is fixed!
the PR should be https://github.com/fusionpbx/fusionpbx/pull/2677

**Comment by manchelsi** [comment]
mafoo, Yes, it works.
