### ISSUE TITLE
version master, open adminer

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2669]
Fatal error: require(): Failed opening required '/var/www/fusionpbx/app/adminer/app_languages.php' (include_path='.:/usr/share/php:/usr/share/pear:/var/www/fusionpbx') in /var/www/fusionpbx/resources/classes/text.php on line 75

**Comment by manchelsi** [comment]
checkout to 0526819a019a4018bd7d14cd6be05c5fcac3d379 adminer not open

**Comment by mafoo** [comment]
That file should exists please could you check the file permissions for it, it should be owned by www-data
also what page were you on I cannot see where $text->get is being called in index.php or adminer.php

**Comment by manchelsi** [comment]
git checkout master
chown -R www-data. /var/www/fusionpbx 

link https://192.168.1.80/app/adminer/index.php?pgsql&db=fusionpbx&ns=public&username=auto =>
Fatal error: require(): Failed opening required '/var/www/fusionpbx/app/adminer/app_languages.php' (include_path='.:/usr/share/php:/usr/share/pear:/var/www/fusionpbx') in /var/www/fusionpbx/resources/classes/text.php on line 75


link https://192.168.1.80/app/adminer/index.php =>
Fatal error: require(): Failed opening required '/var/www/fusionpbx/app/adminer/app_languages.php' (include_path='.:/usr/share/php:/usr/share/pear:/var/www/fusionpbx') in /var/www/fusionpbx/resources/classes/text.php on line 75

**Comment by markjcrane** [comment]
This has been fixed.
