### ISSUE TITLE
Is this free software? 

### ISSUE THREAD

**Issue by xenithorb** [fusionpbx/fusionpbx#2691]
I was attempting to add you to the awesome-selfhosted list under the IPBX section, but I couldn't find any information on how this software is licensed. Note that a CLA is not adequate to describe the license of the project. 

Is this free software? How is it licensed? 

From a user's perspective I didn't find anything about this in the normal spots (LICENSE, etc.) just lots of info about the CLA process and contributing.

**Comment by markjcrane** [comment]
If you look at the top of the php files you will see MPL.

**Comment by xenithorb** [comment]
That moment when you forget to check that actual code itself, eh?

Thanks for clarifying!
