### ISSUE TITLE
Many dialplans with continue=true

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#2696]
As I have been debugging dialplans in 4.2+, I see that many of them created from apps (aka RG, TC, IVR) they have the continue=true. Is this an accident?

If a dial plan hits, the FreeSWITCH will continue evaluation, and if it finds another that hits. It will create a mess. For example, when users put a ring-group with the same number than an extension (just to mention one example)

**Comment by markjcrane** [comment]
Tested current master branch which will become the next release.
IVR Menu - dialplan: continue false
Ring Group - dialplan: continue false
Time condition - dialplan: continue true  (fixed the code to default it to false)

**Comment by daniel-lucio** [comment]
What is your commit?
I have confirmed that it happens on 4.2.x

**Comment by markjcrane** [comment]
The changes to master would not be compatible with 4.2.
