### ISSUE TITLE
Unable to authenticate to different tenants 

### ISSUE THREAD

**Issue by jcroy** [fusionpbx/fusionpbx#2697]
We are running fusionpbx in Amazon Ec2 but running into an issue where users cannot specify which domain they are trying to join.  Ive narrowed the issue down to it being the Cisco 7961 not sending the proper domain/subdomain when it tries to authenticate as I am able to register numerous Zoiper clients to either domain.  Also everything is fine when working with a single domain system.  Looking at the log viewer, I see that no matter how I change the config cnf.xml file on the 7961 I cannot seem to get it to send the domain name when it authenticates.  Any ideas/solutions to get around this? Is there a option in fusion that could help as I cannot get the phone to send the correct authentication details.

**Comment by markjcrane** [comment]
This is a problem with Cisco 7961 the phone has to send the domain for the registration for multi-tenant to work. Suggestion 1.  don't use these phones 2. alternative is create a domain with IP address of the server set the context of the phones to the domain you want and you will be able to dial through the domain dialplan of your choice.
