### ISSUE TITLE
SIP registration doesn't show in WEB UI for TLS

### ISSUE THREAD

**Issue by thomassmart** [fusionpbx/fusionpbx#2699]
Hi,

Registrations don't show within the web interface for TLS  sip registrations. 

<img width="813" alt="screen shot 2017-06-17 at 2 23 53 pm" src="https://user-images.githubusercontent.com/26615060/27250234-7d1f5a1a-536c-11e7-8c9c-92bd4acdf69f.png">

-Tom

**Comment by moteus** [comment]
Wrong domain or profile not internal.
`Registrations`displays only internal profile.
Checkout Status->SIP status

**Comment by mafoo** [comment]
you should be registering to 5061 if you want TLS extension registered

**Comment by thomassmart** [comment]
It is using the external sip profile, do registrations not show up on the web ui for this profile, is it possible to force it to show registrations for the external profile, or should I edit the internal profile to perform similar to the external?

**Comment by thomassmart** [comment]
I've altered to using the sip internal profile. I think I misunderstood that SIP Internal refers to authentication to fusion and not internal/external networks.
