### ISSUE TITLE
Gui logon - Language Issue

### ISSUE THREAD

**Issue by idatacom** [fusionpbx/fusionpbx#2703]
I have built a new platform up on Debian Jessie.
I added a second domain to the Fusinpbx and the language changed, when removed it reverted to English. 
A fresh install has been done and the problem has re-occured. This time all was well until I got the login screen up and the language has changed overnight, attempting to login does not work as the characters are I guess polish.

**Comment by markjcrane** [comment]
Prove this with a video or remote access its just a bit hard to believe.
