### ISSUE TITLE
Codec Configuration

### ISSUE THREAD

**Issue by whiskeyneon** [fusionpbx/fusionpbx#2705]
I apologize if this is documented elsewhere and I'm just overlooking it, but I am attempting to enable higher quality codecs to use with CSIPSimple and I'm not having any luck. I'm also not sure if I am even entering in the variable field correctly.
In `global_codec_prefs` I enter this into the value field: `opus@48000h@40i,speex@32000h@20i,G7221@32000h,G7221@16000h,G722,CODEC2,PCMU,PCMA,GSM`
I have tried only enabling Opus, Speex, and CODEC2 individually in CSIPSimple to no avail. I am assuming that I am doing something wrong here. The FS documentation appears to have a typo and/or incomplete information as to what I should enter as the variable for CODEC2.
https://freeswitch.org/confluence/display/FREESWITCH/Audio+Codecs

**Comment by jebsolutions** [comment]
For Opus...

It may not be installed by default.  E.g. if you are using the Debian Freeswitch packages try this for opus:
apt-get install freeswitch-mod-opus.

In FusionPBX go to Advanced->Modules in the Codec section.  You need to make sure there's an Opus codec here with "mod_opus" and that it's enabled.

Then completely stop/start freeswitch.

fyi...would be nice if the installer did this automatically.

**Comment by jebsolutions** [comment]
For iLBC...

There used to be a Debian package for this.  But somewhere along the way it got removed so you have to build it yourself.

```
#Install prerequisite tools:
apt-get install automake libtool m4 libtool-bin pkg-config
apt-get install -y --force-yes freeswitch-video-deps-most

cd /usr/src
git clone -b v1.6 https://freeswitch.org/stash/scm/fs/freeswitch.git freeswitch.git


# Install libilbc-dev
cd /usr/src
wget http://files.freeswitch.org/downloads/libs/ilbc-0.0.1.tar.gz
tar -xzvf ilbc-0.0.1.tar.gz
cd ilbc-0.0.1
./bootstrap.sh
./configure --enable-shared --prefix=/usr/local
make && make install

apt-get update


git clone -b v1.6 https://freeswitch.org/stash/scm/fs/freeswitch.git freeswitch.git

# reference: https://freeswitch.org/confluence/display/FREESWITCH/Debian+8+Jessie
./bootstrap.sh -j
./configure 
make

cd /usr/src/freeswitch/freeswitch.git/src/mod/codecs/mod_ilbc
make 
make install
# this creates /usr/src/freeswitch/freeswitch.git/src/mod/codecs/mod_ilbc/.libs/mod_ilbc.so
cp  mod_ilbc.so  /usr/lib/freeswitch/mod
```

You also have to add an Advanced->Modules->Codecs section for "iLBC@30i" for "mod_ilbc" and have it enabled.

Fyi...would be nice to have this also added to the installer as an option.  This is a pretty good codec.

**Comment by DigiDaz** [comment]
I do not understand why Freeswitch have stopped building ilbc, we shouldn't be having to go back to source compilation etc for a codec. I'm going to have a dig around see if I can find out why its gone.

With regards to codec2 is this not a codec that was designed for amateur radio?

**Comment by daniel-lucio** [comment]
If you are in the CentOS, you can use my RPM's at https://okay.com.mx/en/blog/rpm-repositories-for-centos-6-and-7.html you will find the CODEC RPM"s ready to use.

**Comment by markjcrane** [comment]
Removed the advertisement.

**Comment by daniel-lucio** [comment]
That was far way to be an ad. @jebsolutions suggested a Debian way
".if you are using the Debian Freeswitch packages try this for opus:"
I suggested a CentOS way.

**Comment by markjcrane** [comment]
In regards to CentOS here is this official RPM install guide.
https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7

**Comment by whiskeyneon** [comment]
I am using Debian and have verified I have the right modules enabled. This is the output of `show codec` from the command line:
> type,name,ikey
> codec,ADPCM (IMA),mod_spandsp
> codec,AMR,mod_amr
> codec,BroadVoice16 (BV16),mod_bv
> codec,BroadVoice32 (BV32),mod_bv
> codec,CODEC2 3200/2400/1400/1200bps,mod_codec2
> codec,G.711 alaw,CORE_PCM_MODULE
> codec,G.711 ulaw,CORE_PCM_MODULE
> codec,G.722,mod_spandsp
> codec,G.723.1 6.3k,mod_g723_1
> codec,G.726 16k,mod_spandsp
> codec,G.726 16k (AAL2),mod_spandsp
> codec,G.726 24k,mod_spandsp
> codec,G.726 24k (AAL2),mod_spandsp
> codec,G.726 32k,mod_spandsp
> codec,G.726 32k (AAL2),mod_spandsp
> codec,G.726 40k,mod_spandsp
> codec,G.726 40k (AAL2),mod_spandsp
> codec,G.729,mod_g729
> codec,GSM,mod_spandsp
> codec,H.261 Video (passthru),mod_h26x
> codec,H.263 Video (passthru),mod_h26x
> codec,H.263+ Video (passthru),mod_h26x
> codec,H.263++ Video (passthru),mod_h26x
> codec,H.264 Video (passthru),mod_h26x
> codec,LPC-10,mod_spandsp
> codec,MP3,mod_shout
> codec,OPUS (STANDARD),mod_opus
> codec,PROXY PASS-THROUGH,CORE_PCM_MODULE
> codec,PROXY VIDEO PASS-THROUGH,CORE_PCM_MODULE
> codec,RAW Signed Linear (16 bit),CORE_PCM_MODULE
>  codec,SILK,mod_silk
>  codec,Speex,CORE_SPEEX_MODULE
>  codec,VP8 Video,CORE_VPX_MODULE
>  codec,VP9 Video,CORE_VPX_MODULE
> 
>  34 total.

I am asking what the proper entries would be for the `global_codec_prefs` variable. Can anyone verify whether or not what I have entered is correct?

**Comment by DigiDaz** [comment]
I think its just: OPUS
