### ISSUE TITLE
RTP_Secure_Media Issue: External Forwarding do not function

### ISSUE THREAD

**Issue by canadamcpherson** [fusionpbx/fusionpbx#2713]
Hi Mark,

I have a working SRTP setup, but external forwarding goes to voicemail. Are you able to help me? If necessary, I can pay for support.

Current setting is:

Under : local_extension

action       export         rtp_secure_media=true

**Comment by markjcrane** [comment]
Called and discussed this and set rtp_secure_media=false on the outbound routes.

**Comment by canadamcpherson** [comment]
Thank you!
