### ISSUE TITLE
Loading G729 Not working FusionPBX 4.2

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2716]
Hi I am having issues loading G729 on my FusionPBX 4.2.

Has anyone experienced a problem loading a Codec.

**Comment by markjcrane** [comment]
You set the variables in advanced -> variables near the top of the page or on the sip profiles.

**Comment by ernestkm** [comment]
Hi Mark

I know this is Freeswitch Issue but have you ever successfully loaded a G729 on a FusionPBX running on VMWare.
I have tried it on 3 VM’s and with no Success.

I could be doing something wrong but I just needed to find out if anyone has done it successfully.
Dont think it is related to FusionPBX but I am only running FusionPBX's

**Comment by mafoo** [comment]
If you come on the IRC we could probably talk you though the problem, however random questions would be are you using the free pass though codec or the commercial codec.
Have you installed it for the operating system (under debian apt-get install freeswitch-mod-g729)
Have you selected it to load in the module page (advanced > Modules)

**Comment by ernestkm** [comment]
Hi All

Thanks for the feedback provided on this query and we managed to sort the problem.
The FreeSwitch License installer was not working properly on the latest FreeSwitch and we found a work around.
