### ISSUE TITLE
Default Settings - Limits

### ISSUE THREAD

**Issue by ChavPaskov** [fusionpbx/fusionpbx#2720]
was wondering if it is feasible to apply limits per domain  and not to all domains.
Example: abc.xyz.com  
limited at  7 destinations and  20 extensions.

Example: def.xyz.com  
limited at  9 destinations and  30 extensions.

Regards
Chav

**Comment by andycol** [comment]
have a look at https://www.youtube.com/watch?v=GIY0wtJ05Tg

**Comment by ChavPaskov** [comment]
Thanks!!
