### ISSUE TITLE
Email to Fax

### ISSUE THREAD

**Issue by elecboy00** [fusionpbx/fusionpbx#2721]
Hi,

I am new to FusionPBX, is this posible without much effort? I will like to receive faxes and send them via email and have with email account "fax@domain.tld". Can this be done? Thank you!

**Comment by andycol** [comment]
as far as i know this cant be done but you can just send from the gui so i dont see a need

**Comment by moteus** [comment]
It is possible. There just no documentation (for reason). Please contact about this on IRC channel.

**Comment by LuckyLuis247** [comment]
Hello Where Can I find the documentation on this feature. I got fax to mail feature working fine, but I want to get email to fax working. Any help would be awesome.
