### ISSUE TITLE
call detailed recoreds show nothing 

### ISSUE THREAD

**Issue by nick950222** [fusionpbx/fusionpbx#2723]
my FREESWITCH version is 1.6.18, POSTGRESQ version is 9.6.3, my system is DEBIAN 8.5
everything works fine, I can register 1000-1019 and call one another ,but whichever number i call, ther is no call detial records on https://192.168.0.185/app/xml_cdr/xml_cdr.php . But when I searched for local freeswitch logs and i found them. Somehow fusionpbx failed to display them ,can you help me with it? Maybe it has something to do with the xml_cdr ? Perhaps the xml files are not accepted by the http server due to ssh key identification failure ? Please help me
@marclaporte @tomgillett @hargut @badcrc @badcrc

**Comment by markjcrane** [comment]
Advanced -> xml editor then click on autoload_configs/xml_cdr.conf.xml

    
    <param name="url" value="http://127.0.0.1/app/xml_cdr/v_xml_cdr_import.php"/>

    
    <param name="cred" value="randomusername:randdompassword"/>

Make sure to update the randomusernam and randompassword with something random.
Advanced -> Modules restart XML CDR.
