### ISSUE TITLE
Feature request, semi or full auto reload/refresh/flush ACL, SIP Profiles, memcache etc. on changes

### ISSUE THREAD

**Issue by powerpbx** [fusionpbx/fusionpbx#2724]
After you make a configuration change in the Asterisk GUI you see an "Apply Change" button at the top to reload the asterisk configuration.  Perhaps something similar can be done on FusionPBX.  

Changes saved in `Advanced > Access Controls` is one example where it is not obvious to many administrators that they need to go to a separate menu area `Status > SIP Status` and `reload ACL` in order for saved ACL changes to take effect. Same situation when changes require flushing memcache and/or reloading sofia profiles or XML.  This can have a compounding negative effect when the changes do take effect later on after a reboot/reload done for other reasons.  At that point the administrator may not be able to easily determine what previous changes caused the problem.

At a minimum, perhaps a message can be displayed prominently after changes are saved explaining what needs to be reloaded/restarted in order for the changes to take effect.

**Comment by markjcrane** [comment]
In many cases reloadxml is done for you.

**Comment by markjcrane** [comment]
We prefer to do it for you in most cases. When reloadxml or reloadacl are run it doesn't spike the CPU at all compare that with the system you referred to.

**Comment by markjcrane** [comment]
ReloadACL is now automatically run on the master branch when changing something in Advanced -> Access Controls.

**Comment by markjcrane** [comment]
As far as SIP Profiles go some of them take restarting the SIP profiles or restarting FreeSWITCH.
Some of them will work with a SIP profile re-scan.

Will consider an 'Apply Button' but its not a small project since we would have to remove all the automatic things that are done for people or make a setting to make the apply button optional.
