### ISSUE TITLE
Latest commit 739aafa 

### ISSUE THREAD

**Issue by cstm** [fusionpbx/fusionpbx#2735]
Are you sure @markjcrane of your latest commit ?
Seems that after modifying some dialplan, the XML will result empty

**Comment by markjcrane** [comment]
Modifying it with the dial plan edit tool?

**Comment by cstm** [comment]
yes on the web interface.

**Comment by markjcrane** [comment]
What version are you running. You can view this from the Dashboard for Status -> System Status.

**Comment by cstm** [comment]
the latest git 4.3.2.

**Comment by markjcrane** [comment]
Which dial plan are you referring to? And have you updated and tested it again?

**Comment by cstm** [comment]
ok sorry, this has been fixed i had a wrong version of database.php
