### ISSUE TITLE
Fusionpbx with apache? 

### ISSUE THREAD

**Issue by RealAgent** [fusionpbx/fusionpbx#2748]
Hi.
I have question - Is it possible to change nginx to apache? 
If not, how to modify the server settings I would also be able to host a website with fusionpbx. The problem is that at this point the server sees only files with fusionpbx.

So I can not upload other software and stick with fusionpbx.

OS: Debian 8 Jessie.

Best Regards!

**Comment by markjcrane** [comment]
Yes its possible to use nginx to apache. There are thousands of tutorials on how to configure apache.
