### ISSUE TITLE
PR for Ring Groups Missed Call Notification break LUA.

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#2754]
Looks like the updates that were done for the missed call notifications in Ring Groups broke something. I'm getting the following errors in my logs when calling a RG. I rolled back to a version before 7/20/17 and it works correctly now. I'm not sure what is causing this. 

```
c5f9922a-0f94-4c14-89d4-88387c1fd41c 2017-07-23 13:59:43.422489 [ERR] mod_lua.cpp:203 /usr/share/freeswitch/scripts/app/ring_groups/index.lua:171: bad argument #1 to len (string expected, got nil) 
c5f9922a-0f94-4c14-89d4-88387c1fd41c stack traceback: 
c5f9922a-0f94-4c14-89d4-88387c1fd41c [C]: in function len 
c5f9922a-0f94-4c14-89d4-88387c1fd41c /usr/share/freeswitch/scripts/app/ring_groups/index.lua:171: in main chunk 
c5f9922a-0f94-4c14-89d4-88387c1fd41c /usr/share/freeswitch/scripts/app.lua:48: in main chunk 
```

**Comment by markjcrane** [comment]
That error refers to line 171 which I don't believe has changed in a while and its complaining that it is nil. Fixed with this https://github.com/fusionpbx/fusionpbx/commit/47b6e497ad60a1ed2dd2a219de2d39b155663e81
