### ISSUE TITLE
[BUG] Broken JSON on CDR

### ISSUE THREAD

**Issue by cstm** [fusionpbx/fusionpbx#2759]
Seems that the json is addslashed on DB now (using the latest commit e691073ed...)

now we have this in DB:
{\\"@attributes\\":{\\"core-uuid\\":...

So xml_cdr_details.php will result on a empty page.

**Comment by DigiDaz** [comment]
Where do you see anything to do with this in that commit? I'm not a programmer but if I'm missing that then I'm far more retarded than I thought I was.

**Comment by DigiDaz** [comment]
You are not referring to that commit, you are just saying, 'on latest master'?

**Comment by cstm** [comment]
yes using latest master, github has replaced this with href)

**Comment by markjcrane** [comment]
What database are you using?

**Comment by markjcrane** [comment]
My guess you are using MySQL? You can see by running advanced -> upgrade -> schema and then it will tell you postgresl or mysql.

**Comment by cstm** [comment]
yep mysql

**Comment by DigiDaz** [comment]
None of the mysql code is tested anymore, you should switch to postgres

**Comment by cstm** [comment]
the code was working some days ago, so you have a compatibility breaker here even if mysql is not *officially* supported.

**Comment by DigiDaz** [comment]
cstm, my point is, you can expect this at any time with mysql, I'm sure this will get fixed but its going to take the community to test these things, the developers won't be testing it.

**Comment by cstm** [comment]
I'm just reporting this to prevent people having the same issue as me.
No worry for me it's already fixed on my side. It was just for information

Dirty but working patch would be on xml_cdr_details.php: 

```
        if (preg_match('/^\{\\\"\@attr/', $json_string))
          $json_string = stripslashes($json_string);
```
