### ISSUE TITLE
Destination App as Admin

### ISSUE THREAD

**Issue by konradSC** [fusionpbx/fusionpbx#2761]
I'm using the Destination app while logged in as an user with admin permission. Every time I edit a destination and choose a new action, it simply adds it as a new action and doesn't replace the original action. 

So if my original action was for extension 1000 and I change it to 2000, it will now have x1000 as action 1 and then x2000 as action 2. When you look at inbound routes you see a double entry. I have tried playing with the permissions to see if that what is causing this, but I can't figure it out. When logged in as a superadmin I don't see this issue. 

![image](https://user-images.githubusercontent.com/22178090/28586457-ec179c5a-7141-11e7-8752-51b74a964b70.png)

![image](https://user-images.githubusercontent.com/22178090/28587497-5f280d76-7145-11e7-94ba-94555c0fa918.png)

**Comment by markjcrane** [comment]
Thanks for reporting the issue it has been fixed. You will have to remove the entries manually using the web interface and the duplicate issue will no longer occur.
https://github.com/fusionpbx/fusionpbx/commit/c84fd7ebe4eccc5c9e3923d7fc358242e4aa77c2
