### ISSUE TITLE
Documentation For Cloud Deployment

### ISSUE THREAD

**Issue by lastradio** [fusionpbx/fusionpbx#2766]
I am following the docs.fusionpbx.com guide and wanted to get some help so we can promote FusionPBX.

I am looking to document and share a guide for deploying FusionPBX in a hosted environment (like vultr.com) so that we can begin to test and recommend this in the forums where FreePBX is seen as the only FOSS Hosted PBX solution.

My only concern with the current guide has to do with the security page. It seems to be written with suggested settings for a LAN deployment. I really want to get something together (step by step for the layman) that would be secure enough to deploy on a public IP address on a public cloud.

FreePBX has done a lot with the Adaptive Firewall, but I believe FusionPBX could be deployed on a public IP and be just as secure. Not sure if this is the best place to post this, but I am doing so since there is no other community space I could find online. Thanks in advance!

**Comment by markjcrane** [comment]
FusionPBX install script instructions can be seen here. Debian 8 is the preferred OS by the FreeSWITCH team but Devuan, CentOS and FreeBSD can also be installed.
https://www.fusionpbx.com/download.php

The install script installs IPtables for Linux or pf for FreeBSD. After the install you can run iptables -L to see the rules it installed.

We have an iptables guide here.
http://fusionpbx-docs.readthedocs.io/en/latest/getting_started/iptables.html?highlight=iptables

Firewall ports listed here
http://fusionpbx-docs.readthedocs.io/en/latest/firewall.html?highlight=firewall

Additional information can be found.
http://fusionpbx-docs.readthedocs.io/en/latest/getting_started/security.html

More will be added as I will be speaking at ClueCon on security in 2 weeks.

Best Regards,

Mark J Crane
www.fusionpbx.com

**Comment by DigiDaz** [comment]
lastradio: could you share the forum, I'll certainly come and help argue fusionpbx's case. Out of the box you are good to go but additional measures can be taken.

**Comment by lastradio** [comment]
https://mangolassi.it/topic/14480/let-s-convince-someone-to-release-a-foss-pbx/

Here is an ongoing thread we have been hashing around. Would be great to have you...

**Comment by lastradio** [comment]
@DigiDaz I started a new thread on ML and have particular interest in making sure I provide everyone with proper security measures as we mostly see users running PBX software on Vultr (or cloud instances)

Based on the docs.fusionpbx.com guide for Jessie it seems Mod_xml_rpc is not secured with the default scripts for a cloud install. It would also be great to get feedback for additional measures.

I have no other way to message you so if you join MangoLassi please hit me up, I am "bigbear".

https://mangolassi.it/topic/14537/replacing-freepbx-with-fusionpbx

Here is a thread I started particularly for helping users switch from FreePBX to FusionPBX.

**Comment by markjcrane** [comment]
> Based on the docs.fusionpbx.com guide for Jessie it seems Mod_xml_rpc is not secured with the default scripts for a cloud install.

mod_xml_rpc is secure by default. For 2 primary reason.
- The module is disabled by default.
- Install script firewalls xml rpc port 8787 and does not allow access by default outside of 127.0.0.1 

If you were to start the module and you want to set a really good password before starting mod xml rpc. I'll have the install script do that by default for new installs.
