### ISSUE TITLE
Gateway or Dialplan to SIP URI Services

### ISSUE THREAD

**Issue by louisyssel** [fusionpbx/fusionpbx#2786]
Hi, I want to be able to make outgoing calls from my FusionPBX client to SIP URI <user@domain.com>. Is this done through an Internet Gateway (If so, please let me have a sample config), or is it a dial plan rule on existing gateway SIP Trunk (If so, please provide a sample of the rule.)

Thanks a lot
Louis

**Comment by markjcrane** [comment]
Can use a bridge statement in an outbound route:
action: bridge    
data: sofia/internal/2085551234@pbx.domain.com:5060

Or you can create a gateway set registration to false and then setup an outbound route to send calls to that gateway.
