### ISSUE TITLE
Where is core/user_settings/user_edit.php?

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#2790]
Still in Home > Account Settings, but PHP file is no longer found in GitHub nor install.

**Comment by konradSC** [comment]
Is this the droid you are looking for?

[user_edit.php](https://github.com/fusionpbx/fusionpbx/blob/master/core/users/user_edit.php)

**Comment by markjcrane** [comment]
Try updating you menu with restore defaults after upgrading.

**Comment by markjcrane** [comment]
Updating the menu should be what is needed no response so closing the issue.
