### ISSUE TITLE
Call Fowarding to outside Number.

### ISSUE THREAD

**Issue by elecboy00** [fusionpbx/fusionpbx#2794]
When I try to do a Call Foward to a cellphone I get the message "The  person at Extension XXX  is no available", and the call never fowards.

Edit This is the log viewer when I type extension 101 that is suppose to foward to a cellphone:

2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com Regex (FAIL) [talking clock date] destination_number(101) =~ /^\*9171$/ break=on-false 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com parsing [voip.fusionpbx.com->call_screen] continue=true 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com Regex (FAIL) [call_screen] ${call_screen_enabled}(false) =~ /^true$/ break=on-false 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com parsing [voip.fusionpbx.com->local_extension] continue=true 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com Regex (PASS) [local_extension] ${user_exists}(true) =~ /true/ break=on-false 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d Dialplan: sofia/external/XXXXXXXXX@sip.telecom.com Action export(dialed_extension=${destination_number}) INLINE 
2eefa849-0b5d-49e3-b47e-5dfee94fad8d EXECUTE sofia/external/XXXXXXXXX@sip.telecom.com export(dialed_extension=101)

**Comment by markjcrane** [comment]
This is most likely a configuration issue.

**Comment by markjcrane** [comment]
Rather than a bug.

**Comment by elecboy00** [comment]
Hi Mark, 

I am trying to reach you, I paid for an additional hour of support to solve this, Thanks!

**Comment by markjcrane** [comment]
Call me tomorrow Monday support number +1 208 906 8227.

**Comment by elecboy00** [comment]
Alright!

**Comment by Knarf007** [comment]
I had the same issue.  I just disabled it then enabled it.

**Comment by markjcrane** [comment]
Call forward has been changed dramatically please update to the latest version in whatever branch you are on 4.2 or master branch and test again.
