### ISSUE TITLE
New install - memcache not clearing?

### ISSUE THREAD

**Issue by Tatermen** [fusionpbx/fusionpbx#2795]
I'm having a curious issue on a newly installed system, whereby we make changes to settings on extensions etc. and they do not take effect.

We found that for example, if we add an Outbound Caller ID to an extension, save and then make a call out - the other party doesn't see the number and in the logs we can see:

```
[effective_caller_id_name]=[UNDEF]
[effective_caller_id_number]=[UNDEF]
```

However if we go into Status -> SIP Status and Flush Memcache, it will start working. On an older install, the changes take effect immediately without having to do this.

Any ideas?

FusionPBX 4.2.3 (594db0dfc61e9116876f902141f149a3234d920e) with FS 1.6.19.

**Comment by Tatermen** [comment]
So, I found on the new system that there is a Default setting Cache ```method=memcache``` which doesn't exist on the old system. I'm going to remove this out of hours on the new system and see if this fixes my issue.

Is this the expected behaviour with memcache enabled?

**Comment by markjcrane** [comment]
That default setting should not be used on 4.2.x its used on 4.3.2 you must put the numbers backwards.

**Comment by markjcrane** [comment]
The memcache delete was broken a slight adjustment corrected the problem. Please test and reply back here to confirm it is fixed.

**Comment by markjcrane** [comment]
This has been fixed.
