### ISSUE TITLE
Call Routing Does Not Work from GUI in Latest Builds

### ISSUE THREAD

**Issue by emaktech** [fusionpbx/fusionpbx#2804]
In the latest master builds, when setting call routing settings (I have tested with call forward) the routing does not apply on the switch immediately. It is necessary to flush memcache for the routing to be applied.

When using the dialcodes (*72, *73) the routing is correctly applied immediately.

I have verified this behavior on a fresh install of master as of a few minutes ago.

**Comment by moteus** [comment]
Is there any errors in log when you set call forward?

**Comment by emaktech** [comment]
May seem like a silly question, but which log would be most helpful for this? Obviously you see the change logged on the transactions page. Nothing notable in the FreeSWITCH logs but not sure

**Comment by andycol** [comment]
yes same issue here and no errors etc in the log, you will see the dial string doesnt add the change until you save twice

**Comment by Tatermen** [comment]
I raised an issue about this 2 weeks ago that's had no response. #2795 

We also found that extension settings were not being flushed either. We ended up disabling memcached in the settings.

**Comment by emaktech** [comment]
Very interesting @Tatermen. There are of course instances where memcache needs to be cleared and it's a bit annoying (like when editing dialplans, etc.)

I'd say any of the user-friendly operations like changing extension settings, routing options, etc. should be able to be adjusted without needing to flush memcache. They used to work though so obviously something has changed in the codebase.

I may end up disabling memcache for the time being like you did because it seems to be a bit more trouble than it's worth. At least until some of these issues can be resolved.

**Comment by markjcrane** [comment]
I just fixed the memcache delete problem for the master branch please update and then test it again.

**Comment by emaktech** [comment]
@markjcrane I can confirm that it is now working correctly. Thanks!
