### ISSUE TITLE
Today's commit

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2807]
go https://ip_address/app/extensions/extensions.php => 

Fatal error: require_once(): Failed opening required '/var/www/fusionpbx/app/registrations/resources/classes/status_registrations.php' (include_path='.:/usr/share/php:/var/www/fusionpbx') in /var/www/fusionpbx/app/extensions/extensions.php on line 31

**Comment by markjcrane** [comment]
You meant the commit in the last hour.

**Comment by manchelsi** [comment]
yes

**Comment by markjcrane** [comment]
Thanks for reporting this it has been fixed.
