### ISSUE TITLE
Double registration.

### ISSUE THREAD

**Issue by manchelsi** [fusionpbx/fusionpbx#2809]
Double registration one extensions, NAT:
![image](https://user-images.githubusercontent.com/15113513/29772569-146b778c-8c02-11e7-85a1-8a1b858a9bd9.png)

Changing values "SIP Force Contact"  = "Rewrite contact and Port"/"Rewrite Contact and Port 2.0" => No results

**Comment by markjcrane** [comment]
Thanks for reporting this it was a bug in the new registrations code. Fixed it an hour ago.
