### ISSUE TITLE
In Debian 8, fusionpbx-install.sh installation from source have problems after install complete

### ISSUE THREAD

**Issue by gary-yu** [fusionpbx/fusionpbx#2812]
#In Debian 8,  installation looks success, no any error during installation procedure, but the freeswitch service process keep rebooting, and the event_socket can't start.  Here is the key procedure infos:

# cat /etc/debian_version 
8.8

# cat /etc/apt/sources.list
deb http://deb.debian.org/debian jessie main
deb http://deb.debian.org/debian jessie-updates main
deb http://security.debian.org jessie/updates main

# wget -O - https://raw.githubusercontent.com/fusionpbx/fusionpbx-install.sh/master/debian/pre-install.sh | sh

# sed -i 's/switch_source=false/switch_source=true/'  /usr/src/fusionpbx-install.sh/debian/resources/config.sh

# sed -i 's/switch_package=true/switch_package=false/'  /usr/src/fusionpbx-install.sh/debian/resources/config.sh

# cd /usr/src/fusionpbx-install.sh/debian && ./install.sh

After installation finish,

# fs_cli -x "sofia status"
[ERROR] fs_cli.c:1659 main() Error Connecting [Socket Connection Error]

# {  could be caused by IPv6 localhost?, but even remove "::1" from hosts file, event_socket still can't start. }
# cat /etc/hosts

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1 localhost
10.144.102.214 iZj6c1qymlyinwg9qpc02nZ

# cat /etc/debian_version 
8.9

# systemctl status freeswitch.service -l
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled)
   Active: deactivating (final-sigterm) (Result: timeout)
  Process: 26781 ExecStart=/usr/local/freeswitch/bin/freeswitch -u www-data -g www-data -ncwait $DAEMON_OPTS (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/freeswitch.service
           └─26782 /usr/local/freeswitch/bin/freeswitch -u www-data -g www-data -ncwait -nonat -ncwait -u www-data -g www-data

Aug 30 12:08:59 hkf freeswitch[26781]: 26782 Backgrounding.
Aug 30 12:09:01 hkf freeswitch[26781]: FreeSWITCH[26781] Waiting for background process pid:26782 to be ready.....
Aug 30 12:09:01 hkf freeswitch[26781]: FreeSWITCH[26781] System Ready pid:26782
Aug 30 12:09:01 hkf systemd[1]: PID file /run/freeswitch/freeswitch.pid not readable (yet?) after start.
Aug 30 12:09:44 hkf systemd[1]: freeswitch.service start operation timed out. Terminating.

# {anyway, the freeswitch service will keep rebooting again and again quickly}

**Comment by manchelsi** [comment]
Debian 8 no problem install
Install listing http://paste.ubuntu.com/25431315/

**Comment by gary-yu** [comment]
Thanks for your checking.  Could you please provide the base version of your Debian 8?

please run these two commands before installation:
# cat /etc/debian_version
# cat /etc/apt/sources.list

**Comment by manchelsi** [comment]
manchelsi@fusionpbx:~$ cat /etc/debian_version 
8.7
manchelsi@fusionpbx:~$ cat /etc/apt/sources.list
# 

# deb cdrom:[Debian GNU/Linux 8.7.1 _Jessie_ - Official amd64 CD Binary-1 20170116-11:01]/ jessie main

#deb cdrom:[Debian GNU/Linux 8.7.1 _Jessie_ - Official amd64 CD Binary-1 20170116-11:01]/ jessie main

deb http://mirror.yandex.ru/debian/ jessie main
deb-src http://mirror.yandex.ru/debian/ jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb http://mirror.yandex.ru/debian/ jessie-updates main
deb-src http://mirror.yandex.ru/debian/ jessie-updates main

**Comment by manchelsi** [comment]
http://paste.ubuntu.com/25436895/

**Comment by gary-yu** [comment]
Thanks manchelsi  for your info.

I tried again (with your sources.list), but still fail.  The detail log: http://paste.ubuntu.com/25438505/

**Comment by manchelsi** [comment]
I used KVM virtualization

**Comment by gary-yu** [comment]
Mine is also KVM

**Comment by gary-yu** [comment]
manchelsi, I just realized that your last log is 
" Aug 30 13:06:15 fusionpbx systemd[1]: PID file /run/freeswitch/freeswitch.pid not readable (yet?) after start."

That's same problem as mine I guess, please check if the free switch process is rebooting again and again in your installed machine.

**Comment by gary-yu** [comment]
Hi manchelsi, could you please check?

# ps -ef | grep freeswitch
then wait for 1 or 2 minutes and run ps again
#ps -ef | grep freeswitch

You should  find the process ID is changing, that shows the process is rebooting repeatedly.

**Comment by Len-PGH** [comment]
check the systemd freeswitch file

**Comment by gary-yu** [comment]
Thanks Len for this tip.  Indeed, it's caused by a wrong systemd folder name:

/lib/systemd/system/freeswitch.service
should be 
/etc/systemd/system/freeswitch.service

and the pid location is wrong:

/run/freeswitch/freeswitch.pid
should be
/usr/local/freeswitch/run/freeswitch.pid

My problem solved.
