### ISSUE TITLE
XML RPC

### ISSUE THREAD

**Issue by fitreklam** [fusionpbx/fusionpbx#2813]
Hello there
How can I run XML RPC?

**Comment by markjcrane** [comment]
FusionPBX doesn't use XML RPC by default so its not installed or running by default but you can install it. Install the module. If using Debian 8 then do the following.

apt-get install freeswitch-mod-xml-rpc

Now you need to configure it with Advanced -> Settings and change the password default is not safe unless using 127.0.0.1. Enable the module in Advanced -> Modules. Then restart FreeSWITCH. Keep in mind this is turned off to increase security so if you do enable make sure to change the password and restrict access to the XML RPC port.
