### ISSUE TITLE
Unable to upload custom voicemail greetings

### ISSUE THREAD

**Issue by thomassmart** [fusionpbx/fusionpbx#2820]
Hi, when trying to upload a custom greeting, the following error message is thrown.

Fatal error: Class 'messages' not found in /var/www/fusionpbx/app/voicemail_greetings/voicemail_greetings.php on line 189

Uploading recordings works fine.

Thanks,
Tom

**Comment by thomassmart** [comment]
Looks like the overall process works, and the file is accessible for use as a greeting

**Comment by mafoo** [comment]
per chance are you 4.2 or 4.3 (master)

**Comment by thomassmart** [comment]
System Information
--
Version | 4.2.2
Git Information | Branch: 4.2

**Comment by markjcrane** [comment]
What operating system?
How did you install FusionPBX?

**Comment by thomassmart** [comment]
Centos 7 - 3.10.0-514.26.2.el7.x86_64
Installed via the install script, which ran with no issues.

**Comment by Slawka** [comment]
In the web interface of the voicemail in the list of greetings is empty
Debian 8
Installed via the install script, which ran with no issues.

**Comment by Slawka** [comment]
**Solved this problem** by replacing
Line 189: `messages::add($text['message-uploaded'].": ".$_FILES['file']['name']);`
 by
`$_SESSION["message"] = $text['message-uploaded'].": ".$_FILES['file']['name'];`

**Comment by markjcrane** [comment]
Thanks for the report. The message::add would work on master branch but not on the 4.2 branch.  I changed it back to the older approach as you suggested.

**Comment by wispaway** [comment]
Thanks Slawka!!!
It worky fine now on 4.2.2.
