### ISSUE TITLE
Provision Template file for GXP16xx name wrongly

### ISSUE THREAD

**Issue by v01ded** [fusionpbx/fusionpbx#2826]
At this moment, the configuration template for GXP16XX is {$mac}.xml. This will generate a configuration file which is in the format of 00aabbccddee.xml but the Grandstream GXP16XX phones are expecting configuration file in the format of cfg00aabbccddee.xml

I have tried changing the file from {$mac}.xml to cfg{$mac}.xml. The configuration file generates correctly but the browser show "file not found" when the provision url http://my.domain.com/app/provision/cfg00aabbccddee.xml is accessed.

**Comment by markjcrane** [comment]
We use a rewrite rule in the web server that make it unnecessary to change the file name of the template. Example nginx rewrite rule.
rewrite "^.*/provision/cfg([A-Fa-f0-9]{12})(\.(xml|cfg))?$" /app/provision/?mac=$1;

**Comment by v01ded** [comment]
I'm using the phone set GXP1628 here. When I place the URL http://my.domain.com/app/provision/?mac=$1 as the provision url, the phone tries to load the configuration file with the following URL

http://my.domain.com/app/provision/?mac=$1/cfg000aabbccdde
http://my.domain.com/app/provision/?mac=$1/cfg000aabbccdde.xml

**Comment by Len-PGH** [comment]
did you check the rewrite rules and see if the one Mark posted is there?  it's in /etc/nginx/sites-available/fusionpbx

**Comment by markjcrane** [comment]
The phone usually doesn't make a request to this url.
http://my.domain.com/app/provision/?mac=$1

Provision url is usually something like this ...
http://my.domain.com/app/provision
For yealink, grandstream and polycom. The user agent string contains the mac address.

**Comment by v01ded** [comment]
I found out what i made wrong. I should just place  http://my.domain.com/app/provision in the phone configuration so request for  http://my.domain.com/app/provision/cfg000aabbccdde.xml will be rewrite to http://my.domain.com/app/provision/?mac=000aabbccdde

Thanks.
