### ISSUE TITLE
Auto changing status of agent ?

### ISSUE THREAD

**Issue by neradpeter** [fusionpbx/fusionpbx#2831]
Extension for callcenter agent is down (not registered) but agent status and state:  Available 	Waiting

It is posible to change  state or status of agent automaticaly ?

**Comment by neradpeter** [comment]
I woud be better ask for freeswitch support with this issue :-D
So im closing it

**Comment by markjcrane** [comment]
Agreed changes to FreeSWITCH mod_callcenter are best to get attention of the maintainers of it.

**Comment by markjcrane** [comment]
I will likely write an alternative backend as an alternative to mod_callcenter.
