### ISSUE TITLE
mp3 records ?

### ISSUE THREAD

**Issue by neradpeter** [fusionpbx/fusionpbx#2833]
Changing extension variable from fusionpbx variables app do nothning...  cals are recorded to wav

Only changing it in source code helps 👎

**Comment by DCVOIP** [comment]
Which variable and did you flush memcache and restart freeswitch??

**Comment by neradpeter** [comment]
variable is record_ext ... enabled true
restarted, memcache flushed... 
new callcenter created with queue record template /var/lib/freeswitch/recordings/home.local/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}/${uuid}.wav

:-(

**Comment by markjcrane** [comment]
Your first post with this issue was not enough detail :-(
Your second try at details exposed enough detail to actually be a valid issue.

**Comment by markjcrane** [comment]
Please update and try again.

**Comment by neradpeter** [comment]
Ok i saw your change in source code.. 

What about if record_ext is not enabled ? It woud be a good choice to have some default value ...

**Comment by markjcrane** [comment]
record_ext is there by default in the master branch and current 4.2 release.
