### ISSUE TITLE
Ring Groups leg timeout > 60 sec

### ISSUE THREAD

**Issue by samael33** [fusionpbx/fusionpbx#2840]
Hi!
In a case of incoming call forwarded to ring group call_timeout by default in Freeswitch = 60 seconds.
If we set leg timeout > 60 seconds, this will make no sense, cause call will interrupt earlier.
Possible workaround - add to global part of dialstring {} call_timeout=max_of_leg_timeouts (plus shift on delays)
Also can be more easy dialplan fix, but just to point.

**Comment by markjcrane** [comment]
Call forward all now uses the dialplan and call timeout could be inherited from the extension's call_timeout.
