### ISSUE TITLE
user_exists fail issue

### ISSUE THREAD

**Issue by 20103306** [fusionpbx/fusionpbx#2841]
i install fusionpbx on aws server(centos7 ami)

It's a log when I play * 9664.

c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:21.750560 [DEBUG] sofia.c:7084 Channel sofia/internal/1010@52.79.231.165 entering state [completed][200] 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:21.750560 [NOTICE] mod_dptools.c:1312 Channel [sofia/internal/1010@52.79.231.165] has been answered 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:21.750560 [DEBUG] switch_channel.c:3773 (sofia/internal/1010@52.79.231.165) Callstate Change RINGING -> ACTIVE 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f EXECUTE sofia/internal/1010@52.79.231.165 playback(silence_stream://2000) 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:21.750560 [DEBUG] switch_ivr_play_say.c:1498 Codec Activated L16@16000hz 1 channels 20ms 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:23.750610 [DEBUG] switch_ivr_play_say.c:1942 done playing file silence_stream://2000 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f EXECUTE sofia/internal/1010@52.79.231.165 execute_extension(is_zrtp_secure XML 52.79.231.165) 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:23.750610 [INFO] mod_dialplan_xml.c:637 Processing 1010 <1010>->is_zrtp_secure in context 52.79.231.165 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 parsing [52.79.231.165->user_exists] continue=true 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (PASS) [user_exists] () =~ // break=on-false 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Action set(user_exists=${user_exists id ${destination_number} ${domain_name}}) INLINE 
2017-09-15 02:01:23.750610 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x2008130 Connected. 
2017-09-15 02:01:23.750610 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x2008130 released. 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f EXECUTE sofia/internal/1010@52.79.231.165 set(user_exists=false) 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f 2017-09-15 02:01:23.750610 [DEBUG] mod_dptools.c:1548 SET sofia/internal/1010@52.79.231.165 [user_exists]=[false] 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (FAIL) [user_exists] ${user_exists}(false) =~ /^true$/ break=on-false 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 parsing [52.79.231.165->call-direction] continue=true 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (PASS) [call-direction] ${call_direction}(local) =~ /^(inbound|outbound|local)$/ break=never 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 parsing [52.79.231.165->variables] continue=true 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (PASS) [variables] () =~ // break=on-false 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Action export(origination_callee_id_name=${destination_number}) 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Action set(RFC2822_DATE=${strftime(%a, %d %b %Y %T %z)}) 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 parsing [52.79.231.165->user_record] continue=true 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (PASS) [user_record] () =~ // break=on-false 
c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Action set(user_record=${user_data ${destination_number}@${domain_name} var user_record}) INLINE 

c55c676c-99b9-11e7-b1ef-3d27ab6b135f Dialplan: sofia/internal/1010@52.79.231.165 Regex (FAIL) [user_exists] ${user_exists}(false) =~ /^true$/ break=on-false 

this line is important

what's wrong?

**Comment by markjcrane** [comment]
Nothing is wrong with this you said you dialed *9664 which user_exists should be false as its referring to the number that was called.
