### ISSUE TITLE
$_SERVER["PROJECT_ROOT"] does not seems to be set in Zoiper apps

### ISSUE THREAD

**Issue by kg2280** [fusionpbx/fusionpbx#2847]
If I go on Apps -> Zoiper, I have a lot of warning.  It seems to be related to the fact that $_SERVER["PROJECT_ROOT"] does not seems to be set in this section.  I have this error : 

Warning: include(): Failed opening '/var/www/fusionpbx/var/www/fusionpbx/resources/app_languages.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear:/var/www/fusionpbx') in /var/www/fusionpbx/resources/classes/text.php on line 19

If I edit /var/www/fusionpbx/resources/classes/text.php and change
 include $_SERVER["PROJECT_ROOT"]."/resources/app_languages.php";
for
include $_SERVER["PROJECT_ROOT"]."/var/www/fusionpbx/resources/app_languages.php";
it is working.  No more warning in Zoiper but all others app are now having warning as $_SERVER["PROJECT_ROOT"] is set as it should

Joined you a screenshot
![selection_042](https://user-images.githubusercontent.com/2558339/30556497-0acb5eea-9c79-11e7-910e-d020d9fe07b7.png)

Thanks

**Comment by markjcrane** [comment]
Its defined in root.php and Zoiper would include that from the local directory.

**Comment by markjcrane** [comment]
To actually be useful need to know the following qustions.
1. What operating system are you using?
2. How did you install FusionPBX?

**Comment by kg2280** [comment]
Hi Mark,

  The OS is debian 8.9 with full update

  I installed FusionPBX with this script : http://www.pbxforums.com/threads/tutorial-creating-a-two-node-fusionpbx-cluster-the-easy-way.126/

**Comment by kg2280** [comment]
I'm having this issue with every apps I added : 
zoiper
webrtc
voicemails_msgs
invoices
hunt group
hot desking

**Comment by markjcrane** [comment]
I'm afraid you have made an assumption about the
fusionpbx/fusionpbx-apps repo one that is incorrect.
You think everything there is production ready it is not.

Zoiper has been updated to use with the master branch
Webrtc is just a demo application not production ready.
voicemai_msgs is old and hasn't been used its essentially archived
invoices works updated to use with the master branch
hunt group is ancient and archived but I thinkg its time to delete it. It was replaced by app/ring_groups which has both ring group abilities and hunt group.
hot desking is the old version of hot desking and has been replaced with something far better. So be considered archived. Most likely will delete it.

**Comment by kg2280** [comment]
Sorry, my bad .  I removed the old apps.

I also updated zoiper.  But I still have the same error.

**Comment by kg2280** [comment]
I took the file from app/ring_groups/root.php and copied it to app/zoiper/root.php and I don't have warning anymore

**Comment by markjcrane** [comment]
Sounds good maybe it was an older version. Updated it as you suggested.
