### ISSUE TITLE
missing ; in /var/www/fusionpbx/app/invoices/app_config.php - line 156

### ISSUE THREAD

**Issue by kg2280** [fusionpbx/fusionpbx#2848]
Hi,

  I think there is a missing ";" in /var/www/fusionpbx/app/invoices/app_config.php on line 156

  I tried to install the invoices apps and when I tried to upgrade the "Menu Default" and "Permission Default", I had an error on line 157.  I looked at the file and there was missing a ";" n the line above.  Added it and then there was no more error when trying to upgrade menu and permission

Thanks
![selection_043](https://user-images.githubusercontent.com/2558339/30558389-300bf952-9c7f-11e7-8aec-dfb5a14460a5.png)

**Comment by markjcrane** [comment]
Thanks for reporting this I added the missing semi-colon and should work now.
