### ISSUE TITLE
Time condition always take alternate destination

### ISSUE THREAD

**Issue by glk70** [fusionpbx/fusionpbx#2868]
I've written a time condition with saturaday monday condition for offices closed and a second playback as alternate condition
![fusionpbx bug - time condition alternate always taken](https://user-images.githubusercontent.com/9905025/31312598-7373068e-abc7-11e7-93b8-0d6c09e07f90.png)
.
the playback for saturday sunday plays corretly , but after that thealternate condition is always taken and the second playback, that set as alternate condition,  starts.

**Comment by markjcrane** [comment]
Your condition is invalid.

Days are represented by numbers.
1 Sunday 
2 Monday
3 Tuesday 
4 Wednesday 
5 Thursday
6 Friday 
7 Saturday 

A valid range is lowest number first highest number last. You used 6-1 which is invalid. This is documented in FreeSwitch documentation.

**Comment by glk70** [comment]
Likely I didnt't explained correctly the problem
I've pasted a new image.
on saturday I hear the message "ufficiChiusiWE" ("offices closed in weekend") and after that I hear the message "ufficiChiusi" ("offices are closed please recall from monday to friday")
the same on Sunday.
Now th two days have two different time conditions, but during sunday and saturday I hear TWO messages, the one specified for saunday and saturday AND the alternate destination.

**Comment by markjcrane** [comment]
I talked with glk70 and he has fixed the range. saturday and sunday with their own entry that is fine. Time condition alternative destination is the end of the line in other words its expected that everyone has gotten off the train and by the end of the time condition if they haven't been sent somewhere else they get sent to the alternate destination. There is a lot of flexibility with this design for those with a full understanding of it and creative thinking.
