### ISSUE TITLE
multi-tenant same ext (ie 101) on each domain....?

### ISSUE THREAD

**Issue by 5280advantage** [fusionpbx/fusionpbx#2869]
Hi. It seems that I cannot register ext 101 on one domain and on another domain. This is a multi-tenant system, and most tenants will likely want easy extensions (like 101-)

Is this not possible??

**Comment by 5280advantage** [comment]
An example subdomain is pbx.5280designco.com. When I try to connect to 101, I get...

2017-10-08 02:56:19.209020 [WARNING] sofia_reg.c:1737 SIP auth failure (REGISTER) on sofia profile 'internal' for [101@pbx.5280designco.com] from ip 217.73.141.183

**Comment by markjcrane** [comment]
This definitely works you can have extension 101 on every domain.

**Comment by 5280advantage** [comment]
Yep, got it working. IP's were blacklisted. I am having an issue where my Grandstream will only ring with others for the first few min, then it stops ringing all together, on all accounts. If I reboot it, it works again for a few min

**Comment by markjcrane** [comment]
May not be keeping the connection alive through firewall. Nat Keep alive or register often to keep the call alive.
