### ISSUE TITLE
Debian 9 support?

### ISSUE THREAD

**Issue by blackyzero** [fusionpbx/fusionpbx#2872]
Dear everyone,

Is that possible to install FusionPBX on Debian 9?
Please share your experience.

Thank you

**Comment by andycol** [comment]
currently freeswitch does not support debian 9

**Comment by andycol** [comment]
https://freeswitch.org/confluence/display/FREESWITCH/Debian+9+Stretch

**Comment by blackyzero** [comment]
yeah, i see.
better to use Debian 8 at the moment.

Thank you, Andycol

**Comment by markjcrane** [comment]
Wait on Debian 9 until FreeSWITCH officially supports it.
