### ISSUE TITLE
Yealink registration on cloud hosted Multi-tenant PBX

### ISSUE THREAD

**Issue by StinkyCow** [fusionpbx/fusionpbx#2873]
I am having trouble trying to get both yealink t38g and t48g to register to a cloud hosted instance. 

I am trying to create a test instance for a model (dont need SIP trunk or DIDs or anything, just extension to extension calling). I have assigned the provisioning server and it seems to be pulling the setting fine from the pbx, but it is setting the "SIP Server" as the company name, but I do not have hosted domains for each tenant, only the domain created in fusionPBX.  I tried manually configuring a phone with the PBX's IP and I got user@12.34.56.78 not found. I then tried renaming the domain to 12.34.56.78 and the user not found error vanish, but I still got a auth failure error. 

What am i doing wrong?

**Comment by DigiDaz** [comment]
Just create a single domain with an fqdn then and put your extensions in there.

**Comment by StinkyCow** [comment]
DigiDaz that seems like it would defeat the purpose: to have a multi-tenant PBX to allow duplicate extensions and no accidental cross traffic between entities.

**Comment by DigiDaz** [comment]
I thought you were saying you didn't want multiple domains, in that case just create tenants as normal with their own domains. Most of us just use one domain with client1.mypbx.com, client2.mypbx.com, etc

**Comment by StinkyCow** [comment]
Digi i didn't think about that. That seems to solve that problem. 
Thank you
