### ISSUE TITLE
Annoying and serious issues

### ISSUE THREAD

**Issue by 5280advantage** [fusionpbx/fusionpbx#2881]
Any help appreciated

1. Multiple devices registered to exts do whatever they want - sometimes they ring, sometimes they don't, but most times they never all ring. I don't understand why, if I'm staring right at "registered" that it doesn't ring...(ext has max 5 devices set)
2. Ring group can be set to ring ext 101 and ext 102 simultaneously and only one of them rings
3. Most if not all of call routing options don't work -- at all. Like I didn't even change anything
4. Can't delete domains. Acts like it did but did nothing

**Comment by blackc2004** [comment]
Just FYI on #2 if you're using multiple-reg you need to make sure the ring group strategy is set to "enterprise".

**Comment by plettonline** [comment]
WRT extensions not ringing, are the extensions on the same subnet? If not,
you could be having a NAT issue.



On 16 Oct 2017 19:21, "5280 Advantage" <notifications@github.com> wrote:

Any help appreciated

   1. Multiple devices registered to exts do whatever they want - sometimes
   they ring, sometimes they don't, but most times they never all ring. I
   don't understand why, if I'm staring right at "registered" that it doesn't
   ring...(ext has max 5 devices set)
   2. Ring group can be set to ring ext 101 and ext 102 simultaneously and
   only one of them rings
   3. Most if not all of call routing options don't work -- at all. Like I
   didn't even change anything
   4. Can't delete domains. Acts like it did but did nothing

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fusionpbx/fusionpbx/issues/2881>, or mute the thread

**Comment by 5280advantage** [comment]
For #2, not working with enterprise, but this could simply be the fact that there are issues ringing the extension already. Btw, how does enterprise even work? It's the same as simultaneous?

**Comment by 5280advantage** [comment]
@plettonline They're on different networks. This is a new system, and I can't tell if most of these issues arised after adding SSL to server, because I didn't test that much before SSL. 

Are there any big/obvious settings that need to be done after installing SSL?

**Comment by 5280advantage** [comment]
Also, when I call some exts, I get silence, then the voicemail....Here are logs for most recent call

48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:40 sofia/internal/101@10.1.10.179:5060 Standard INIT 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:48 (sofia/internal/101@10.1.10.179:5060) State Change CS_INIT -> CS_ROUTING 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:627 (sofia/internal/101@10.1.10.179:5060) State INIT going to sleep 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:584 (sofia/internal/101@10.1.10.179:5060) Running State Change CS_ROUTING (Cur 2 Tot 81) 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] sofia.c:7084 Channel sofia/internal/101@10.1.10.179:5060 entering state [calling][0] 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:643 (sofia/internal/101@10.1.10.179:5060) State ROUTING 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] mod_sofia.c:143 sofia/internal/101@10.1.10.179:5060 SOFIA ROUTING 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_ivr_originate.c:67 (sofia/internal/101@10.1.10.179:5060) State Change CS_ROUTING -> CS_CONSUME_MEDIA 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:643 (sofia/internal/101@10.1.10.179:5060) State ROUTING going to sleep 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:584 (sofia/internal/101@10.1.10.179:5060) Running State Change CS_CONSUME_MEDIA (Cur 2 Tot 81) 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:662 (sofia/internal/101@10.1.10.179:5060) State CONSUME_MEDIA 
48e6b92a-099e-4917-9229-f098a66f386e 2017-10-16 19:05:39.094940 [DEBUG] switch_core_state_machine.c:662 (sofia/internal/101@10.1.10.179:5060) State CONSUME_MEDIA going to sleep

**Comment by blackc2004** [comment]
Sounds like a NAT issue to me.

But RE enterprise, with multiple reg it's the only way that I know is supported to get all the phones at same EXT to ring. It works the same as simultaneous..

**Comment by 5280advantage** [comment]
If I change the Grandstream's to TCP, they ring almost every time. It works for now, but I prefer UDP. Can't figure out issues 3 & 4

**Comment by markjcrane** [comment]
Items 1-3 work fine for most people. Unlikely to be bugs and more likely configuration issues on how  the system is setup.
4 may depend on the version of FusionPBX you have installed.

**Comment by 5280advantage** [comment]
I can't fathom how 4 could not work. The entire premise of this system is multi-tenant, and yet the very simple ability to delete a tenant does not work??? Please help me understand the logic here

**Comment by DigiDaz** [comment]
You on Debian 8??

**Comment by 5280advantage** [comment]
Yes

**Comment by 5280advantage** [comment]
Not sure about Postgres but Debian 8 "jessie" and Nginix I assume since that's how SSL was installed
