### ISSUE TITLE
Does installing SSL affect anything?

### ISSUE THREAD

**Issue by 5280advantage** [fusionpbx/fusionpbx#2883]
Hi. Does installing SSL affect anything or cause for anything to be need to be configured differently? The system seems to work as usual, but something just feels different and I can't place it. A bit less stable and consistent..

**Comment by markjcrane** [comment]
Well there is different types of SSL such as SSL for NGINX, for FreeSWITCH and there are alternatives to OpenSSL library. Without additional details we would just be taking a wild guess.

**Comment by markjcrane** [comment]
I'll assume the first option that you just used SSL for NGINX and FreeSWITCH. SSL uses TCP which may behave different than UDP. Its also encrypted to so SIP ALG doesn't touch it, and it does take a little more load on the server because its encrypted.

**Comment by 5280advantage** [comment]
Got it. Yes first option using Let's Encrypt. So I'd assume you you recommend using TCP on all devices? (although UDP on some seems to work but haven't tested much). And, it seems to work with SIP ALG. Do you mean it shouldn't work at all with SIP ALG or there is just no benefit of it in that regard?

Lastly, is it common to just avoid SSL for better performance? Or do most selling the service use it?

Thanks for answering all my questions!
