### ISSUE TITLE
Hellppp...Can't delete domains and really need to

### ISSUE THREAD

**Issue by 5280advantage** [fusionpbx/fusionpbx#2884]
When I try to delete a domain it acts like it did but it doesn't do anything...

**Comment by 5280advantage** [comment]
Debian 8

**Comment by markjcrane** [comment]
Version of FusionPBX

**Comment by 5280advantage** [comment]
4.2

**Comment by 5280advantage** [comment]
Do I need to pay for support to fix a bug?

**Comment by ruslanguns** [comment]
Try upgrading your FusionPBX to latest by doing that 

![imagen](https://user-images.githubusercontent.com/19806968/31843299-7cb96444-b5af-11e7-8aec-de58ff9d31a4.png)

Then just try hitting the X button and it should work.

![imagen](https://user-images.githubusercontent.com/19806968/31843327-9870d79e-b5af-11e7-8fa4-5f91c8595501.png)

If you are still having issues, try rebooting your server and then try again.

**Comment by 5280advantage** [comment]
Nope. Neither worked

**Comment by Len-PGH** [comment]
Are you trying to delete the domain while you are in it?  You could also try to rename the domain.

**Comment by 5280advantage** [comment]
@Len-PGH I've tried while in a different domain. None will delete. I don't want to rename. I'm OCD and don't want a bunch of extra domains in the list that can't be used. This is a "multi-tenant" system and it's quite amateurish that I can't delete them.  I like organization. I've seen this issue on here elsewhere but no help there

**Comment by markjcrane** [comment]
Insults aren't a great way of getting free support.

**Comment by 5280advantage** [comment]
I hear you worthless fucks do this on purpose so you can charge for support
