### ISSUE TITLE
Feature Request: Sponsor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#501]
```
there should be a way in the GUI we should copy settings to all domains.
(example, we create outbound routes - Schedules -  MOH - Call Flows - etc.
and when we create a new domain it should some how, ask if we wanna copy those 
settings, to the new domain.
it would be a good feature to have, (we can chose what to copy when oppning a 
new domain, so we wouldn't need to create it again and again..)
what would it take to sponsor this feature?

```

Original issue reported on code.google.com by `6279...@gmail.com` on 14 Nov 2013 at 11:35

**Comment by markjcrane** [comment]
We can now copy several settings and move it to other domains. Does not include all features yet.

**Comment by markjcrane** [comment]
Current version of FusionPBX has a domain select list for most things like devices, dialplans and extensions, gateways and more. You can make a copy and then select the domain you want to move it to.
