### ISSUE TITLE
add phonebook on provisioning and upload phonebook xml file to domain directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#665]
```
In order to automatic download phonebook to device such as granstream gxp2140, 
it needs a php script to upload the phonebook to directory under domain.
```

Original issue reported on code.google.com by `spw...@gmail.com` on 24 Jul 2014 at 5:13

**Comment by markjcrane** [comment]
This has been done for Yealink and Polycom as the preferred phones. If you want it done for grandstream consider sponsoring the work.
