### ISSUE TITLE
Ring Group - CallerID Name & Number Issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#693]
```


I have 2 call flows

I also lookup client names with a external callerid lookup

Main Business
DID->Time Condition->IVR->Ring Group(per IVR Option, prepend to caller_id_name)

Direct Lines
DID->Ring Group (again to prepend to caller_id_name)

the Ring Group was breaking the callerid, Main Business lines where what I 
expected but calls to the Direct Lines where not.

I had this problem with 3.4 and it still exists after upgrading to 3.6

I modified the lua script in 3.4 also
```

Original issue reported on code.google.com by `erin.ome...@salmonbaytechnology.com` on 22 Aug 2014 at 4:43

Attachments:
* [index.lua](https://storage.googleapis.com/google-code-attachments/fusionpbx/issue-693/comment-0/index.lua)
* [00_FixCallerID.xml](https://storage.googleapis.com/google-code-attachments/fusionpbx/issue-693/comment-0/00_FixCallerID.xml)

**Comment by markjcrane** [comment]
Fixed in latest FusionPBX what will be released as 4.2
