### ISSUE TITLE
Feature request:  Ability to use non-anonymous LDAP authentication

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#792]
```
It would be nice to have the ability to use LDAP if you have anonymous binding 
disabled on your LDAP server.  This would require the ability to set a flag for 
anon or not, as well as the bind username and password for non-anonymous.  The 
LDAP code would then also need adjustments to bind with the bind 
username/password and then search for the user attempting to log in.
```

Original issue reported on code.google.com by `teleut...@gmail.com` on 12 Dec 2014 at 10:02

**Comment by mschaefers** [comment]
@markjcrane I would try to create a pull request for this enhancement - if you could show me how to use the LDAP authentication plugin.

**Comment by markjcrane** [comment]
Anonymous ldap sounds very insecure why add support for it? Please describe a reason you are using anonymous.

**Comment by markjcrane** [comment]
You did say non anonymous which would mean password is required. That is what do by default we don't support anonymous.

**Comment by mschaefers** [comment]
OK, so right now you are forced to _bind_ **non**-anonymously? Then this Feature request is obsolete, as it asks for exactly that. Sorry for the confusion, I just could not try it myself as I found no docs for LDAP authentication.

**Comment by markjcrane** [comment]
LDAP instructions included in the training.
