### ISSUE TITLE
MOH on dial out

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#831]
```
What steps will reproduce the problem?
1. call out to your cell phone
2. on the cell phone pick up a differerent call
3. You will hear your own MOH

What is the expected output? What do you see instead?
That the sip message when a receiver puts you on hold you should hear their MOH 
not from your own system

What version of the product are you using? On what operating system?

newest fusion
Please provide any additional information below.

```

Original issue reported on code.google.com by `sha...@jaytele.com` on 29 Jan 2015 at 5:56

**Comment by danry25** [comment]
I attempted to reproduce this using Fusionpbx v4.0.0 and was unable to reproduce this issue. What cellular provider and which FusionPBX version can you recreate this issue with? Any settings I should change when attempting to reproduce?
