### ISSUE TITLE
CDR systemwide download

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#835]
```
Ability to download the CDR's from the GUI from all the domains with one click, 
Not having to go into every domain separately.
```

Original issue reported on code.google.com by `sha...@jaytele.com` on 29 Jan 2015 at 5:59

**Comment by danry25** [comment]
This works in v4.0.0, in Apps --> Call Detail Records click Show All then Export and choose CSV.
