### ISSUE TITLE
Ring All not work for call center queue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#874]
```
Selected strategy as Ring All in call_center_queue_edit.php.

But it doesn't work.
```

Original issue reported on code.google.com by `spw...@gmail.com` on 9 Mar 2015 at 2:49

**Comment by markjcrane** [comment]
Agent status set to Available.
Agent device registers every 60 - 120 second registration time.
Agent settings (set to something short like 1 second)
* No Answer Delay Time
* Max No Answer 	
* Wrap Up Time 	
* Reject Delay Time 	
* Busy Delay Time
