### ISSUE TITLE
Feature Request: Mobile Web

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#915]
```
Would be great if FusionPBX web was screen size aware.
If size as mobile phone then menu like "Hamburger" style.

```

Original issue reported on code.google.com by `ekaskris...@gmail.com` on 11 Apr 2015 at 8:35

**Comment by markjcrane** [comment]
Menu in 4.2 now uses boostrap which is built for mobile browsers.
