### ISSUE TITLE
Call Center Agent Status search and grouping

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#925]
```
able to view Call Center Agent Status by queues.
limit views to certain queues
to be able to search for agent 
```

Original issue reported on code.google.com by `canlitht...@gmail.com` on 17 Apr 2015 at 2:40

**Comment by markjcrane** [comment]
Agents are now listed and assigned to a Queue from the Call Center Queue edit page.
