### ISSUE TITLE
Some fields in FPBX allow a + infront of destinations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#975]
```
What steps will reproduce the problem?
1. Enable Follow Me
2. Input +91(digits for indian number)
3. Make a call to the extension. 

What is the expected output? What do you see instead?
Expected: The call to proceed. 
What happens: multiple regexes are wrongly failed by this + which each regex 
does not test for. 

What version of the product are you using? On what operating system?
newest stable upgrade available as of 12:00 MDT 01-Jun-2015 

Please provide any additional information below.

08b1f3d6-0882-11e5-bdb8-8722d02a2833 Dialplan: loopback/+919909503920-b Regex 
(FAIL) [call-direction] destination_number(+919909503920) =~ /^\d{7,20}$/ 
break=on-false


Suggestion: Strip '+' from all destinations when entered via forward, or follow 
me.  Seems perhaps a slight oversight, as the +  stripping is definitely there 
in CID Number fields. 
```

Original issue reported on code.google.com by `myst...@gmail.com` on 1 Jun 2015 at 6:28

**Comment by markjcrane** [comment]
Outbound route 'North America' with ^\+?1?(\d{10})$ makes the + optional and then automatically strips it. The prefix on the outbound route can then add it if its required. Follow me and forward are not always restricted to numeric as this issues seems to suppose.

**Comment by markjcrane** [comment]
I don't see a problem here as you are allowed to set it up how you want to.

If you want specific attention on this issue pay for an hour of support and call the support number listed on that page.
http://www.fusionpbx.com/support.php
