### ISSUE TITLE
unable to create a new user

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#981]
```
What steps will reproduce the problem?
1. check the group list (superadmin, admin, user, agent...)
2. accounts > user manager > add a new user (+)
3. select a group for this new user

What is the expected output? What do you see instead?
no groups in the group list when i want to add a new user so i'm unable to 
create a new user

What version of the product are you using? On what operating system?
V3.9.0 on debian 7 (ESX 6.0)

Please provide any additional information below.
I'm able to create new groups in Group Manager (Advanced Menu)
I'm using Multi Tenant and when i click on "fusionpbxadmin" user (user manager 
menu), i can't add or delete groups for this users) but to add another user, 
there is no group list.
```

Original issue reported on code.google.com by `jean-fra...@cnsi.fr` on 3 Jun 2015 at 9:03

**Comment by semyazza** [comment]
I can confirm this issue.  Debian Jessie x64 fresh install. FusionPBX revision 8738.  Multi-tenant.

**Comment by arressen** [comment]
This thread seems to have gone quiet - was a resolution ever found?  I just completed fresh install on raspberry pi 2 (Raspbian) using standard FusionPBX script, also ran updates for both FreeSwitch and FusionPBX, but no groups are listed when adding a new user.

**Comment by arressen** [comment]
I worked out a way to get around this. Perhaps this is also the correct approach, but not clear.

When creating an extension there is an option in the "Range" section to create a new user with the same value as the extension.  The record can then be modified in User Manager, with all available groups listed.

**Comment by markjcrane** [comment]
This problem has already been fixed. This most likely means everyone that has commented here are running an old version of FusionPBX on google code and subversion

The project has moved to github. See the following instructions.
http://wiki.fusionpbx.com/index.php?title=GIT

Upgrade instructions that may be useful for you.
http://wiki.fusionpbx.com/index.php?title=Upgrade

**Comment by csbac** [comment]
I believe the main problem is, that there is no installer script for the github based sources. The installer script that can be found uses the google code version; and no new fpbx admin will patch the script or migrate the sources during installation/compilation to another repository.
Maybe someone can change the installation script, and/or make a note how it has to be changed to work with github "out-of-the-box"?

**Comment by markjcrane** [comment]
We can't change the install script from google code as it is write only and will be turned off entirely in a couple months by google when it shuts down google code.

The installation approach described on this download page uses the github version of FusionPBX. The wiki is community driven the website is official.
http://fusionpbx.com/download.php

**Comment by arressen** [comment]
The fusionpbx wiki site also has a separate page with instructions for install to a Raspberry Pi: http://wiki.fusionpbx.com/index.php?title=Raspberry_Pi_Script

I found the page top of the results list when I searched for "fusionpbx raspberry pi"

**Comment by jcapp** [comment]
I was able to reproduce this problem and have a solution.  Referring to core/users/signup.php (revision 8739), the query to "select * from v_groups" has a clause to check for either a matching domain_uuid or a domain_uuid that is null.  It also has a bindParam for the domain_uuid but no replaceable param in the query.  Finally, $prep_statement->execute(); unecessarily repeated.

In my experience, a string compare on a null value will cause unexpected results in some SQL databases.  I am suggesting that we reorder the query parameters, performing a null check first, then performing a string compare if the domain_uuid value is not null. I am also suggesting the removal of the bindParam and the duplicate $prep_statement->execute();

<pre>
Index: core/users/signup.php
===================================================================
--- core/users/signup.php	(revision 8739)
+++ core/users/signup.php	(working copy)
@@ -319,12 +319,12 @@
 	echo "		<td class='vtable'>";
 
 	$sql = "select * from v_groups ";
-	$sql .= "where (domain_uuid = '".$domain_uuid."' or domain_uuid is null) ";
+	$sql .= "where (domain_uuid is null or domain_uuid = '".$domain_uuid."') ";
 	$sql .= "order by domain_uuid desc, group_name asc ";
 	$prep_statement = $db->prepare(check_sql($sql));
-	$prep_statement->bindParam(':domain_uuid', $domain_uuid);
+	//$prep_statement->bindParam(':domain_uuid', $domain_uuid);
 	$prep_statement->execute();
-	$prep_statement->execute();
+	//$prep_statement->execute();
 	$result = $prep_statement->fetchAll(PDO::FETCH_NAMED);
 	echo "			<select name='group_uuid_name' class='formfld' style='width: auto; margin-right: 3px;'>\n";
 	echo "				<option value=''></option>\n";
</pre>

These small changes solved this problem for me.

**Comment by markjcrane** [comment]
You are having this issue because your using subversion which is out of date. So comments on subversion will be ignored. Move to git I provided instructions here and on the wiki. If you need assistance paid support.
