### ISSUE TITLE
Feature request: call waiting enable/disable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#988]
```
Hello,

I would like to have the ability to enable/disable call waiting on certain 
devices.

My problem is that when in a call center, if an agent is making an outgoing 
call, still can receive calls. Disabling call waiting solves this.

Thanks!
```

Original issue reported on code.google.com by `bad...@gmail.com` on 11 Jun 2015 at 1:20

**Comment by badcrc** [comment]
Just for the updates! (I'm the op)

**Comment by badcrc** [comment]
Hi,

I already have this working using Device->Settings options.

You can close the ticket.

Thanks!

**Comment by markjcrane** [comment]
Glad you found a way to do it with the current existing interface.
