### ISSUE TITLE
Can not add new user can't assign group

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#997]
```
What steps will reproduce the problem?
1. download latest version of fusionpbx
2.add new user via User Manager
3. add group to user

What is the expected output? What do you see instead?
It is expected to see list of groups in a group form. I see empty list instead.

What version of the product are you using? On what operating system?
3.8

Please provide any additional information below.

```

Original issue reported on code.google.com by `andrey.l...@smartnet.in.ua` on 18 Jun 2015 at 3:07

Attachments:
* [Screen Shot 2015-06-18 at 4.05.27 PM.png](https://storage.googleapis.com/google-code-attachments/fusionpbx/issue-997/comment-0/Screen Shot 2015-06-18 at 4.05.27 PM.png)

**Comment by mhancock1959** [comment]
Has there been a resolution to this issue?

**Comment by ScITGmbH** [comment]
Is there any status update to this problem? Same here, revision 8739 / FS 1.4.20

**Comment by markjcrane** [comment]
I can't reproduce the problem someone needs to share access with me send email to support@fusionpbx.com.

**Comment by markjcrane** [comment]
Someone sent me details to login and I discovered there system is still using google code and svn.
This problem was fixed a while ago on github.

Here is instructions to switch to github.
http://wiki.fusionpbx.com/index.php?title=GIT
