### ISSUE TITLE
Empty group list in adding new user

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#999]
```
What steps will reproduce the problem?
1.Add new User
2.Select Group


```

Original issue reported on code.google.com by `whins...@gmail.com` on 22 Jun 2015 at 2:11

Attachments:
* [22.06.png](https://storage.googleapis.com/google-code-attachments/fusionpbx/issue-999/comment-0/22.06.png)

**Comment by amoonrah** [comment]
I just installed version 3.8.4 
i'm using sqllite as my backend database

this is a fresh install, when I try to add a user the group menu is empty, I'm logged in as admin.

I'm running it on centos 7 also a fresh install

freeswitch 1.4.20 also a fresh install

**Comment by markjcrane** [comment]
You are not using github your source code is still from google code subversion. If you were using github you wouldn't have this problem as it has been fixed on git.
